### ISSUE TITLE
Sprint I

### ISSUE THREAD

**Issue by whyrusleeping** [ipfs/pm#10]
**Sprint Goals**:

This sprint is focusing on making ipfs more robust and dependable, api tests, crash fixes, and maybe even a little perf as we prepare for new features (electron shell, dht records improvements)

**Sprint Participants**:

- @whyrusleeping @krl @cryptix @wking @jbenet @tv42 @gatesvp @chriscool @rht

**Sprint Deliverables**:

#### @whyrusleeping
- [ ] https://github.com/ipfs/go-ipfs/pull/1187
  - [ ] https://github.com/ipfs/go-ipfs/pull/1299 patch command
- [x] https://github.com/ipfs/go-ipfs/pull/1290
- [ ] refactor DHT to make find providers better
  - waiting until its time to implement the record spec
- [ ] https://github.com/ipfs/go-ipfs/issues/1246 Avoid dialing known local addresses when not in that network
  - posted iptables commands to help issue
- [ ] https://github.com/ipfs/go-ipfs/issues/1247 Config option to disable dialing specific subnets entirely

#### @krl
- [ ] https://github.com/ipfs/go-ipfs/issues/1153
-- i'll add ipfs brand, and hand over to someone for go integration
- [ ] electron shell app https://github.com/ipfs/webui/54
- [ ] node-ipfs-api test coverage
- [x] shipped webui 0.2.0
- [x] browserified build

#### @jbenet
-- blocked on api testing, dht findprovs json return not parsing cleanly

- [x] https://github.com/ipfs/go-ipfs/issues/1197
- [ ] swapping out the stream muxer (or having multiplex in go)
- [ ] get a build of go-ipfs for node-ipfs compatibility
- [ ] readme on how to implement ipfs on another lang
- [x] DHT Records Spec!
- [ ] Keystore Spec!
- [x] CR pinning
- [ ] CR migration
- [ ] CR S3

#### @tv42 
- [ ] pinning in blockstore (merge)
  - blocked on https://github.com/ipfs/fs-repo-migrations/pull/7
- [ ] pinning perf? log?
- [ ] s3 datastore

#### @gatesvp
- [ ] https://github.com/ipfs/go-ipfs/issues/1211 ipfs refs --recursive --unique is not recursive
- [ ] https://github.com/ipfs/go-ipfs/pull/1232 - .ipfsignore support

#### @chriscool
- [x] https://github.com/jbenet/git-push-each/issues/2
- [x] https://github.com/jbenet/git-push-each/pull/6

#### @wking
- [x] posting a list of possible add APIs for discussion (to help with https://github.com/ipfs/go-ipfs/pull/1136) https://github.com/ipfs/go-ipfs/issues/1291
- [ ] start working on an IPFS storage driver for https://github.com/docker/distribution

#### @rht
- [ ] https://github.com/ipfs/go-ipfs/issues/740
- [ ] https://github.com/ipfs/go-ipfs/issues/143
- [ ] https://github.com/ipfs/go-ipfs/issues/593
- [ ] https://github.com/ipfs/go-ipfs/issues/1060
- [ ] https://github.com/ipfs/go-ipfs/issues/555
- [ ] https://github.com/ipfs/go-ipfs/issues/1030
- [x] https://github.com/ipfs/go-ipfs/pull/1294
- [ ] CR bot formalizing guidelines into literate code (go lint & vet should be put here instead), constraint that commits can't fail the test at any point in history

#### @cryptix 
- [ ] https://github.com/ipfs/go-ipfs/pull/1287 (print after opening listener)
- [ ] talk with @blame about the 'client only' mode from https://github.com/ipfs/go-ipfs/issues/1118

#### @harlantwood
- [ ] https://github.com/ipfs/webui/issues/56 spike on graph viz of DAG data

#### triage - anyone can pick these up
- [ ] https://github.com/ipfs/go-ipfs/issues/1289
- [ ] https://github.com/ipfs/go-ipfs/issues/1248 fix fuse unmount
- [ ] https://github.com/ipfs/go-ipfs/issues/1241 network write latencies
- [ ] https://github.com/ipfs/go-ipfs/issues/1222 add uses a lot of ram and cpu
- [ ] daemon init cleanup?
- [ ] https://github.com/ipfs/go-ipfs/issues/1224 decimate eventlog 
- [ ] stable resolution (tests)
- [ ] merge https://github.com/ipfs/go-ipfs/pull/1277
- [ ] use latest version of cheggaaa/pb to fix some races: https://github.com/ipfs/go-ipfs/issues/1012

**Comment by rht** [comment]
I'm picking ipfs/go-ipfs#1224 because this is basically ipfs/go-ipfs#593

**Comment by whyrusleeping** [comment]
@rht okay, when you get around to that lets chat on irc about what we want to do for it

**Comment by cryptix** [comment]
Some one please hit me if I don't follow through with these:

- ipfs/go-ipfs#1297 - sharness t0060 cleanup (also fixes ipfs/go-ipfs#1297)
- ipfs/go-ipfs#1287 - print port after listening
- godeps (fuse Attr() changes, ipfs/go-ipfs#1012, follow up to ipfs/go-ipfs#1156, all to master(?))

**Comment by chriscool** [comment]
> ipfs/go-ipfs#1297 - sharness t0060 cleanup (also fixes ipfs/go-ipfs#1297)

It looks strange that you talk about ipfs/go-ipfs#1297 twice in the above sentence.

**Comment by cryptix** [comment]
@chriscool thx. copy pasta fail. I meant ipfs/go-ipfs#1277.

**Comment by tv42** [comment]
Stuff listed for me is really just pending reviews & merges, for now.

**Comment by cryptix** [comment]
For next weeks spring I'd like to do:

* Talk with @BrendanBenshoof about the 'client only' mode
* support /tcp/0 properly by putting actual used addresses into the repo dir for CLI to look them up
* fix writeable http gw (PUT is still broken)

**Comment by jbenet** [comment]
hey everyone! this sprint's text is only sort of accurate. people did a lot more things than what's listed here. wonder whether we should have people drop links to issues here when they do something?

**Comment by dylanPowers** [comment]
@jbenet Doesn't waffle serve that purpose?

**Comment by jbenet** [comment]
@dylanPowers true it should. i havent been using it as much. i'll give it a try this week.

**Comment by harlantwood** [comment]
Nice.  Someone with access please drag ipfs/webui#56 into "In Progress" -- or add me as a collaborator and I'll do it...

**Comment by jbenet** [comment]
@harlantwood collab-ed! read https://github.com/ipfs/community/blob/master/contribution-guidelines.md#conventions

**Comment by harlantwood** [comment]
Awesome, thanks : )  Moved the story to "In Progress".  I think Waffle seems kind of awesome BTW.
