### ISSUE TITLE
Sprint: April 18 → May 3

### ISSUE THREAD

**Issue by RichardLitt** [ipfs/pm#104]
# Sprint April 18, 2016

## Sprint Discussions

[Schedule](https://github.com/ipfs/pm#sprint-discussion-schedule)

Please take notes in a separate pad, if you can, and link it here.

Endeavour         | Lead            | Time (PDT - **UTC/Z** - CEST) | Pad
:---------------: | :-------------: | :--------------------------: | :----:
sync              | @RichardLitt    | 9:00PDT **16:00Z** 17:00CEST  | IRC: #ipfs on Freenode
apps on ipfs      | @dignifiedquire | 10:30PDT **17:30Z** 18:30CEST | https://public.etherpad-mozilla.org/p/ipfs-april-18-apps-on-ipfs
infrastructure    | @lgierth        | 11:00PDT **18:00Z** 19:00CEST | https://public.etherpad-mozilla.org/p/ipfs-april-18-infrastructure
libp2p            | @diasdavid      | 11:30PDT **18:30Z** 19:30CEST | https://public.etherpad-mozilla.org/p/ipfs-april-18-libp2p
js-ipfs           | @diasdavid      | 12:00PDT **19:00Z** 20:00CEST | https://public.etherpad-mozilla.org/p/ipfs-april-18-js-ipfs
go-ipfs           | @whyrusleeping  | 12:30PDT **19:30Z** 20:30CEST | https://public.etherpad-mozilla.org/p/ipfs-april-18-go-ipfs
multiaddr           | @jbent | 13:00PDT **20:00Z** 21:00CEST | https://public.etherpad-mozilla.org/p/ipfs-april-18-multiaddr

Please add the Agenda to the Pad before the endeavour sprint starts.

## Sprint Deliverables

- Add your tasks below in a comment, that way we only have people listed who are really in the sprint
- Add links to issues down here. Only add things you can finish this sprint.

**Comment by whyrusleeping** [comment]
## go-ipfs

#### Lead: @whyrusleeping

#### Participants
@jbenet
@diasdavid
@richardlitt
@dignifiedquire

## Notes

- fixed 0.4.0 listener bug, shipping 0.4.1 soon
- hoping to fix findpeers bug this week
  - requires swarm dial refactor
  - that needs reviews
- also going to continue extracting deps with gx

- looking at progress bars would be a good thing to tackle this week

- IPNS issues
  - people reporting problems with resolving entries and consistency
  - should open and issue to track these problems

roadmap for Q2: https://github.com/ipfs/go-ipfs/issues/2247#issuecomment-211441820
  - break this up into set of items for each sprint (sign up for things youre going to tackle)
  - misc issues at end of list for newcomers to grab easier issues

- add sharding spec as a task on the roadmap

**Comment by diasdavid** [comment]
# libp2p hangout

## Notes

enroute to js-ipfs milestone 1
  - multistream spec needs to be finished - https://github.com/jbenet/multistream/pull/7#discussion_r59335408
  - ipfs multiaddr support on multiaddr package (https://github.com/jbenet/js-multiaddr/issues/15) (dignifiedquire)
  - js-libp2p-ipfs-browser -> a libp2p build dedicated for the browser + browser tests with it on js-ipfs (dignifiedquire)
  - fix swarm 'random' bug https://github.com/diasdavid/js-libp2p-swarm/issues/37 (dignifiedquire)
  - ensure that both go-libp2p and js-libp2p use the same version tags for protocols https://github.com/ipfs/specs/pull/94 (~~need to ping Jeromy~~ already pinged)
- Add semver awareness to multistream (future)

**Comment by diasdavid** [comment]
# js-ipfs hangout

## Notes

enroute to js-ipfs milestone 1
  - ipfs core api spec https://github.com/ipfs/js-ipfs/issues/110 (Juan)
  - files add, get and cat (David + Nathan)
  - http-api spec https://github.com/ipfs/http-api-spec/pulls (Richard)
  - bitswap https://github.com/ipfs/specs/pull/95
  - examples of js-ipfs (loading a webpage) (Nathan )
  - every other endeavour https://github.com/ipfs/js-ipfs/issues?q=is%3Aissue+is%3Aopen+label%3A%22help+wanted%22
  - aegir/js guidelines merge https://github.com/ipfs/community/pull/111 (https://github.com/ipfs/community/pull/119)
 
  
David's plan
  - Focus Monday and Tuesday on the Files thing with Nathan
  - Focus Wednesday, Thursday and Friday on Bitswap

Build an app on js-ipfs:
  - load the dist
  - construct page  
  - video loads

**Comment by diasdavid** [comment]
# DAVID DIAS TODO

### js-ipfs

- **management**
- **files API**
  - [ ] redo the importer
  - [ ] finish the integration to js-ipfs with Voxelot
- **bitswap**
  - [ ] do eeeet

### js-ipfs-api

### libp2p

### npm on IPFS

### IPLD

### specs

### extra

- [x] have a good chat with Nicola on how libp2p works and how he can use it for his P2P class at MIT

**Comment by lgierth** [comment]
## Infrastructure

#### Lead: @lgierth

#### Participants

## Agenda

- connectivity
  - ssl *.ipfs.io cert
  - ipv6
  - don't have gateways peer with each other over cjdns
- dns
  - move domains to company account
  - codify the domain zones
  - outage postmortem blogpost
- ipns pages


## Notes

- ssl cert
  - we have the new wildcard cert for *.ipfs.io now
  - need whyrusleeping to get me the private key too
  - and then install it on the gateways
- ipv6
  - enabling ipv6 will hopefully make NAT issues a bit better for some people
- cjdns peering
  - having the gateways not peer with each other over cjdns, *might* make the hangs we see a bit better
- dns
  - not much new to discuss about these points :)
- ipns pages
  - not much new to discuss here either

**Comment by lgierth** [comment]
- go-ipfs
  - [ ] backport and deploy ipfs/go-ipfs#2549 to v03x ipfs/go-ipfs@0-3-stable
  - [x] update go-libp2p dependency ipfs/go-ipfs#2576
  - [ ] readme: mention building from source on windows ipfs/go-ipfs#2550
- infrastructure
  - [ ] prevent gateways from dialing each other over cjdns (attempt at fixing slowness) ipfs/infrastructure@b34f10337cc3c27c35637d49633e8e4f1dd58a5a
  - [ ] metrics: fix mtail's duplicate output
- DNS outage actionables
  - [ ] codify domains
  - [ ] prepare moving domains to gandi company account
  - [ ] better ipns tests
  - [ ] lower ttl for all ipfs.io zones
  - [ ] postmortem blog post
- weekly
  - [ ] add things to it
  - [ ] pick a content-type of the week
- pages
  - [ ] get `ssh <page>@pages.ipfs.team deploy <hash>` working

**Comment by nginnever** [comment]
<h2>TODO</h2>
- js-unixfs-engine
 - [~] Rework importer
- js-ipfs
 - [ ] cat command http-api
 - [ ] get command http-api
 - [ ] ls command
 - [ ] add command http-api
- Webui
 - [ ] write tests
 - [ ] document in contibuting.md
- go-ipfs
 - [ ] study go-lang
- pub/sub - crdt - ipld
 ` [ ] research
 ` [ ] test what is already built

**Comment by RichardLitt** [comment]
#### To Do

- [x] Sprint Management
- [x] Merged remaining 10 http-api-spec PRs
- [x] Merged all open guideline PRs in ipfs/community
- [x] Ship Weekly 9
- [ ] Write and ship Weekly 10
- [ ] Make an IPFS NYC Meeting blogpost
- [ ] Organize April 20th MIT Meetup
  - [ ] Write roundup afterwards

**Comment by RichardLitt** [comment]
Mid-week hangout will be happening in 25 minutes, at 12:00noon EDT, 9:00am PDT, 6:00pm CEST, 4:00pm UTC.

**Comment by noffle** [comment]
## noffle

This week I brought some ipfs/libp2p JS modules up to spec re test coverage and API docs. I also spent time adding tests for my PR on go-ipfs that improves our DHT CLI commands -- we'll soon finally have sharness DHT tests! :star:   Beyond that, some progress on my big go-ipfs CLI consistency/discoverability PR, and work on getting the broken ipget build in working condition again. 

- go-ipfs
  - [x] Revisions on big CLI consistency/discoverability PR (https://github.com/ipfs/go-ipfs/pull/2542)
  - [x] Revisions & tests on DHT CLI improvements PR (https://github.com/ipfs/go-ipfs/pull/2560)
- js-ipfs
  - [x] js-libp2p-tcp: test coverage, readme
  - [x] js-ipfs-repo: test coverage, readme
- ipget
  - [x] Worked on using gx to resolve conflicting deps + resultant panic

**Comment by RichardLitt** [comment]
Note: The sprint for this Monday will be on **Tuesday**, due to the meetup in Berlin taking place at the normal time for Europeans. 

All videos and the IRC hangout will happen at Tuesday at the normal times.

**Comment by nginnever** [comment]
<h2>Check-In</h2>

I spent the majority of my time finishing js-ipfs cat, get, add commands in core, cli, and http. There is only one issue left with the cli calling the http resources from js-ipfs-api and getting different responses than then expected or as shown in the test files. I may need to edit js-ipfs-api to add cooperating interfaces.

I began looking into libp2p as I plan to move toward the network stack after finishing data. I also began looking at whyrusleeping's libp2p-pub/sub code and learning more go-lang in preparation for creating dynamic ipfs applications

- js-ipfs
 - [x] cat command http-api
 - [x] get command http-api
 - [x] cat command core
 - [x] cat command http-api
 - [x] add command http-api
 - [x] add command rework core
- go-ipfs
 - [~] study go-lang
- pub/sub - crdt - ipld
 - [x] research
 - [ ] test what is already built

**Comment by RichardLitt** [comment]
#### Update

This week I went over the HTTP API spec with a fine comb, fixing all of the linting errors and working hard to make it web-ready. I did a lot of small stuff, such as PRing the website to add the weekly, opening question issues in community and FAQ, ordering hundreds of stickers with the new logo design, and reviewing the ipfs.pics blogpost. I worked on documentation for go-ipfs; I also went through all of the FAQ issues and added 'answered' labels where appropriate.

#### To Do

- [x] Sprint Management
- [x] Merged remaining 10 http-api-spec PRs
- [x] Merged all open guideline PRs in ipfs/community
- [x] Ship Weekly 9
- [~] Write and ship Weekly 10 (done)
- [~] Make an IPFS NYC Meeting blogpost (waiting on one set of slides)
- [x] Organize April 20th MIT Meetup
  - [~] Write roundup afterwards (waiting on video)

**Comment by haadcode** [comment]
#### Sprint end update - 18 Apr - 3 May
Spent a good time figuring out CRDTs and how to use them in orbit-db. Found a solution and implemented counters in orbit-db (G-Counter CRDT). Refactored orbit-db as per feedback and modularized it even further. Rest of the sprint was spent at Squatconf and organizing the IPFS Berlin Meetup. The meetup was last night, live-streamed and overall it went well.

**Comment by whyrusleeping** [comment]
This last week i put a bunch of effort into diagnosing and fixing libp2p issues. I have completed the swarm dialing refactor and i'm gonna start getting that all merged in. I also addressed some issues with bitswap using an inordinate amount of memory randomly, part of the problem was base58 encoding taking way too long, and the other half was making too many find provider calls we we'rent cancelling.

Aside from that i pushed my pubsub code up to github, along with a branch of go-ipfs that uses it. 

go-multiaddr has some really inefficient parsing code in it, so i pushed up a PR to make that a little better. It was actually the cause of a lot of excess CPU time on the gateways. 

Beyond CodeStuff (tm) I put more work into gx-ifying our packages while still leaving them `go get`able. go-libp2p is *almost* installable and usable through go get, just one pesky PR i need to get merged upstream.

**Comment by noffle** [comment]
Last week I was at squatconf in Berlin, which had lots of great discussions at and around it. Much of the week was travel and working on my talk. The slides are on https://github.com/noffle/talks and there's a recording on youtube.
                                                                                                       
I also wrote https://github.com/noffle/ipfs-twitter-resolver, which resolves a `/twitter/user/key` addr to an IPFS address (handy for pointing to your IPFS blog's/website's location without running a daemon). Centralized IPNS-like mutable pointers! Still in Berlin this week; expecting to be back by next weekend!

**Comment by lgierth** [comment]
# @lgierth sprint update

From my side, not much IPFS-related happened this week.

I spent the first week in Toronto hacking on the cjdns android app with benhylau, and we got it working without root in the end, so now nothing stops us from publishing it in the Play Store (in addition to F-Droid). It needs a few more features to become really useful, e.g. sharing one's IPv6 address.

The second week was spent traveling back to Europe, and attending Squatconf.

- go-ipfs
  - [x] backport and deploy ipfs/go-ipfs#2549 to v03x ipfs/go-ipfs@0-3-stable
  - [x] update go-libp2p dependency ipfs/go-ipfs#2576
  - [ ] readme: mention building from source on windows ipfs/go-ipfs#2550
- infrastructure
  - [x] prevent gateways from dialing each other over cjdns (attempt at fixing slowness) ipfs/infrastructure@b34f10337cc3c27c35637d49633e8e4f1dd58a5a
  - [ ] deploy ssl wildcard cert
  - [ ] metrics: fix mtail's duplicate output
- DNS outage actionables
  - [ ] codify domains
  - [ ] prepare moving domains to gandi company account
  - [ ] better ipns tests
  - [ ] lower ttl for all ipfs.io zones
  - [ ] postmortem blog post
- weekly
  - [x] add things to it
  - [x] pick a content-type of the week
- pages
  - [ ] get `ssh <page>@pages.ipfs.team deploy <hash>` working
