### ISSUE TITLE
Sprint: May 16 → May 30th

### ISSUE THREAD

**Issue by RichardLitt** [ipfs/pm#109]
## Sprint Discussions

[Schedule](https://github.com/ipfs/pm#sprint-discussion-schedule)

Please take notes in a separate pad, if you can, and link it here.

Endeavour         | Lead            | Time (PDT - **UTC/Z** - CEST) | Pad
:---------------: | :-------------: | :--------------------------: | :----:
sync              | @RichardLitt    | 9:00PDT **16:00Z** 18:00CEST  | IRC: #ipfs on Freenode
apps on ipfs      | @dignifiedquire | 10:30PDT **17:30Z** 19:30CEST | https://public.etherpad-mozilla.org/p/ipfs-may-16-apps-on-ipfs
infrastructure    | @lgierth        | 11:00PDT **18:00Z** 20:00CEST | https://public.etherpad-mozilla.org/p/ipfs-may-16-infrastructure
js-ipfs task force mega sprint            | @diasdavid      | 11:30PDT **18:30Z** 20:30CEST | https://public.etherpad-mozilla.org/p/ipfs-may-16-js-ipfs-task-force
go-ipfs           | @whyrusleeping  | 12:30PDT **19:30Z** 21:30CEST | https://public.etherpad-mozilla.org/p/ipfs-may-16-go-ipfs

Please add the Agenda to the Pad before the endeavour sprint starts.

## Sprint Deliverables

- Add your tasks below in a comment, that way we only have people listed who are really in the sprint
- Add links to issues down here. Only add things you can finish this sprint.

**Comment by lgierth** [comment]
Timezones are off, fixed in #110

**Comment by RichardLitt** [comment]
Thank you.

**Comment by dignifiedquire** [comment]
##Apps on IPFS

#### Lead: @dignifiedquire

#### Participants

- @haadcode 
- @whyrusleeping
- @diasdavid
- @dignifiedquire
- @Kubuxu
- @RichardLitt 

## Notes

### Orbit Update
  - write improvements (100 ops/sec)
  - Akasha wants to use orbit-db
  - Added user auto complete
  - Emoji auto complete + preview coming soon
  - Next Level: orbit-db in the browser, orbit in the browser, everything in the browser :)
  
### https://ipfs.io/ipns/bin.ipfs.ovh
- Kubuxu if the work on orbit-db would help adding write access to his pastebin style project
- Answer, mostly no but js-ipfs will help by having your own node in the browser connecting to other (potentially browser) nodes and
  sharing the content

### ipfs-twitter-resolver
- Storing "ipns records" in a tweet

### Demo of gx from whyrusleeping

- deps tree 
- pinning site for gx packages

**Comment by lgierth** [comment]
## Infrastructure

#### Lead: @lgierth

#### Participants

## Agenda

- SSL
  - HSTS preloading
  - http=>https redirect
- metrics stability
  - mtail bug
  - flakey cjdns routing
- pages deploys
  - it's in progress, but not yet working :)

## Notes

- /version commit needs to be fixed
- whyrusleeping wants to be able to use provsn
  - provsn needs secrets handling
  - provsn needs host grouping
  - provsn needs parallelism (it's sooooo sloooow)
- lgierth badly wants to not be a bottleneck for others (pages && provsn)

**Comment by lgierth** [comment]
### @lgierth todo

- js-ipfs crunch
  - [ ] deploy websockets bootstrappers
  - [ ] p2p_peers_total metric by transport
- infrastructure
  - [ ] stop being a bottleneck
    - [ ] provsn secrets handling
    - [ ] provsn parallelism
    - [ ] make `ssh <page>@pages.ipfs.team publish <hash>` work
  - [ ] fix /api/v0/version#CurrentCommit
  - [ ] fix cjdns routing
  - [ ] figure out http/https redirect logic
  - [ ] fix mtail double-metric bug
- go-ipfs
  - [ ] figure out CORS problems
- various
  - [ ] newsletter content
  - [ ] move domains to protocol labs account

**Comment by dignifiedquire** [comment]
@dignifiedquire Todo

- Workshop preparation 
- "Introduction to IPFS" Talk preparation
- Help out @diasdavid and @haadcode where I can with demos and all the things js-ipfs
  - First steps: 
    - https://github.com/haadcode/orbit-db/pull/5
    - https://github.com/haadcode/ipfs-log/pull/5

**Comment by diasdavid** [comment]
# JS IPFS TASK FORCE MEGA SPRINT

> This is a joint hangout to sync in the latest details to get js-ipfs out the door and some really cool examples working on it.

#### Lead: @diasdavid (David Dias)

#### Participants

- David
- Richard
- Friedel
- Kuba
- Samuli
- Nathan

## Agenda

- Status Update
- What is left
- Assign Tasks and try to come up with ETA
- Make sure we are not missing anything


## Notes

**Features**

- [ ] 100% js-ipfs-api and js-ipfs interface matching
  - [ ] complete interface-ipfs-core https://github.com/ipfs/interface-ipfs-core
  - [ ] update both API accordingly
- WebRTC Transport (@diasdavid) 
  - [ ] full mesh
  - [ ] packet switching 
- [ ] (go-ipfs) support the right multicodecs https://github.com/ipfs/go-ipfs/issues/1549 (@whyrusleeping)
- [ ] (go-ipfs) websockets support (@whyrusleeping)
  - [ ] https://github.com/jbenet/go-multiaddr-net/pull/15
- [ ] http endpoints for get, add, and cat working 100% (@nginnever)
  - [ ] Separate get, add and cat into different PR
  - [ ] Create an issue with the constructed http-response from get so that we can infer what is wrong
  - notes: current PR:
     - js-ipfs: https://github.com/ipfs/js-ipfs/pull/205
     - js-ipfs-api get: https://github.com/ipfs/js-ipfs-api/pull/271
     - interface core spec: https://github.com/ipfs/interface-ipfs-core/pull/8
- [ ] change multiaddr from /websockets to /ws only

**Orbit on js-ipfs**

- [ ] orbit
  - [ ] on js-ipfs
  - [ ] on js-ipfs browser connected to a js-ipfs Node.js node
  - [ ] on js-ipfs browser nodes connected through WebRTC
- [ ] orbit-db
  - [ ] get core-ipfs api spec for `ipfs cat`
- [ ] ipfs-log
  - [x] Working (+ tests) with js-ipfs

**Demos**

> Create easy to reproduce demos with good visualizations of what is going on:

- Load an Image from js-ipfs (through blocks)
- Load a Video from js-ipfs (through blocks) using the MediaSourceAPI
- Load a modular app (load pieces of the app by clicking "Load this piece"

**Infrastructure**

- [ ] WebSockets in some Bootstrap nodes (ws.ipfs.io to just balance between those) @lgierth 
- [ ] metrics for peers count by transport (/tcp, /udp/utp, /ws) @lgierth 

**robustness and interoperability**

- [ ] libp2p interop tests (@diasdavid)
- [ ] bitswap interop tests 

**Good to have**

- [ ] js-ipfs-api module quality

**Comment by Kubuxu** [comment]
### @Kubuxu todo:

#### go-ipfs:
* [ ] Fix minor bugs:
 * [ ] https://github.com/ipfs/go-ipfs/pull/2718
* [ ] QoL changes:
 * [ ] https://github.com/ipfs/go-ipfs/pull/2706
* [ ] Features:
 * [ ] Offline mode: https://github.com/ipfs/go-ipfs/pull/2696
* [ ] Take over AUR go-ipfs-git
 * [x] Fix it
 * [x] add ipfs.service user service file
 * [x] bump version

**Comment by RichardLitt** [comment]
## go-ipfs

#### Lead: @whyrusleeping

#### Participants

- whyrusleeping
- kubuxu
- jbenet
- RichardLitt
- daviddias
- dignifiedquire
- noffle

## Agenda

- https://github.com/ipfs/specs/issues/98
- yamux bug
- multistream name compat
- tests greener?
- issue triage
- bitswap stream reuse


## what we need for the demos

tag these with "dev", "solarnet", and/or "release" based on what we NEED and WANT by **May 29**

(ordered by priority)
- yamux bug fixed (NEED: dev + solarnet, WANT: release)
- websockets in go-ipfs (NEED: dev solarnet, WANT: release)
- multstream name fixes (NEED: dev + solarnet, WANT: release)
- relay in go-ipfs (NEED: dev + solarnet, WANT: release)
- metrics change to monitor peers per transport (NEED: solarnet)

- CORS issue api


**You have 30 minutes for this agenda**, 5 minutes before the meeting ends, consider moving the remaining items to a github discussion thread so that all the other sprint meetings can start in time.

## Notes


##### After sprint meeting is finished, create the respective action items on the Github sprint issue

**Comment by dignifiedquire** [comment]
Mid-week hangout will be happening now, at 12:10noon EDT, 9:10am PDT, 6:10pm CEST, 4:10pm UTC.

**Comment by Kubuxu** [comment]
### @Kubuxu sprint summary

During this week I worked on resolving some issues, and introducing few QoL changes. I also kept the go-ipfs issues and PRs up to date as @whyrusleeping was on a trip. Most notably the offline mode of go-ipfs (no p2p connections, still provides local content and API) works but might still require few changes. I also moved some go-ipfs dependencies from Godeps to gx, it seems simple at first but is quite a bit of work.


#### go-ipfs
* [ ] Offline mode
 * [x] fixed issue that showed up last time and added tests
 * [ ] review - https://github.com/ipfs/go-ipfs/pull/2696
* Quality of Life changes:
 * [x] Add --format option to mfs stat command - https://github.com/ipfs/go-ipfs/pull/2706
 * [x] Allow to specify where to put default options in option description - https://github.com/ipfs/go-ipfs/pull/2744
* Bugfixes:
 * [x] Make ipfs config edit run on client - https://github.com/ipfs/go-ipfs/pull/2718
 * [x] Require diag cmds command to run on daemon - https://github.com/ipfs/go-ipfs/pull/2761
 * [ ] Make RO API use Gateway's CORS headers - got stuck - https://github.com/ipfs/go-ipfs/tree/feature/GatewayCORS
* Docs:
 * [x] Remove note about Go1.6 not being supported - https://github.com/ipfs/go-ipfs/pull/2724
 * [x] Use one verbose flag description - https://github.com/ipfs/go-ipfs/pull/2746
 * [ ] Remove conflict of names in the debugging guide - https://github.com/ipfs/go-ipfs/pull/2752
* gx migrations - https://github.com/ipfs/go-ipfs/issues/2722:
 * [x] Wave one - https://github.com/ipfs/go-ipfs/pull/2733
 * [x] Wave two - https://github.com/ipfs/go-ipfs/pull/2736
 * [ ] Wave three - WIP - https://github.com/ipfs/go-ipfs/pull/2757
* Tests:
 * [ ] Add test for directly adding hidden file - https://github.com/ipfs/go-ipfs/pull/2756

#### General
* Discuss UNIX socket based API - https://github.com/ipfs/notes/issues/129
* Propose bloom frequency table based garbage collector - https://github.com/ipfs/notes/issues/130
* Fix gx-go not working on symlinked workspaces - https://github.com/whyrusleeping/gx-go/pull/8

**Comment by dignifiedquire** [comment]
@dignifiedquire sprint summary

The past two weeks were fast paced but exciting. I prepared and gave my first talk on IPFS at my local meetup. In addition to that I nearly finished my implementation of secio in JavaScript. There is just one racing condition fix and some integration work to be done there. And all the rest of my time was spent helping @diasdavid and @haadcode to get js-ipfs in the best shape possible, including an important fix to js-bitswap to ensure blocks are actually distributed to everyone.

--- 

- [ ] "Introduction to IPFS" Talk 
  - [ ] Prepare talk
  - [ ] Give talk
- [ ] Help out @diasdavid and @haadcode where I can, with demos and all the things js-ipfs
  - [ ] https://github.com/haadcode/orbit-db/pull/5
  - [ ] https://github.com/haadcode/ipfs-log/pull/5
  - [ ] Fix issues in bitswap: https://github.com/ipfs/js-ipfs-bitswap/pull/17
- [ ] Secio
  - [ ] [libp2p-crypto](https://github.com/ipfs/js-libp2p-crypto)
  - [ ] [libp2p-secio](https://github.com/ipfs/js-libp2p-secio)
  - [~] Integrate into libp2p-swarm: https://github.com/diasdavid/js-libp2p-swarm/pull/67

**Comment by diasdavid** [comment]
## David Dias Check In

> **Summary:** This last sprint (2 weeks) have been super intense, having a clear, common goal (shipping orbit on js-ipfs) + getting js-ipfs milestone one ready, has given the team an immense focus on a set of things that were crucial to achieve those goals, making everyone working very closely together and that feeling has been amazing :).

----- 

Here is a gist of things I've been focused on:

- [x] Debug and fix things for go & js IPFS interop with @whyrusleeping. There are still some missing parts, but we know what to do (mostly, move js-ipfs Identify to use length-prefixed-messages as well)
- [x] Made libp2p-webrtc-star, a WebRTC Transport for libp2p, enables Orbit peers to use IPFS just from a browser tab
- [x] Lot's of fixes on spdy, tcp, websockets, identify, duplex streams that were not being wrapped properly, fix identify that was not working on the browser (cause of the missing keys).
- [x] libp2p-ipfs got a face wash and now it is less fragmented between the internals of js-ipfs and libp2p itself
- [x] Lot's of more test coverage
- [x] Havoc tests (blow up processes so that the others stay intact)
- [x] Worked with @ngginever and @noffle on interface-ipfs-core 

- Community
  - [x] IPFS talk at require('lx')
  - [x] Prepare talk for WebRebels

**Comment by haadcode** [comment]
### @haadcode sprint end report - 16 May - 29 May
#### Summary
I've worked on getting Orbit to run in the browser with js-ipfs (https://github.com/haadcode/orbit/tree/js-ipfs). We've been making very good progress and as of couple of days ago, we got it all working! \o/ It's still brittle so the next steps are to make it more stable and performant. Nevertheless, a huge kudos to the JS team, you've made awesome work so far! Also helped the Akasha project to integrate orbit-db and they wrote a really nice blog post describing what they achieved with it (http://blog.akasha.world/2016/05/26/update-highlights-and-interesting-developments/).

**Comment by noffle** [comment]
## noffle check in

I've been focusing all my efforts on driving the JS IPFS Core API interface effort ([interface-ipfs-core](https://github.com/ipfs/interface-ipfs-core)), with @nginnever and @diasdavid. I'm just about done with 'add', which had a lot of edge cases to get unified across js-ipfs-api and js-ipfs. Richard and I got cracking on the remaining work for releasing standard-readme.

**Comment by RichardLitt** [comment]
This week, I've been less productive than I hoped, because I have been travelling intensively. Mainly, I worked on some Standard-Readme stuff, PRs to http-api-spec, and making sure that awesome_bot works well with our newsletters. Today, I've merged some things to the website and to the blog. I also worked on presenting my endangered-languages repo to professional linguists at a conference; I'm hoping to turn it into an IPFS use-case for archiving academic code.

**Comment by nginnever** [comment]
<h2>voxelot</h2>
The past week i started off with more interface-core, js-ipfs-api, and js-ipfs work. There are some open PRs that will be revisited over the week, just little improvements / more features to js-ipfs cat, add, get. Also vacationing in Seattle at the moment enjoying the lovely green things and water!

**Comment by lgierth** [comment]
### @lgierth sprint update

Good sprint -- while team JS has been crunching away,
I took care of a couple of smaller things and fixes,
and prepared the infrastructure side of js-ipfs and Orbit.
It's not running yet, but all the steps are layed out.

Also made a bit of progress on the fc00 CryptoAuth and Switch specs.

I didn't finish my personal quest of stopping being a bottleneck to others, yet :)

- js-ipfs crunch
  - [ ] deploy the things needed
    - [ ] https://github.com/ipfs/infrastructure/issues/165
    - [ ] make others happy by having them deploy their own stuff :)
  - [x] p2p_peers_total metric by transport ipfs/go-ipfs#2728
    - [x] create graph http://metrics.ipfs.team/dashboard/db/0verview
  - [ ] catch go-ipfs crashes on gateways/bootstrappers
  - [x] changelog for go-ipfs 0.4.2 ipfs/go-ipfs#2714
  - [x] update dist.ipfs.io and update.ipfs.io records
  - [x] point install doc on website to 0.4.2
- infrastructure
  - [ ] stop being a bottleneck
    - [ ] provsn secrets handling
    - [x] provsn parallelism
    - [ ] make `ssh <page>@pages.ipfs.team publish <hash>` work
  - [x] fix /api/v0/version#CurrentCommit
  - [x] fix cjdns routing ipfs/infrastructure@fc651c7
  - [ ] figure out http/https redirect logic
  - [x] ~~fix~~ workaround for mtail double-metric bug
- go-ipfs
  - [x] revert `ipfs init` regression in 0.4.2 ipfs/go-ipfs#2749
  - [x] build: specify a dist.ipfs.io hash ipfs/go-ipfs#2711
  - [ ] add ipns-pub to dist
  - [ ] add netbsd build to dist ipfs/distributions#64
  - [ ] ~~figure out CORS problems~~
- various
  - [x] deploy weekly \#10
  - [ ] deploy newsletter
  - [ ] newsletter content
  - [x] recover fc00 spec drafts from old laptop fc00/spec#2 fc00/spec#3
  - [ ] move domains to protocol labs account
    - [ ] prepare drill list

**Comment by whyrusleeping** [comment]
@whyrusleeping's checkin

The first week of sprint I spent a lot of time working with @diasdavid on go and js interop, I *think* we figured out all of the current issues preventing us from talking across implementations, but before i was certain of that i flew to mexico and had no internet for a week.

**Comment by jbenet** [comment]
### @jbenet udpate

This last sprint I've been focused mostly on IPFS and Protocol Labs organizational things. Some highlights: 

- Working with a company who is revamping our ipfs.io website. It looks very exciting. Stay tuned!
- Collab/org discussions with: 
  - Akasha http://akasha.world/
  - Stellar
  - BigchainDB
  - Estonian E ID group
  - Mediachain
  - Internet Archive
  - ConsenSys / uPort
  - Blockstack
  - W3C members
- Participated in http://weboftrust.info last weekend, which is an identity workshop/conf for emerging tech to be used in Identity. Participated there with many of our friends, including @nicolagreco. Spoke with many people about standards relevant, including IPLD, Keychain, multikey, and more.
- Some small code review here and there.
- Planning + prep for the Decentralized and Encrypted conference - I'm in Berlin this week for it!
- Planning + prep for the Decentralized Web Summit - i'm in SF next week for it!

**Comment by nicola** [comment]
#### @nicola update
- participated at rebooting the web of trust with @jbenet @manusporny & friends. Got up to speed with what is happening with Decentralized IDentifiers ()
- read interesting papers on verifiable computations, causal chains, BFTs (and clever tricks for DHTs), distributed pubsub and the different proposal to scale bitcoin
- preparing for the decentralized web summit (sf next week)
- worked on [js-gossip-cyclon](https://github.com/nicola/js-gossip-cyclon) new api
