### ISSUE TITLE
Sprint J

### ISSUE THREAD

**Issue by whyrusleeping** [ipfs/pm#11]
**Sprint Goals**:

This sprint is focusing on making ipfs more robust and dependable, api tests, crash fixes, and maybe even a little perf as we prepare for new features (electron shell, dht records improvements)

**Sprint Participants**:

- @whyrusleeping @krl @cryptix @wking @jbenet @tv42 @gatesvp @chriscool @rht @harlantwood @dylanPowers @daviddias

**Sprint Deliverables**:

#### @whyrusleeping
- [x] util.Key -> block.Key
- [ ] take a look at spdystream issues https://github.com/jbenet/go-peerstream/pull/9
- [ ] https://github.com/ipfs/go-ipfs/pull/1187
  - [x] https://github.com/ipfs/go-ipfs/pull/1299 patch command
- [x] https://github.com/ipfs/go-ipfs/issues/1241 network write latencies
- [x] implemented go-multistream and a netcat tool to help interact with it

#### @krl
- [ ] https://github.com/ipfs/go-ipfs/issues/1153
-- i'll add ipfs brand, and hand over to someone for go integration
- [x] electron shell app https://github.com/ipfs/webui/54
- [ ] electron shell app polish and packaging
- [x] node-ipfs-api test coverage
- [ ] node-ipfs-api for multiple nodes, dht, etc
- [x] publish new version of webui

#### @jbenet

- [x] weigh in on  github.com/ipfs/go-ipfs/issues/1291
- [x] CR patch
- [x] issues for @lgierth infra.
- [ ] ipfs single-file micro-spec / interfaces
- [ ] get a build of go-ipfs for node-ipfs compatibility
- [ ] readme on how to implement ipfs on another lang
- [ ] merge pinning
- [x] CR migration
  - https://github.com/ipfs/fs-repo-migrations/pull/7
- [x] CR S3

#### @tv42 
- [ ] pinning in blockstore (merge)
  - blocked on https://github.com/ipfs/fs-repo-migrations/pull/7
- [ ] pinning perf? log?
- [ ] s3 datastore

#### @gatesvp
- [ ] https://github.com/ipfs/go-ipfs/issues/1211 ipfs refs --recursive --unique is not recursive
- [ ] https://github.com/ipfs/go-ipfs/pull/1232 - .ipfsignore support

#### @wking
- [ ] start working on an IPFS storage driver for https://github.com/docker/distribution
- [ ] https://github.com/ipfs/go-ipfs/pull/1151

Probably won't get to:
- [ ] https://github.com/ipfs/go-ipfs/pull/1136 (partially blocked on reviewing the API in https://github.com/ipfs/go-ipfs/issues/1291 )

#### @rht
- [ ] https://github.com/ipfs/go-ipfs/pull/1279
- [ ] https://github.com/ipfs/go-ipfs/issues/740
- [ ] https://github.com/ipfs/go-ipfs/issues/143
- [ ] https://github.com/ipfs/go-ipfs/issues/593
- [ ] https://github.com/ipfs/go-ipfs/issues/1060
- [ ] https://github.com/ipfs/go-ipfs/issues/555
- [ ] https://github.com/ipfs/go-ipfs/issues/1030
- [ ] CR bot formalizing guidelines into literate code (go lint & vet should be put here instead), constraint that commits can't fail the test at any point in history

#### @cryptix 
- [ ] support /tcp/0 properly by putting actual used addresses into the repo dir for CLI to look them up
- [ ] fix wrietable http gw - PUT is still broken
- [ ] https://github.com/ipfs/go-ipfs/pull/1287 (print after opening listener)
- [ ] talk with @blame about the 'client only' mode from https://github.com/ipfs/go-ipfs/issues/1118

#### @harlantwood
- [ ] https://github.com/ipfs/webui/issues/56 spike on graph viz of DAG data

#### @lgierth
- [ ] https://github.com/ipfs/go-ipfs/pull/1316 discover peers from cjdns
- [ ] Lay out more possible integrations with cjdns
- [ ] Gateway stuff
- [ ] One or two easy bugs

#### @dylanPowers
- [ ] https://github.com/ipfs/website/issues/13 Check for dead links on the website

#### @diasdavid
- [ ] spec minimum necessary for node-ipfs to work 
- [ ] node-ipfs revamp 

#### triage - anyone can pick these up
- [ ] https://github.com/ipfs/go-ipfs/issues/1289
- [ ] https://github.com/ipfs/go-ipfs/issues/1248 fix fuse unmount
- [ ] https://github.com/ipfs/go-ipfs/issues/1222 add uses a lot of ram and cpu
- [ ] daemon init cleanup
- [ ] https://github.com/ipfs/go-ipfs/issues/1224 decimate eventlog 
- [ ] merge https://github.com/ipfs/go-ipfs/pull/1277
- [x] use latest version of cheggaaa/pb to fix some races: https://github.com/ipfs/go-ipfs/issues/1012
- [ ] https://github.com/ipfs/go-ipfs/issues/1246 Avoid dialing known local addresses when not in that network
  - posted iptables commands to help issue
- [ ] https://github.com/ipfs/go-ipfs/issues/1247 Config option to disable dialing specific subnets entirely

**Comment by jbenet** [comment]
Made https://github.com/jbenet/ipfs-vbox

**Comment by harlantwood** [comment]
_DAG visualized as D3 tree_ now has it's own issue in the new dataviz repo: ipfs/dataviz#1

**Comment by jbenet** [comment]
Let's be careful who we tag for @dylanPowers (so far we've tagged dpowers, dylan)

**Comment by jbenet** [comment]
Hey everyone, some tweaks to the sprint meeting + community hangout details: https://github.com/ipfs/community/issues/28

**Comment by harlantwood** [comment]
Can't make meetings today, but added updated dataviz tasks to the etherpad.

**Comment by whyrusleeping** [comment]
etherpad link for next sprint: https://etherpad.mozilla.org/Fo3cmIE6jk
