### ISSUE TITLE
Sprint: June 20 → July 3

### ISSUE THREAD

**Issue by RichardLitt** [ipfs/pm#114]
# Sprint June 20th -- July 3rd

This sprint, instead of having the long 30-minute discussions, we are having another short video sprint. This is because of travel issues and vacation for many endeavors, and because of a tight schedule at the moment for a few people working on IPFS.

**For this sprint** please do the following:
- Put your **completed tasks** in the [old sprint issue](https://github.com/ipfs/pm/issues/112).
- Put your To Do items for the upcoming sprint in the Etherpad for the video sprint **before** the sprint. (I'll ping you about this, if you're in the [active contributor list](https://github.com/ipfs/pm#active-contributors)).
- Finalize your To Do items during the hangout and put them in this issue by Tuesday, June 21st, the Solstice. ☀️ 

## Sprint Discussions

[Schedule](https://github.com/ipfs/pm#sprint-discussion-schedule)

Endeavour         | Lead            | Time (PDT - **UTC/Z** - CEST) | Pad
:---------------: | :-------------: | :--------------------------: | :----:
Video sync              | @RichardLitt    | 11:00PDT **17:00Z** 19:00CEST  | https://public.etherpad-mozilla.org/p/ipfs-june-20-video-sync

@RichardLitt will post the Hangout link on the IRC channel, as normal. 

## Participants

@whyrusleeping
@diasdavid
@Kubuxu
@lgierth
@nicola
@em-ly
@richardlitt

## Sprint Deliverables

- Add your tasks below in a comment, that way we only have people listed who are really in the sprint
- Add links to issues down here. Only add things you can finish this sprint.
- Add your To Dos in Markdown format. That means using `- [ ]`, which GitHub automatically converts to a checkbox.
- As the sprint progresses, refer back to this issue and check of any tasks you have done, and subdivide, delete, or add tasks accordingly. That way, the list at the end gives an accurate depiction of what was done this sprint.
- If anyone seems to be doing something you could do, approach them and see if you can take any of their tasks. Likewise, if you have too much.

**Comment by RichardLitt** [comment]
## @RichardLitt To Do

#### go-ipfs
- [ ] @whyrusleeping, @chris: Go-ipfs GitHub Issue Templates https://github.com/ipfs/go-ipfs/issues/2770 https://github.com/ipfs/go-ipfs/pull/2786
- [~] Make a How To File An Issue file for go-ipfs https://github.com/ipfs/go-ipfs/pull/2786
- [ ] CLI interop for js-ipfs and go-ipfs
- [ ] Write helptext for all commands https://github.com/ipfs/go-ipfs/pull/2648

#### Blog
- [ ] Rewrite "Static Web Publishing with IPFS - Simpler and Decentralized" https://github.com/ipfs/blog/pull/31
- [ ] Rewrite "Blog post detailing quick install of IPFS latest" https://github.com/ipfs/blog/pull/8/files
- [ ] Spruce up ipfs.pics blogpost
- [ ] Start new newsletter
- [ ] Publish or destroy IPFS Weekly 11

#### name-your-contributors
- [ ] Fix name-your-contributors empty-repo bug: https://api.github.com/repos/ifps//issues isn't right.

#### github-task-status
- [~] Build badge to check issue lists https://github.com/ipfs/pm/issues/111
  - [x] Started work at https://github.com/RichardLitt/github-task-status/issues/1
  - [ ] Enable grabbing items from a list of URLs to check
  - [ ] Set up as a server-side task that runs on a cron-job
  - [ ] Make a GitHub bot to add issues to a list
  - [ ] Enable for sublists
    - [ ] Like this one
  - [ ] Enable for comments that aren't the first in the issue
  - [ ] Check completion of tasks from issues linked in one issue

#### ipfs-http-api
- [ ] Go through issues and open PRS on ipfs-http-api with fine comb
- [~] Standardize returns (errors + formats) on API
- [~] Ship ipfs-http-api (on it)
  - [~] Put up publicly on Apiary
    - [x] Publish on Apiary
    - [ ] Talk about it
      - [ ] Draft a blog post
      - [ ] Link on the website
    - [ ] Check in with @diasdavid about using for the clientbase
    - [ ] Link @jbenet and @daviddias to talk about automating generation of the CURL requests in the spec

#### READMEs
- [~] Standardize Readmes across all IPFS repos https://github.com/ipfs/community/issues/124
- [ ] Add roadmap / readme list of modules for js-ipfs https://github.com/ipfs/js-ipfs/issues/271
- [ ] Fill out usage docs and API section for https://github.com/ipfs/go-ipfs-api README.md
- [ ] README spruce for interface-ipfs-core https://github.com/ipfs/interface-ipfs-core
- [ ] Make generator-nms compliant with stdmd https://github.com/RichardLitt/generator-nms/issues/12
- [ ] Improve community information:
  - [ ] Project repos page - Check up on all issues
  - [ ] Fix CI reporting - check up on with @HarlantWood

**Comment by Kubuxu** [comment]
@Kubuxu - TO-DOs
----------
### go-ipfs:
* [ ] - get my PRs merged
* [ ] - Improve write cache - https://github.com/ipfs/go-ipfs/issues/2850
  * [x] - find good bloom filter impl - https://github.com/AndreasBriese/bbloom
    * [ ] - tweak it for our use - https://github.com/gxed/bbloom
    * [ ] - publish to gx
* [ ] - migrate go-fuse to gx - it is last big dep in Godeps
* [ ] - work on core-api with @lgierth to also work well for FUSE

### Misc
* [ ] - clean up [hasteIPFS](https://github.com/Kubuxu/hasteIPFS)
* [ ] - learn about Eth's Smart Contracts as a comment aggregation medium
* [ ] - setup HTTP redirect server to global gateways: `http://bin.ipfs.ovh -> https://ipfs.io/ipns/bin.ipfs.ovh`

**Comment by diasdavid** [comment]
## David Dias Task List 📝 

[**From the `js-ipfs` Captain Log**](https://github.com/ipfs/js-ipfs/issues/30)
  - [ ] ⏫ Finish the remaining items on `libp2p Transports + Connection` section
  - [ ] ⏫ Finish the remaining items on `go and js interop`
  - [ ] ⬆️ Finish the remaining items in `libp2p UX`
  - libp2p new features
    - [ ] ↕️ multicastDNS
    - [ ] ↕️ ping
    - [ ] ↕️ secio
  - [ ] ↕️ Isolate tests
  - [ ] ↕️ js-ipfs compatible with iptb
  - [ ] ↕️ Complete the interface-ipfs-core
**Other goals**
  - npm on ipfs
    - [ ] ↕️ rename registry-mirror to ip-npm
    - [ ] ↕️ update the CLI interface (following the discussed interface)
    - [ ] ↕️ dogfood my npm needs with registry-mirror (set up a node at home with whole npm on RPI)
  - [ ] ↕️ set up network testbed (connect my remaining rpi to my routers for a test bed

I'm experimenting a new thing, adding priority to my tasks, so that others now if I'm still super busy with really important priorities or if I'm just doing 'stuff'. This way, if something comes up in the middle (which always comes), I can also tag it with priority and that way, I can evaluate if I did well bumping the priority of something else face of what were the primary needs.

**Legend**
- ⏫ Top Priority
- ⬆️ Next
- ↕️ Regular

**Comment by lgierth** [comment]
### @lgierth todo

- infrastructure
  - [ ] issues triage
  - [ ] provsn secrets handling
- misc
  - [ ] v03x EOL blog post
  - [ ] newsletter content
- go-ipfs-gateway extraction
  - [ ] clean up the surface ipfs/go-ipfs#2874
  - [ ] implement and use core-api ipfs/go-ipfs#2876
  - [ ] extract to go-ipfs-gateway
- website
  - [ ] fix standalone blog
  - [ ] add ipns-pub to dist

**Comment by nicola** [comment]
## nicola's task

DONE
- [x] got up to speed with Filecoin/Cube
- [x] written down a roadmap for IPLD https://github.com/ipfs/specs/issues/112

TODO
- [ ] do further work on IPLD selectors / IPLD transforms
- [ ] read on pub/sub (possibly clean up gossip-cylcon) 
- [ ] write down a structure for a possible IPLD paper
- [ ] write down about `family URI` (to be discussed)
- [ ] further readings on BFT

**Comment by Kubuxu** [comment]
@Kubuxu - Mid-sprint Updates
----------
### go-ipfs:
* [x] - get my PRs merged
* [ ] - get my new PRs merged
* [ ] - Improve write cache - https://github.com/ipfs/go-ipfs/issues/2850
  * [x] - find good bloom filter impl - https://github.com/AndreasBriese/bbloom
    * [x] - tweak it for our use - https://github.com/gxed/bbloom
    * [x] - publish to gx
  * [x] - implement `Has` bloom filtering
  * [x] - implement `Has` ARC caching
  * [x] - get blocked on http://github.com/ipfs/go-ipf#2601
  * [ ] - wait for http://github.com/ipfs/go-ipf#2601 to be resolved
* [ ] - migrate go-fuse to gx - it is last big dep in Godeps
* [x] - work on core-api with @lgierth to also work well for FUSE
* [x] - work with @em-ly on labels/issue organisation
* [x] - update go-log across the go-ipfs subprojects
* [x] - PR: read rehashing for blockstore - https://github.com/ipfs/go-ipfs/pull/2904
* [ ] - PR: resolve symlinks if they are directly referenced in path - https://github.com/ipfs/go-ipfs/pull/2897
  * [ ] - more tests

### Misc
* [ ] - clean up [hasteIPFS](https://github.com/Kubuxu/hasteIPFS)
* [x] - refresh Ethereum knowledge
* [ ] - setup HTTP redirect server to global gateways: `http://bin.ipfs.ovh -> https://ipfs.io/ipns/bin.ipfs.ovh`

**Comment by RichardLitt** [comment]
#### Mid-week updates

This week, I wrote around 100 pull requests, standardizing READMEs and licenses across the organization. That sums it up for me. 

- [x] Open up community issue about context-leaders
- [x] Go-ipfs GitHub Issue Templates https://github.com/ipfs/go-ipfs/issues/2770 https://github.com/ipfs/go-ipfs/pull/2786
- [x] Make a How To File An Issue file for go-ipfs https://github.com/ipfs/go-ipfs/pull/2786
- [x] Standardize Readmes across all IPFS repos https://github.com/ipfs/community/issues/124

**Comment by whyrusleeping** [comment]
## Whyrusleeping mid-week update

the biggest thing i worked on last week was getting the path clean bug resolved. We've decided to base32 encode all binary keys before creating datastore keys with them. This will unblock a bunch of other PRs and fix a few fairly major issues we have.

Beyond that, i've been working on writing providers to disk so as to not keep them in memory. Fixing this will fix the largest cause of memory bloat in long running ipfs daemons.

**Comment by diasdavid** [comment]
During last week, I've been focused on refactoring our libp2p transports, stream muxer, swarm and libp2p builds, introducing the new Identify protocol (new as in: "working like go-ipfs"). This work was a dependency of getting go-ipfs and js-ipfs interop. I'm currently checking (hoping to finish today) if everything is ok now. Will try to tackle and check everything with @whyrusleeping while we have a overlap work time across timezones.

There were many PR's to achieve this, here is the list of the major ones. They can also be checked at the [Captain.log](https://github.com/ipfs/js-ipfs/issues/30#issuecomment-226043268)

![image](https://cloud.githubusercontent.com/assets/1211152/16387082/384b6314-3c8b-11e6-8730-c5bcad75f151.png)

**Comment by nginnever** [comment]
<h1>voxelot mid-sprint update</h1>

This week I worked a bit on js-ipfs add http and reviewed some first steps on js-ipfs-api get requests. Finished setting up a basic UI for a react/redux based distributed collaborative text editor running on orbit-db as well. 

- [ ] js-ipfs
 - [ ] add http
 - [ ] get http
- [ ] js-ipfs-api
 - [ ] get
- [ ] ipfs-pad

**Comment by diasdavid** [comment]
## David Dias Sprint Check In

> I'm posting this on Sunday, as I'm not 100% of my availability to be present this Monday. Will be out till the 12th of July.

This sprints was pretty exciting, we got js-ipfs and go-ipfs exchanging blocks with one another after all the _wire battles_, pretty energising moment. During the process, I've had the change to work a lot in the transport layer, improving our interfaces, implementations, integrations and (something that is very dear to me), adding more tests, enabling that code base to be more robust, without the feeling of 'cutting corners' to reach a quick goal. More on this can be seen on the [Mid Week Check in](https://github.com/ipfs/pm/issues/114#issuecomment-228796123)

Nevertheless, it is important to note that in order to get interop, a custom build of go-ipfs was required, simply because of some network assumptions in go-libp2p, namely that `secio` is assumed by default and that go-libp2p doesn't extract the public keys from the Identify protocol. More on https://github.com/ipfs/go-ipfs/issues/2738 and https://github.com/libp2p/js-libp2p-swarm/issues/78.

**Other things I did during this sprint were:**

- Work on a next version of ipfs-npm (previously known as registry-mirror)
  - https://github.com/diasdavid/npm-on-ipfs/issues/42
  - https://github.com/diasdavid/npm-on-ipfs/pull/43
- Write and Implement the config API spec
  - https://github.com/ipfs/interface-ipfs-core/pull/39
  - https://github.com/ipfs/js-ipfs-api/pull/307
  - https://github.com/ipfs/js-ipfs/pull/340
- Kick off and work towards js-ipfs-api ng https://github.com/ipfs/js-ipfs-api/pull/305
- Fix
  - Files Add promise API https://github.com/ipfs/js-ipfs-api/pull/314 (tests were not detecting it also, now they are)
- Other assorted PR CRs and merges
- Review and give feedback to @whyrusleeping on the fs-repo-migrations

**Blockers:**

  - Unixfs sharding for ipnpm
  - https://github.com/ipfs/go-ipfs/issues/2927

**I've had also some very good conversations with members on the IPFS community and some volunteered their free time to contribute to completion of the last entry of the js-ipfs Captain.log, you rock! ❤️. These tasks are:**

- finish up secio - https://github.com/libp2p/js-libp2p-secio - @dignifiedquire 
- Block API spec + tests - https://github.com/ipfs/interface-ipfs-core/pull/32 - @nginnever 
- Generic API spec + tests - https://github.com/ipfs/interface-ipfs-core/pull/33 - @nginnever 
- ipfsd-ctl with bin-wrapper - https://github.com/ipfs/js-ipfsd-ctl/issues/78 - @jgantunes
- integrate the ping protocol again - https://github.com/libp2p/js-libp2p-ping - @xicombd

As soon as I get back, one of my focused goals will be to complete the ipfs-api next generation, it is a dependency of many of our projects and the first door for many people in the community to try out IPFS and currently, it is kind of hard to use due to lack of good documentation, examples and specially, the code is just overly complex. We can make this way much better with https://github.com/ipfs/js-ipfs-api/pull/305. So, if someone wants to take part of it while I'm out, please do, your contributions are always super appreciated :)

**Comment by RichardLitt** [comment]
#### @RichardLitt check in

Last week, I worked on the [http-api-spec](http://github.com/ipfs/http-api-spec) a fair amount, closing issues and opening a few PRs, making sure that it is a bit more up to date. I also wrote a blogpost about it, [here](https://github.com/ipfs/blog/pull/63) that would <3 some review. On the blog side, I had a lot of discussions on how best to move forward on this, and set up Waffle.io to track our blogposts. I also tried to rework the ipfs.pics post, and have some more work to do on that. I worked on the CLI interop a tiny bit for js-ipfs and go-ipfs with @Kubuxu, but didn't have as much time for it as I wanted. 

I may have a been a bit overambitious in what I expected to do. 

### Updated TODOs

#### go-ipfs
- [x] @whyrusleeping, @chris: Go-ipfs GitHub Issue Templates https://github.com/ipfs/go-ipfs/issues/2770 https://github.com/ipfs/go-ipfs/pull/2786
- [x] Make a How To File An Issue file for go-ipfs https://github.com/ipfs/go-ipfs/pull/2786
- [~] CLI interop for js-ipfs and go-ipfs
- [ ] Write helptext for all commands https://github.com/ipfs/go-ipfs/pull/2648

#### Blog
- [ ] Rewrite "Static Web Publishing with IPFS - Simpler and Decentralized" https://github.com/ipfs/blog/pull/31
- [ ] Rewrite "Blog post detailing quick install of IPFS latest" https://github.com/ipfs/blog/pull/8/files
- [~] Spruce up ipfs.pics blogpost
- [ ] Start new newsletter
- [ ] Publish or destroy IPFS Weekly 11

#### name-your-contributors
- [ ] Fix name-your-contributors empty-repo bug: https://api.github.com/repos/ifps//issues isn't right.

#### github-task-status
- [~] Build badge to check issue lists https://github.com/ipfs/pm/issues/111
  - [x] Started work at https://github.com/RichardLitt/github-task-status/issues/1
  - [ ] Enable grabbing items from a list of URLs to check
  - [ ] Set up as a server-side task that runs on a cron-job
  - [ ] Make a GitHub bot to add issues to a list
  - [ ] Enable for sublists
    - [ ] Like this one
  - [ ] Enable for comments that aren't the first in the issue
  - [ ] Check completion of tasks from issues linked in one issue

#### ipfs-http-api
- [x] Go through issues and open PRS on ipfs-http-api with fine comb
- [x] Standardize returns (errors + formats) on API
- [x] Ship ipfs-http-api (on it)
  - [x] Put up publicly on Apiary
    - [x] Publish on Apiary
    - [x] Talk about it
      - [x] Draft a blog post
      - [x] Link on the website
    - [x] Check in with @diasdavid about using for the clientbase
    - [x] Link @jbenet and @daviddias to talk about automating generation of the CURL requests in the spec

#### READMEs
- [x] Standardize Readmes across all IPFS repos https://github.com/ipfs/community/issues/124
- [ ] Add roadmap / readme list of modules for js-ipfs https://github.com/ipfs/js-ipfs/issues/271
- [ ] Fill out usage docs and API section for https://github.com/ipfs/go-ipfs-api README.md
- [ ] README spruce for interface-ipfs-core https://github.com/ipfs/interface-ipfs-core
- [ ] Make generator-nms compliant with stdmd https://github.com/RichardLitt/generator-nms/issues/12
- [x] Improve community information:
  - [x] Project repos page - Check up on all issues
  - [x] Fix CI reporting - check up

**Comment by Kubuxu** [comment]
@Kubuxu - update
This week at fist glance didn't seem as productive as I wanted it to be, not PR and published code wise but at second glance I see that I've done quite a lot by gaining knowladge and planning ahead. I started working with @RichardLitt on [ipfs-mans](https://github.com/ipfs/ipfs-mans), I've extracted data form go-ipfs and structured it into YAML as can be seen [here](https://github.com/ipfs/ipfs-mans/tree/master/doc-src/ipfs). I've helped reviewing many PRs and finalized the bloom filtering of requests to blockstore (it is waiting for final merge https://github.com/ipfs/go-ipfs/pull/2885). I also refreshed my Ethereum and Solidity knowledge, learned about new security advisements and tools.
I experimented with injected interface pattern for Golang, were one package defines interface and other inject implementations of it. I planned to use it for go-log but it is something we should think about more before implementing it but it seems great pattern for metrics reporting.
