### ISSUE TITLE
Sprint: July 4 → July 10

### ISSUE THREAD

**Issue by RichardLitt** [ipfs/pm#119]
# Sprint July 4th → July 10th

This sprint, instead of having the long 30-minute discussions, we are having another short video sprint. This is because of travel issues and vacation for many endeavors, and because of a tight schedule at the moment for a few people working on IPFS.

**For this sprint** please do the following:
- Put your **completed tasks** in the [old sprint issue](https://github.com/ipfs/pm/issues/113).
- Put your To Do items for the upcoming sprint in the Etherpad for the video sprint **before** the sprint. (I'll ping you about this, if you're in the [active contributor list](https://github.com/ipfs/pm#active-contributors)).
- Finalize your To Do items during the hangout and put them in this issue by Tuesday, July 5th, the Solstice. ☀️ 

## Sprint Discussions

[Schedule](https://github.com/ipfs/pm#sprint-discussion-schedule)

Endeavour         | Lead            | Time (PDT - **UTC/Z** - CEST) | Pad
:---------------: | :-------------: | :--------------------------: | :----:
Video sync              | @RichardLitt    | 9:00AM PDT 12:00PM EDT 17:00 GMT 18:00 CEST  | https://public.etherpad-mozilla.org/p/ipfs-july-04-video-sync

@RichardLitt will post the Hangout link on the IRC channel, as normal. 

## Sprint Deliverables

- Add your tasks below in a comment, that way we only have people listed who are really in the sprint
- Add links to issues down here. Only add things you can finish this sprint.
- Add your To Dos in Markdown format. That means using `- [ ]`, which GitHub automatically converts to a checkbox.
- As the sprint progresses, refer back to this issue and check of any tasks you have done, and subdivide, delete, or add tasks accordingly. That way, the list at the end gives an accurate depiction of what was done this sprint.
- If anyone seems to be doing something you could do, approach them and see if you can take any of their tasks. Likewise, if you have too much.

**Comment by RichardLitt** [comment]
### My ToDos

## Public

#### project-repos
  - [ ] Improve community information by checking up on the project-repos page

### Current drafts:
  - [ ] Rewrite "Static Web Publishing with IPFS - Simpler and Decentralized" https://github.com/ipfs/blog/pull/31
  - [ ] Rewrite "Blog post detailing quick install of IPFS latest" https://github.com/ipfs/blog/pull/8/files

#### cli interop
  - [ ] cli help across go-ipfs and js-ipfs

#### go-ipfs
  - [ ] Check in on the label conversation
  - [ ] Write helptext for all commands https://github.com/ipfs/go-ipfs/pull/2648

#### name-your-contributors
- [ ] Fix name-your-contributors empty-repo bug: https://api.github.com/repos/ifps//issues isn't right.


#### github-task-status
- [~] Build badge to check issue lists https://github.com/ipfs/pm/issues/111
  - [x] Started work at https://github.com/RichardLitt/github-task-status
  - [ ] Enable grabbing items from a list of URLs to check
  - [ ] Set up as a server-side task that runs on a cron-job
  - [ ] Make a GitHub bot to add issues to a list
  - [ ] Enable for sublists
    - [ ] Like this one
  - [ ] Enable for comments that aren't the first in the issue
  - [ ] Check completion of tasks from issues linked in one issue

#### ipfs-http-api
  - [ ] Go through issues and open PRS on ipfs-http-api with fine comb

#### standard-readme
  - [ ] Add roadmap / readme list of modules for js-ipfs https://github.com/ipfs/js-ipfs/issues/271
  - [ ] Fill out usage docs and API section for https://github.com/ipfs/go-ipfs-api README.md
  - [ ] README spruce for interface-ipfs-core https://github.com/ipfs/interface-ipfs-core
  - [ ] Make generator-nms compliant with standard-readme https://github.com/RichardLitt/generator-nms/issues/12

**Comment by dignifiedquire** [comment]
## My Todos

- [ ] ipld.io
  - [ ] Finish design
  - [ ] Get design approved
  - [ ] implement design
  - [ ] implement playground react component
- [ ] prepare things for teamweek
- [ ] js-libp2p-secio
  - [ ] finish refactor to pull-streams
  - [ ] finish integration into js-libp2p-swarm
  - [ ] test compatibility with go-ipfs

**Comment by whyrusleeping** [comment]
@whyrusleeping TODO:
- check these boxes: https://github.com/ipfs/go-ipfs/issues/2247#issuecomment-225731241
- maybe start unixfs sharding

**Comment by haadcode** [comment]
@haadcode goals for this sprint:

  - [ ] Write talk proposals
  - [ ] Review Orbit PR https://github.com/haadcode/orbit/pull/36
  - [ ] Get admin tasks sorted (travel arrangements, email backlog, etc.)

**Comment by Kubuxu** [comment]
@Kubuxu goals:
* [ ] - ARC Caching of Get - https://github.com/ipfs/go-ipfs/pull/2942
* [ ] - Metrics interface extraction and prometheus implementation
* [ ] - check ipns-pub
* [ ] - pack-up and fly to Lisbon for the *TEAM WEEK*.

**Comment by lgierth** [comment]
### @lgierth todo

- go-ipfs
  - [ ] extract gateway ipfs/go-ipfs#2876
  - [x] test fs-repo 3-to-4 migration
  - [ ] test automatic fs-repo 3-to-4 migration ipfs/go-ipfs#2939
  - [x] CR ipfs/go-ipfs#2943
- infrastructure
  - [ ] secrets handling
  - [ ] project-repos.ipfs.io dnslink ipfs/ops-requests#25
- packet switching
  - [x] endeavour introduction ipfs/notes#143
  - [ ] multigram draft 1

**Comment by lgierth** [comment]
I might not make the sprint hangout on Monday. My flight is at 12.25pm UTC, so I'll hopefully be out of the airport by 3pm, but I'm not sure I'll make it to some good cafe (or ideally David's place) on time.

**Comment by RichardLitt** [comment]
#### Update

Checked off my ToDos in my list, above. I had a few days of solid coding this week, fixing bugs in [name-your-contributors](//github.com/RichardLitt/name-your-contributors) by removing submodules and just making everything work in the main module. I also worked on github-task-status a bit, but mostly in planning. Finally, I did a lot of work on the [project-repos](//github.com/ipfs/project-repos) page (viewable at https://project-repos.ipfs.io/) along with @harlantwood, and I am much happier with the page as a result. Most of those red squares are my task; a lot of them are [simply PRs which need code review](https://github.com/search?p=1&q=user%3Aipfs+is%3Apr+author%3ARichardLitt+is%3Aopen&ref=searchresults&type=Issues&utf8=%E2%9C%93).

**Comment by dignifiedquire** [comment]
## Update

This week was not as productive in results as I would have liked, but I have done some good amount of research and understanding issues in js-ipfs. Secio is in itself ready to be used but by trying to integrate it into swarm, I realised more fundamental issues with our swarm implementation and node streams. Solutions for these will be discussed when @diasdavid is back from his holidays. 
IPLD wise I made some good progress on [a playground](https://github.com/ipfs/react-ipld) as well as on the design and will gather feedback from the team on these in the coming week.

**Comment by haadcode** [comment]
## @haadcode's Sprint Update

Spend the week mostly going through my email backlog after holidays, catching up with GH issues and generally responding to everything I haven't in the past 3 weeks. If you're still in need for my feedback on something, please let me know! Managed to review @claus' PR and started to work on refactoring Orbit's main class (working towards to fix all the things in Orbit and make it work again with both go-ipfs and js-ipfs). Sorted all travel & admin tasks.

**Comment by Kubuxu** [comment]
This week started with plan of getting the 0.4.3rc1 out on 7th. Due to discovered issues we have to delay its release. I've worked on metrics for whole Go codebase and improved our benchmarking software.

@Kubuxu updates:
* [ ] - ARC Caching of Get - https://github.com/ipfs/go-ipfs/pull/2942
 * [x] - waits for review
 * [x] - delay it
* [ ] - Metrics interface extraction and prometheus implementation
 * [x] - create [go-metrics-interface](https://github.com/ipfs/go-metrics-interface) - a light interface of prometheus
 * [ ] - create go-metrics-prometheus
  * [ ] - gx go-prometheus
* [x] - check ipns-pub
 * [x] - PR fix to ipns-pub - https://github.com/whyrusleeping/ipns-pub/pull/5
* [x] - fix Walk bug in go-datastore: https://github.com/ipfs/go-datastore/pull/45
* [x] - improve [ipfs-whatever](https://github.com/whyrusleeping/ipfs-whatever)
 * [x] - benchmark caching PRs using it
* [x] - fix bloom filter building in case of ephemeral nodes - https://github.com/ipfs/go-ipfs/pull/2953

**Comment by nginnever** [comment]
This past week I took on some js-ipfs interop tasks to define the block, version, id, and a few other commands. Currently testing the different responses from js-ipfs and go-ipfs http. 

I also built a distributed registry for the gx package manager.  This uses an append only log in an ethereum smart contract to publish and map human readable names to ipfs hashes of the data in the repo.  I plan to flush out ideas for using this log for other low frequency update state apps.

Cheers!

**Comment by lgierth** [comment]
Sorry for posting this sooo long after the fact -- notes from my desktop computer

### @lgierth sprint 4-jul-2016 -> 11-jul-2016

I had a pretty productive week!

- go-ipfs
  - [ ] extract gateway ipfs/go-ipfs#2876
  - [x] fix gateway restrictions on API port ipfs/go-ipfs#2949
  - [x] test fs-repo 3-to-4 migration on a big repo
  - [ ] automatic fs-repo migration ipfs/go-ipfs#2939
    - [x] patch custom linux-musl build into dist.ipfs.io
    - [x] detect linux-musl in go-ipfs
    - [x] test on live nodes
    - [ ] migrate all the gateway and storage hosts
  - [x] smaller docker and sharness fixes
  - [ ] use official golang docker images
  - [ ] fix docherhub tags of ipfs/go-ipfs image
  - [x] CR ipfs/go-ipfs#2939 ipfs/go-ipfs#2943
- infrastructure
  - [x] v03x EOL blog post
  - [x] disable go-ipfs restarter for v04x
  - [x] fewer ipfs.io gateway hosts (now 2, venus and earth)
  - [ ] secrets handling
  - [x] project-repos.ipfs.io dnslink ipfs/ops-requests#25
  - [x] dist.ipfs.io dnslink bump
  - [ ] bring hosts back to live
    - [x] pollux, has fs-repo@4, deploy new go-ipfs
      - waiting on chown :/
    - [x] pluto, has new go-ipfs, fails fs-repo migration
    - [ ] nihal, needs full ~~bootstrap~~rebuild or ubuntu 16.04 support
- packet switching
  - [x] endeavour introduction ipfs/notes#143
  - [x] multigram draft 1 ipfs/specs#123
- team week
  - [x] fly to lisbon on the 11th
  - [ ] prepare opsec session
  - [ ] prepare packet switching session
- misc
  - [ ] https://github.com/issues/assigned
  - [ ] set up waffle.io board for infrastructure
