### ISSUE TITLE
Sprint K

### ISSUE THREAD

**Issue by whyrusleeping** [ipfs/pm#12]
**Sprint Goals**:

- get go-ipfs / node-ipfs interop (spdy)
- get pinning merged
- get electron-app stable enough to release

**Sprint Participants**:

- @whyrusleeping @krl @cryptix @wking @jbenet @tv42 @gatesvp @chriscool @rht @harlantwood @dylanPowers @diasdavid @lgierth @kbala

**Sprint Deliverables**:

Add links to issues down here. Only add things you can finish this sprint.

#### @chriscool
- [x] https://github.com/mlafeldt/sharness/pull/20 add test_pause to sharness
- [x] https://github.com/mlafeldt/sharness/pull/22 add test_seq to sharness
- [ ] upgrade our sharness version & use test_seq from sharness

#### @diasdavid
- [x] Implement PDD (Protocol Driven Development) Framework - https://github.com/ipfs/specs/pull/12
- [x] Do PDD for MultiStream Node.js implementation (https://github.com/diasdavid/node-multistream) ang Go (on going - https://github.com/whyrusleeping/go-multistream/issues/3)
- [ ] Do PDD for DHT pingl (spec is under being written down)

#### @dylanPowers
- [ ] https://github.com/ipfs/website/issues/13 Check for dead links on the website (in review)
- [ ] Formulate responses to https://github.com/ipfs/faq/issues/21 and https://github.com/ipfs/faq/issues/17
- [ ] https://github.com/ipfs/website/issues/28
- [x] https://github.com/ipfs/community/issues/22

#### @harlantwood
- [ ] https://github.com/ipfs/dataviz/issues/1 DAG visualized as D3 tree
- [ ] consult & test as needed on https://github.com/ipfs/go-ipfs/issues/1322 Expose read-only API via Gateway

#### @jbenet
- [ ]  merge pinning 
- [ ] S3 figure out direction forward.
- [x] meldium ipfs team
- [x] cleanup + fix iprs spec 
- [ ] dht spec
- [x] go-random-files
- [x] ipfs-stress-fs
- [x] fixed spdystream https://github.com/jbenet/go-peerstream/pull/9

#### @kbala
- [ ] get basic bitswap simulator working https://github.com/ipfs/bitswap-ml/issues/3
- [ ] look into simulating latency and bandwidth caps

#### @lgierth
- [x] https://github.com/protocol/infrastructure/issues/56 Have nginx prefer the local IPFS daemon
- [ ] https://github.com/ipfs/go-ipfs/pull/1316 discover peers from cjdns
- [x] https://github.com/protocol/infrastructure/issues/44 Replace `ipfs-gateway-fs` with `ipfs daemon`
- [ ] https://github.com/protocol/infrastructure/issues/58 Monitoring
- [ ] https://github.com/ipfs/notes/issues/14 lay out more possible integrations with cjdns
- [ ] https://github.com/protocol/infrastructure/issues/54 Publish the Ansible scripts

#### @rht
- [ ] https://github.com/ipfs/go-ipfs/pull/1279
- [ ] https://github.com/ipfs/go-ipfs/issues/740
- [ ] https://github.com/ipfs/go-ipfs/issues/143
- [ ] https://github.com/ipfs/go-ipfs/issues/593

- [ ] CR bot / commit hook for guidelines, e.g. constraint that commits can't fail the test at any point in history

#### @travisperson
- [ ] https://github.com/ipfs/go-ipfs/issues/1322 Expose read-only API via Gateway

#### @tv42 
- [ ] S3 repo

#### @whyrusleeping
- [x] multistream, mss-nc node compatability
- [ ] package tool
  - started writing. still playing with UX. 
- [x] merge ipfs-shell updates
- [x] debug spdystream deadlock
- [x] diagnose bitswap memory leak
- [x] marvel at mars' being up for an entire week

#### @wking
- [ ] publish initial IPFS storage driver for https://github.com/docker/distribution

#### triage - anyone can pick these up
- [ ] https://github.com/ipfs/go-ipfs/issues/1289
- [ ] https://github.com/ipfs/go-ipfs/issues/1248 fix fuse unmount
- [ ] https://github.com/ipfs/go-ipfs/issues/1222 add uses a lot of ram and cpu
- [ ] daemon init cleanup
- [ ] https://github.com/ipfs/go-ipfs/issues/1224 decimate eventlog 
- [ ] merge https://github.com/ipfs/go-ipfs/pull/1277
- [ ] https://github.com/ipfs/go-ipfs/issues/1246 Avoid dialing known local addresses when not in that network
  - posted iptables commands to help issue
- [ ] https://github.com/ipfs/go-ipfs/issues/1247 Config option to disable dialing specific subnets entirely

**Comment by jbenet** [comment]
@krl add stuff up there o/

**Comment by harlantwood** [comment]
I can't make the call, so here is my sprint report: 
 - Working on automated testing of dataviz ipfs/dataviz#3
 - Still looking for support with ipfs/go-ipfs#1322 in order to complete ipfs/dataviz#1

**Comment by travisperson** [comment]
@harlantwood - Working on ipfs/go-ipfs#1322, it's a bit more involved than I originally thought.

**Comment by harlantwood** [comment]
Yeah, I know the feeling @travisperson :wink: 

Just making sure you saw my comment about the limited scope needed to support the dataviz at this time: https://github.com/ipfs/go-ipfs/issues/1322#issuecomment-108793521

**Comment by harlantwood** [comment]
Added a comment to be even clearer: https://github.com/ipfs/go-ipfs/issues/1322#issuecomment-112249251
