### ISSUE TITLE
Q3 Roadmap: go-ipfs

### ISSUE THREAD

**Issue by RichardLitt** [ipfs/pm#127]
This is the general roadmap for tasks and priorities for [go-ipfs](//github.com/ipfs/go-ipfs) for this year's third quarter - July, August, and September. Please refer to this issue to see where we are in the current process, and what should be worked on. 
### Pre Q3 (end of July)
- [ ] **Ship go-ipfs 0.4.3.** Owner: @whyrusleeping
- [ ] **HAMT Sharding Go-ipfs Protobuf.** Owner: @whyrusleeping.
- [ ] Keystore - Implemented and released.
- [ ] Resource limits:
  - [ ] memory
  - [ ] bandwidth
  - [ ] storage
- [ ] Performance
### August Week 2
- [ ] **SHIP Intervations JS-IPFS needs from go**
  - [ ] **Not get PubKey from Secio**
  - [ ] **Websockets**
- [ ] Multiple Protocol version handling
- [x] Datastore
  - [x] too many fd fixes
### August Week 3
- [ ] Multicodecs implemented
- [ ] Benchmarking
  - [ ] Automated suite on Teamcity
  - [ ] Benchmarks across API space
### August Week 4
- [ ] Extract Gateway to its own tool using core-api
  - [ ] Better metrics
  - [ ] up on Grafana
### September Week 1
- [ ] IPLD Blockstore Integration
- [ ] Multicodes implemented
- [ ] Benchmarking
  - [ ] Automated suite on Teamcity
  - [ ] Benchmarks across API space
### September Week 2
- [ ] Ship GO-IPFS 0.4.4
- [ ] Better metrics
  - [ ] up on Grafana
### September Week 3
- [ ] **Code Coverage > 80% all packages.** Owner: @whyrusleeping.
- [ ] Ship complete go-ipfs-api
- [ ] GO // IPNS:
  - [ ] better performance
  - [ ] use for own website
  - [ ] integration testing 
- [ ]  Reliability
  - [ ] Don't run out of file descriptors 
- [ ] IPLD Blockstore integrationIPFS/IPLD
- [ ] Write sharding data sheets
  - [ ](HAMT)
### September Week 4
- [ ] Ship go-ipfs 0.4.4
### October Week 1
- [ ] go-ipfs 0.5.0-rc1. Owner: @why
- [ ] GO // IPNS
  - [ ] better perf
  - [ ] use for own website
  - [ ] integration testing
- [ ]  IPLD 
  - [ ] Bitswap Integration
### October Week 4
- [ ] Ship go-ipfs 0.5.0.
#### 

Q4 and Beyond
- [ ] Keystore - Implemented and released.
- [ ] Resource limits:
  - [ ] memory
  - [ ] bandwidth
  - [ ] storage
- [ ] Performance

go-ipfs bug fixes
 Reduce idle bandwidth usage
TODO: list PRs
It is not shipped
NAT Traversal (Not completed, the priority on this was dropped)
The NAT Traversal still is being issues sometimes.
 Fix Memory leaks
TODO: we need to gather these metrics and showcase them somewhere
 Fix Providers Problem (Was not completed)

go-ipfs improvements
Testing for 0.4.0 was poor, identify process improvements for testing.
TODO: quantify 'improve testing'
Implement bitswap paths (in wantlists)
discussed with @jbenet and @diasdavid
'request ID' for each wantlist entry
Improve Disk performance
TODO: Make an 0.4.2 and 0.4.3 release pictures with perf improvements.
RECOMMENDATION: Run performance benchmarks for each PR or release.
Easy-to-consume API for transfer progress and stats
TODO: outline usecases and rough API features
NOTE: can use cmds diag codepaths to store transfer id's
“Sys node vs app node” problem
TODO: define usecases and what 'done' means
resource limits
Memory limits (user config)
Bandwidth limits (user config)
Storage limits (user config) - Sept

**Comment by kevina** [comment]
@whyrusleeping do you think we could get my filestore code (ie ipfs/go-ipfs#875, ipfs/go-ipfs#2634)  merged the next three months?  Sorry for the spam if this is not a good place to bring this up.

**Comment by jbenet** [comment]
Hello @kevina! let's talk about this-- would love to hear about the approach and see if i can shepherd this to landing sooner

**Comment by kevina** [comment]
@jbenet Thanks!  What did you have in mind?  Do you want to set a time for a meeting or do you want to hash this out online?

**Comment by jbenet** [comment]
@Kevina let's meet this week or next. I'd like to talk you through
splitting pieces up to mKe review and merge easier. Have been looking at
the code and have some ideas. I'll put them in writing here first

**Comment by kevina** [comment]
@jbenet, okay.  I'll wait until you put something in writing, it would probably be best to move this conversation over to ipfs/go-ipfs#2634.

**Comment by diasdavid** [comment]
This was last quarter, closing
