### ISSUE TITLE
Q3 Roadmap: js-ipfs

### ISSUE THREAD

**Issue by RichardLitt** [ipfs/pm#128]
This is the general roadmap for tasks and priorities for [js-ipfs](//github.com/ipfs/js-ipfs) for this year's third quarter - July, August, and September. Please refer to this issue to see where we are in the current process, and what should be worked on.

### August Week 3
 - [ ] **JS-IPFS Milestone 2 - Quality and Correctness**

### September Week 2
 - [ ] JS-IPFS - Milestone 4 - Ship interop routing

### October Week 1
- [ ] **Milestone 5, integrate IPLD.**

### November Week 2
- [ ] JS-IPFS Milestone 6, Ship feature parity with go-ipfs.

**Comment by diasdavid** [comment]
This roadmap is incorrect. See https://github.com/ipfs/js-ipfs/pull/375

**Comment by RichardLitt** [comment]
Closing in favor of ipfs/js-ipfs#375.
