### ISSUE TITLE
Q3 Roadmap: IPLD

### ISSUE THREAD

**Issue by RichardLitt** [ipfs/pm#129]
This is the general roadmap for tasks and priorities for IPLD for this year's third quarter - July, August, and September. Please refer to this issue to see where we are in the current process, and what should be worked on. 
### Unscheduled
- [ ] get js-ipfs onto par @dignifiedquire
### Pre Q3
- [ ] **SPECS - proto to IPLD migration plan** @diasdavid
  - [x] identifier
  - [ ] modules
### August Week 1
- [ ] **Ship & Review  PY-IPLD** @dignifiedquire
  - **py-multiadder**
- [ ] **Review Go-IPLD** @jbenet @whyrusleeping
  - **Live CBOR Querying** @whyrusleeping
- [x] Write up + post IPLD CID notes @jbenet
     may create:
  - [ ] write CID spec
  - [ ] write CID explainer webpage
  - [ ] figure out addressing changes to interfaces (go/js-ipfs)
  - [ ] roadmap for module changes for CID support (go/js-ipfs)
### August Week 2
- [ ] work on/ship go-ipld (maybe week 3) @whyrusleeping
### August Week 3
- [ ] IPLD Branding @dignifiedquire @jbenet
### August Week 4
- [ ] **SHIP IPLD.io** @richardlitt @jbenet
  - Spec, docs, simple review
- [ ] **Write IPLD Paper** @nicola @jbenet
- [ ] **Write more legitimate spec clean up, alignment** @nicola @jbenet
### September Week 1
- [ ] Complete I/0 Test Suite. Owner: @dignifiedquire @chriscool
  - [ ] define command interface
- [ ] Design & Build Playground. Owner: @jbenet
  - Ref https://github.com/ipfs/react-ipld
- [ ] 01/ IPFS Write sharding data structs. (HAMT) @whyrusleeping @jbenet
### October Week 1
- [ ] Publish Data importer Spec + IPLD

**Comment by diasdavid** [comment]
This was last quarter, closing.
