### ISSUE TITLE
Sprint L

### ISSUE THREAD

**Issue by jbenet** [ipfs/pm#13]
## Sprint Goals

- go-ipfs protocol transition
- shorten bug-list
- get electron-app stable enough to release

## Sprint Discussions

2015-06-15:
- 21:00Z (14:00 PDT) infrastructure - https://plus.google.com/hangouts/_/gq3ieylu6bufzbnovemvb2rraia
- 21:30Z (14:30 PDT) node-ipfs - https://plus.google.com/hangouts/_/gyafa4mpgz7g6jntijoxshfe3ma
- 22:00Z (15:00 PDT) go-ipfs - https://plus.google.com/hangouts/_/g4hc3dnpdvwsklyfd2sxhkwbgqa
- 22:30Z (15:30 PDT) testing + ci - https://plus.google.com/hangouts/_/gwn656w2cihn7lekdarfzhaquea
- 23:00Z (16:00 PDT) protocol + specs
- 23:30Z (16:30 PDT) bitswap (ml) - https://plus.google.com/hangouts/_/grcpjefkp4fv4zqz3xe4ty3mbea

2015-06-16:
- 19:00Z (12:00 PDT) apps on IPFS - electrum host
- 19:30Z (12:30 PDT) data structures

## Sprint Deliverables

- Add yourself below, that way we only have people listed who are really in the sprint
- Add links to issues down here. Only add things you can finish this sprint.

#### @jbenet
- [ ] setup mss muxer in go-ipfs
- [x] rm secio for node-ipfs interop - https://github.com/ipfs/go-ipfs/pull/1399
- [x] figure out "OSS hygiene" signoff for past commits on go-ipfs
- [x] electron menu design
- [ ] wire spec diagram
- [ ] IPFS system diagram
- [x] next IPRS spec iteration
- [ ] DHT spec
- [x] gateway hotfix
- [x] mount test error https://github.com/ipfs/go-ipfs/pull/1391
- [x] multiaddr nil conn fix https://github.com/ipfs/go-ipfs/pull/1395
- [x] ipfs swarm addrs local, ipfs id -f=<addrs>, tests - https://github.com/ipfs/go-ipfs/pull/1399
- [x] https://gist.github.com/jbenet/d1fedddfef85f0c4efd5 modules listing

#### @whyrusleeping
- [ ] spdystream/multistream protocol transition
- [ ] https://github.com/ipfs/go-ipfs/issues/1366
  - postponing until after s3 datastore merges
- [ ] https://github.com/ipfs/go-ipfs/issues/1247
- [x] https://github.com/ipfs/go-ipfs/issues/1224
- [ ] https://github.com/ipfs/go-ipfs/issues/1222 add uses a lot of ram and cpu
  - pipeline for now, larger refactor later
- [x] https://github.com/ipfs/go-ipfs/pull/1405
- [x] https://github.com/ipfs/go-ipfs/pull/1404
- [x] https://github.com/ipfs/go-ipfs/pull/1382
- [x] open sourced https://github.com/whyrusleeping/gx

#### @diasdavid
- [X] node-spdystream - With big thanks to Indutny https://github.com/indutny/node-spdy/issues/208#issuecomment-113861481
- [ ] PDD on DHT spec for go-ipfs
 
#### @krl
- [ ] finish electron app html menu
- [ ] starlog proposal

#### @lgierth
- [ ] https://github.com/protocol/infrastructure/issues/58 Monitoring for gateway.ipfs.io
- [ ] https://github.com/ipfs/go-ipfs/pull/1316 discover peers from cjdns
- [ ] https://github.com/ipfs/notes/issues/14 lay out more possible integrations with cjdns
- [ ] https://github.com/protocol/infrastructure/issues/54 Publish the Ansible scripts

#### @chriscool
- [x] add some GitCop/commit-msg hook related doc
- [ ] https://github.com/ipfs/go-ipfs/pull/1266 add circleci support
- [x] https://github.com/ipfs/community/pull/34 add ammending commits help
- [x] https://github.com/ipfs/go-ipfs/pull/1414 fix test error 

#### @rht
- [ ] https://github.com/ipfs/go-ipfs/issues/593
- [x] https://github.com/ipfs/go-ipfs/pull/1359

#### @kbala
- [ ] collect metrics from simulation
- [ ] add more control over connections in bitswap testnet

#### @harlantwood
- [ ] https://github.com/ipfs/dataviz/issues/3 Dataviz Automated tests + CI
- [ ] https://github.com/ipfs/dataviz/issues/1 DAG visualized as D3 tree
- [ ] consult & test as needed on https://github.com/ipfs/go-ipfs/issues/1322 Expose read-only API via Gateway

#### @dylanPowers
- [ ] https://github.com/ipfs/website/issues/13 Check for dead links on the website (in review)
- [ ] Formulate responses to https://github.com/ipfs/faq/issues/21 and https://github.com/ipfs/faq/issues/17
- [x] https://github.com/ipfs/go-ipfs/issues/1368
- [ ] https://github.com/ipfs/website/issues/28
- [x] https://github.com/ipfs/go-ipfs/issues/1336
- [x] https://github.com/ipfs/go-ipfs/issues/1337

#### @cryptix
- [ ] https://github.com/cryptix/git-remote-ipfs/ git-remote-ipfs 
- [ ] https://github.com/ipfs/go-ipfs/pull/1406 nicer index pages

#### triage - anyone can pick these up
- [ ] https://github.com/ipfs/go-ipfs/issues/1289
- [ ] https://github.com/ipfs/go-ipfs/issues/1248 fix fuse unmount
- [ ] daemon init cleanup
- [x] https://github.com/ipfs/go-ipfs/issues/1224 decimate eventlog 
- [x] merge https://github.com/ipfs/go-ipfs/pull/1277
- [ ] https://github.com/ipfs/go-ipfs/issues/1246 Avoid dialing known local addresses when not in that network
  - posted iptables commands to help issue

**Comment by diasdavid** [comment]
I mentioned this in previously meetings, by just realized I never wrote it down. I'm during today and tomorrow on MediterraneaJS, which means I won't be able to do much. Also attending the Sprint meeting will be hard as the Wifi is pretty much broken (currently on 3G Roaming). 

Would it be good to sync up Wed/Thu on node-ipfs?

Thank you

**Comment by whyrusleeping** [comment]
etherpad for next sprint: https://etherpad.mozilla.org/4LhJKyOF3j

**Comment by jbenet** [comment]
Hey @diasdavid -- this was notice enough, thanks! and yeah let's talk node-ipfs tomorrow or later.

**Comment by diasdavid** [comment]
@jbenet cool. Meantime I'll be testing spdy-transport against spdystream and making the node-peerstream wrapper, while making the remaining tests that Indunty needs for spdy-transport.

Need to have a convo about the rest of the network elements to make it work. Essentially if you could point what stuff from here: https://github.com/ipfs/specs/tree/master/protocol/network is on go code and where, it would work :)

That and of course, continuing the DHT, spec would be appreciated, but I believe that I'm getting the hang of how it was implemented by continuously reading the code and making questions.

**Comment by lgierth** [comment]
> Essentially if you could point what stuff from here: https://github.com/ipfs/specs/tree/master/protocol/network is on go code and where

:+1: :+1:
