### ISSUE TITLE
Sprint: Aug 8 → Aug 14

### ISSUE THREAD

**Issue by RichardLitt** [ipfs/pm#133]
# Sprint August 8th--August 14th

_For information about these calls and how they work, read [the ipfs/pm README](https://github.com/ipfs/pm)._

[Calendar](https://calendar.google.com/calendar/embed?src=ipfs.io_eal36ugu5e75s207gfjcu0ae84@group.calendar.google.com&ctz=America/New_York)

Endeavour         | Lead            | Time (PDT - **UTC/Z** - CEST) | Pad
:---------------: | :-------------: | :--------------------------: | :----:
All Hands Call   | @flyingzumwalt    | 9:00PDT **16:00Z** 18:00CEST  | [pad-all-hands](https://public.etherpad-mozilla.org/p/ipfs-8-8-16-all-hands)
pubsub | @diasdavid | 10:00 PDT **17:00Z** 19:00CEST | [pad-pubsub](https://public.etherpad-mozilla.org/p/ipfs-8-8-16-pubsub)
IPLD                | @nicola       | 10:30PDT **17:30Z** 19:30CEST | [pad-IPLD](https://public.etherpad-mozilla.org/p/ipfs-8-8-16-ipld)
js-ipfs              | @diasdavid   | 11:00PDT **18:00Z** 20:00CEST | [pad-js-ipfs](https://public.etherpad-mozilla.org/p/ipfs-8-8-16-js-ipfs)
libp2p            | @diasdavid      | 11:30PDT **18:30Z** 20:30CEST | [pad-libp2p](https://public.etherpad-mozilla.org/p/ipfs-8-8-16-libp2p)

Please add any agenda items you have to the pad before the project-specific sprint call starts.

**Comment by RichardLitt** [comment]
Proposal for a breakout call: mfs and `ipfs files`. See [this issue](https://github.com/ipfs/specs/issues/98#issuecomment-238032795).

**Comment by flyingzumwalt** [comment]
Proposal for discussion: Renaming libp2p-swarm to net-machine. See [this issue](https://github.com/libp2p/js-libp2p-swarm/issues/40#issuecomment-238034905).

**Comment by RichardLitt** [comment]
Proposal for discussion: pubsub. See [this comment](https://github.com/ipfs/pm/issues/130#issuecomment-237293938).

Proposal for discussion: IPLD. See [this issue](https://github.com/ipfs/pm/issues/124).

**Comment by diasdavid** [comment]
Can we get an update on the community calendar as well?
![image](https://cloud.githubusercontent.com/assets/1211152/17484418/9abea936-5d81-11e6-8679-dee71979243f.png)

**Comment by RichardLitt** [comment]
@diasdavid Do you still see those? Did you just take that screenshot? It should only show the All Hands Call today.

**Comment by diasdavid** [comment]
yeah, the screenshot was from just now, I still see them.

**Comment by flyingzumwalt** [comment]
FYI I've updated the agenda [etherpad for the all hands call](https://public.etherpad-mozilla.org/p/ipfs-8-8-16-all-hands) with all the proposals from this thread.

**Comment by diasdavid** [comment]
All solved, my calendar looks good. Seems that it was a sync problem.

**Comment by jbenet** [comment]
thanks @flyingzumwalt for running the all-hands! it was great! :heart:

**Comment by diasdavid** [comment]
PubSub notes and repo for further discussions -> https://github.com/libp2p/pubsub/issues/1#issue-169980356

**Comment by RichardLitt** [comment]
## To Do this week

### Multiformats

 - [ ] Standardize all of the READMEs
 - [ ] Assign owners to the repositorities
 - [ ] Design and deliver a basic 

### Extra

- [ ] Get project-repos working with the commit messages https://github.com/philschatz/octokat.js/issues/107
- [ ] First draft of a README at https://github.com/RichardLitt/awesome-opsec

_Please feel free to bring anything else to my attention._

**Comment by RichardLitt** [comment]
# IPFS All Hands Call 08 August 2016

**Moderator:** Matt Zumwalt  (@flyingzumwalt)

**Notetaker:** Richard Littauer (@RichardLitt)

**Attendees** 
- @nicola
- @RichardLitt
- @jbenet
- @flyingzumwalt
- @haadcode
- @em-ly
- @dignifiedquire
- @diasdavid
- @betaphors
- @Kubuxu
- @haadcode
- @gavinmcdermott
- @ReidWilliams

## Agenda
1. Roll call by alphabetical order (moderator)
2. New call/sprint format and Community Calendar - [issue 134](https://github.com/ipfs/pm/issues/134)  and [this comment](https://github.com/ipfs/pm/issues/133#issuecomment-238265884)
3. Call for additional agenda items (moderator)
4. Checking in on the GitHub issue. (@diasdavid)
5. PM Process Discussions  [PR 131](https://github.com/ipfs/pm/pull/131) (@flyingzumwalt)
6. Proposal for a breakout call: mfs and `ipfs files`. See [this issue]
8. Proposal for discussion: pubsub. See [this comment](https://github.com/ipfs/pm/issues/130#issuecomment-237293938). (@diasdavid)
(https://github.com/ipfs/specs/issues/98#issuecomment-238032795). (@diasdavid)
9. Proposal for discussion: IPLD. See [this issue](https://github.com/ipfs/pm/issues/124). (@nicola)
10. Schedule for the day
11. Renaming libp2p-swarm to net-machine. See [this issue](https://github.com/libp2p/js-libp2p-swarm/issues/40#issuecomment-238034905). (@diasdavid)
12. RFI about Q2 Update (jbenet)


1. Moderator/notetaker for next time:
 * Moderator: @flyingzumwalt 
 * Notetaker: @dignifiedquire 

--

# Notes

- Raise questions by raising hands.

## New format for quick round
- type of discussion:
  - Cross-cutting
  - Need discussion
- delegate conversations for later
- moderator
  - can rotate
  - keeps things on track
  - keeping things rolling
  - keepin' it smooth

## Agenda items
- write them on github
- announce them at the beginning of the call
- writing them in the PAD

## Checking in for Github
- We should continue to check in on the Sprint issue
- But this isn't happening
- We should also have a section about things which we said we could do, but don't
- @jbenet: I don't know if we're going with Kanban or Agile, or so on, and this will make sense later. Super important to track though.
- @dignifiedquire: Writing the tasks is a waste of time if we have Boards. We need to be able to check things at places in time, though, and take a screenshot (or some other way of capturing time-sensitive information), once a week or so.
- @jbenet: We can discuss this, and what models we want, on GitHub
- TODO: @diasdavid Open a GitHub issue about this topic so we can discuss it async

## PM Process Discussions

- Note for new people: We are working on our process right now; in particular, we're trying to get our model down. 
- After Lisbon, the goal is to put together a process for managing our projects in the IPFS community. 
- We need to find a general-enough process that we can use, but that people can choose to opt into (or not). 
- Some IPFS projects may need this now, however. 
- So far, a lot of discussion about how we do PM. First, we've been figuring out the model - as @jbenet says, "figuring our the description for the process so that you can implement it with post-it notes if needed."
- There's a document in a PR (https://github.com/ipfs/pm/pull/131) that is good, and we're working on feedback for that
- We need some tool which can be automated, though: roadmaps, milestones, tags, and so on. Ideally, something does this all for you (CI hook, or something similar). 
- @jbenet: What should people do this week while we hash this out?
- TODO: @ipfs/devs: Add your sprint todos this Monday for the following work, using the old method, while we figure out how we want this to look. Explicit decision: Use what we used to do that worked (aka huge markdown lists in the sprint issue). 
- This pertains to: @RichardLit, @jbenet, @flyingzumwalt, @haadoce, @dignifiedquire, @diasdavid, @Kubuxu, @whyrusleeping, @nicola
- Anyone want to get involved, but havent yet?
- @RichardLitt: Waiting becuase there are a lot of cooks, would like to get involved when you feel it is a good time.
- @dignifiedquire: I'd also like to know, but when there is a draft.
- @haadcode: Review it this week; next week is tooling. 

## MFS

@jbenet: All the bike sheds! Can we do this over GitHub?
@diasdavid: If we commit to that, but over a couple of days, not two months, if possible?
@jbenet will do.

## PubSub

@diasdavid: Breakout Discussion!! 
- What do we do with our time, research, prototype, and so on. 

When: Immediately after this call

## IPLD

Scheduled. 

## Renaming

@diasdavid: Should be part of the libp2p discussion
@jbenet: I can't make that call, and this should be on github. 
TODO: Can we prioritize that issue? (Yes)

## RFI about Q2 Update

@jbenet: I'm preparing an update on Q2 for the whole IPFS project. Highlighting a lot of important things, too.
I will post a skeleton or a draft and tag relevant people about this (also needs pictures!).
@RichardLitt: Let me haaaalpp

## Done. Retrospective

Done in under 45 minutes. We'll tighten this up.

**Comment by diasdavid** [comment]
# David Dias TODO

- interface-ipfs-core endeavour
  - write spec for:
    - [ ] name https://github.com/ipfs/interface-ipfs-core/pull/37
    - [ ] dht https://github.com/ipfs/interface-ipfs-core/pull/36
    - [ ] swarm https://github.com/ipfs/interface-ipfs-core/pull/35
    - [ ] pinning https://github.com/ipfs/interface-ipfs-core/pull/34
  - [ ] review, fix and merge ipfs.get PR on js-ipfs-api and interface-ipfs-core
  - [ ] revisit the files API https://github.com/ipfs/interface-ipfs-core/issues/29
  - [ ] ipfsFactory - https://github.com/ipfs/interface-ipfs-core/issues/53
  - tests for:
    - [ ] name https://github.com/ipfs/interface-ipfs-core/pull/37
    - [ ] dht https://github.com/ipfs/interface-ipfs-core/pull/36
    - [ ] swarm https://github.com/ipfs/interface-ipfs-core/pull/35
    - [ ] pinning https://github.com/ipfs/interface-ipfs-core/pull/34
- pubsub
  - curate and organize the info on pubsub and move it to the pubsub repo
- [ ] interop tests between js-ipfs and go-ipfs
- [ ] Reduce js-ipfs-api complexity ipfs/js-ipfs-api#313
- [ ] Get as much done as possible on the js-ipfs-api next generation endeavour ipfs/js-ipfs-api#305

**Comment by nicola** [comment]
### Nicola's todos

- [ ] write down pub-sub skeleton issue (see https://github.com/libp2p/pubsub/issues/1)
- [ ] clean up the results from the first IPLD call (see https://github.com/ipfs/pm/issues/124)
- [ ] close all the issues we have agreed about IPLD
- [ ] write first draft of new IPLD spec
- [ ] sync with @jbenet about the IPLD papers

**Comment by nicola** [comment]
Notes about IPLD were here: https://github.com/ipfs/pm/issues/124

**Comment by Kubuxu** [comment]
Kubuxu's TODO:
-------
Planned:
*  [x] - c-multihash decoding and basic tests
* [ ] - go-ipfs -  test coverage goal (2 packages)
* [ ] - go-ipfs - metrics lib refactor

Unplanned:
* [x] - go-ipfs `ipfs config replace` test - asked by @diasdavid if it works correctly

**Comment by haadcode** [comment]
## haadcode's sprint check in - Sprint August 8

I managed to complete all goals set for the first milestone for dynamic content in this quarter: Fix Orbit (https://github.com/haadcode/orbit/milestone/2?closed=1). Orbit is now back up and running and ready for the next milestone: Integrate Orbit with uPort (https://github.com/haadcode/orbit/milestone/3) which is what I'm oging to work on this week.

The discussion on PM process continues at https://github.com/ipfs/pm/pull/131 and while not done yet, we made great progress!

Last week's goals:
- [X] "Fix Orbit" milestone goals, https://github.com/haadcode/orbit/milestone/2
- [ ] Help to define and implement a project management process

**Comment by Kubuxu** [comment]
Kubuxu done:
----------------
Kubuxu's TODO:
-------
Planned:
* [x] - c-multihash decoding and basic tests
* [x] - go-ipfs:  test coverage goal (2 packages)
* [ ] - go-ipfs: metrics lib refactor

Unplanned:
* [x] - go-ipfs: `ipfs config replace` test - asked by @diasdavid if it works correctly
* [x] - go-ipfs: update go-is-domain list and move it to gx - https://github.com/ipfs/go-ipfs/pull/3077

**Comment by noffle** [comment]
## noffle

Not strictly IPFS, but I wrote https://github.com/noffle/github-dependency-crawl/ as a base module for https://github.com/jbenet/random-ideas/issues/37.
