### ISSUE TITLE
Sprint M

### ISSUE THREAD

**Issue by whyrusleeping** [ipfs/pm#17]
## Sprint Goals

- go-ipfs protocol transition
- go-ipfs node interop?? (pls)
- shorten bug-list
- move @jbenet to the north ???
- get electron-app stable enough to release

### @whyrusleeping
- [x] ipfs 'checksum' (name WIP)
- [ ] mark and sweep GC to destroy indirect pins https://github.com/ipfs/go-ipfs/issues/1416
- [x] merge https://github.com/ipfs/go-ipfs/pull/1378
- [ ] assist in go-multistream integration and merge
- [ ] take a look at batch interface for datastore https://github.com/ipfs/go-ipfs/issues/1415

### @krl
- [ ] jbenets PR issues with html-menu
- [ ] breaking up webui into modules

### @cryptix
- [ ] merge the new index PR ipfs/go-ipfs#1406

### @lgierth
- https://github.com/protocol/infrastructure/issues/58 Monitoring for gateway.ipfs.io
  - [ ] https://github.com/ipfs/go-ipfs/pull/1422 ipfs daemon generates metrics
  - [x] https://github.com/protocol/infrastructure/pull/66 gateway.ipfs.io runs cjdns, peers into hyperboria
  - [x] https://github.com/protocol/infrastructure/pull/68 expose metrics to whitelisted cjdns nodes
  - [ ] prometheus instance collects metrics and serves them
  - (@rht) I had wanted to do the metrics thing as well. has been stated in https://github.com/ipfs/go-ipfs/issues/920, https://github.com/ipfs/go-ipfs/issues/930.
- [ ] https://github.com/protocol/infrastructure/issues/54 publish gateway ansible scripts at ipfs/infrastructure
- [ ] https://github.com/ipfs/go-ipfs/pull/1316 discover peers from cjdns
- [ ] https://github.com/ipfs/notes/issues/14 lay out more possible integrations with cjdns

### @jbenet
- [x] review https://github.com/ipfs/go-ipfs/pull/1348 (should be ready for merge)
- [x] review  https://github.com/ipfs/go-ipfs/pull/1378 (RFM)
- [x] review https://github.com/ipfs/go-ipfs/pull/1407 (needs decision on intermediate auto-creation)
- [x] merged https://github.com/ipfs/go-ipfs/pull/1399
- [x] full single-file listing of all interfaces in the IPFS system 
- [x] diagrams of parts of the system

### @wking
- [ ] land https://github.com/ipfs/go-ipfs/pull/1351
- [ ] land https://github.com/ipfs/go-ipfs/pull/1407
- [ ] land https://github.com/ipfs/go-ipfs/pull/1413

Time permitting, I'd like to build on go-ipfs#1413 to associate Merkle metadata nodes with file/directory nodes.

### @chriscool
- [x] https://github.com/ipfs/go-ipfs/pull/1266 add circleci support

### @rht
- [ ] fix https://github.com/ipfs/go-ipfs/pull/1385
- [ ] ipfs "HEAD" log/versioning, https://github.com/ipfs/go-ipfs/issues/1353
- [ ] refactor unixfs/tar/reader.go
- [ ] ipfs daemon metrics

### @harlantwood
- [ ] consult & test as needed on ipfs/go-ipfs#1322 Expose read-only API via Gateway

### @diasdavid
- [ ] DHT Spec - https://github.com/ipfs/specs/pull/14
- [X] go & node interop (it is all about that spdy)
  - https://github.com/indutny/spdy-transport/issues/2
  - https://github.com/indutny/spdy-transport/issues/1
- [X] spdy-transport documentation https://github.com/indutny/spdy-transport/pull/5
- [ ] spdy-transport spdy parser.js tests  https://github.com/indutny/spdy-transport/pull/3

**Comment by whyrusleeping** [comment]
https://etherpad.mozilla.org/kKFTHJz4xu
