### ISSUE TITLE
Proposal: Dedicate 03-Oct and 10-Oct community calls to Roadmap Discussions

### ISSUE THREAD

**Issue by flyingzumwalt** [ipfs/pm#202]
The project leads will be together in-person on the week of 10/10 to talk about the Q4 Roadmaps. To prepare for this, @em-ly and I came up with the idea of dedicating the 10/3 community calls and also the 10/10 calls to discussing Roadmaps with the community.  We should announce these in advance and push for active community members to participate.

10/3 Focus on Reviewing the Q3 Roadmaps
10/10 Focus on gathering Milestones for the Q4 Roadmaps

## Why do this?

* Allows community input into the Roadmap Planning process
* Gets the Roadmap discussions going ASAP so we're prepared to assemble and finalize the Roadmaps when the Project Leads meet Oct 10-14
* This can be our first step towards convening Roadmap Planning as a decentralized activity that includes the whole community. 

Project Leads, what do you think of this idea? @whyrusleeping @diasdavid @jbenet @haadcode

**Comment by RichardLitt** [comment]
If we decide to do this, we can do a few things to make sure that the community is on board:

- [ ] Write up a blogpost. I have a draft here:  https://github.com/ipfs/blog/pull/75
- [ ] Post in the issues on ipfs/ipfs (_I don't think this is necessary_)
- [ ] Post in the Sprint issue before hand (and I should create the before hand)
- [ ] Tweet about it. We have Buffer, we can schedule tweets every couple of days.
- [ ] Send out a short newsletter to the tinyletter about this.

**Comment by em-ly** [comment]
Thanks for putting that list together @RichardLitt! I think we should do all of them - I dont know if we have a good sense of which of our communication channels are most effective, so I think we need to post this information wherever possible. Posting to ipfs/ipfs might catch others who aren't paying attention to other channels, so let's make sure something gets listed there.

**Comment by flyingzumwalt** [comment]
@whyrusleeping @diasdavid I should have been more thorough about making sure this got onto your radar while you were traveling. Also, I guess I've been in a time warp. I thought I posted it over a week ago. Actually it was only 4 days.

**Comment by RichardLitt** [comment]
@flyingzumwalt Can we announce next week's talks on the blog? And elsewhere?

**Comment by flyingzumwalt** [comment]
Yes please. I guess the blog post we wrote last week needs to be rewritten because it didn't go out before 03-Oct

**Comment by RichardLitt** [comment]
Posted everywhere but the newsletter. I am not sure it should go out there, as I am unsure on the audience for the newsletter, and how this would look after so long without a newsletter, in general. I think the developers who would be interested in joining would have seen the notice on the blog, twitter, in the PM announcement, in the IPFS Newsletter thread. 

@flyingzumwalt What do you think?

**Comment by flyingzumwalt** [comment]
We did this.
