### ISSUE TITLE
Sprint O

### ISSUE THREAD

**Issue by jbenet** [ipfs/pm#21]
## Sprint Discussions

See https://github.com/ipfs/pm#sprint-discussion-schedule

## Sprint Deliverables

- Add yourself below, that way we only have people listed who are really in the sprint
- Add links to issues down here. Only add things you can finish this sprint.

### @jbenet
- [ ] iprs, records, record chain
- [ ] signed records
- [ ] record tests
- [ ] merge GC, batching (datastore), batching (go-ipfs)
- [x] https://github.com/jbenet/node-bsdash

### @whyrusleeping
- [x] extra logs for bitswap dashboard
- [x] implement basic bitswap dashboard
- [x] land GC
- [x] land batching (go-datastore)
- [x] land batching (go-ipfs)
- [x] field test dev0.4.0
- [ ] fix too many open files issue with bitswap/flatfs https://github.com/ipfs/go-ipfs/issues/1456
- [x] add lazy negotiation to go-multistream

### @lgierth 
- [x] cjdns-based auth for prometheus https://github.com/ipfs/infrastructure/pull/40
- [ ] prometheus dashboard https://github.com/ipfs/infrastructure/issues/35
- [ ] discover peers from cjdns https://github.com/ipfs/go-ipfs/pull/1316
- [ ] spec out relevant cjdns internals https://github.com/ipfs/notes/issues/14
- [ ] migrate IRC bots to solarnet https://github.com/ipfs/infrastructure/issues/33
- [ ] make IPFS config an Ansible step https://github.com/ipfs/infrastructure/issues/39
- [x] h.gateway.ipfs.io https://github.com/ipfs/infrastructure/issues/30

### @krl
- [ ] ipfs-app-tool
  that can add unixfs directories
- [ ] ipfs-app
- [ ] webui -> ipfs-app(s):

### @diasdavid
- [ ] Get node-swarm working
  - [x] Opening sockets between peer
  - [x] Negotiate a spdy-transport session (Connection) through multistream-select
  - [x] Open streams on top of spdy
  - [ ] Switch to Protobufs
- [x] Have node-identify working
- [ ] Write a good amount of tests for all of the above
  - [x] random-bytes-stream https://github.com/diasdavid/random-bytes-stream
  - [x] abstract stream muxer https://github.com/diasdavid/abstract-stream-muxer
  - [x] node abstract stream muxer compliant spdy implemenetation https://github.com/diasdavid/node-spdy-stream-muxer
  - [x] write remaining tests for abstract-stream-muxer https://github.com/diasdavid/abstract-stream-muxer/tree/master/tests
- [ ] Integrate swarm with the routing layer (to make the DHT interesting)
- [ ] Other
  - [X] Make the API for abstract-stream-muxer more flexible - https://github.com/diasdavid/abstract-stream-muxer/issues/1

**Comment by jbenet** [comment]
@whyrusleeping @heems @rht  @wking @cryptix @chriscool  and anyone else, post stuff below and i'll add it to the top.

**Comment by rht** [comment]
[ ] Fix processLink leak https://github.com/jbenet/goprocess/issues/5

Also I have had the confusion of the man-hour/week/month tracker that there is no 1-to-1 mapping between:
1. waffle.io board (planning, in progress, done) labels
2. this pm weekly issue (planning and done) + daily sprint sync (in progress). This is supposedly a strict subset of 1, but not many items are stated in an issue explicitly (although they will eventually turned into PR's). Just wondering if things need to be more semantic.
3. github per-repo milestone (opposite of icebox, or monthly-scale backlog). https://github.com/ipfs/pm/milestones

**Comment by chriscool** [comment]
Improve ipfs-paste: https://github.com/jbenet/ipfs-paste/pull/2

**Comment by whyrusleeping** [comment]
next sprint etherpad: https://etherpad.mozilla.org/biFo0CDpCp

**Comment by jbenet** [comment]
> Also I have had the confusion of the man-hour/week/month tracker that there is no 1-to-1 mapping between:
> 1. waffle.io board (planning, in progress, done) labels
> 2. this pm weekly issue (planning and done) + daily sprint sync (in progress). This is supposedly a strict subset of 1, but not many items are stated in an issue explicitly (although they will eventually turned into PR's). Just wondering if things need to be more semantic.

yeah, unfortunately we aren't using waffle as much. do we want to really commit to it? (i find it a bit tedious to organize, but if someone helps me with that, i'm down to commit to labeling all the things well). the labels will certainly help people asynchronously know what's going on. i'm no expert in agile/kanban, so if someone with better PM experience wants to take this on, lmk! whatever makes us more effective = really useful.

i still want the etherpad / sprint issue to be the canonical repr of what someone's definitely taking care of that week.

> 3. github per-repo milestone (opposite of icebox, or monthly-scale backlog). https://github.com/ipfs/pm/milestones

per-repo milestones are usually just groupings of related issues. @whyrusleeping and i hoped to move the milestones to be releases (like `0.4.0` for go-ipfs).

**Comment by rht** [comment]
This should have been sprint O.

**Comment by rht** [comment]
I am in for an AI/bot pm overlord.

**Comment by rht** [comment]
> per-repo milestones are usually just groupings of related issues. @whyrusleeping and i hoped to move the milestones to be releases (like 0.4.0 for go-ipfs).
Where labels should have been used for groupings instead.

Yet the waffle labels for issues are clearly still in the use.

If manual checkmarks can be removed https://github.com/blog/1506-closing-issues-via-pull-requests

**Comment by whyrusleeping** [comment]
@rht the waffle stuff is kinda done automatically. we have wanted to use it, but its a little difficult to get it integrated into (at least my) workflow. Unless you really like it, i wouldnt worry about it
