### ISSUE TITLE
Enter all Q4 Milestones into Github

### ISSUE THREAD

**Issue by flyingzumwalt** [ipfs/pm#224]
The Protocol Labs people did an extensive hands-on roadmapping exercise with milestones written on index cards. Now we've got to dump all those milestones into github.  On the all-hands call we decided to break these up per-project. When you have finished inputting your project's milestones, please check the box here.

_Note: this whole data-input step is a bit of a time sink. For future roadmap planning we will probably put this info into github first, before planning the roadmaps._
- [ ] core-api ???
- [ ] blog - ???
- [x] docs - @flyingzumwalt
- [x] websites - @VictorBjelkholm 
- [ ] ipfs-cluster - @hsanjuan 
- [x] libp2p - @diasdavid 
- [x] js-ipfs - @diasdavid 
- [ ] go-ipfs - @Kubuxu, @whyrusleeping 
- [ ] gx - @Kubuxu, @whyrusleeping 
- [ ] IPLD - @nicola 
- [x] infrastructure & dist @lgierth, @VictorBjelkholm 
- [x] research - @flyingzumwalt, @nicola 
- [x] project-repos - @RichardLitt 
- [x] standard-readme - @RichardLitt 
- [ ] multiformats - @diasdavid 
- [x] orbit - @haadcode 
- [x] PM/Decision Making/Governance - @flyingzumwalt

**Comment by Kubuxu** [comment]
I can handover cluster to @hasjuan

**Comment by flyingzumwalt** [comment]
PM/Decision Making/Governance Milestones: https://github.com/ipfs/pm/milestones

**Comment by Kubuxu** [comment]
I have to talk with @whyrusleeping how he wants to structure the goals so for now I am posting them here:
### go-ipfs:

- Week 02 (2016-10-24): Ship IPLD in go-ipfs, @whyrusleeping 
- Week 04 (2016-11-07): Sharding, @whyrusleeping 
- Week 04 (2016-11-07): Metrics lib consistency, @Kubuxu
- Week 04 (2016-11-07): Add helptext to all commands [go-ipfs#2648](https://github.com/ipfs/go-ipfs/pull/2648) @RichardLitt 
- Week 06 (2016-11-21): Reduce memory usage, @whyrusleeping 
- Week 06 (2016-11-21): Ship 0.4.5, @whyrusleeping 
- Week 07 (2016-11-28): Write Private Networks [go-ipfs#3313](https://github.com/ipfs/go-ipfs/issues/3313), @whyrusleeping 
- Week 08 (2016-12-05): Ship Filestore [go-ipfs#2634](https://github.com/ipfs/go-ipfs/issues/2634), @whyrusleeping 
- Week 09 (2016-12-12): Don't kill routers, @whyrusleeping 
- Week 09 (2016-12-12): Reach global 80% code coverage, @whyrusleeping 
- Week 09 (2016-12-12): Use HAMT for pinsets, @whyrusleeping 
- Week 10 (2016-12-19): Improve conectivity, @whyrusleeping 
- Week 10 (2016-12-19): Developer documentation, @whyrusleeping 
- Week 12 (2017-12-02): Reduce bandwidth, @whyrusleeping 
- Week 12 (2017-12-02): Developer experience, @whyrusleeping 
- Week 13 (2017-12-09): Improve performance, @whyrusleeping 
- Week 14 (2017-12-16): Ship keystore, @whyrusleeping 

### gx:
- Week 02 (24-10-2016): Workspaces #1: update, @lgierth 
- Week 08 (2016-12-05): gx test coverage

**Comment by VictorBjelkholm** [comment]
Infrastructure miletones + issues setup here: https://github.com/ipfs/infrastructure/milestones

**Comment by haadcode** [comment]
Updated Orbit's [ROADMAP](https://github.com/haadcode/orbit/blob/master/ROADMAP.md). I haven't created and assigned all the goals to the milestones yet but will do so asap.

In the process, I added the roadmap-generator tool to Orbit's repo, take a look [here](https://github.com/haadcode/orbit/tree/master/tools/roadmap-generator) if you want to include it in your project in a similar way.

For those who are interested, my process for generating the roadmap is:
1) Add milestones to the [project repositories](https://github.com/haadcode/labels-and-milestones/blob/master/config.yml#L1) with [labels-and-milestone](https://github.com/haadcode/labels-and-milestones) tool. This creates/updates the defined milestones across all the repos in Orbit project.
2) Generate ROADMAP.md in Orbit's repo with [roadmap-generator](https://github.com/haadcode/orbit/tree/master/tools/roadmap-generator).
3) Copy the generated ROADMAP.md to the root of the repo and commit it to Git.

This is fairly nice workflow and mostly automated, but in the future I'd like to remove the manual generation step and just let CI handle it. This comes in handy when the goals for a milestone get updated and the roadmap document needs to be re-generated.

**Comment by RichardLitt** [comment]
Project repos: https://github.com/ipfs/project-repos/milestones
Standard-Readme: https://github.com/RichardLitt/standard-readme/milestones?with_issues=no

A lot of my tasks were more tasks, or aren't tracked directly by themselves - for instance, events and docs. There is only one real milestone for standard-readme, at the moment, although I could easily fabricate more. For now, I've logged it there, and I'll keep a list of what I am doing internally.

**Comment by dignifiedquire** [comment]
> Design - @dignifiedquire

@flyingzumwalt @em-ly any thoughts on where to put this roadmap?

**Comment by VictorBjelkholm** [comment]
**Websites**
IPLD: https://github.com/ipld/website/milestone/1
Multiformats: https://github.com/multiformats/website/milestone/1
Libp2p: (hidden within a PR currently) https://github.com/libp2p/libp2p/pull/8

**Comment by flyingzumwalt** [comment]
@hsanjuan are all of the ipfs-cluster milestones in Github?

@RichardLitt I think there were Blog milestones to enter. Can you check and enter them if there are any?

**Comment by hsanjuan** [comment]
@flyingzumwalt some are, will take care of the rest asap.

**Comment by RichardLitt** [comment]
I just found these:

## Week 2, Oct 24
- Create editorial board

## Week 5, Nov 14
- Website presentation redesign

We don't have a lead for these, and the priorities will likely change in the coming week for blog milestones. I am going to belay adding them to ipfs/blog for now.

**Comment by diasdavid** [comment]
I just saw that I'm the captain of multiformats if https://github.com/ipfs/pm/issues/224#issue-183468315 is correct. I was unaware of this, is it correct?

**Comment by VictorBjelkholm** [comment]
@diasdavid this is not the first time there is a confusion about the caption of multiformats... I think in this case, it's just about the roadmap + milestones for Q4 that you captain, Richard is captain over the multiformats/multiformats repository and I think we're still missing a decision on who exactly captains the overall multiformats organization/effort, see this issue: https://github.com/multiformats/multiformats/issues/29

**Comment by RichardLitt** [comment]
@diasdavid AFAIK the list above was not meant to mean that you were captaining that effort, but that you would add the multiformats milestones somewhere. Someone needs to do that secretarial work.

**Comment by diasdavid** [comment]
I see, my apologies for those not being up yet, kind of short in time, will try to do it tomorrow or not later than next week

**Comment by RichardLitt** [comment]
No worries! I'm not shaming; just pointing out why I think your name is up there. :)
