### ISSUE TITLE
Sprint Q

### ISSUE THREAD

**Issue by jbenet** [ipfs/pm#23]
## Sprint Discussions

See https://github.com/ipfs/pm#sprint-discussion-schedule

## Sprint Deliverables

- Add yourself below, that way we only have people listed who are really in the sprint
- Add links to issues down here. Only add things you can finish this sprint.

### @jbenet

- [ ] talks for meetups
- [ ] coordinating meetups
- [ ] ipfsdld / jsonld / cborld
- [ ] land requests
- [ ] fix go-ipfs get problem
- [ ] fix go-ipfs CORS problem 

### @whyrusleeping
- [ ] docker registry demo fun times
- [x] figure out random API failures (https://github.com/ipfs/go-ipfs/issues/1490)
- [x] global timeout flag for API (https://github.com/ipfs/go-ipfs/issues/1325)
- [x] fix notifications test

### @daviddias || @diasdavid

- [x] abstract-stream-muxer
  - [x] Timing reports (https://github.com/diasdavid/abstract-stream-muxer/commit/a454989cf83e62f38b4206e3c9d9a3c110f592b6#diff-4663341696a08eef2606d83e7fb282a9R4)
- [ ] node-ipfs
  - [x] swarm
    - [x] avoid multiaddr explosion (https://github.com/diasdavid/node-ipfs-swarm/issues/1)
    - [x] write proper README
  - [x] Get dignifiedquire up to speed (he is busy)
  - [ ] routing
    - [ ] Define de facto standard routing interface
    - [ ] DHT
      - [ ] Open a stream between any peer
      - [ ] `Provide`
    - [x] ping protocol
  - [ ] Blog post about the importance of protocol multiplexing (spdy + multistream-select)   
- [ ] Other
  - [ ] travis-ci all the things
  - [x] IFPS meetups extravaganza!

### @rht
- [ ] cleanup https://github.com/ipfs/go-ipfs/pull/1495, https://github.com/ipfs/go-ipfs/pull/1487
- [ ] repo constraint https://github.com/ipfs/go-ipfs/issues/1482
- [ ] versioning

### @krl
- [x] finish modularizing the last apps
- [ ] prepare ipfs-app demo
- [x] node-api/ctld issues and PRs
- [x] start building out starlog

### @mappum
- [x] cube UX document for designers
- [ ] build interface w/ React
- [ ] cube server API
- [ ] cube CLI client

### @lgierth

- [ ] discover peers from cjdns https://github.com/ipfs/go-ipfs/pull/1316
- [ ] spec out relevant cjdns internals https://github.com/ipfs/notes/issues/14
- [ ] have repo config managed by ansible https://github.com/ipfs/infrastructure/issues/39
- [ ] rebuild more gateway hosts

### @chriscool

- [ ] https://github.com/chriscool/sharnessify

**Comment by diasdavid** [comment]
### Sprint Update

- [x] - Meetup extravaganza 
- [x] - Update the Network Layer (libp2p) spec with new understanding of how Peer Routing, Discovery integrates it (still a work in progress, but the code has moved towards the libp2p direction two with better standardise interfaces and expectations)
- [ ] - network-layer || libp2p
  - [x] Implement PING proto
  - [x] - Add READMEs, open issues to make it more friendly for others to contribute 
  - [x] discovery
	- [x] standardise the interface
	- [x] make mDNS a separate module and conform with the interface + ability for the peer to announce itself and also to verify if it can indeed open a connection https://github.com/diasdavid/node-ipfs-mdns		
	- [x] create bootstraplist / railing module - https://github.com/diasdavid/node-ipfs-railing
  - [~] swarm
      - [x] Avoid multiaddr explosion
      - [x] add ability to open just connection (without a protocol stream)
      - [x] standardise the interface (pretty much done)	
      - [x] wire tests with timestamps
   - [ ] Peer routing
       - [~] Standardize the interface

**Comment by whyrusleeping** [comment]
This past week I got the docker registry code up and running, but while doing that, I hit more api failures than I wanted to shake a stick at, so I spent some time on fixing that.
I implemented a global timeout flag that will allow you to get a timeout'ed context from a commands request.
I fixed the notifications test failure that has been plaguing us for quite some time, i made our CI detection aware of circleCI which reduces even more random test failures.
windows builds now work again, and binaries are available through gobuilder once more.
I added a --create option to object patch that is still in CR.
And I am working on a PR that adds errors through http trailers to fix silent API failures.

**Comment by lgierth** [comment]
very short update from myself:
- started working on cjdns-in-ipfs (codename interplanetary express), read *a lot* of cjdns code, and getting better with golang. it's generally good to go forward, but i need a bit of direction feedback
- neptune is being rebuilt tonight, includes repo config managed by ansible
- a few more battlemesh preparations
- no progress on peer discovery via cjdns

**Comment by krl** [comment]
finished ipfs-web-app, modularized the webui using this, still needs to be made a release.
wrote a wrapper to run the node-ipfs-api tests in node and browser (phantomjs)
worked on append-only log with text-search, almost done.

will build and publish a new version of webui and finish the log proof of concept, build it out to a demo.

**Comment by jbenet** [comment]
- I had a pretty unproductive week -- burned tons of time in coordinating logistics for PDX travel, including surprise re-booking places :(, traveling, and meetup things.
- I did find _lots_ of bugs while demoing / hacking with people, which we're in the process fixing.
- Anyway, talks for meetups + coordinating meetups done.
- Lots of CR + issues
- ipfsld draft is over at https://github.com/ipfs/go-ipfsld -- this now just needs a cleanup of the dag.Node/Link part, and the marshal/unmarshal, but i think we have a pretty good API now.
- land requests -- apparently i'm physically incapable of landing this. 
- fix go-ipfs get problem -- worked with @whyrusleeping on this, looks close to done
- gix go-ipfs CORS problems -- still WIP. hope to have a PR ready next couple of days. (though anyone can pick this up from me)
- hacking on federated wiki: added support for adding images. (need to cleanup + fix CORS problem)
- node-ipfs-api -- figured out the vinyl files stream problem. it's still broken though
- worked with @daviddias on formulating the interfaces for "the network" components / libp2p

**Comment by chriscool** [comment]
Working on https://github.com/chriscool/sharnessify

**Comment by lgierth** [comment]
Sprint R: https://etherpad.mozilla.org/gnmzVUSJQk
