### ISSUE TITLE
Sprint Aug 17

### ISSUE THREAD

**Issue by lgierth** [ipfs/pm#28]
## Sprint Goals

...

## Sprint Discussions

See https://github.com/ipfs/pm#sprint-discussion-schedule

## Sprint Deliverables

- Add yourself below, that way we only have people listed who are really in the sprint
- Add links to issues down here. Only add things you can finish this sprint.

### @lgierth

- Bad blocks
  - [ ] deploy gateway-dmca-denylist https://github.com/ipfs/infrastructure/issues/59
- cjdns
  - [ ] land Discovery.Cjdns https://github.com/ipfs/go-ipfs/pull/1316
- Static pages on the gateways
  - [ ] migrate gateway.ipfs.io to ipfs.io https://github.com/ipfs/infrastructure/issues/4
  - [ ] dist.ipfs.io and ipfs.io/dist https://github.com/ipfs/distributions
- Hosts
  - [x] rename willie and scruffy https://github.com/ipfs/infrastructure/issues/58
  - [x] storage hosts sirius and pollux https://github.com/ipfs/infrastructure/pull/62
  - [ ] access to storage host for @davidar
- SSL/TLS on the gateways
  - [ ] StartSSL cert https://github.com/ipfs/infrastructure/issues/6
  - [x] erase plaintext secrest from history
- downloads.openwrt.org in IPFS
  - [ ] investigate `ipfs add` bottleneck https://github.com/ipfs/infrastructure/issues/64

### @diasdavid

- [x] Add more tests to kad-router
- [x] Review and provide feedback on HTTP-P2P https://datatracker.ietf.org/doc/draft-benfield-http2-p2p/
- [ ] Revamp network spec -> make a libp2p spec
- [ ] "hopefully" have something like a record store
- [x] Catch up on W3C WebRTC WG, document railing process
- [x] update multistream + multicodec https://github.com/jbenet/multicodec/pull/2 https://github.com/jbenet/multistream/pull/3 https://github.com/jbenet/multistream/pull/2

**Comment by lgierth** [comment]
@jbenet @whyrusleeping @krl @cryptix @diasdavid @mappum please add your tasks

**Comment by jbenet** [comment]
@lgierth thank you. sorry i keep failing at this-- (ton of lose endes). Actually, if someone wants to take over the materializing of the etherpad + sprint issues from me, would be much appreciated

**Comment by jbenet** [comment]
@whyrusleeping and i discussed go-ipfs over 
- https://etherpad.mozilla.org/Qn2JQa4eXx
- https://botbot.me/freenode/ipfs/2015-08-19/?msg=47633855&page=3
- https://botbot.me/freenode/ipfs/2015-08-22/?msg=47880245&page=4

Summary is: 
- this week we land batches: 1, 4, 7, 8
- next are: 2, 5 > 3, 9 > 6

all the Go help we can get is useful.

**Comment by jbenet** [comment]
### IPLD / Records

#### Batch 1:
- implement protobuf support (missing) @jbenet
- solve https://github.com/ugorji/go/issues/93
- go-ipld module (done) (needs a tweak to just use go-multicodec) @jbenet
- extract all the merkle dag tooling into own module(s), maybe
  under go-ipld, or maybe under go-merkledag or go-mdag
- public/private blockstores

#### Batch 2:
- implement go-iprs on top of go-ipld  // records + ipld
- keystore (@whyrusleeping)

#### Batch 3:
- dht / naming fixes
- migration! \o/ (let's do this last, because records may need it too)

### other batches

this doesn't make much sense, as they're not ordered. just some "coarser units of work".

#### Batch 4 -- landing @whyrusleeping's PRs
- pub/priv blockstore https://github.com/ipfs/go-ipfs/pull/1538
- nodebuilder https://github.com/ipfs/go-ipfs/pull/1572 @whyrusleeping
- blocklists https://github.com/ipfs/go-ipfs/pull/1551 @whyrusleeping
- mfs https://github.com/ipfs/go-ipfs/pull/1550 @whyrusleeping
- Editor more efficient https://github.com/ipfs/go-ipfs/pull/1567 @whyrusleeping

#### Batch 5 -- symlinks!
- symlink support!!! 

#### Batch 6 -- ipget + ipfs-update
- ipget
- ipfs-update (using new dist.ipfs.io)

#### Batch 7 -- landing @rht's PRs
- gc https://github.com/ipfs/go-ipfs/pull/1495 @rht there is filesize bug so this is pending
- ctx https://github.com/ipfs/go-ipfs/pull/1585 @rht RTM
- get https://github.com/ipfs/go-ipfs/pull/1558 @rht
- notify https://github.com/ipfs/go-ipfs/pull/1569 @rht RTM

#### Batch 8 -- bughunting
- memory leak/fail when >20GB https://github.com/ipfs/go-ipfs/issues/1584
- add abruptly dies https://github.com/ipfs/go-ipfs/issues/1591
- UTF8 corruption https://github.com/ipfs/go-ipfs/issues/1582

#### Batch 9 -- bughunting less important
- pin path ancestors? https://github.com/ipfs/go-ipfs/issues/1580
- datastore keys cant contain '/' https://github.com/ipfs/go-ipfs/issues/1554

**Comment by jbenet** [comment]
@whyrusleeping I've CRed all your Batch 4. (still need to play more with mfs. im not super sold on the UX. maybe it could be another tool entirely, but consider the `local` (`/myfs/...` at `$repo/local/myfs`) idea i suggested there.

**Comment by jbenet** [comment]
@rht i merged ctx, get, and notify! :) If you can tackle some of the things above, maybe some of the bugs, or even symlinks, would be great.

**Comment by rht** [comment]
> symlink support!!! @whyrusleeping

what about unixfs permission?

**Comment by jbenet** [comment]
@rht yeah, we should add these as well.

**Comment by jbenet** [comment]
- My sprint update for tonight. 
- sorry for failing again on the etherpad-- @lgierth has picked this up instead
- whyrusleeping and i charted a roadmap for go-ipfs dev 0.4.0 in writing. it was good way to list out all the things we need to do. may be useful to do similar for other things.
- we're behind on many things, let's pick it up!

---

- [ ] ship dist.ipfs.io (not done)
  - [x] improved mkdist.js for more dists / versions
  - [x] ipfs-app mkdist.js
  - [ ] need ipfs-app gif
  - [ ] first build of dist.ipfs.io
- [x] ipld / go-multicodec -- implemented + shipped
  - [ ] needs cbor ordering fix + protobuf test fixes
- [x] upcoming go-ipfs things + dev 0.4.0 roadmap
- [x] fix https://github.com/ipfs/infrastructure/blob/master/seeding/refs-to-seed
  - [x] ensure everything is seeded
  - [ ] seed on {sirius,pollux}.i.ipfs.io (not done)
- outreach
  - [x] berlinjs meetup talk
  - [x] podcast invterview (out tonight)
  - [x] caught up on mailpile
  - [x] caught up on ext discussions
- [x] catch up on CR (anything left for me?) 

---

- I may not be back in time for IRC checkin. _if i'm not_, someone (maybe @lgierth or @diasdavid) go through everyone?
- @whyrusleeping may be out today.

**Comment by diasdavid** [comment]
## SPRINT UPDATE

This past week was +- productive. Coming back home after 53 of travelling meant that I had to take care of a lot of stuff in the first couple of days.

- [x] Wrote more tests to the kad-router (which covered some more edge cases)
- [x] Reviewed HTTP-P2P proposal
- [x] Worked a lot of revamping the network spec, now known as libp2p. It still requires more though, specially after having a good conversation today with @jbenet where we learned that we weren't completely in sync of how the Record Store would work, did some progress, hopefully it will be nailed down by today node-ipfs meeting
- [x] continue pursuing my role in the W3C WebRTC WG, documented railing process and still digesting all of the info available
- [x] update multistream + multicodec specs https://github.com/jbenet/multicodec/pull/2 https://github.com/jbenet/multistream/pull/3 https://github.com/jbenet/multistream/pull/2

**Comment by lgierth** [comment]
Pad for Sprint Aug 24: https://etherpad.mozilla.org/CFlfCtFXnB

**Comment by krl** [comment]
Starlog can now do infinite scroll, publishing and viewing of entries. Webcomponents turn out to be a really nice match to ipfs, from starlog repo you can now do 'npm run local', and 'npm run gateway' to use vulcanize to pack everything up into one html file, and view it on 5001 or gateway (still fails on CORS though)

I would like to take next week to properly package the ipfs-api webcomponent, and make it part of the build-step of node-ipfs-api (maybe rename it too?). Things left to be done for starlog is editing entries.

have been bitten by untested edge cases in the append only log, and spent quite some time fixing that and covering all things we need.

**Comment by lgierth** [comment]
hosts
- applied proper naming to the utility hosts scruffy and willie, they're now deimos and phobos
- built out the storage hosts sirius and pollux
- gave davidar a login for sirius and pollux
- mirrored downloads.openwrt.org to pollux
- investigating ipfs add bottlenecks
gateways
- still using a self-signed cert, waiting for startssl.com's process
- made IPNSHostname work (kind of), for self-hosting ipfs.io
  - needs a bit more work regarding stylesheets in directory listings
- ongoing fixes to the readonly api, we need CORS there
- erased secrets from the infrastructure.git history (i.e. rewrite history)
not-done
- dist.ipfs.io deployment
- gateway-dmca-denylist
- discovery.cjdns
general things
- picked up sprint sync
- badly need to increase infrastructure bus factor, i'm the only one that can deploy at the moment and that sucks. it makes me a bottleneck, and keeps me from working on go-ipfs and cjdns stuff

**Comment by chriscool** [comment]
My sprint update (sorry for being late):
- gave my talk at LinuxCon NA where I talked about Sharness and a bit about IPFS
- met some people who already know about IPFS like Alexis Rossi of the Internet Archive
- changed the GitCop message a bit and responded to Gary (the GitCop guy)
- started https://github.com/ipfs/go-ipfs/pull/1599 and sent email to Markus
