### ISSUE TITLE
Sprint Aug 24

### ISSUE THREAD

**Issue by lgierth** [ipfs/pm#29]
## Sprint Goals

- IPLD/records, whyrusleeping's PRs, rht's PRs, and bughunting. More details here ff.: https://github.com/ipfs/pm/issues/28#issuecomment-133756315
- everybody able to deploy our infrastructure

## Sprint Discussions

See https://github.com/ipfs/pm#sprint-discussion-schedule

- Infrastructure discussion: https://etherpad.mozilla.org/SHYH0M9LvG

## Sprint Deliverables

- Add yourself below, that way we only have people listed who are really in the sprint
- Add links to issues down here. Only add things you can finish this sprint.
 
### @krl

- [ ] make ipfs-api webcomponent part of node-ipfs-api build process
- [ ] editing of starlog entries

### @rht
- [ ] https://github.com/ipfs/go-ipfs/issues/1072
- [ ] https://github.com/ipfs/go-ipfs/issues/1584
- [ ] dag archive

### @chriscool
- [x] https://github.com/ipfs/go-ipfs/pull/1599

### @lgierth

- [x] enable CORS for API https://github.com/ipfs/go-ipfs/issues/1586 https://github.com/ipfs/infrastructure/pull/68
- Infrastructure bus factor
  - [ ] split up https://github.com/ipfs/infrastructure/pull/74
- Bad blocks / denylist
  - [x] review why's PR https://github.com/ipfs/go-ipfs/pull/1551
  - [ ] add reason field (dmca vs. code-of-conduct)
    - i.e. 451 Unavailable For Legal Reasons vs. 452 Violation of Code of Conduct, or so
  - [ ] denylist.ipfs.io https://github.com/ipfs/infrastructure/issues/59
- [x] TLS/SSL for gateways https://github.com/ipfs/infrastructure/issues/6
- Static pages on gateway
  - [ ] migrate gateway.ipfs.io to ipfs.io https://github.com/ipfs/infrastructure/issues/4
  - [ ] inline directory-listing stylesheets https://github.com/ipfs/go-ipfs/pull/1615 (from http://gateway.ipfs.io/ipfs/QmWxrgcm6nTNbRB7S2ugq7Wfw3pD1FVBTN6WMtkHiD396u/bundle.css)
  - [ ] make /ipfs and /ipns work for (gateway.)ipfs.io https://github.com/ipfs/infrastructure/pull/72
- [ ] giving people non-root access

### @diasdavid

- [ ] Continue working on libp2p-spec
- [ ] Implement Record, following IPRS
- [ ] Make abstract-record-store
- [ ] Implement kad-record-store, that follows abstract-record-store interface
- [ ] Implement distributed-record-store
- [ ] node-ipld https://github.com/diasdavid/node-ipld
- [x] Make the Node.js implementation more welcoming by:
  - [x] Adding CI
  - [x] Adding Code Coverage reference
  - [x] Adding Badges
    - [x] david-dm
    - [x] codestyle
    - [x] build

### @jbenet

- [x] doc for ipfs-api implementors https://github.com/ipfs/go-ipfs/blob/master/docs/implement-api-bindings.md
  - [x] implement `--api <multiaddr>` option https://github.com/ipfs/go-ipfs/pull/1598
  - [x] tests for  `--api <multiaddr>` option (can someone pick this up?)
- [ ] batch 1 of go-ipfs https://github.com/ipfs/pm/issues/28#issuecomment-133756372
  - [x] multicodec protobuf support https://github.com/jbenet/go-multicodec/pull/1
  - [x] go-ipld module use multicodec 
  - [ ] extract all the merkle dag tooling into own module
- [ ] dist.ipfs.io
  - [ ] screenshot for ipfs-app
  - [ ] make sure ipfs-app dist works
  - [ ] run a full dist in a storage node
- statship
  - [x] figure out docker reqs
  - [x] detailed spec (inc UX and what's needed)
  - [ ] prototype it
- eth
  - [ ] c++ api bindings? (req ipfs-api impls)
  - [ ] patricia tree stuff?
- outreach
  - [x] organize IPFS Berlin meetup
  - [x] ipfs meetup
  - [x] talk with ascribe.io 
  - [ ] talk with alexandria
  - [x] prepare Zurich talks

### @whyrusleeping
- [ ] finish mfs PR
- [ ] finish lists PR
- [ ] land node constructor PR
- [ ] land blocklists PR
- [x] investigate/fix cbor encoding issue
- [x] fix protobuf multicodec

**Comment by jbenet** [comment]
added my tasks above. @whyrusleeping

**Comment by jbenet** [comment]
@lgierth maybe deprecate the etherpad when making issues: https://etherpad.mozilla.org/CFlfCtFXnB that way people who are late know to post it here

**Comment by lgierth** [comment]
> maybe deprecate the etherpad when making issues: https://etherpad.mozilla.org/CFlfCtFXnB that way people who are late know to post it here

yep good call

**Comment by jbenet** [comment]
- @whyrusleeping your list  looks sparse-- are you getting through all of Batch 1 + 4 stuff? https://github.com/ipfs/pm/issues/28#issuecomment-133756372 
- @whyrusleeping @rht how are we handling batch 8 ?
- @rht i think dag-archive is way under specified atm. land batch 8 instead? 
- @rht what is next step on https://github.com/ipfs/go-ipfs/pull/1495 ?

**Comment by rht** [comment]
batch 8:
"progress" on https://github.com/ipfs/go-ipfs/issues/1072 if @whyrusleeping can take a head shot on it.

There are 3 cases of the bug:
1. the original issue, which is too big for me to download and to reproduce. It was said there is no symlink.
2. @davidar's, also too big. Can't tell if there is a symlink.
3. my case, which can be reproduced with `ipfs add -r Godeps/_workspace/src/github.com/jbenet/go-multihash`. This is fixed with removing the broken symlink.

Still can't tell why the symlink err doesn't appear in the daemon or `ipfs add`.
The symlink err appears, however, when I forced to Stat() all the fileinfo right after https://github.com/ipfs/go-ipfs/blob/master/commands/files/serialfile.go#L58

**Comment by davidar** [comment]
@rht No symlinks. I can try to make a test case that doesn't require downloading anything if that helps

**Comment by rht** [comment]
@davidar It will definitely help. It is likely any file that is not regular file or directory?

One culprit of the not returning err is likely in one of `os.Open`.
Currently pulling things from https://github.com/ipfs/go-ipfs/pull/1413 (but with Stat replaced by Lstat).

**Comment by davidar** [comment]
@rht No, just regular files. Test case:

```bash
mkdir foo
for i in `seq 999`; do dd if=/dev/urandom of=foo/$i bs=1M count=1; done
ipfs add -r foo
```

**Comment by lgierth** [comment]
I'll likely be on the train tomorrow CEST evening, can someone head the sprint sync for me? That involves:

- announce at 5pm UTC
- post new etherpad here
- role call and start at 5:15pm UTC
- discuss sprint goals

**Comment by whyrusleeping** [comment]
@lgierth I got it.

**Comment by lgierth** [comment]
Thanks @whyrusleeping, I'll materialize the sprint issue on tuesday

**Comment by lgierth** [comment]
My sprint update, I likely won't be around for sync.

done

- enable CORS for API -- this was blocking krl's work
- TLS/SSL for gateways
  - our setup is graded A by SSL Labs :) https://www.ssllabs.com/ssltest/analyze.html?d=gateway.ipfs.io&latest
- Infrastructure bus factor
  - split up the monolithic ansible playbook -- this will make deploys faster since we don't need to run *all* the tasks, but only the ones we want
- hellabot CR
- hetzner netscan alert, once more

pending CR/merge/deploy

- Static pages on gateway
  - inline directory-listing stylesheets https://github.com/ipfs/go-ipfs/pull/1615 (from http://gateway.ipfs.io/ipfs/QmWxrgcm6nTNbRB7S2ugq7Wfw3pD1FVBTN6WMtkHiD396u/bundle.css)
  - make /ipfs and /ipns work for (gateway.)ipfs.io https://github.com/ipfs/infrastructure/pull/72

little/no progress

- Bad blocks / denylist
  - not a lot of progress, direction changed a bit and there was fruitful discussion, i held back from taking further steps though while it wasn't clear which direction we're taking
- giving people access to our boxes
  - just didn't get to it

**Comment by whyrusleeping** [comment]
New etherpad: https://etherpad.mozilla.org/ijvTxGAhOP

**Comment by diasdavid** [comment]
## SPRINT CHECKIN

This week's primary goal, pushing a working version of a libp2p, was majorly delayed to the current challenges when implementing IPLD, due to json-ld limitations, which lead to a lot of discussion in what is the best approach from here forward when it comes to Linked Data. IPLD is necessary for creating MerkleDAG obj/links, which is the data structure of IPRS.

- Worked in the Node.js implementation https://github.com/diasdavid/node-ipld
- Listed current components of the IPFS Node.js implementation in the node-ipfs repo, so other people could follow their state. 
- Added some convenient features for contributors to the set of node modules we have for libp2p, so other people feel more encourage to contribute following things like codestyle, passing tests, coverage, etc.
- Edited Kyle's talk on "Making the Web Permanent"
- Started writing an article (currently on: https://raw.githubusercontent.com/diasdavid/blog.daviddias.me/master/drafts/2015-09-XY-real-time-communications-the-challenges-solved-with-webrtc.md) to document how WebRTC solves the transversal network problems for P2P applications
- Continued working and reviewing WebRTC specs, sent out some request for clarifications and editorial mistake fixes. (It is kind of refreshing seeing how some of WebRTC specs have been broken down into smaller, with a single focus, specs)
- Also took some time to look more in depth to React stuff for the electron app

**Comment by jbenet** [comment]
### @jbenet's update

I'm at an IPFS dinner meetup organized by IPFSers in Basel (switzerland). will be giving a talk tomorrow at ETH, and talks to other groups here. Will look through updates + sync up with people a bit later tonight.

- got about half of what i wanted to get done :/
- The critical stuff is IPLD + Starship. 
- Starship on track
- Ran into issues with IPLD's model, discussing with mildred and daviddias
- multicodec improvements took a bit longer, but it's in great shape now.
- below is the checkbox listing:

- [x] doc for ipfs-api implementors https://github.com/ipfs/go-ipfs/blob/master/docs/implement-api-bindings.md
  - [x] implement `--api <multiaddr>` option https://github.com/ipfs/go-ipfs/pull/1598
  - [x] tests for  `--api <multiaddr>` option (can someone pick this up?)
- [ ] batch 1 of go-ipfs https://github.com/ipfs/pm/issues/28#issuecomment-133756372
  - [x] multicodec protobuf support https://github.com/jbenet/go-multicodec/pull/1
  - [x] go-ipld module use multicodec 
  - [ ] extract all the merkle dag tooling into own module
- [ ] dist.ipfs.io
  - [ ] screenshot for ipfs-app
  - [ ] make sure ipfs-app dist works
  - [ ] run a full dist in a storage node
- statship
  - [x] figure out docker reqs
  - [x] detailed spec (inc UX and what's needed)
  - [ ] prototype it
- eth
  - [ ] c++ api bindings? (req ipfs-api impls)
  - [ ] patricia tree stuff?
- outreach
  - [x] organize IPFS Berlin meetup
  - [x] ipfs meetup
  - [x] talk with ascribe.io 
  - [ ] talk with alexandria
  - [x] prepare Zurich talks
- added
  - [x] ipld discussions with json-ld folks, mildred, daviddias
  - [x] multicodec binary to test out the interface
  - [x] tons of CR

**Comment by whyrusleeping** [comment]
## @whyrusleeping's update

- [ ] finish mfs PR
  - switched from 'session' flag to pathing
  - ready for final CR
- [ ] finish lists PR
  - still unclear on what steps to take
- [x] land node constructor PR
- [x] investigate/fix cbor encoding issue
- [x] fix protobuf multicodec
- [x] rewrite trailers code for go1.5 (not merged yet)
  - should discuss *when* to switch to 1.5
- [x] symlinks PR is up, implements basic support for adding symlinks, viewing them in fuse, and writing them via `ipfs get`
- [ ] rm blockservice workers
  - bitswap doesnt block, provides collector makes sure of that.
  - still have a couple TODO's on that
- worked on gx
- wrote https://github.com/whyrusleeping/gx-go-import to make importing packages easy
