### ISSUE TITLE
Sprint 2

### ISSUE THREAD

**Issue by jbenet** [ipfs/pm#3]
**Sprint Goals** - 
1. Get the migrations done + flat repo merged
2. Finish the container assets for last week
3. DHT interface changes
4. Prepare keystore

**Sprint Participants** - @jbenet @dylanPowers @hosh @whyrusleeping

**Sprint Deliverables**

- [ ] Containers:
  - [ ] Demo #6 https://github.com/jbenet/ipfs-container-demos/issues/3 (@hosh)
      - [ ] Prepare VM that can scale X VMs
  - [ ] Demo #7  https://github.com/jbenet/ipfs-container-demos/issues/4 (@hosh)
      - This likely requires mounting Docker Daemon on IPFS. Otherwise, part of this
         has already been demo'd by Demo #4 (IPFS in a container)
  - [ ] https://github.com/jbenet/ipfs-container-demos/issues/5 (@hosh)
    - [ ] Astralboot. Note: likely dropped for the sprint after
  - [ ] https://github.com/jbenet/ipfs-container-demos/issues/8 (@jbenet)
  - [ ] https://github.com/jbenet/ipfs-container-demos/issues/17 (@whyrusleeping)
    - [ ] Blocker: vm's take forever to add, makes working on this painful

- [ ] Community
  - [ ] Periodic Newsletter (@dylan) https://github.com/ipfs/community/issues/8
  - [ ] Waffle documentation (@dylan) https://github.com/ipfs/infrastructure/issues/8
  - [ ] Explain the label scheme (@dylan) https://github.com/ipfs/community/issues/10
  - [ ] godoc/readmes on packages
  - [ ] go-ipfs reorg (@jbenet)

- [ ] DHT
  - [ ] interface adjustments (@jbenet, @whyrusleeping)
  - [ ] request collation (@whyrusleeping)

- [ ] Migrations + Flat Repo (@whyrusleeping)
  - [x] write migration 1-2 (@whyrusleeping)
  - [ ] merge flat repo in datastore (@whyrusleeping)
  - [x] use flat repo in go-ipfs (@whyrusleeping)
    - Done, not merged

- [ ] other
  - [ ] review + improve the keystore spec (@whyrusleeping, @jbenet)
    - Note: has been updated
  - [x] merge outstanding PRs in go-ipfs (@whyrusleeping, @jbenet)
  - [x] merging outstanding webui PRs (@jbenet)
  - [ ] add @travisperson eventdrop (@travisperson)
  - [ ] Publish the blog (@jbenet)
  - [x] push website "how it works" update (@jbenet)
  - [x] website better links to things (@jbenet)
  - [x] move ipn.io out of protocol/websites (@jbenet)
  - [x] more pinning tests (@jbenet) https://github.com/ipfs/go-ipfs/commit/d26a0a27055a7c431c5eb682f93361861908c826
  - [x] fix pinning usage in add
  - [x] made ipfs installable via npm (@jbenet) https://github.com/jbenet/node-go-ipfs and https://www.npmjs.org/package/go-ipfs
  - [x] fixed goprocess bug  (@jbenet) https://github.com/ipfs/go-ipfs/pull/1061
  - [x] fixed add error (@whyrusleeping, @jbenet) https://github.com/ipfs/go-ipfs/pull/1061
  - [x] made playback player use ipfs (@jbenet) https://github.com/jbenet/playback
  - [x] removed msgio wrapping (@jbenet) https://github.com/ipfs/go-ipfs/pull/1065
### Backlog

- [x] periodically measure gateway performance
    - https://ipfs-stats.rbel.co/dashboard/db/ipfs-global
- [ ] fix `refs local` bug (ipfs/go-ipfs#994)
- [ ] Implement a tool that achieves `ipfs-docker run <ipfs-path>`
    - Note: mount ipfs, run registry on ipfs-path, `docker pull image-name`/`docker run localhost:5000/imagename`
- [ ] Fix Broken Symlinks (ipfs/go-ipfs#979)
