### ISSUE TITLE
Sprint Aug 31

### ISSUE THREAD

**Issue by diasdavid** [ipfs/pm#30]
## Sprint Discussions

See https://github.com/ipfs/pm#sprint-discussion-schedule

- this could be links to your discussion etherpads

## Sprint Deliverables

- Add yourself below, that way we only have people listed who are really in the sprint
- Add links to issues down here. Only add things you can finish this sprint.

### @diasdavid

- IPFS Node.js Implementation
  - [x] Make a decision on the direction of IPLD with @jbenet and @whyrusleeping 
  - [x] node-ipld https://github.com/diasdavid/node-ipld/releases/tag/v0.1.0
  - [x] remap-keys https://github.com/diasdavid/remap-keys
  - [x] Implement Record, following IPRS spec, with IPLD
  - [x] IPRS Review https://github.com/ipfs/specs/pull/26 https://github.com/ipfs/specs/pull/25 https://github.com/ipfs/specs/pull/22
  - [x] Define abstract-record-store https://github.com/diasdavid/abstract-record-store/blob/master/README.md
  - [x] abstract-record-store test suit
  - [x] idempotent codecs post - https://github.com/diasdavid/blog.daviddias.me/blob/master/drafts/2015-09-07-idempotent-encoders-decoders.md (up for review)
  - [ ] Implement kad-record-store, that follows abstract-record-store interface
  - [x] Implement distributed-record-store
  - [ ] Continue working on libp2p-spec
- W3C WebRTC WG + IETF RTCWeb
  - [ ] Finish the article studying WebRTC and how it solves the transversal problems to P2P applications

### @lgierth

- Denylist
  - https://github.com/ipfs/go-ipfs/pull/1551
  - https://github.com/ipfs/gateway-dmca-denylist
- SSL @ gateway
  - [x] fix CORS for https:// https://github.com/ipfs/infrastructure/issues/76
- ipfs.io @ gateway
  - [x] SSL cert for dogfeed.ipfs.io
  - [ ] SSL SNI to switch between ipfs.io, dogfeed.ipfs.io, other
  - [x] /ipfs and /ipfs on self-hosted ipfs.io https://github.com/ipfs/infrastructure/pull/72
  - [x] switch ipfs.io over
  - [ ] update deploy instructions https://github.com/ipfs/website
- Deploy
  - [ ] get one other person to deploy something
- cjdns
  - [ ] peer discovery using cjdns https://github.com/ipfs/go-ipfs/pull/1316
- Arbitrary static pages @ gateway
  - [ ] embed directory-listing styles -- https://github.com/ipfs/go-ipfs/pull/1615
  - [ ] refuse SSL handshake

### @whyrusleeping

- [x] symlinks
- [x] print API panics
- [x] rebase dev0.4.0 again
- [ ] get mfs merged
- [ ] add improvements https://github.com/ipfs/go-ipfs/pull/1567
- [ ] fix notifications test https://github.com/ipfs/go-ipfs/issues/1614

### @jbenet

- [ ] IPLD
  - [x] plan fwd with @mildred and @diasdavid 
  - [x] go-ipld module use multicodec 
    - [x] go-ipld old protobuf coding
  - [x] multicodec tool to make working with it easy
  - [ ] extract all the merkle dag tooling into own module
- statship
  - [ ] CLI tool scaffolding
  - [ ] polish the UX
  - [ ] write help / docs
  - [ ] starship site mock
  - [ ] test it with distribution plugin + export
  - [ ] test it with distribution plugin + FUSE
  - [ ] test it with load/save
- go-ipfs
  - [ ] secret key for private swarms

**Comment by lgierth** [comment]
my sprint update:

- had a really slow week, but a few nice things got finished anyhow, and i'm happy to largely leave the infrastructure be for now.
- done:
  - fixed CORS for https:// on the gateways, as per @jbenet's bug report
  - got another SSL cert, for testing on dogfeed.ipfs.io
  - switched over to ipfs.io, with gateway.ipfs.io being still in place, with no redirect so far. we need to talk about security implications re: ipfs.io
  - made /ipfs,/ipfs,/api work alongside an ipfs-hosted static page
- not so completely done:
  - denylist -- another week without much progress, but we know what to do know and i'm working on it pretty much right now
  - get another person to deploy -- there are two lined up just waiting for a good occasion :)
  - peer discovery using cjdns -- i might other babysteps progress on go-cjdns though
- nothing:
  - custom static pages -- postponed that for now

**Comment by diasdavid** [comment]
## SPRINT CHECK IN

During last week, in a overview, managed to develop more of the Records system that libp2p uses, once me and @jbenet managed to figure how to push IPLD forward. The WebRTC wg F2F meeting is this Wednesday, where I'll be attending remotely.

- [x] Decide on minimum viable IPLD, that doesn't break json-ld and can be used for IPFS with @jbenet 
- [x] Create https://github.com/diasdavid/node-ipld (currently https://github.com/diasdavid/node-ipld/releases/tag/v0.1.3)
- [x] During the process of creating node-ipld, created the remap-keys module https://github.com/diasdavid/remap-keys
- [x] As an extra wrote a blog post about Idempotent encoder/decoders (up for review) - https://github.com/diasdavid/blog.daviddias.me/blob/master/drafts/2015-09-07-idempotent-encoders-decoders.md
- [x] Reviewed and patched IPRS spec ipfs/specs#26 ipfs/specs#25 ipfs/specs#22
- [x] Implement node-ipfs-record, which follows IPRS and uses IPLD https://github.com/diasdavid/node-ipfs-record
- [x] Define the interface for abstract-record-store https://github.com/diasdavid/abstract-record-store/blob/master/README.md
- [x] Implement a test for the abstract-record-store suite
- [x] Implement the first working iteration of Distributed Record Store https://github.com/diasdavid/node-ipfs-distributed-record-store which only needs now kad-record-store to be done, so it's 'extra record store' system to be complete
- [ ] (Still working on it) kad-record-store

**Comment by lgierth** [comment]
Pad for the Sep 7 sprint: https://etherpad.mozilla.org/nJ6U0IhKCb

**Comment by jbenet** [comment]
### @jbenet's update

- this week a lot of my time was taken up by talks in Basel and Zurich. which went well.
- We ran into more snags in the ipld definitions, but seems settled enough to implement in node + go. (thanks @daviddias and @mildred). I've implemented multicodec and everything we need from IPLD (except one last format sync i'll looking at daviddias's module). 
- But putting that on hold as i'm focusing on starship exclusively this week. more on that later.

- [ ] IPLD
  - [x] plan fwd with @mildred and @diasdavid 
  - [x] go-ipld module use multicodec https://github.com/ipfs/go-ipld/pull/6
    - [x] go-ipld old protobuf coding https://github.com/ipfs/go-ipld/pull/6
  - [x] multicodec improvements https://github.com/jbenet/go-multicodec/pull/6
  - [x] multicodec tool to make working with it easy https://github.com/jbenet/go-multicodec/pull/6
  - [x] msgio improvements https://github.com/jbenet/go-msgio/pull/9
  - [ ] sync with latest format + daviddias impl
  - [ ] extract all the merkle dag tooling into own module -- still need to do this
- starship
  - [x] narrowed scope of the tool
  - [x] tested all the components -- distribution
  - [~] CLI tool scaffolding -- working on this now.
  - [ ] polish the UX
  - [ ] write help / docs
  - [ ] test it with distribution plugin + export
- go-ipfs
  - [x] lots of CR
  - [ ] secret key for private swarms
  - [x] fix proc/ctx wiring https://github.com/ipfs/go-ipfs/pull/1655
  - [x] made a test for mappum's resolve PR
- comms
  - [x] talk at ETH (in Basel) to biotech people
  - [x] talk at Webilea (web dev meetup in Basel)
  - [x] discussions with a number of swiss crypto folks

**Comment by whyrusleeping** [comment]
@whyrusleeping's update

- [x] implement symlinks in unixfs
- [x] print panics when they happen in the API
- [x] rebase dev0.4.0 again
- [ ] get mfs merged
    - change of plans, going to rework
- [x] commands lib can now return errors correctly from a goroutine through the channel marshaler
- [x] blockservice no longer ignore blockstore errors
- [x] make editor more efficient https://github.com/ipfs/go-ipfs/pull/1567
    - [x] add --only-hash doesnt keep everything in memory
- [x] fix notifications test https://github.com/ipfs/go-ipfs/issues/1614
- [x] fix repo config panic
- [x] updates to gx
  - [x] gx-go-import works and can import go-ipfs (albeit not ideally)

**Comment by mildred** [comment]
Hi,

I'm willing to jump in this sprint, and work a bit on go-ipld with the format discussed with @jbenet. Especially if nobody is working on it this week.

I'll try to :

- write tests that can extract links and other information from the new format
- implement ipld using these tests
- find a way to get the algorithm extract information from the protobuf format (either special case or implement a generic method)
- find out if that is enough to plug in IPLD inside the core IPFS code.

**Comment by lgierth** [comment]
@mildred cool, much appreciated! we usually add the tasks we pick to the pad for the next sprint: https://etherpad.mozilla.org/nJ6U0IhKCb

And then on the next day, someone synthesizes a new issue in this repository
