### ISSUE TITLE
Sprint Sep 7

### ISSUE THREAD

**Issue by lgierth** [ipfs/pm#31]
## Sprint Goals

- container.camp
- go-ipfs 0.4.0

## Sprint Discussions

See https://github.com/ipfs/pm#sprint-discussion-schedule

*Please take notes in a separate pad, if you can, and link it here.*

## Sprint Deliverables

- Add yourself below, that way we only have people listed who are really in the sprint
- Add links to issues down here. Only add things you can finish this sprint.

### @whyrusleeping
- [x] assist in building of shp tool
- [ ] pull relevant changes out of mfs PR
- [ ] fix swarm notification failures
- [x] go1.5 sadhack failure fix
- [x] clean up goroutine leaks in tests
  - made some progress, not as much as i'd like
- [ ] tool to manually make bitswap requests
  - 'ipfs block get' to make a single request
  - [ ] 'ipfs bitswap unwant' to cancel
- [ ] investigate a timeout in FindProvs
- [ ] finish private-blocks PR
- [x] rebase dev0.4.0 again
- [x] go-peerstream bug 
- [x] fix ipns fuse tests

### @diasdavid

- [x] kad-record-store
- [ ] plug kad-record-store into distributed-record-store
- [ ] node-libp2p
- [x] attend WebRTC WG F2F Meeting remotely
- [x] attend container.camp
- [x] upgrade modules to be  `"engines" : { "node" : "^4.0.0" },`
  - https://github.com/diasdavid/libp2p-website/pull/1
  - https://github.com/diasdavid/node-ipld/pull/4
  - https://github.com/diasdavid/abstract-record-store/pull/1
  - https://github.com/diasdavid/node-ipfs-record/pull/1
  - https://github.com/diasdavid/node-ipfs-kad-record-store/pull/1
  - https://github.com/diasdavid/node-ipfs-kad-router/pull/1
  - https://github.com/diasdavid/node-ipfs-distributed-record-store/commit/a991524e7d7e16d35b2a18f2fb10d6d32869beab
  - https://github.com/diasdavid/remap-keys/commit/7150c2be829c3e34de824e9723dcfb462fa09f10
  - https://github.com/diasdavid/node-merkledag-store/commit/dd3f44c4d0b006a6789da74d46aaf27e25f9fe1a
  - https://github.com/diasdavid/node-ipfs-railing/commit/70fcf8cc501d646a13a32ccd07951e5c28b721a9
  - https://github.com/diasdavid/node-libp2p/commit/c1e9f5c6c09b83878e0095a1727f61e6f010c250
  - https://github.com/diasdavid/node-ipfs-peer/commit/5317037a26d3331f07ed38f734adc16e4dff2108
  - https://github.com/diasdavid/node-ipfs-logger/commit/b0318918bed6094813e9dbb2a0200850da6fff2c
  - https://github.com/diasdavid/node-ipfs-peer-id/commit/171a56153785ec5c6903372f4e4d5b7fcd888629
  - https://github.com/diasdavid/node-multistream/commit/cda1c1b53fbc7747cd284e11c74eeac6a69f2518
  - https://github.com/diasdavid/node-ipfs-swarm/commit/139ac6e85219a27b557330435375c590cdaf6fd0
  - https://github.com/ipfs/starlog/pull/24

### @lgierth

- [ ] denylist daemon https://github.com/ipfs/go-ipfs/pull/1551 https://github.com/ipfs/gateway-dmca-denylist
- [ ] storage user for @mikolalysenko https://github.com/ipfs/infrastructure/issues/84
- [x] h.ipfs.io for access via cjdns https://github.com/ipfs/infrastructure/pull/78
- [x] update gateway links on website https://github.com/ipfs/website/pull/40
- [ ] gateway: caching headers
- [ ] fix CORS headers for chrome https://github.com/ipfs/go-ipfs/issues/1659
- [x] chat.ipfs.io
- [x] HN outfall: full disks https://github.com/ipfs/infrastructure/issues/29 https://github.com/ipfs/infrastructure/issues/80
- pushed to next sprint
  - [ ] ipfs.io self-hosted blog post
  - [ ] peer discovery using cjdns https://github.com/ipfs/go-ipfs/pull/1316
  - [ ] switch-ping IPE<->cjdns https://github.com/lgierth/ipe
  - [ ] check out the ruby bindings https://github.com/Fryie/ipfs-ruby

### @richardlitt
- [x] Check in with krl about the front end for starlog
- [x] Take a look at the ipfs distro page and see if it can be touched up.
- [ ] Prepare a spec for an ops job
- [x] Check out the IPFS app and see if you can get it up, running, and clear without help or a walkthrough.
- [x] See about setting DNS records for DO programmatically. 
- [x] Take a look at node-ipfs. PR review from daviddias. 

### @chriscool

- [ ] https://github.com/ipfs/go-ipfs/pull/1644 vendor go-sleep as iptb

### @mildred

See: https://github.com/ipfs/pm/issues/30#issuecomment-138363384

- [ ] write tests that can extract links and other information from the new format
- [ ] implement ipld using these tests
- [ ] If time allows, find a way to get the algorithm extract information from the protobuf format (either special case or implement a generic method)
- [ ] If time allows, find out if that is enough to plug in IPLD inside the core IPFS code.

**Comment by diasdavid** [comment]
## SPRINT CHECKIN

- [x] built kad-record-store
- [x] attended container.camp (@jbenet did a great closing talk btw!!! starship is awesome)
- [x] attended W3C WebRTC WG Seattle Meeting
- [x] pushed on Node.js v4.0.0 for our Node.js repos through a bunch of PR (let me know if I missed any)

++ 

- Learned about a possible side-channel attack to ECDSA with secp256k1 curves, proposed a change for IPRS to mitigate that - https://github.com/ipfs/specs/issues/24#issuecomment-140136140 This would require me to change the DRS code, but better now than later
- I'll need to push for a new thing, a WebCrypto module that abstracts away the browser WebCryptoAPI and the crypto module in Node.js, so we can have isomorphic code (otherwise it is going to be a mess). Fedor validated the Idea :) https://github.com/nodejs/node/issues/2833#issuecomment-139854058
- Revisited swarm design, concluded I need to break it a lil more and follow two new interfaces
  - abstract-transport for a transport that offers a stream interface and that can be built on top of another stream too (for example, putting crypto stream on top of a plain text stream and or add things like congestion mechanism if needed for non reliable transports)
  - abstract-socket for a dial/listen interface, this will generate things like libp2p-tcp, libp2p-udp, libp2p-webrtc, etc
- people have been asking for bitswap, which I was waiting to have a libp2p all polished before shipping any code, but something we should consider is start migrating the network layer in go (even if a separate repo) to libp2p, so that when the Node.js one is ready, the Go one will be compatible from the start and bitswap can be interoperable.

**Comment by whyrusleeping** [comment]
### @whyrusleeping
- [x] assist in building of shp tool
- [ ] pull relevant changes out of mfs PR
  - still working on branch locally, mostly done
- [ ] fix swarm notification failures
  - very stubborn and random, needs more work
- [x] go1.5 sadhack failure fix
  - also fixed gobuilder at the same time!
- [x] clean up goroutine leaks in tests
  - made some progress, not as much as i'd like
  - [x] kill thirdparty/waitable for a solution that doesnt use extra goroutines
- [ ] tool to manually make bitswap requests
  - 'ipfs block get' to make a single request
  - [ ] 'ipfs bitswap unwant' to cancel (PR ready)
- [ ] investigate a timeout in FindProvs (didnt get to it, wasnt high priority)
- [ ] finish private-blocks PR (ready for CR again)
- [x] rebase dev0.4.0 again
  - [x] fix a few test failures that popped up after repeated rebasing
- [x] go-peerstream bug 
- [x] fix ipns fuse tests
- [ ] flatfs put retry PR (https://github.com/jbenet/go-datastore/pull/29)
  - going to extract logging from go-ipfs to use here
- [x] fix nat spam issue by caching external port mappings
- [x] wrote a tar importer and exporter command for ipfs
- [x] kill thirdparty/waitable

**Comment by RichardLitt** [comment]
@richardlitt
- [x] Check in with krl about the front end for starlog. _Worked on this, some PRs and set up, have more open PRs to do. Going to wait before doing more UX things until it is a bit more mature._
- [x] Take a look at the ipfs distro page and see if it can be touched up. _Done, working on building a longer document about what I see are the pros and cons of the current page, what can be touched up_
- [ ] Prepare a spec for an ops job _not done yet. Currently just trying to do everything I can, need to plan a bit better and see how I can help more. At the moment I am focusing on making contributing easier for new members (based on my own issues getting this up and running), and on general READMEs and open PRs_
- [x] Check out the IPFS app and see if you can get it up, running, and clear without help or a walkthrough. _Done, but would like to do it again. A lot of the problems I've run into are educational - I think we should have an overarching textbook about IPFS. For instance, I'm still not quite clear what a Merkledag thing is. My solution to this is to research everything I'm confused about and see if I can make an easy-to-understand FAQ with terms and explanations. Onerous, but I think worth it._
- [x] See about setting DNS records for DO programmatically. _Did the lion's share of this, see https://github.com/RichardLitt/set-dns-records. Currently I need access to DigitalOcean to test it, though._
- [x] Take a look at node-ipfs. PR review from daviddias. _Reworked the readme, added a contribute section. Going to take a look at some of the swarm modules soon, been busy fighting other fires._

**Comment by lgierth** [comment]
Pad for Sprint Sep 14: https://etherpad.mozilla.org/CBVep5omJj

**Comment by jbenet** [comment]
### @jbenet update

(sorry i failed to add it last time)

this last week:
- we saw fantastic news spreading thanks to kyledrake's awesome post. still handling lots of inbound requests, messages, discussions, etc. Great response! :clap: :clap: 
- i was focused most of the week on finishing starship, and giving a talk at container.camp. it went great! many people were very impressed with ipfs, and asked all about it afterwards. good stuff.
- I got through some amt of CR/merging, but i'm way behind. catching up over the next few days.

- starship / container.camp
  - [x] make dkr-shp tool
  - [x] test dkr-shp tool
  - [x] test with a small network
  - [x] make demo
  - [x] write talk
  - [x] give talk at container.camp
- other
  - [~] catching up on PRs and discussions
  - [x] lots of CR and discussions
  - [x] made https://github.com/ipfs/install-go-ipfs which should simplify installation in various platforms.
- outreach:
  - [x] container.camp
  - [x] PR requests
  - [x] twitters

**Comment by krl** [comment]
worked on starlog documentation, and the edit-feature, both are more or less complete. 

firefox support polyfill is still not working in gateway, but firefox dev works fine. It's probably just a command line switch to make sure the polyfills are not bundled up, and some rewriting hackery to make it load it off ipfs.

i would like to flesh out the issues, and what features should be available (automatic check for updated feeds, supporting quoting), for crypto-quoting, we're blocked on ipns records. for proper management of the log, keystore blocks.

**Comment by chriscool** [comment]
https://github.com/ipfs/go-ipfs/pull/1644 was closed because it was not needed, so I worked instead on https://github.com/ipfs/go-ipfs/pull/1692

**Comment by mildred** [comment]
@mildred

last week:

- [x] write tests that can extract links and other information from the new format (pending in ipfs/go-ipld#7)
- [x] implement ipld using these tests (pending in ipfs/go-ipld#7)
- [ ] If time allows, find a way to get the algorithm extract information from the protobuf format (either special case or implement a generic method)
- [ ] If time allows, find out if that is enough to plug in IPLD inside the core IPFS code.

**Comment by lgierth** [comment]
- i'm still getting distracted by all the little "can you quickly do x for me" things, need to say no more often, and let people make gh-issues for the stuff that i might do in another sprint.          
- also i'm still the only deployer :) need to bug people more.             
- completed         
  - [x] h.ipfs.io for access via cjdns https://github.com/ipfs/infrastructure/pull/78     
  - [x] update gateway links on website https://github.com/ipfs/website/pull/40       
  - [x] chat.ipfs.io           
  - [x] HN outfall: full disks https://github.com/ipfs/infrastructure/issues/29 https://github.com/ipfs/infrastructure/issues/80
- work in progress
  - [~] gateway-dmca-denylist          
  - [~] storage user for @mikolalysenko https://github.com/ipfs/infrastructure/issues/84         
- not started             
  - [ ] gateway: caching headers         
  - [ ] fix CORS headers for chrome https://github.com/ipfs/go-ipfs/issues/1659`O           
  - [ ] ipfs.io self-hosted blog post           
  - [ ] peer discovery using cjdns https://github.com/ipfs/go-ipfs/pull/1316  
  - [ ] switch-ping IPE<->cjdns https://github.com/lgierth/ipe      
  - [ ] check out the ruby bindings https://github.com/Fryie/ipfs-ruby

**Comment by davidar** [comment]
Didn't realise I was in a sprint until this morning (and I'm generally asleep at 3AM, btw :) so here's stuff I've done recently (mostly under ipfs/archives):

- pushed http://chat.ipfs.io live (thanks @lgierth )
  - still some outstanding issues, but it works pretty well for me (@Luzifer has also kindly tested it)
- pushed a demo of the IA book reader, and had a brief conversation with @brewsterkahle about it, which was cool :)
- pushed for closer integration between ipfs and matrix, resulting in some brainstorming from both teams
- broached the subject of using `dat` to push datasets onto ipfs
- made some notes about aggregation ipfs/notes#40 which seems to be one of the main sore points in getting "dynamic" websites onto ipfs on a large scale
- argued with people about IPLD and the path meta-scheme naming :)

Upcoming:

- the arXiv mirror is *this close* to going public, which I think will make a great demonstration of the power of ipfs in helping the Open Access movement, and hopefully enable further cool stuff to be done to highlight the benefits of Creative Commons licensing for academic papers
- continue plodding along with ipfs/archive and matrix integration, and continue giving input into how to make ipfs a great platform for people to host lots of cool stuff in a distributed way :)

**Comment by jbenet** [comment]
@davidar no worries at all, was just giving you space to talk about the awesome stuff you've been up to if you wanted to :)



—

**Comment by davidar** [comment]
@jbenet wasn't complaining, thanks for thinking of me :)

**Comment by lgierth** [comment]
Who made the pad link a big heading? I like it, thanks!

**Comment by diasdavid** [comment]
@lgierth aahah it was me :)
