### ISSUE TITLE
Sprint: Browser accesses go-ipfs content

### ISSUE THREAD

**Issue by diasdavid** [ipfs/pm#310]
> Hi! If you are coming to this issue for the first time, this might be new to you. We are going to try something new, instead of having milestones and tackling through them during the quarter, we are going to have teams focused for 2 week periods on getting some parts of IPFS that fulfill a user story, so that things can be completed incrementally and in a discrete way instead of continuously spreading our attention too thin.

# What is this sprint going to achieve

**Browser accesses go-ipfs content**

- As a user, be able to cat files from a browser ipfs node that the user added through go-ipfs CLI
- User story:
  - 1. User follows an example on js-ipfs README and spawns a node in the browser
  - 2. User sees that node has already some peers (bootstrappers)
  - 3. User adds a file with go-ipfs CLI
  - 4. User cats the file in the browser node and sees the file

### Tasks

- libp2p-webrtc-direct transport (@diasdavid)
  - [x] Update js-multiaddr to support this new transport
  - [x] Update js-mafmt to support this new transport
  - [x] complete webrtc-direct implementation
  - ~~Integrate it with libp2p-webrtc-star signalling server~~ Aborted, see update: https://github.com/ipfs/pm/issues/310#issuecomment-273050193
  - ~~Test the dial behind https~~
  - ~~Deploy the new signalling server to signal.libp2p.io~~
- https://signal.libp2p.io @lgierth + @diasdavid
  - [x] Need a cert for signal.libp2p.io
  - [x] Deploy a signalling server that exposes https endpoint
- stream multiplexer, two options
  - multiplex route @VictorBjelkholm + @diasdavid
    - [x] ~~Finish implementation of multiplex (find better name) https://github.com/libp2p/js-libp2p-multiplex/pull/44~~ @VictorBjelkholm
    - [x] Fix and finish pull-wrap version of multiplex @VictorBjelkholm
    - [x] multiplex spec - Move to libp2p/specs - identify if there is anything missing
      - https://github.com/whyrusleeping/go-multiplex/blob/master/spec.md @VictorBjelkholm 
    - [x] interop stream muxer assured https://github.com/ipfs/js-ipfs/issues/721 @VictorBjelkholm 
- multiaddr
  - [ ] /wss/ - Add `wss` support go-ipfs ipfs/go-ipfs#3613 @lgierth 
  - [x] /dns/ 
    - [x] spec @lgierth multiformats/multiaddr#22
    - [x] impl in go-ipfs @lgierth multiformats/go-multiaddr#46
    - [x] impl in js-ipfs @diasdavid https://github.com/multiformats/js-multiaddr/issues/37
- [ ] Deploy bootstraper nodes
  - [x] go-ipfs with `/ws/` and `/wss/` @lgierth ipfs/infrastructure#194
  - [ ] js-ipfs with `/ws/`, `/wss/`, `/libp2p-webrtc-star/` and `/tcp/` @lgierth
- [ ] Upgrade IPFS Config @lgierth ipfs/go-ipfs#3613
  - [ ] addresses to listen
  - [ ] addresses to announce
    - add /dns addrs here
  - [ ] addresses to not announce
  - [ ] This needs essentially a lot of tests to make sure we don't screw up (nodes starting to send through Identify, multiaddrs that they are not accesible through). Have a node dedicated just for the tests we will run in modules
- [ ] Tutorials with Demos @haad
  - Every example should be ready by working with js-ipfs Node.js to js-ipfs Browser.
  - [ ] list of examples to be made
    - [ ] ~~file Explorer (like what Whyrusleeping did)~~
    - [ ] cat a file in the browser that was added through go-ipfs https://github.com/ipfs/js-ipfs/pull/714
      - [ ] UI/UX
      - [x] Demo done and complete
      - [ ] Tutorial explaning step by step how to create the same demo
    - [ ] files feed https://github.com/ipfs/js-ipfs/pull/716
      - [ ] UI/UX
      - [x] Demo done and complete
      - [ ] Tutorial explaning step by step how to create the same demo
- [x] Documentation, from 0 to hero - We need to make it very easy for someone that opens github.com/ipfs/js-ipfs, to go from nothing to having a Node running in the browser, that is the whole goal, preferably with a tutorial that is not massive ~~@haad~~ @diasdavid - 
  - [x] Update documentation, readme and examples https://github.com/ipfs/js-ipfs/pull/723
  - [x] Organize README so that the first impression is more pleasant https://github.com/ipfs/js-ipfs/pull/722

- [ ] Circuit relay (Basic Turn, no relay discovery) libp2p/go-libp2p#82
  - [x] review current implementation (understand what it actually does) @lgierth
  - [x] spec @lgierth
      - ~~usage #1: a flag on the swarm/connect command~~ Not going to happen anymore
      - [x] usage #2: encapsulate relay info in multiaddr
  - [ ] implementation
    - [ ] in JS @diasdavid
    - [ ] in Go @lgierth 
- [ ] discovery
  - [x] make sure that having mdns discovery and webrtc-star discovery doesn't freat out js-ipfs (write tests for it)  https://github.com/ipfs/js-ipfs/pull/717
  - [ ] fix mdns interop between go-ipfs and js-ipfs https://github.com/libp2p/go-libp2p/issues/176
- [x] DHT as a service @lgierth  
    - [x] expose findProovs in the gateways
    - [x] expose findPeers in the gateways

Outside of the sprint (Time on this should not be invested unless all the above is done
  - [ ] Improving Init endeavour @haad

# Timeline

We will be running this sprint for 2 weeks, starting on Week 3 (15 Jan) and ending on the final day of Week 4 (22 Jan). During these period, we know that:
- @haadcode unavailable the second week
- ~~@lgierth unavailable from 19th to 24th~~

We will be using this issue to do daily check in, please avoid commenting if you are not check in in, if you have a question, consider opening another issue or asking through the #IPFS channel in freenode.

**Comment by diasdavid** [comment]
# David's Check in Mon 16

- Flying out to Lisbon today during the morning ✈️
- Available for the calls later
- Will use the remaining available time to focus on working on webrtc-direct and integrating it in webrtc-star, hope to have it done by the end of the day in a state that is deployable.

**Comment by haadcode** [comment]
I'll be working on the following today:
- Design the interop examples
- Implement skeletons for the examples
- Open issues and PRs for tracking the work
- Weekly calls
- [ ] Update Waffle

I don't have any blockers atm. Will need feedback for examples soon.

**Comment by VictorBjelkholm** [comment]
Gonna be working on finishing @dignifiedquire's implementation of multiplex. To track: libp2p/js-libp2p-multiplex#44

**Comment by lgierth** [comment]
Damn I was pretty sure I posted earlier.

- No blockers
- Current: looking into relay in go-ipfs, what needs fixing, and how to actually make use of it.
- Next: /wss prespec

**Comment by victor** [comment]
I don't care about this, sorry, but if you feel this way you'll work better, then go for it 👍🏼

Enviat des del meu iPhone

El 16 gen 2017, a les 19:40, Lars Gierth <notifications@github.com> va escriure:

**Comment by lgierth** [comment]
@victor uhm, are you trying to tell use anything related to this sprint?

**Comment by diasdavid** [comment]
@victor my apologies for bothering you, apparently we tagged you instead of @VictorBjelkholm. Fixed now, you can unsubscribe to this issue.

**Comment by lgierth** [comment]
Ah that makes sense, sorry victor!

**Comment by diasdavid** [comment]
# David's `check in` `Mon 17`

- [ ] Integrate webrtc-direct in webrtc-star
- [ ] test behind https
- [ ] deploy it as a new signalling server
- [ ] review haads first example
- [ ] fix interop tests in js-ipfs
- [ ] release 0.21

**Comment by haadcode** [comment]
Yesterday:
- Implemented the browser side of things for the first example ("basic"), and with it you can .cat pictures between browser nodes (try it from https://github.com/ipfs/js-ipfs/pull/714).
- Drafted a skeleton for a tutorial for the basic example.

Today:
- Implement first version of the second example ("advanced")
- Continue writing the tutorial
- Test the actual interop with the basic example (if available today in js-ipfs). 

Blockers:
none

**Comment by diasdavid** [comment]
Notes from pull-multiplex extravaganza discussion: https://hackmd.io/KYdmGMAYQVgTgLQgMwCYAcCAsJ2PQGzgBmCAhsQIyXhbCqRwAmMQA===?edit

**Comment by lgierth** [comment]
Yesterday I examined the relay impl in go-ipfs. It's not wired up with anything and doesn't provide end-to-end encryption. I've described a way forward 

- Blockers: feedback on relay-as-a-transport (see above).
- Current: adding multiaddr codes for /relay, /wss, /dns to go-ipfs
- Next: implement relay-as-a-transport and wire it up

**Comment by diasdavid** [comment]
# David's `check in` `Wed 18`

- [ ] make sure that having mdns discovery and webrtc-star discovery doesn't freat out js-ipfs (write tests for it)
- [ ] Chase @whyrusleeping to get back to me on "fix mdns interop between go-ipfs and js-ipfs libp2p/go-libp2p#176"
- Work on DNS for JS

**Comment by haadcode** [comment]
End of the day check in:
- Yesterday I started working on the "advanced" (second) example for interop. 
- Today I continued on it and made a WIP PR: https://github.com/ipfs/js-ipfs/pull/716. The UI and browser side is pretty much done, next step is to interopopopop.
- Will be traveling rest of today --> afk

Tomorrow:
- Make the interop work
- Continue writing the tutorials

Blockers:
- I couldn't find documentation on how do I connect js-ipfs (node.js) and js-ipfs (browser) nodes, so I need instructions on links to documentation to get started. cc @diasdavid

**Comment by diasdavid** [comment]
> I couldn't find documentation on how do I connect js-ipfs (node.js) and js-ipfs (browser) nodes, so I need instructions on links to documentation to get started. cc @diasdavid

@haadcode by using webrtc-star, they will find each other automatically, however it would be good, since go-ipfs won't have that feature, that you use websockets addr in the js-ipfs node and that in the demo page, you have a box saying "multiaddr to dial". Which reminds me, it would be ideal to have a list of peers connected visual in the webdemo

**Comment by lgierth** [comment]
- No blockers
- Yesterday: added /dns, /libp2p-relay, /wss to the protocols list in multiaddr (multiformats/multiaddr#34), and to go-multiaddr (multiformats/multiaddr#46.
- Current: working on turning go-libp2p's RelayService into a transport (libp2p/go-libp2p-relay).
- Next: add config options to enable relay.

**Comment by diasdavid** [comment]
# David's `check in` `Thu 19`

- Continue working on DNS for JS multiformats/js-multiaddr#37 (see list of tasks inside this issue)

**Comment by haadcode** [comment]
After yesterday's check in:
- Tried js-ipfs(nodejs) and js-ipfs(browser) interop without success. Getting segfaults sometimes and .cat is not working either way, but I do get the peers connected. I need to discuss this in sync today, will ping relevant people on IRC:
- Added a list of connected peers to the UI of the second example (file manager)

Today:
- Will add the missing UI elements for manually connecting to peers ("Connect to multiaddr" inputs)
- Continue figuring out how to make the interop work
- Document the interop steps as I discover what is needed

Blockers:
I have 2 days left for this sprint and while the browser side of things should be good to go in terms of finishing them, leaving them for others to work, I'm running low on time for writing the tutorials and documentation. I'm not convinced I can finish all of that in 2 days (and I'll be gone next week). I know you're not in this sprint @RichardLitt, but would you be able to help out next week with the tutorials (I can work with you on those).

I'll bring these up in our sync today so we can discuss the steps forward.

**Comment by diasdavid** [comment]
I've noticed that folks aren't giving love to the waffle board, what's up?

**Comment by diasdavid** [comment]
# Group Check In Jan 19, Thu

Notes: https://hackmd.io/GYTgJmCMDsDMwFoBMBTJAOBAWADAI0gTwGMwkF0A2LMSnYPdYaEIA===?both

Top priorities before the weekend:

- [ ] Get cert for signal.libp2p.io (@lgierth)
- [ ] Get signal.libp2p.io deployed with http and https (no HSTS header) (@lgierth)
- [ ] Review both examples (@diasdavid)
  - [ ] https://github.com/ipfs/js-ipfs/pull/714
  - [ ] https://github.com/ipfs/js-ipfs/pull/716
- [ ] circuit relay spec draft for review (@lgierth)

**Comment by RichardLitt** [comment]
> I have 2 days left for this sprint and while the browser side of things should be good to go in terms of finishing them, leaving them for others to work, I'm running low on time for writing the tutorials and documentation. I'm not convinced I can finish all of that in 2 days (and I'll be gone next week). I know you're not in this sprint @RichardLitt, but would you be able to help out next week with the tutorials (I can work with you on those).

@haadcode Can we schedule a short video call for talking about this? I haven't been tracking this sprint, and the state is not in my head. I should have some bandwidth to help, however.

**Comment by diasdavid** [comment]
# David's `check in` `Thu 19`

- [ ] Review @haadcode js-ipfs tutorials
- Hopefully, last push to finish on DNS for JS multiformats/js-multiaddr#37 (see list of tasks inside this issue)

**Comment by diasdavid** [comment]
@RichardLitt definitely have that chat with @haadcode but here are some good things to read:

- Debugging through Browser and Node.js (or Go for what is worth) issues - https://github.com/ipfs/js-ipfs/issues/720#issuecomment-273751466
- Simple Example (cat) - https://github.com/ipfs/js-ipfs/pull/714
- Advanced Example (File Browser) - https://github.com/ipfs/js-ipfs/pull/716
- Description of the examples - https://github.com/ipfs/js-ipfs/issues/711

**Comment by diasdavid** [comment]
# David's `check in` `Mon 23`

Plan:

- [ ] Review @haadcode examples
- Participate in @haadcode handoff to @RichardLitt 
- Catch up with @pgte (he is coming to Lisbon today), plan the rest of the week
- Attends All Hands calls
- Help out speed up the Stream Muxer situation https://github.com/ipfs/js-ipfs/issues/721

**Comment by lgierth** [comment]
Lars monday
- Blockers
  - CR, but no real "blocker" blockers
- Last
  - Deployed two hosts running go-ipfs with /ws listeners (not wired to nginx yet)
  - SSL cert for star-signal.cloud.ipfs.team
- Today
  - Circuit relay proposal for review before implementation

**Comment by diasdavid** [comment]
# David's `check in` `Tue 24`

- Continue speeding up Pedro on things
- Continue helping @VictorBjelkholm with the Stream Muxer situation (made a lot of progress yesterday, still ongoing)
  - [ ] Fix multiplex 'clean itself out' tests
  - [ ] Understand why the heck go-multiplex limits to 1024

**Comment by lgierth** [comment]
Lars tuesday
- Blockers
  - no real "blocker" blockers
- Yesterday
  - circuit-relay prespec and ethereum meetup
- Today
  - circuit-relay prespec
  - /ws bootstrappers

**Comment by diasdavid** [comment]
# David's `check in` `Wed 25`

- Focus of this day will be doing an last pass on the examples and doing the 'documentation from 0 to hero'

**Comment by RichardLitt** [comment]
@RichardLitt today:
- Worked on [node-github-issue-bot](https://github.com/RichardLitt/node-github-issue-bot), hoping to find some time today to work on this.

**Comment by lgierth** [comment]
Last wednesday
- No blockers
- Yesterday
  - Wanted to get circuit-relay prespec done, but got distracted by 0.4.5 release prep and pinbot/gateway debugging.
- Today
  - circuit-relay prespec
  - Provisioned a host for the 300TB sprint

**Comment by lgierth** [comment]
circuit-relay prespec: libp2p/go-libp2p-relay#1 -- feedback much appreciated, sorry this document gets written so late in the sprint.

**Comment by diasdavid** [comment]
# David's `check in` `Wed 25

**Comment by lgierth** [comment]
Lars thursday
- No real blockers
- Yesterday
  - posted circuit-relay prespec libp2p/go-libp2p-relay#1
- Today
  - go-ipfs multiaddr update
  - 0.4.5 release prep

**Comment by diasdavid** [comment]
# The last mile

> We just had the second group check in to discuss the state of tasks and decide what are the things which we should spend our time for the last day and showcase Monday. Notes: https://hackmd.io/GYEwxiCMkBwKwFowENgAYEBYBsAjbCyAnGogKYy5lFjC65EBMYQA?edit

- [ ] Host WebSockets Secure Bootstrapers @lgierth 
- [ ] Tutorials
  - [ ] Transfers Files
    - [ ] DX/UX - @VictorBjelkholm 
    - [ ] Tutorial Steps @RichardLitt 
  - [ ] File Feed
    - [ ] Review and complete example @diasdavid
    - [ ] DX/UX - @VictorBjelkholm 
    - [ ] Tutorial Steps @RichardLitt 
- @lgierth will check https://github.com/libp2p/go-libp2p/issues/176
- Update IPFS Config with `addrs to listen, addrs to announce, addrs to not announce` @lgierth 
- DHT as a service @lgierth (expose it in the gateway)
- Continue the `multiplex` battle @diasdavid

**Comment by lgierth** [comment]
Here are two /ws bootstrappers which also have the gateway on the same port:

```
/ip4/159.203.166.189/tcp/80/ws/ipfs/QmWyLSnMHW2H6bmCG9e9PQq4ARve94JduvGjbutUuzx4a8
/ip4/178.62.215.134/tcp/80/ws/ipfs/QmVcj9MATxGTAFoQSbrJvZ9Fbs4Jzvrxy9hyJeRwbW8NeA
```

These *should* also work on `/tcp/443/wss` but I haven't tested it, as I have yet

**Comment by lgierth** [comment]
The respective /dns+/wss addresses:

```
/dns4/strawberry.i.ipfs.io/tcp/443/wss/ipfs/QmWyLSnMHW2H6bmCG9e9PQq4ARve94JduvGjbutUuzx4a8
/dns4/blueberry.i.ipfs.io/tcp/443/wss/ipfs/QmVcj9MATxGTAFoQSbrJvZ9Fbs4Jzvrxy9hyJeRwbW8NeA
```

and https://strawberry.i.ipfs.io + https://blueberry.i.ipfs.io for the gateway.

**Comment by lgierth** [comment]
For deferring routing to the gateway:

- dht/findprovs: https://strawberry.i.ipfs.io/api/v0/dht/findprovs?arg=QmaYRrBpZQRjonxBpBBSLvYmy893ySPpXpHCakhomaQtkU
- dht/findpeer: https://blueberry.i.ipfs.io/api/v0/dht/findpeer?arg=QmWyLSnMHW2H6bmCG9e9PQq4ARve94JduvGjbutUuzx4a8

And you can use `api/v0/refs?r=true` to warm up the /ws bootstrapper/gateway with a stuff added on other go-ipfs nodes. That way we cheat our way around the lack of relaying.

**Comment by diasdavid** [comment]
You know something cool, now we have multiplex working woooo \o/ :D Once go-ipfs 0.4.7 is release, no user will have to worry about it again :D

**Comment by flyingzumwalt** [comment]
@diasdavid can we call this "done"?

**Comment by diasdavid** [comment]
Yes! :D
