### ISSUE TITLE
Sprint Sep 14

### ISSUE THREAD

**Issue by lgierth** [ipfs/pm#32]
## Sprint Goals

- ship 0.4.0

## Sprint Discussions

See https://github.com/ipfs/pm#sprint-discussion-schedule

Please take notes in a separate pad, if you can, and link it here.

- infrastructure: https://etherpad.mozilla.org/wns7nqRsZa

## Sprint Deliverables

- Add yourself below, that way we only have people listed who are really in the sprint
- Add links to issues down here. Only add things you can finish this sprint.

### @RichardLitt
- [x] Write an issue about how to rework ipfs.io so it is more than a list of videos. If possible, draw or commit an alternative front page on a branch.
- [ ] Work with ___ to make sure that set-dns-record tool works as expected. :thumbsup:
- [x] Create IFPS/support
- [x] Figure out how to put IPFS repositories on IPFS. Open a discussion in the community repo for this.
- [ ] Rebuild the community page, or build a new one listing all of the repos currently in development and make sure that their internal READMEs are streamlined. Write a starlog about this once it is done, the blog needs more <3
- [x] Review https://github.com/diasdavid/node-spdy-stream-muxer
    this one follows abstract-stream-muxer and has one request open that is, to make it return a duplex stream, which won't work till spdy-transport returns also a duplex-stream (just FYI :) ) and TY! (Cool, thanks!)
- [x] Review https://github.com/diasdavid/node-multistream
- [ ] Review https://github.com/ipfs/website/pull/14
- [ ] Review https://github.com/ipfs/website/issues/2
- [x] Close or review issues on ipfs/community
- [ ] Fix textarea scrolling on https://github.com/ipfs/starlog/issues/26 
- [ ] See if I can codify how I can help manage sprints and project management better.
- [ ] Give IPFS install another test run through for ease of use.
- [x] Start document about higher level abstraction education for IPFS to non-cryptos
- [ ] Finish job spec. 

### @diasdavid || @daviddias

- [ ] Refactor Swarm
    - [x] abstract-transport
        - [ ] libp2p-tls (??)
    - [x] abstract-connection
        - [x] libp2p-tcp
        - [ ] libp2p-udp
    - [x] libp2p-spdy
- [x] Fixed bug caused by bad pattern on mDNS discovery https://github.com/diasdavid/node-ipfs-mdns/commit/43472a59002c03afcdda134541acbc175c9e61fa
- [x] Upgrade IPRS impls (ipfs-record, drs, kad-drs) depending on https://github.com/ipfs/specs/issues/24#issuecomment-140136140
- [x] abstract-peer-routing
- [ ] WebCrypto module (discussions, where to go)
- [x] write a description for each node-ipfs module on node-ipfs repo as separate issues
- [x] write 'what can you do' on node-ipfs-api
- [x] merge https://github.com/ipfs/node-ipfsd-ctl/pull/12

### @whyrusleeping
- [x] merge https://github.com/ipfs/go-ipfs/pull/1672
- [x] investigate efficacy of https://github.com/ipfs/go-ipfs/pull/1658
- [ ] follow up on https://github.com/ipfs/go-ipfs/pull/1648
- [x] merge https://github.com/ipfs/go-ipfs/pull/1622
- [x] flatfs put retry PR (https://github.com/jbenet/go-datastore/pull/29)
  - [x] integrate into go-ipfs
- [ ] finish private-blocks PR (ready for CR again)
- [x] update go-peerstream in go-ipfs after last PR
- [ ] finish mfs extraction
- [ ] epoll fixes (https://github.com/jbenet/go-reuseport/issues/8)
- [ ] investigate udp libs, try integration
- [ ] add chunking algo to root unixfs file blocks

### @jbenet

- [ ] put ipld into go-ipfs
- [ ] make libp2p go interfaces file
- [x] decide on crypto transport
- [ ] node-ipfs repo module listings
- [ ] api docs designdoc
- [ ] car designdoc
- [ ] dkr-shp webpage
- [ ] dkr-shp improvements
- [ ] infra accounting
- [ ] libutp bindings

**Comment by jbenet** [comment]
Not sure if we can ship 0.4.0 this week but we may be able to at least get everything ready.






—

**Comment by diasdavid** [comment]
@dignifiedquire let me know if you want to be part of the checkin this week and tell us about your developments for the electron-app stuff :) We have a ipfs-apps sprint meeting at 18:30Z https://github.com/ipfs/pm#sprint-discussion-schedule

**Comment by Dignifiedquire** [comment]
@diasdavid sure, I should be able to make time for the discussion (today?) I'll happily check in, as much as I can get done :octocat:

**Comment by Dignifiedquire** [comment]
Working on electron-app. 
* Added hot module reloading
* Using babel and webpack for building
* Improving stability (using safer ipc variant to avoid crashes on reload)
* New design ideas

Details at: https://github.com/ipfs/electron-app/pull/43

**Comment by whyrusleeping** [comment]
- [x] merge https://github.com/ipfs/go-ipfs/pull/1672
- [x] investigate efficacy of https://github.com/ipfs/go-ipfs/pull/1658
- [x] merge https://github.com/ipfs/go-ipfs/pull/1622
- [x] flatfs put retry PR (https://github.com/jbenet/go-datastore/pull/29)
  - [x] integrate into go-ipfs
- [ ] finish private-blocks PR 
- [x] update go-peerstream in go-ipfs after last PR
- [ ] finish mfs extraction (PR in progress)
- lots of work towards UDT, one more PR should do it
  - [ ] https://github.com/jbenet/go-udtwrapper/pull/13
- working on a set of patches for ipns to make it work until we get ipld stuff

udt stuff was quite the time suck. But i'm pretty confident in it now

**Comment by lgierth** [comment]
- [~] wip: gateway-dmca-denylist, this time for real
- [x] added storage users for rht, mikolalysenko, davidar
- [x] disabled docker container logging to prevent disks from filling up, as they don't get rotated
- [x] fixed ipfs container's permissions for ipfs log files
- monitoring / prometheus fixing and tuning
  - [ ] node_exporter docker container
  - [x] node_exporter should only export cpu, net, ram, fs
  - [ ] node_exporter should forget network interfaces that don't exist anymore (i.e. docker's veth)
- alexandria
  - [x] discussed our gateway setup with gendale
  - [ ] cjdns peering
- [ ] peer discovery using cjdns https://github.com/ipfs/go-ipfs/pull/1316
- [ ] gateway: caching headers
- [ ] fix CORS headers for chrome https://github.com/ipfs/go-ipfs/issues/1659

**Comment by diasdavid** [comment]
### SPRINT UPDATE 

- Making progress on the Swarm revisit, right now the current version of Swarm supports multitransport, but once at a time and only if they follow the net module interface, we are changing that to make it even more cool :) - https://github.com/diasdavid/node-ipfs-swarm/issues/8
  - revisit branch https://github.com/diasdavid/node-ipfs-swarm/tree/revisit
  - [x] abstract-transport https://github.com/diasdavid/abstract-transport
  - [x] abstract-connection https://github.com/diasdavid/abstract-connection
  - [x] libp2p-tcp https://github.com/diasdavid/node-libp2p-tcp
  - [x] libp2p-spdy https://github.com/diasdavid/node-libp2p-spdy
- [x] Fixed bug caused by bad pattern on mDNS discovery https://github.com/diasdavid/node-ipfs-mdns/commit/43472a59002c03afcdda134541acbc175c9e61fa
- [x] IPRS - Reach a conclusion with @jbenet on how to make IPRS more flexible from the validation standpoint
  - https://github.com/ipfs/specs/issues/24#issuecomment-140214514
  - https://github.com/ipfs/specs/issues/31
- [x] Made abstract-peer-routing
- Generic Crypto module for libp2p use that is Node.js and Browser compatible
  - still very new https://github.com/diasdavid/webcrypto
  - @tomgco is making a callbacks (not promisses) interface for the browser WebCryptoAPI https://github.com/tomgco/node-webcrypto
  - Been bouncing ideas with Ian https://github.com/diasdavid/webcrypto/issues/1 and reaching the conclusion that we need an abstract-crypto interface
- [x] Descriptions for the IPFS Node.js modules that people can contribute and understand more (avoiding the ones that are more unstable) https://github.com/ipfs/node-ipfs/issues
- [x] merge https://github.com/ipfs/node-ipfsd-ctl/pull/12
- [x] Collect conferences that we can/should participate till Feb 2016
- [x] Got my head around ipfs-blob-store https://github.com/ipfs/ipfs-blob-store/pull/2 (we need mfs to make everything super sweet! :) )

**Comment by RichardLitt** [comment]
Update: 

Summary:

  I was AFK for most of the week, which I did not take into account when I planned this spring on Monday. So, I need to be better at that, and at saying before hand that I will or will not be online much. Also, I need to be careful not to overload on the sprint tasks.

  I PRed a few things - go-ipfs Contribute, ipfs/support Readme. I looked at all of the IPFS issues this week and am starting to get a wider feel for the community as a whole and what we're doing, but still don't understand a large amount of the actual talk going on. This made the two reviews I did of diasdavid's modules hard, because I feel I don't have too much to add. I started https://github.com/RichardLitt/ipfs-textbook as a place for me to slowly figure out and make a document aimed at teaching people about IPFS and relevant crypto. This is mostly for me, but hopefully more people will get involved.

  I worked on a few other issues, like the baseURL issue for the website. But I didn't have time to do as much as I would like, or to overhaul the community page yet.

- [x] Write an issue about how to rework ipfs.io so it is more than a list of videos. If possible, draw or commit an alternative front page on a branch.
- [x] Create IFPS/support
- [x] Figure out how to put IPFS repositories on IPFS. Open a discussion in the community repo for this.
- [x] Review https://github.com/diasdavid/node-spdy-stream-muxer
- [x] Review https://github.com/diasdavid/node-multistream
- [x] Close or review issues on ipfs/community
- [x] Start document about higher level abstraction education for IPFS to non-cryptos
- [ ] Work with ___ to make sure that set-dns-record tool works as expected.
- [ ] Rebuild the community page, or build a new one listing all of the repos currently in development and make sure that their internal READMEs are streamlined. Write a starlog about this once it is done, the blog needs more <3
- [ ] Review https://github.com/ipfs/website/pull/14
- [ ] Review https://github.com/ipfs/website/issues/2
- [ ] Fix textarea scrolling on https://github.com/ipfs/starlog/issues/26 
- [ ] See if I can codify how I can help manage sprints and project management better.
- [ ] Give IPFS install another test run through for ease of use.
- [ ] Finish job spec.

**Comment by jbenet** [comment]
### Sprint Update

This week I got stuck catching up with an insanely large comm backlog:
- [x] lots of ipfs mail
- [x] issue discussions
- [x] PRs/CR
- [x] discussion calls
- [x] design/impl discussions with @whyrusleeping
- [x] design discussions with @daviddias
- [x] org/logistical todos
- [x] visited consensys (who are using IPFS) - http://cryptogeeks.com/ipfs-consensys-planing-future
Did not expect how much of a time sink all this would be.

Of the items I listed I only got through one :(
- [x] decide on crypto transport

**Comment by amstocker** [comment]
Sprint Update

python-ipfs-api:
- [ ] pydoc documentation
- [ ] make readthedocs.org page
- [ ] make it easy to integrate python-ipfs-api into async environment
- [ ] make filestreaming chunk large files/multiple files
- [x] python 3 support
- [x] testing framework
- [x] tavisci setup
(otherwise python-ipfs-api is pretty much stable)
other:
- [ ] python-multiaddr
  - [ ] make testing framework
  - [ ] python 3 support
  - [ ] feature parity with go-multiaddr/node-multiaddr
