### ISSUE TITLE
Sprint Sep 28

### ISSUE THREAD

**Issue by lgierth** [ipfs/pm#35]
## Sprint Goals

- 

## Sprint Discussions

See https://github.com/ipfs/pm#sprint-discussion-schedule

Please take notes in a separate pad, if you can, and link it here.

- main pad: https://etherpad.mozilla.org/juEv7EcG5l
- node-ipfs notes: https://etherpad.mozilla.org/lm3txgSGbZ
- go-ipfs notes: https://etherpad.mozilla.org/FQE1OWzp6Q
- ipfs-app notes: https://github.com/ipfs/electron-app/pull/43#issuecomment-143883929

## Sprint Deliverables

- Add yourself below, that way we only have people listed who are really in the sprint
- Add links to issues down here. Only add things you can finish this sprint.

### @noffle
- [ ] ipget (https://github.com/noffle/ipget)
  - [ ] tests + travis ci
  - [ ] support godep
  - [ ] smarter default filename when given a x/y/z path
  - [ ] logging with github.com/Sirupsen/logrus
  - [ ] plan out work toward 'ipfs get' feature parity

### @jbenet

- [x] make issue about ipfs-update 
- [x] multiaddr-net modularizing https://github.com/jbenet/go-multiaddr-net/issues/7
- [ ] exo-transport design doc
- [ ] put ipld into go-ipfs
- [ ] figure out dkr-shp next steps
- [ ] go-ipfs roadmap
- [ ] blockstore intergration / onename profiles
- [x] ascribe catchup
- [ ] whittle down open PRs in go-ipfs
- [x] @willglyn's go-ipfs paths PR
- [x] @mildred's go-ipld PR
- [ ] start ipfs-api repo for spec, docs, tests.
- [ ] define multikey standard
- [ ] HK Blockchain Workshop
  - [ ] Smart Contracts + IP Working Group doc work
  - [ ] IoT Working Group doc work
- [ ] re-record computer from DTN
- [x] CR + land mfs/files - https://github.com/ipfs/go-ipfs/pull/1769
- [x] CR + land IPNS patches - https://github.com/ipfs/go-ipfs/pull/1739
- [ ] CR + land utp patches - https://github.com/ipfs/go-ipfs/pull/1789
- [x] review growing libp2p spec
  - [x] discuss questions with @diasdavid

### @amstocker

python-ipfs-api:
- [~] api method documentation (almost done)
- [ ] readthedocs.org page
- [ ] easy integration with async environments
- [ ] better file streaming
community:
- [ ] start python/ipfs hangout on monday sprints

### @mappum

- [ ] jbenet/vinyl-fs browser changes
- [ ] create PR from jbenet/vinyl-fs to gulpjs/vinyl-fs (maybe)
- [ ] inpm alternate install types (dupe, link to local registry)
- [ ] ship inpm initial release
- [ ] fix cube server expiration calculation
- [ ] basic cube-web PoC for designer

### @RichardLitt

- [ ] Add <language>-contribute.md files to community list. Do Go and Node. [go-ipfs#1734](https://github.com/ipfs/go-ipfs/pull/1734)
- [ ] Resolve issues on ipfs/community as much as possible. Add open issues to next week's sprint.
- [ ] Write 300 words~ on how I can codify how I can help manage sprints and project management better.
- [ ] Give IPFS install another test run through for ease of use. Minimum: Getting started page.
- [ ] Actually finish job spec. Google what these should look like, too.
- [ ] Take a crack at node-ipfs-api docs! Minimum: 1 hour.
- [ ] Add update-or-create to dnslink-deploy [dnslink-deploy#5](https://github.com/ipfs/dnslink-deploy/issues/5).
- [ ] Mention ipfs/support on the google groups email list.
- [ ] Make sure the google groups list is advertised in the appropriate places.
- [ ] Work on IPFS-Textbook. Deliverables: A read through and edit; close all PRs and issues; update glossary.
- [ ] Help @jbenet with email lists. (logistics)
- [ ] Talk to @jbenet about IPFS google apps so that I can create the calendar [community#35](https://github.com/ipfs/community/issues/36#issuecomment-143964614)
- [ ] PR the Readme standards and guidelines.
- [ ] Build a README parser and standard checker. Test IPFS repositories with it.
- [ ] Write a Starlog about Readme standards and all repositories.
- [ ] Close gencmdref issue for the website [go-ipfs#1735](https://github.com/ipfs/go-ipfs/issues/1735)
- [ ] Setup keybase.io, and take a look at the BookReader [issue](https://github.com/ipfs/archives/issues/14) as payment of that debt to @davidar
- [ ] Add node-ipfs-api node-ipfs question to ipfs/faq.

### @lgierth

- [ ] make gateway-dmca-denylist accessible at ipfs.io/refs/lists/denylists/dmca
- [ ] make sure infrastructure is documented well
- [ ] hand off to whyrusleeping jbenet richardlitt cryptix
- [ ] chill

### @diasdavid

- [ ] kick of the tires on libp2p in go
- [ ] ipsurge tool

### @dignifiedquire
- [ ] init screen
   - [ ] advanced options tab
   - [ ] move path into advanced
   - [ ] add key choice into advanced. (make algo a dropdown, with only RSA but say "ECC and more coming soon". it's an important detail)
- [ ] menu screen
  - [ ] logo in menu title `[  ] IPFS` (Ref https://github.com/ipfs/logo/issues/6)
  - [ ] hide settings for now
  - [ ] figure out if "console" and "browser" can be more clear (a bit confusing atm)
- [ ] file upload
  - [ ] re-enable file upload
  - [ ] add progress bars for file upload

### @rht
- [ ] integrate ipget into gx
- [ ] more ipfs add test cases (--trickle, --chunker)
- [ ] ipfs add benchmark (vs cp vs rsync vs tar vs tar z vs git vs ?) -- sorry, benchmark almost always means apple vs orange, but can still be useful
- [ ] `ipfs object cache $hash` / `ipfs object get --cache-only $hash`? i.e. store a particular hash into blocks without outputting to $PWD or stdout. Useful for partial backup of parts of a huge node, pre-ipfs-cluster
- [ ] git on ipfs

### @whyrusleeping
- [x] ipns merged
  - [ ] old record fix
- [ ] mfs api redux
- [ ] chunking/layout algorithm into unixfs roots
- [ ] UDT into go-ipfs
  - [ ] udt into go-multiaddr-net
  - [ ] refactor multiaddr-net
    - waiting on discussion for interfaces
- [ ] more stats in repobench
- [ ] reduce dialing concurrency
- [x] chat with blame about scaling provides

**Comment by jbenet** [comment]
- node-ipfs notes: https://etherpad.mozilla.org/lm3txgSGbZ
- go-ipfs nodes: https://etherpad.mozilla.org/FQE1OWzp6Q

**Comment by jbenet** [comment]
Reminder to add things to etherpad -- @whyrusleeping @lgierth @mappum @richardlitt @dignifiedquire @davidar @chriscool @rht @diasdavid

**Comment by jbenet** [comment]
hey @diasdavid @whyrusleeping -- reminder: your things o/ o/

**Comment by diasdavid** [comment]
sorry, just added :)

**Comment by jbenet** [comment]
### @jbenet's end of sprint update

- [X] HK Blockchain Workshop prep
  - [x] Smart Contracts + IP Working Group doc work
  - [x] IoT Working Group doc work
- [ ] re-record computer from DTN
- [x] CR + land mfs/files - https://github.com/ipfs/go-ipfs/pull/1769
- [x] CR + land IPNS patches - https://github.com/ipfs/go-ipfs/pull/1739
- [~] CR + land utp patches - https://github.com/ipfs/go-ipfs/pull/1789
- [x] review growing libp2p spec
  - [x] discuss questions with @diasdavid
- [ ] ship 0.3.8 -- we haven't done this.

**Comment by jbenet** [comment]
### @jbenet's end of sprint update

This week i had a bunch of small things. Lots of CR upkeep, figuring out various issues, lost of discussions with people.
- [x] make issue about ipfs-update  -- finishing this up, will post in a bit.
- [x] multiaddr-net modularizing https://github.com/jbenet/go-multiaddr-net/issues/7 -- still some figuring out to do there.
- [~] exo-transport design doc -- working on this
- [ ] put ipld into go-ipfs -- not yet
- [~] figure out dkr-shp next steps -- working on this.
- [ ] go-ipfs roadmap - not yet. need to do this.
- [x] ascribe.io catchup -- figuring out integration points
- [ ] whittle down open PRs in go-ipfs
- [x] @willglyn's go-ipfs paths PR
- [x] @mildred's go-ipld PR
- [ ] start ipfs-api repo for spec, docs, tests. -- need to do this still.
- [ ] define multikey standard -- need to do this still
- [X] HK Blockchain Workshop prep
  - [x] Smart Contracts + IP Working Group doc work
  - [x] IoT Working Group doc work
- [ ] re-record computer from DTN
- [x] CR + land mfs/files - https://github.com/ipfs/go-ipfs/pull/1769
- [x] CR + land IPNS patches - https://github.com/ipfs/go-ipfs/pull/1739
- [~] CR + land utp patches - https://github.com/ipfs/go-ipfs/pull/1789
- [x] review growing libp2p spec
  - [x] discuss questions with @diasdavid
- [ ] ship 0.3.8 -- we haven't done this.

**Comment by lgierth** [comment]
- [~] make gateway-dmca-denylist accessible at ipfs.io/refs/lists/denylists/dmca
- [~] make sure infrastructure is documented well
- [~] hand off to whyrusleeping jbenet richardlitt cryptix
- [x] chill
- [x] instrument api and gateway HTTP handlers for Prometheus https://github.com/ipfs/go-ipfs/pull/1799
- [x] fix pluto's private key and peerid https://github.com/ipfs/go-ipfs/pull/1748
- [x] gc'd the gateways before the techcrunch article hit

**Comment by Dignifiedquire** [comment]
- [~] Welcome Screen (IPFS Electron App)
- [ ] File Upload (IPFS Electron App)

**Comment by RichardLitt** [comment]
Etherpad for the next sprint, https://github.com/ipfs/issues/36: https://etherpad-mozilla.org/sprint-36

**Comment by chriscool** [comment]
Some very small fixes in sharness tests:

- ipfs/go-ipfs#1792
- ipfs/go-ipfs#1786
- ipfs/go-ipfs#1783
- ipfs/go-ipfs#1784
- ipfs/go-ipfs#1781

And improved shellquote():

- ipfs/go-ipfs#1772

**Comment by diasdavid** [comment]
### SPRINT UPDATE

> Apologies for missing today's checkin, I thought I would be able to do it in Newark Airport, but the airport was impressively full today and after waiting in all the queues, had to run to my gate.

My main focus for this past week was working on a interopable go-libp2p and get ipsurge off the ground. 

- [x] Work on getting more stuff documented on libp2p https://github.com/ipfs/specs/pull/19
- [x] Discuss with @jbenet some very important details about libp2p architecture and agree on how transports are architectured
- [x] Got formally invited to lecture a Post Graduation course on "Programming for the Web" (woot:))
- [x] schedule travel plans for &yetConf
- [x] ipsurge https://github.com/diasdavid/ipsurge https://github.com/diasdavid/ipsurge-preview
````
Usage: ipsurge COMMAND [OPTIONS]

Available commands:

browse    Open your application in a browser
init      Initialize a ipsurge project
preview   Preview your application through a collection of snapshots
publish   Publish your project
versions  Check each version published 
```
- [x] deploy my website with ipsurge and DNS hack http://ipfs.daviddias.me/
- [x] WebRTC WG mails and review stuff (worked a bit more on the article distilling WebRTC)
- [ ] libp2p in Go

**Comment by davidar** [comment]
@davidar update: https://github.com/ipfs/apps/issues

**Comment by noffle** [comment]
- [ ] ipget (https://github.com/noffle/ipget)
 - [ ] tests + travis ci
 - [x] support godep
 - [x] smarter default filename when given a x/y/z path
 - [ ] logging with github.com/Sirupsen/logrus
 - [x] plan out work toward 'ipfs get' feature parity

I chatted with @whyrusleeping about logrus and logging for ipget, and decided against it: the logging isn't very human friendly, and CLI tools like this are primarily talking to humans. [go-logging](https://github.com/op/go-logging) looks nice, but I think just writing to stderr is sufficient for this tool.

I didn't get to delve very deeply into testing, but I got a wealth of information about how current `ipfs get` testing works with [sharness](https://github.com/mlafeldt/sharness), which I'll tackle this week.

**Comment by rht** [comment]
@noffle If you `git blame` the code, the one who put logrus into almost all logging was me, sorry.
One reason against logrus that I know of is that logrus doesn't tell line number when an err happens (a much requested feature as in https://github.com/Sirupsen/logrus/issues/63).
Though it would be more helpful if you elaborate on "the logging isn't very human friendly", lest the back-and-forth switching between the two libs.
(will fix the composite files PR later)

**Comment by Sirupsen** [comment]
> I chatted with @whyrusleeping about logrus and logging for ipget, and decided against it: the logging isn't very human friendly, and CLI tools like this are primarily talking to humans. go-logging looks nice, but I think just writing to stderr is sufficient for this tool.

Curious what you mean here? You may want to write a custom formatter if it's to show users and not the developers.

**Comment by whyrusleeping** [comment]
@Sirupsen its not really that its not 'human friendly' its just information overload to use a full fledged logging library for an app that has functionality similar to 'wget'. 

While youre here... any news on the filename/line-number front? logrus is definitely more flexible, but the lack of line numbers makes debugging more difficult for me (prompting the discussion about switching back to `go-logging`)

**Comment by noffle** [comment]
> Curious what you mean here? You may want to write a custom formatter if it's to show users and not the developers.

Jeromy did a better job of clarifying than I did -- sorry about that. I didn't know about the line number feature-want, but yes, my qualm was with logrus being heavy (creating a custom formatter that outputs essentially just what `fmt.Fprintf(os.Stderr, "...")` does) in relation to the tininess of this tool. Having line numbers (maybe behind a `-d` debug switch) would be nice, though.

**Comment by Sirupsen** [comment]
@whyrusleeping I've never needed the functionality myself and noone has ever opened a convincing PR to do it that works in every situation (see [this comment](https://github.com/Sirupsen/logrus/pull/75#issuecomment-146408086)). I'm very surprised noone has written a hook for it, people seem to insist it has to be in core.

**Comment by lgierth** [comment]
Let's move this to an appropriate issue in another repo
