### ISSUE TITLE
Sprint Oct 5th

### ISSUE THREAD

**Issue by RichardLitt** [ipfs/pm#36]
## Sprint Goals  - October 5th, Sprint Issue #36

- _None specified_

## Sprint Discussions

See https://github.com/ipfs/pm#sprint-discussion-schedule

Please take notes in a separate pad, if you can, and link it here.

- node-ipfs notes:
- go-ipfs notes: 
- ipfs-app notes: 

## Sprint Deliverables

- Add yourself below, that way we only have people listed who are really in the sprint
- Add links to issues down here. Only add things you can finish this sprint.

### @dignifiedquire

- [ ] Implement welcome screen
- [ ] Mockup and implement file upload
- [ ] Plan and document component and design architecture (ref conversation with @jbenet)

### @whyrusleeping
- [x] fix go-msgio
  - [ ] update in go-ipfs
- [ ] fix nil address panic in go-multiaddr-net
  - [ ] merge fix into go-ipfs
- [ ] merge go1.5 trailers
- [ ] merge fd limiter
- [ ] debug bitswap notifications bug
- [ ] ship 0.3.8

### @lgierth

- [ ] gateway-dmca-denylist https://github.com/ipfs/infrastructure/pull/95
- [x] updated solarnet readme https://github.com/ipfs/infrastructure/pull/97
- [x] http://metrics.i.ipfs.io now useful 
  - check out `ssh -L 8080:metrics.i.ipfs.io:80 root@<any-solarnet-host>.i.ipfs.io`
  - https://snapshot.raintank.io/dashboard/snapshot/EVo4WlYtlp1VmxcePdeGjJRpzJzdBoRd

### @diasdavid

- ipscend https://github.com/diasdavid/ipscend
  - [ ] Polish the screenshot feature 
  - [x] reach to people to try it out, get feedback from Kyle
- IPFS npm companion
  - [ ] Get the `files` api available through node-ipfs-api https://github.com/ipfs/node-ipfs-api/issues/72
  - [ ] Make ipfs-blob-store use `files` https://github.com/ipfs/ipfs-blob-store
- [x] &yetConf

**Comment by amstocker** [comment]
python-ipfs-api
- [ ] readthedocs.org page
- [x] support for large file upload
- [x] support for streaming download directly to file/directory (`ipfs get`)
- [ ] easy integration for async environments

**Comment by mappum** [comment]
### `inpm`
- [ ] Fix crash errors
  - [x] `vinyl-multipart-stream` error when adding symlinks ([#1](https://github.com/jbenet/node-vinyl-multipart-stream/pull/1))
  - [x] intermittent ENOTFOUND when making requests to `registry.npmjs.org`
  - [ ] `ipfsd-ctl` daemon giving ECONNREFUSED
  - [ ] hanging
- [ ] Duplication install
- [ ] Flatten modules when duplicating (npm v3 behavior)
- [ ] Run pre/postinstall scripts, duplicate if files change

**Comment by noffle** [comment]
- [ ] ipget
 - [ ] sharness testing
 - [ ] finish up @rht's PR if they don't get a chance

**Comment by diasdavid** [comment]
### SPRINT UPDATE

- [x] Conferencing at &yetCond
- ipscend
  - [x] Polish, screenshot, preview (also did a ipscend-example with several stages to quickly recreate a ipscend project with several iterations)
  - [x] Documentation for the tool (also add the DNS trick)
- [x] get `files api` on node-ipfs-api https://github.com/ipfs/node-ipfs-api/issues/72  
- [x] Hangout with Kyle (which is really nice), walk him through our process, libp2p and ipscend
- [ ] worked on ipfs-blob-store (not finished yet), but it lead to:
- [x] discuss and plan with @whyrusleeping how we are going to make npm's IPFS companion https://github.com/ipfs/pm/issues/38 (plus the mfs multiverse)
- [x] code reviews and merged some PR here and there

**Comment by Dignifiedquire** [comment]
# Sprint Update

## Work on Electron App

- [x] Implement welcome screen
  - [x] Advanced option screen
  - [x] Close application on cancel
  - [x] Auto start on successfull setup
- [x] Implement file upload via drag n drop
  - [x] Native (only OS X) menubar
  - [x] Cross platform drop area in the window
  - [x] Native notifications for finished file upload
- [x] Add file logging using winston
- [x] Upgrade to react 0.14
- [x] Clean up code
- [x] Add logo to menu title
- [ ] Packaging setup
  - [x] Make it work
  - [ ] Fix issue with inifinite applications started :(
  - [ ] Automated release process (build and push to github releases)
- [ ] Documentation
  - [ ] Components
  - [ ] File structure
  - [ ] Used libraries
- [ ] Rename to IPFS Station

## WebUI

- [ ] Start work on mockups for the new design

**Comment by whyrusleeping** [comment]
- [x] fix go-msgio
  - [x] update in go-ipfs
- [x] fix nil address panic in go-multiaddr-net
  - [x] merge fix into go-ipfs
- [ ] merge go1.5 trailers
- [x] merge fd limiter
- [x] debug bitswap notifications bug
  - [x] fix go-peerstream close bug
  - [x] fix bitswap notifications bug
- [ ] ship 0.3.8
  - [x] changelog updated
Lots of bugfixes and test fixes here, things are quite a bit more stable.

**Comment by lgierth** [comment]
- [~] gateway-dmca-denylist https://github.com/ipfs/infrastructure/pull/95
- [x] updated solarnet readme https://github.com/ipfs/infrastructure/pull/97
- [x] http://metrics.i.ipfs.io is now useful, thanks to a bit of recreational pointing and clicking
  1. `ssh -L 8080:metrics.i.ipfs.io:80 root@<any-solarnet-host>.i.ipfs.io`
  2. then goto http://localhost:8080
  3. to avoid the ssh tunnel, set up cjdns locally
  4. there are a number of metrics already available -- goroutines! file descriptors! gc time!
  5. dashboard snapshots can be shared with the public: https://snapshot.raintank.io/dashboard/snapshot/EVo4WlYtlp1VmxcePdeGjJRpzJzdBoRd

**Comment by RichardLitt** [comment]
- [x] Mention ipfs/support on the google groups email list.
- [x] Make sure the google groups list is advertised in the appropriate places.
- [x] Create and advertise the IPFS calendar in [community#36](https://github.com/ipfs/community/issues/36)
- [x] Add node-ipfs-api vs. node-ipfs question to ipfs/faq.
- [x] Checked daviddias/ipscend.
- [x] Update node-ipfs-api README.md.
- [x] Take a crack at node-ipfs-api docs!
- [x] See if I can codify how I can help manage sprints and project management better.
- [x] Add ipfs/apps to project-directory.md
- [x] Look into Readme.io and Swagger for the go-ipfs HTML api.
- [x] Sprint mastery.


- [ ] Add update-or-create to dnslink-deploy [dnslink-deploy#5](https://github.com/ipfs/dnslink-deploy/issues/5).
- [ ] Add <language>-contribute.md files to community list. Do Go and Node. [go-ipfs#1734](https://github.com/ipfs/go-ipfs/pull/1734)
- [ ] Resolve issues on ipfs/community as much as possible. Add open issues to next week's sprint.
- [ ] Write 300 words~ on how I can codify how I can help manage sprints and project management better.
- [ ] Give IPFS install another test run through for ease of use. Minimum: Getting started page.
- [ ] Actually finish job spec. Google what these should look like, too.
- [ ] Work on IPFS-Textbook. Deliverables: A read through and edit; close all PRs and issues; update glossary.
- [ ] Help @jbenet with email lists. (logistics)
- [ ] PR the Readme standards and guidelines.
- [ ] Build a README parser and standard checker. Test IPFS repositories with it.
- [ ] Write a Starlog about Readme standards and all repositories.
- [ ] Close gencmdref issue for the website [go-ipfs#1735](https://github.com/ipfs/go-ipfs/issues/1735)
- [ ] Setup keybase.io, and take a look at the BookReader [issue](https://github.com/ipfs/archives/issues/14) as payment of that debt to @davidar

**Comment by davidar** [comment]
- continued working on ipfs/apps#5, and graduated it into its own repo: https://github.com/davidar/TeX.js
  - this will soon be applied to the arXiv papers, and published on IPFS
- accidentally sparked a lot of discussion about CRDTs on ipfs/notes#40
