### ISSUE TITLE
Publish Q1 2017 Roadmap

### ISSUE THREAD

**Issue by flyingzumwalt** [ipfs/pm#365]
- [x] Post Roadmap in [waffle board](https://waffle.io/ipfs/roadmaps)
- [ ] Announce on the All Hands call
- [ ] Update Roadmap.md in ipfs/ipfs
- [ ] Blog Post? https://github.com/ipfs/blog/issues/90

**Comment by flyingzumwalt** [comment]
In blog post, if we write it, we should discuss 
* stale endeavors
* lessons learned about kanban (loosely coordinated vs. not coordinated)
* thrashing
* sprints, sprintinos

**Comment by diasdavid** [comment]
Thank you @flyingzumwalt :) Love all the issues 🌟

**Comment by em-ly** [comment]
I think having a blog post for the kick off of the new quarter is a great idea. started an issue on that here: https://github.com/ipfs/blog/issues/90
