### ISSUE TITLE
Sprint Oct 12th

### ISSUE THREAD

**Issue by RichardLitt** [ipfs/pm#39]
# Sprint 37
Date: October 12, 2015

## Sprint Goals

- Ship 0.3.8

## Sprint Discussions

See https://github.com/ipfs/pm#sprint-discussion-schedule

Please take notes in a separate pad, if you can, and link it here.

- Apps on IPFS notes: https://pad.okfn.org/p/sprint-37-apps-on-ipfs
- node-ipfs notes:  https://pad.okfn.org/p/sprint-37-node-ipfs 

## Sprint Deliverables

- Add yourself below, that way we only have people listed who are really in the sprint
- Add links to issues down here. Only add things you can finish this sprint.

#### At sync time
daviddias, lgierth, kyledrake, krl, RichardLitt, whyrusleeping, dignifiedquire

#### With deliverables this week
* [x] daviddias
* [x] lgierth
* [x] kyledrake
* [x] krl
* [x] richardlitt
* [x] whyrusleeping
* [x] dignifiedquire
* [ ] jbenet
* [ ] mappum
* [ ] noffle
* [x] ike
* [x] amstocker

#### electron-app

- [ ] Packaging setup 
  - [ ] Fix issue with inifinite applications started :(
  - [ ] Automated release process (build and push to github releases)
- [ ] Documentation
  - [ ] Components
  - [ ] File structure  
  - [ ] Used libraries-
- [ ] Rename to IPFS Station

#### WebUI

- [ ]  Start work on mockups for the new design

### @krl

- [ ] ipfs webcomponents
  - [ ] best practices, frameworks
  - [ ] tooling, versioning, etc

### @kyledrake

Recap from last sprint:

> First sprint. Last week I did some initial work on setting up DMCA compliance. I also did some work preparing for the libp2p announcement, including copy for a blog post. Next week is mostly a continuation of that work. New item is copy for the Electron app announcement. I have a talk this Saturday at BSides that will discuss IPFS. I also want to start getting us on a more active blog cycle. We're doing a ton of great work here that isn't getting the attention it deserves because we're not talking about it.

#### DMCA

- [ ] Approval from jbenet on DMCA items, and required info.
- [ ] Get access to company virtual mailbox to be able to check for DMCA letters.
- [ ] Register a Protocol Labs a fax line (lol)
- [ ] Fill out Interim Designation of Agent to Receive Notification of Claimed Infringement form.
- [ ] Send form to copyright office with check, will be expensed to Protocol Labs ($105)
- [ ] Initial DMCA takedown info page (example: ipfs.io/dmca.html).
- [ ] Figure out process for DMCA takedowns (list of hashes?)
- [ ] Coordinate with @lgierth on DMCA denylist (see https://github.com/ipfs/go-ipfs/pull/1551)

#### Blog and Outreach

- [x] Finish draft of libp2p announcement
- [ ] Work to improve the libp2p web site
- [ ] Announcement post for Electron app (see https://github.com/ipfs/electron-app/issues/46)
- [x] Finish BSides Talk
- [x] Work on getting a process for more frequent blog posts.

### @lgierth

_ :palm_tree: No tasks this week_

### @whyrusleeping

- [ ] ship 0.3.8
- [ ] fix goprocess panic in swarm/dialer
- [ ] improve address dial ordering
- [ ] PR to gobuilder to fix ipfs builds
- [ ] get numbers for ipfs transfers over WAN
  - [x] [tool to simulate WAN on a virtual net](https://github.com/whyrusleeping/testnet-utils)
  - [ ] docker test environment and scripts for benchmarks

### @RichardLitt

- [ ] Work on IPFS-Textbook. Deliverables: A read through and edit; close all PRs and issues; update glossary.
- [ ] Help @jbenet with email lists. (logistics)

#### README Overhaul
- [ ] Add <language>-contribute.md files to community list. Do Go and Node. [go-ipfs#1734](https://github.com/ipfs/go-ipfs/pull/1734)
- [ ] PR the Readme standards and guidelines.
- [ ] Build a README parser and standard checker. Test IPFS repositories with it.

#### API Documentation
- [ ] Close gencmdref issue for the website [go-ipfs#1735](https://github.com/ipfs/go-ipfs/issues/1735)
- [ ] Work on the HTTP api for ipfs/go-ipfs

### @diasdavid || @daviddias

- [x] ipfs-blob-store
- [x] ipscend+c3 planning/building
- [x] Make a case for blogging on IPFS (what are the tools we can use out there and how can we make it interesting)

#### Python ipfs api:
- [x] started docs: python-ipfs-api.readthedocs.org
- [x] now support file streaming for large uploads/downloads
- [ ] async implementations for gevent, asyncio, etc
#### Other:
- [ ] pubsub on ipfs research, SSB on ipfs, CRDTs on ipfs
- [ ] distributed web forum on ipfs built on CRDTs

#### indie-comments:
  - [ ] consider initial project goals
  - [ ] work on user stories
  - [ ] outline initial MVP UX

**Comment by jbenet** [comment]
we should probably just deploy our own damn etherpad until we make one on ipfs.

**Comment by Dignifiedquire** [comment]
> we should probably just deploy our own damn etherpad until we make one on ipfs.

What exactly is the benefit in the current structure of the sessions for an etherpad, as far as I can tell everybody is just pasting his or her goals for the week and then it gets copied over to github. So why not just post it as a comment directly on github?

**Comment by jbenet** [comment]
benefits
- we sometimes discuss the todos in the hangout
- time to edit it and all edit at once
- people can help reallocate for each other, and so on.

this is more vestigial from when i had more time to PM better. 

we could move to:
- everyone post an individual comment on the sprint issue and not have one comment at the very top.
- have a better PM than me

**Comment by RichardLitt** [comment]
Why don't we try posting individual comments in the sprint issue this week? I want to see if that works, I suspect it will work just as well. Combined with a list of attendants at the top, it'll streamline my efforts, anyway. I haven't seen anyone edit it async in the past few weeks. 

I'm just the sprint master, not a PM, so I don't know if I can help completely, but I think that would be a smart thing to do.

**Comment by diasdavid** [comment]
### SPRINT UPDATE

- [x] figure out things for SF Meetup (meetup.com madness, etc)
- [x] Get things together to be nominated for Computer Society Distinguished Lecturer Program http://www.computer.org/web/chapters/speaker-nomination
- npm on IPFS
  - [x] ipfs-blob-store with mfs
  - [x] registry-static working with ipfs-blob-store 
  - Get all of npm inside IPFS (_blocked_, need to have good Internet for 24h++, planning on doing that 1st thing when I get back to Lisbon on Sunday)
- Node.js Interactive Logistics (request travel fund, etc)		
- [x] collect IPFS meetups all over the world https://github.com/ipfs/community/pull/56
- [x] make a notes for blogging case on IPFS https://github.com/ipfs/notes/issues/66 (get that discussion going), explore how harp can help us achieve that (https://github.com/kennethormandy/hb-casper/issues/3)
- [x] Merkle Tuesday Hangout
  - https://etherpad.wikimedia.org/p/merkle-tuesday
  - https://github.com/datproject/discussions/issues/29

**Comment by Dignifiedquire** [comment]
## Sprint Update

### Station (was electron-app)

- [x] Merge big refactoring
- [x] Rename electron-app to station
- [~] Setup automatic release process for station
- [x] Fix https://github.com/jbenet/node-subcomandante/issues/2 to avoid fork bombing ourselve in packed versions
- [x] Extract location formatting into ipfs-geoip (https://github.com/ipfs/ipfs-geoip/pull/3)

### (Web)Components on IPFS

- [~] Discussions with @krl about possible solutions
- [x] Webpack sample for packaged components served from ipfs (https://github.com/Dignifiedquire/components-on-ipfs)

### node-ipfs-api

- [~] Setup browser tests using karma (https://github.com/ipfs/node-ipfs-api/pull/78)

### WebUI

- [x] Research on current functionality
- [~] First draft on how the new design should look like: https://ipfs.io/ipfs/QmTr8oTzi1upsHhHoK3ixmsxosD7hFMuMgbEZSakMRbTUT

**Comment by whyrusleeping** [comment]
- [x] ship 0.3.8
- [x] fix goprocess panic in swarm/dialer
- [x] fix goprocess panic in bitswap
- [x] improve address dial ordering
- [x] add system diagnostics command
- [x] add local flag to ipfs name resolve
- [x] aided in debugging of station
- [ ] PR to gobuilder to fix ipfs builds
- [ ] get numbers for ipfs transfers over WAN
  - [x] learn more about linux traffic control than i wanted to
  - [x] PR against dockers libnetwork
  - [x] [tool to simulate WAN on a virtual net](https://github.com/whyrusleeping/testnet-utils)
  - [ ] docker test environment and scripts for benchmarks

**Comment by jbenet** [comment]
### @jbenet's update

- [x] blockchain workshop in hong kong -- this took up most of my time last week.
- [x] @epicenterbtc interview released
- [x] catching up on github discussions + CR (a bit behind still)
  - [x] ipfs update
  - [x] ipfs hosting binaries plan
- [x] help @whyrusleeping land go-ipfs 0.3.8
- [x] find space for SF meetup
- [x] merge fixes for node-subcomandante, vinyl-multipart-stream, website
- [x] lots of admin things
- [x] lining up various meetings this week
- [x] prep for talks this week -- http://web.stanford.edu/class/ee380/Abstracts/151021.html

**Comment by RichardLitt** [comment]
@RichardLitt's update:

- [x] Worked on the calendar
- [~] Worked on IPFS textbook
- [x] PRed go-contribution-guidelines.md
- [~] Worked on README standards and finding a parser; still working on that.
- [~] Looked at starting HTTP api for ipfs/go-ipfs; still preliminary
- [ ] Helped juan with Email lists
- [ ] Close gemcmdref

**Comment by chriscool** [comment]
@chriscool's update:

- [x] first version of Sharness coverage script
- [x] tests for `ipfs commands` in t0010 and related cleanup
- [x] helped implement `ipfs commands --flags`
- [x] first try at handling no nc in t0060
- [x] added a few issues about the build infrastructure

**Comment by ike** [comment]
@ike's update:

I got laid off this week, so I made no progress on indie-comments. If anybody has any leads on front-end dev or bizdev gigs, I'd be super appreesh.

indie-comments:
[ ] consider initial project goals
[ ] work on user stories
[ ] outline initial MVP UX

**Comment by RichardLitt** [comment]
New sprint! https://github.com/ipfs/pm/issues/40

**Comment by davidar** [comment]
@davidar's update:

- still working on [TeX.js](https://davidar.io/TeX.js/)
  - discussing how to get this applied to the arXiv corpus ipfs/archives#31
- started discussions about integrating @hypothesis with IPFS
- slowly making progress on ipfs/archives#3
- spreading the word about CRDTs ipfs/notes#40 ;)
