### ISSUE TITLE
Sprint C

### ISSUE THREAD

**Issue by jbenet** [ipfs/pm#4]
**Sprint Goals** 
1. Get the migrations done + flat repo merged
2. Finish the container assets
3. DHT interface changes (both spec and implementation)

**Sprint Participants** - @jbenet @dylanPowers @hosh @whyrusleeping

**Sprint Deliverables**

- [ ] Containers:
  - [ ] Demo #6 https://github.com/jbenet/ipfs-container-demos/issues/3 (@hosh)
      - [ ] Prepare VM that can scale X VMs
  - [ ] https://github.com/jbenet/ipfs-container-demos/issues/5 (@hosh)
    - [ ] Astralboot. Note: likely dropped for the sprint after

- [ ] Bugs
  - [ ] Diagnose https://github.com/ipfs/go-ipfs/issues/1036 (@whyrusleeping)
  - [ ] Address memory leak (likely culprit is goprocess)
  - [x] Fix the pinning bugs https://github.com/ipfs/go-ipfs/pull/1010 (@whyrusleeping, @jbenet)

- [ ] DHT
  - [ ] Record spec (@jbenet)
  - [ ] Implement record changes (@whyrusleeping)

- [x] Migrations + Flat Repo
  - [x] Moving migrations to separate repo (@whyrusleeping)
  - [x] Make the runner inside go-ipfs (@whyrusleeping)
  - [x] Migration repo locks (@jbenet)
  - [x] Make the migration guide (@jbenet)
  - [x] Merge (@jbenet)

- [ ] Community
  - [ ] Periodic Newsletter (@dylan) https://github.com/ipfs/community/issues/8
  - [ ] Waffle documentation (@dylan) https://github.com/ipfs/infrastructure/issues/8
  - [ ] Explain the label scheme (@dylan) https://github.com/ipfs/community/issues/10
  - [ ] fix command docs links (@dylan)
  - [ ] fix broken links (@dylan)
  - [ ] go-ipfs reorg (@jbenet)

- [ ] Other
  - [ ] Publish the blog (@jbenet)
  - [x] Improve bitswap transfer speed (@whyrusleeping)
  - [x] Fix nasty secio err msg -- https://github.com/ipfs/go-ipfs/issues/1016 - https://github.com/ipfs/go-ipfs/issues/1073 (@jbenet)

### Backlog

- [ ] HTTP API Doc
- [ ] godoc/readmes on packages
 - [ ] review + improve the keystore spec (@whyrusleeping, @jbenet)
    - Note: has been updated

**Comment by jbenet** [comment]
1/3
