### ISSUE TITLE
Sprint Oct 26

### ISSUE THREAD

**Issue by RichardLitt** [ipfs/pm#41]
# Sprint Oct 26
Date: October 26, Stardate 2015

## Sprint Goals

- _TBD_

## Sprint Discussions

See https://github.com/ipfs/pm#sprint-discussion-schedule

Please take notes in a separate pad, if you can, and link it here.

- node-ipfs notes:  
- go-ipfs notes:  
- ipfs-app notes:  

## Sprint Deliverables

- Add yourself below, that way we only have people listed who are really in the sprint
- Add links to issues down here. Only add things you can finish this sprint.

### David Dias (@diasdavid)

- libp2p
  - [x] Decide in which papers + surveys should be written for libp2p with Juan
  - [ ] Speed Jeromy up on libp2p
  - [ ] Get webrtc-explorer as one of the transports
  - [x] add a libp2p hangout to Mondays https://github.com/ipfs/pm/pull/42
  - [x] https://github.com/diasdavid/webcrypto
- npm's registry on IPFS
  - [ ] download the entire npm
  - [ ] install modules via IPFS using reginabox+registry-static
- js-ipfs-api
  - [x] Finish 0.3.7 Node.js tests on solid-tests branch
  - [x] Merge solid-tests branch
  - [x] Upgrade node-ipfs-api to be compatible with the new 0.3.9
  - [x] 'callbacks vs promises' path with @dignifiedquire
  - [x] fix regression https://github.com/ipfs/js-ipfs-api/pull/99
  - [x] get files on js-ipfs-api working again (after all the release madness) https://github.com/ipfs/js-ipfs-api/pull/74
- js-ipfs
  - [x] https://github.com/jbenet/js-multihash/pull/4
  - [x] https://github.com/jbenet/js-multihashing/pull/4
  - [x] https://github.com/diasdavid/webcrypto
- extra
  - [ ] Edit SF meetup recordings
  - [x] rename javascript projects to js-name instead of node-name. Write an issue explaining the motivation and link all the projects to that issue. https://github.com/ipfs/node-ipfs/issues/32
  - community
    - [x] sync with meetup.com and learn about their plans and pro features
    - [ ] [sync back with @tmatcha on SF meetup]
    - [x] schedule Lisbon IPFS meetup http://www.meetup.com/ipfs-lisbon-meetup/events/226457561/
(https://github.com/ipfs/community/issues/53#issuecomment-149785583)

### Christian Couder (@chriscool)

- [x] investigate golang/build
- [x] polish/improve previous PR to get them merged

### @jbenet

- [x] CR golang/utp and other pending 0.3.10 PRs.
- [x] lots of CR + discussions for go-ipfs
- [x] discuss golang libp2p transports
- [x] various meetings + org things
- [x] shipped 0.3.9 (testing, npm-go-ipfs, etc)
  - [x] updated webui for 0.3.9
  - [x] updated js-ipfs-api tests for 0.3.9

### @kyledrake

- [x] IPFS interview questions
- [x] Run IPFS on a VPS blog post
- [ ] OVH feedback on IPFS usage (contacted, pending response from business development team)
- [x] DMCA info/takedown contact page for ipfs.io
- [x] Document ARIN SWIP process for IPFS nodes
- [ ] Improvements to libp2p site

### @lgierth

- dmca / ipfs.io/refs
  - [~] deploy refs.ipfs.io
  - [ ] point ipfs.io/refs to refs.ipfs.io
  - [ ] ping victor re: refs
- storage
  - [x] new storage hosts with ovh and hetzner ipfs/infrastructure#89
  - [~] move pollux to protocol labs account ipfs/infrastructure#73
  - [ ] periodic ovh renewal
  - [ ] write to ovh support re: bandwidth rules
  - [x] propose how to keep track of storage ipfs/infrastructure#106
  - [x] disable ipfs restarter on storage hosts
  - [~] ipfs add openwrt 15.05
  - [x] file issue about ipfs add memory leak ipfs/go-ipfs#1924
- [ ] open up cors on gateways (allow origin *)
- [ ] fix go-ipfs --api description ipfs/go-ipfs#1866
- [ ] add notes about cdnjs ipfs/archives#35

**Comment by jbenet** [comment]
hey @diasdavid -- very little of the stuff above is actually required for getting a js-ipfs node running. things like editing the SF meetup videos, renaming, the meetup.com things -- it's all very useful stuff, but really side quests from the main goals -- should only really devote a small percentage of time to that stuff compared to the main prios.

**Comment by jbenet** [comment]
@whyrusleeping @lgierth @mappum @richardlitt drop todos here pls.

**Comment by RichardLitt** [comment]
- [ ] Go-IPFS HTTP API Documentation

**Comment by jbenet** [comment]
### @jbenet update

- [x] CR golang/utp and other pending 0.3.10 PRs.
- [x] discuss golang libp2p transports
- [x] lots of CR + discussions for go-ipfs
- [x] various meetings + org things
- [x] shipped 0.3.9 (testing, npm-go-ipfs, etc)
  - [x] updated webui for 0.3.9
  - [x] updated js-ipfs-api tests for 0.3.9

**Comment by cryptix** [comment]
* [ ] re writable gateway: move to POST instead of PUT for object patching (tests for that in https://github.com/ipfs/go-ipfs/pull/1917)
* [x] git-remote-ipfs: proper ipfs pathes and..! you can now push _MORE THAN ONCE_ to a remote... X_X
* [ ] git-remote-ipfs: next: clone from /ipns/ and set the current version as the remote (until keystore improved)
* [x] created a starlog!: /ipns/www.mindeco.de
* [ ] some CR for ipns caching #1887 - we need this. compare above with /ipns/mindeco.de/blog which is a dnslink=/ipns/...
* [ ] embedded golang node question: https://github.com/cryptix/git-remote-ipfs/issues/5

**Comment by lgierth** [comment]
- dmca / ipfs.io/refs
  - [~] deploy refs.ipfs.io
  - [~] point ipfs.io/refs to refs.ipfs.io
  - [ ] ping victor re: refs
- storage
  - [x] new storage hosts with ovh and hetzner ipfs/infrastructure#108
  - [~] move pollux to protocol labs account ipfs/infrastructure#73
  - [ ] periodic ovh renewal
  - [ ] write to ovh support re: bandwidth rules
  - [x] propose how to keep track of storage ipfs/infrastructure#106
  - [x] disable ipfs restarter on storage hosts
  - [~] ipfs add openwrt 15.05
  - [x] file issue about ipfs add memory leak ipfs/go-ipfs#1924
- [~] open up cors on gateways (allow origin *) ipfs/infrastructure#109
- [~] fix go-ipfs --api description ipfs/go-ipfs#1866 ipfs/go-ipfs#1866
- [ ] add notes about cdnjs ipfs/archives#35

**Comment by whyrusleeping** [comment]
- [x] fix windows builds https://github.com/ipfs/go-ipfs/pull/1875
- [x] fix streaming output https://github.com/ipfs/go-ipfs/pull/1882
- [x] replace go1.5 requirement https://github.com/ipfs/go-ipfs/pull/1882
- [ ] fix running ipfs id on self https://github.com/ipfs/go-ipfs/pull/1856
- [x] a few new calls in go-ipfs-api
- [ ] cache results of ipns name resolution for a short time https://github.com/ipfs/go-ipfs/pull/1887
- [x] ipfs swarm connect should error when it fails https://github.com/ipfs/go-ipfs/pull/1900
- [x] ipfs 0.3.9!
- [x] fix content type bug
- [x] lottsss of gx work (its super dooper cool guys)
- [ ] started tool to visualize dht queries

TODO:
- [ ] rewrite utp https://github.com/ipfs/go-ipfs/pull/1789
- [ ] work on integrating ipfs-update into go-ipfs
- [ ] fix bug in go-log https://github.com/ipfs/go-ipfs/issues/1874
  - write tests
- [ ] rebase 0.4.0 (after utp merges!)

**Comment by kyledrake** [comment]
- [x] IPFS interview questions
- [x] Run IPFS on a VPS blog post
- [ ] OVH feedback on IPFS usage (contacted, pending response from business development team)
- [x] DMCA info/takedown contact page for ipfs.io
- [x] Document ARIN SWIP process for IPFS nodes
- [ ] Improvements to libp2p site

**Comment by diasdavid** [comment]
### SPRINT UPDATE

This week sprint update goes by endeavours (helps keep things organised).

- libp2p
  - [x] Decide in which papers + surveys should be written for libp2p with Juan
  - [~] Speed Jeromy up on libp2p - I didn't have the opportunity to formally do it, but @whyrusleeping went through the newly merged specs for libp2p and liked it, so I consider that there was indeed some knowledge transfer
  - [~] Get webrtc-explorer as one of the transports - I worked on this and got it on its path (even received some really nice emails and tweets of people excited about its development), however, the fact that node-webrtc is broken in Node.js 4.0.0 and above is blocking me a bit (also consuming my time to figure it out)
  - [x] add a libp2p hangout to Mondays https://github.com/ipfs/pm/pull/42 - Yes, today we will have a libp2p hangout!
  - [x] https://github.com/diasdavid/webcrypto
- npm's registry on IPFS - got a bit slowed down by the IPFS release and js-ipfs-api update stravaganza, didn't manage to finish the thing.
  - [ ] download the entire npm
  - [ ] install modules via IPFS using reginabox+registry-static
  - [x] get files on js-ipfs-api working again (after all the release madness) https://github.com/ipfs/js-ipfs-api/pull/74
- js-ipfs-api
  - [x] Finish 0.3.7 Node.js tests on solid-tests branch
  - [x] Get some solid-tests on this module (finally)
  - [x] Upgrade node-ipfs-api to be compatible with the new 0.3.9 (@jbenet started it)
  - [x] 'callbacks vs promises' path with @dignifiedquire
  - [x] fix regression https://github.com/ipfs/js-ipfs-api/pull/99
- js-ipfs - this is a new endeavour that will take the approach of starting ipfs.js from the top (exposing the desired API by using js-ipfs-api and then replacing its internals till it is a complete node. A great part of this is ensuring that every module runs well in the browser
  - [x] https://github.com/jbenet/js-multihash/pull/4
  - [x] https://github.com/jbenet/js-multihashing/pull/4
  - [x] https://github.com/diasdavid/webcrypto -> this is going to be really cool! join today's IPFS meeting for news
- extra
  - [x] CR and merge PR 'here and there'
  - [0] Edit SF meetup recordings - Unfortunately, it is impossible to see the screen and since everything is demos... Really disappointed with the quality, I'm going to start bringing my whole backpack for these events, including my video capture box.
  - [x] rename javascript projects to js-name instead of node-name. Write an issue explaining the motivation and link all the projects to that issue. https://github.com/ipfs/node-ipfs/issues/32
  - community
    - [x] sync with meetup.com and learn about their plans and pro features (we had a quick discuss and decided not to go the meetup.com pro route)
    - [x] schedule Lisbon IPFS meetup http://www.meetup.com/ipfs-lisbon-meetup/events/226457561/
(https://github.com/ipfs/community/issues/53#issuecomment-149785583)

**Comment by RichardLitt** [comment]
- [~] Go-IPFS HTTP API Documentation. I worked on this, started manually going through and filling out answers according to the Swagger schema. I would like to automatically generate them from the ipfs docs, but I'm not sure that the API would be the same - my strategy right now is to go through and test curling each different command. It'll take a while.
- [x] Worked on contributing docs across repositories.
- [x] Made security documentation a bit tighter.
- [x] Finally grokked IPNS
- [x] Worked on IPFS-textbook by making a glossary.
- [x] Double checked and cleaned up project-directory.md

**Comment by ion1** [comment]
* [x] Contributed a small part to https://github.com/ipfs/go-ipfs/pull/1887 “cache ipns entries to speed things up a little”

* [~] Posted https://github.com/ipfs/go-ipfs/pull/1921 “Gateway: Add Cache-Control/max-age and ETag to IPNS requests”. It works, but needs to be rebased onto master after 1887 is merged. Needs a CR.

**Comment by diasdavid** [comment]
Notes from IRC
- @cryptix pick @diasdavid brain on ipscend
- @diasdavid learn about metalsmith and see how it stacks up to Harp for https://github.com/ipfs/starlog/issues/31

**Comment by RichardLitt** [comment]
Follow up for peeps:

* Please look at the list of contributors who it is OK to follow up on for the sync and the GitHub issues, at https://github.com/ipfs/pm#active-contributors. Please add or remove yourself if you would like to be on this list!!

**Comment by VictorBjelkholm** [comment]
### Update

**IPFS in JS**

- [X] working on node-ipfs-api to pass the tests in browser + node env (didn't help very much with this...)
- [~] find and help out with things to contribute to node-ipfs (will need help from daviddias with this)
- [~] Finish writing docs and API docs (Still haven't pushed the branch for this, will do tonigh!)

**go-ipfs**

- [ ] Start contributing and improve the API for setting config params, especially nested ones

**OpenIPFS** - https://github.com/victorbjelkholm/openipfs

- [~] having openipfs ready for public consumption, mainly to scratch my own need for ipfsbin

**IPFSBin** - https://github.com/victorbjelkholm/ipfsbin

- [X] new ui for ipfsbin to be able to select language amongst other things
- [ ] start using openipfs for ipfsbin, to make content more available

**Community**

- [~] preparing talk for local meetups here in Barcelona 
- [ ] collecting things for awesome-ipfs showcase
- [ ] Barcelona hack day with IPFS and Redbooth
