### ISSUE TITLE
Sprint D

### ISSUE THREAD

**Issue by jbenet** [ipfs/pm#5]
**Sprint Goals** 

1. Solid talks (+ demos)
2. DHT spec
3. merge outstanding PRs

**Sprint Participants** - @jbenet @dylanPowers @hosh @whyrusleeping

**Sprint Deliverables**

- Talks
  - [x] localdns (@whyrusleeping, @jbenet)
  - [x] registry demo (@jbenet)
  - [x] talk at fluentconf (@jbenet)
  - [x] talk at Eth Meetup (@jbenet)

- [ ] DHT
  - [ ] Record spec (@jbenet)

- [ ] Containers:
  - [ ] Merge outstanding PRs (@hosh)

- [ ] Community
  - [x] Periodic Newsletter (@dylanPowers) https://github.com/ipfs/community/issues/8
  - [ ] Waffle documentation (@dylanPowers) https://github.com/ipfs/infrastructure/issues/8
  - [ ] Explain the label scheme (@dylanPowers) https://github.com/ipfs/community/issues/10
  - [x] fix command docs links (@dylanPowers)
  - [x] fix broken links (@dylanPowers)

- [ ] Other
  - [ ] Publish the blog (@jbenet)
  - [ ] go-ipfs reorg (@jbenet)
  - [x] https://github.com/ipfs/go-ipfs/pull/1093 (@whyrusleeping)
    - [ ] Ready For Merge!
  - [x] merge https://github.com/ipfs/go-ipfs/pull/1037 (@jbenet)

Addons:
  - [x] https://github.com/ipfs/go-ipfs/pull/1111 (@jbenet)
  - [x] https://github.com/ipfs/go-ipfs/pull/1110 (@jbenet)
  - [x] Fix log file:line printing (@whyrusleeping)
  - [x] use iptb for a new test (@whyrusleeping)
  - [x] merge dnslink PR (@whyrusleeping)
    - [x] waiting on @jbenet's 'Ship It!'

### Backlog

- [ ] Bugs
  - [ ] Diagnose https://github.com/ipfs/go-ipfs/issues/1036 (@whyrusleeping)
  - [ ] Address memory leak (likely culprit is goprocess)

- [ ] ipfs pipe (@whyrusleeping)
- [ ] Implement record changes (@whyrusleeping)
- [ ] HTTP API Doc
- [ ] godoc/readmes on packages
 - [ ] review + improve the keystore spec (@whyrusleeping, @jbenet)
    - Note: has been updated

**Comment by hosh** [comment]
Continuing with https://github.com/ipfs/container-demos/issues/3

**Comment by jbenet** [comment]
@whyrusleeping is the cmds lib hacking you're doing for https://github.com/ipfs/go-ipfs/issues/858 -- and should we add it to this sprint?

**Comment by dylan** [comment]
Please stop mentioning me. Thanks!

**Comment by jbenet** [comment]
Sorry about that!
