### ISSUE TITLE
Sprint Nov 23

### ISSUE THREAD

**Issue by diasdavid** [ipfs/pm#56]
# Sprint Nov 23

## Sprint Goals

- 

## Sprint Discussions

[Schedule](https://github.com/ipfs/pm#sprint-discussion-schedule)

Please take notes in a separate pad, if you can, and link it here.

Endeavour         | Lead           | Pad    | Permanent Link
:---------------: | :------------: | :----: | :------------:
Apps on IPFS      | Juan Benet and Friedel Ziegelmayer | https://public.etherpad-mozilla.org/p/nov-23-apps-on-ipfs |  
infrastructure    | Lars Gierth    | https://public.etherpad-mozilla.org/p/nov-23-infrastructure |  
libp2p            | David Dias     | https://public.etherpad-mozilla.org/p/nov-23-libp2p0-and-js-ipfs |  https://github.com/ipfs/pm/issues/56#issuecomment-159072713
js-ipfs         | David Dias     | https://public.etherpad-mozilla.org/p/nov-23-libp2p0-and-js-ipfs |  https://github.com/ipfs/pm/issues/56#issuecomment-159072713
go-ipfs           | Jeromy Johnson | https://public.etherpad-mozilla.org/p/nov-23-go-ipfs | 
testing + ci      | Jeromy Johnson | https://public.etherpad-mozilla.org/p/nov-23-testing-ci |  
protocol + specs  | Juan Benet     | https://public.etherpad-mozilla.org/p/nov-23-protocol-specs |  
bitswap ml        | Juan Benet     | https://public.etherpad-mozilla.org/p/nov-23-bitswap-ml |  
Data Structures   | Juan Benet     | https://public.etherpad-mozilla.org/p/nov-23-data-structures |  

Please add the Agenda to the Pad before the endeavour sprint starts.

## Sprint Deliverables

- Add yourself below, that way we only have people listed who are really in the sprint
- Add links to issues down here. Only add things you can finish this sprint.

### [David ](@diasdavid)
- libp2p
  - [~]() get Castor juiced up with all of the modules
  - [x] review and merge https://github.com/diasdavid/libp2p-website/pull/3/files
  - [x] add ipscend to libp2p-website https://github.com/diasdavid/libp2p-website/pull/5
  - [ ] Make libp2p-ping be a thing again (guarantees swarm compatibility)
  - [x] Write is the libp2p expected UX https://github.com/ipfs/specs/commit/340e98dd1495fe26cf1c78af2c6b6fb86e98e9d8
  - [x] Update and add more detail to the libp2p interfaces https://github.com/ipfs/specs/pull/48
  - [x] Update the libp2p implementations chapter https://github.com/ipfs/specs/pull/49
  - [x] Update libp2p datastructures https://github.com/ipfs/specs/pull/50
- npm on IPFS
  - [x] Clone the MerkleDAG node pointed by Castor IPNS https://github.com/diasdavid/registry-mirror/issues/5
  - [x] modularize https://github.com/diasdavid/registry-mirror/pull/9
  - [x] ~~cry for love~~🎵😜 Ask feedback on https://github.com/diasdavid/registry-mirror/issues/10
  - [ ] Automate "update IPNS process" for Castor https://github.com/diasdavid/registry-mirror/issues/4
  - [ ] collect stats
    - [ ] npm on fs
    - [ ] npm on ipfs
    - [ ] npm on ipfs with ipfs tar
    - [ ] npm on ipfs with rabin
    - [ ] time registry.npmjs.org to registry-mirror
- ipscend
  - [x] CR and merge https://github.com/diasdavid/ipscend-screenshot-visualizer/pull/1
  - [x] made a blog post http://blog.daviddias.me/2015/11/27/ipscend
  - [x] get in touch with surge people :) 
- js-ipfs-api
  - [x] Set a global timeout variable for mocha tests https://github.com/ipfs/js-ipfs-api/pull/145
  - [x] fix DHT bug on js-ipfs-api https://github.com/ipfs/js-ipfs-api/pull/153
  - [ ] Rebase and merge mocha auto generated tests in https://github.com/ipfs/js-ipfs-api/pull/146 (blocked due to identified bug on https://github.com/mochajs/mocha/issues/1978)
- js-ipfs
- extra
  - [ ] reinstall Go in my brain
  - [x] travel logistics for Node.js Interactive 
  - [ ] prepare talk for Node.js Interactive

### @lgierth

- npm
  - [x] enable nosync on dev040 nodes ipfs/infrastructure@ca1454a
  - [x] test registry-mirror
  - [x] profile zfs performance on castor
  - [x] start mirroring on pollux too
- go-ipfs
  - [ ] RFM X-Ipfs-Gateway-Prefix hardening ipfs/go-ipfs#1988
  - [ ] RFM add commit to :8080/version ipfs/go-ipfs#2002
  - [x] test automatic gc with @rht ipfs/infrastructure#125
  - [ ] investigate red builds ipfs/go-ipfs#2001
  - [ ] test fs-repo-migrations
- infrastructure
  - [x] open up cors on gateways (allow origin *) ipfs/infrastructure#109
  - [x] OVH renewal of castor
  - [x] increase metrics retention ipfs/infrastructure@49295a9
  - [x] reactivate logs from all docker containers ipfs/infrastructure#127
- cjdns
  - [~] discover peers from cjdns ipfs/go-ipfs#1316
  - [~] invite to fc00 development (aka go-cjdns) https://github.com/fc00/spec
- hope
  - [ ] writable gateway
  - [ ] files api response status codes
  - [ ] ~~build a prometheus exporter using :5001~~

**Comment by Dignifiedquire** [comment]
## IPFS Apps

#### Lead: Friedel Ziegelmayer

## Agenda

### IPFS (HTTP) API (SPEC)

- https://github.com/ipfs/go-ipfs/issues/785
- https://github.com/ipfs/specs/issues/6
- https://github.com/ipfs/api


## Participants

- @dignifiedquire (Friedel Ziegelmayer)
- @kyledrake (Kyle Drake)
- @richardlitt (Richard Litt)
- @ion (Johan Kiviniemi)
- Many more, sorry forgot to put in everyone

## Notes

### IPFS (HTTP) API (SPEC)

#### Questions

@dignifiedquire: Who has implemented the original version? Is thera  short breakdown on how this came to be?

@jbenet: The goal for the http API was for it to be able to be layered over any transport. Some people may want to do non-http transports, like UNIX main sockets. Sometimes yuo don't even have HTTP over the wire. Another example woudl be websockets; ie, piping all requests through amux over the daemon, etc. The goal was to design an API that was simply patterened so that it could be layered. We just implemented the HTTP one first. The commands library supports reading and writing with JSON on HTTP and also over the CL. That means all of the regular ways of specifying commands and arguments / options need to be have a ways to be transported to the command in question. So, flags, pathing, query strings, etc. 

@dignifiedquire: Ok. There are some main issues. Richard, I know you've been trying to get some actual stuff done using http commands. We also have the js-ipfs-api docs, because that is kind of a documentation. 
So, today, _how does the API as it is now implemented?_ Ie, returning JSON, chunks, newline-delimitered, etc. 

@jbenet: Yeah, we don't even have a thing where that is documented. Another thing is that the core API - what API means - also needs to be defined. API could be a process around the daemon, or actually an API for the libraries. What would be good would be to have the core as close as possible to the daemon, so that you coudl follow the same for all. We're a little bit far from that, but we're close. 

@dignifiedquire: So the goal wouldbe to have a spec for the API commands and then a version of that which would structure how the API works. 

@dignifiedquire: @diasdavid said earlier that it's not just about documenting, but we also need a Spec that the implementation follows. Ideally, a spec that we could generate a test feed from would be good. Rather than having to guess and think and hope, which is the current scope.

@jbenet: Are there any good versions of that?

@dignifiedquire: That's why I've been looking at apiary. They have two way support. If you write a spec in this format, there are tools for generating mock servers.

@jbenet: One constraint is that the spec will have to be more general than the HTTP. It should be idiomatic, but that should be optional.
@RichardLitt: We need to make sure that the main source of truth is the HTTP spec, so that each implementation should talk to that.

@jbenet: one possibility is to make a spec for the core API, and then just go from there. 
...<@RichardLitt was talking>

@dignifiedquire: So, HTTP is just a subset of what we need. So, we should have a high level, and then use tooling to convert it into Swagger, or whatever.

@jbenet: https://github.com/ipfs/specs/blob/master/modules/modules.go. This shows off how go might be used as an interface langauge.

@jbenet: another approach is enumerate all of the functions in a file, and then enum. all of the ways that interfacing components may do that. We have the ability to: positional arguments, flags, mention files, and that's when we start hitting things which are less defined. When do we need streaming? When do we need APIs such that we are going to be able to stream the output out, like with huge dirs where you need to stream the output as you stream the input.
@dignifiedquire: yeah, we'll need that.

@jbenet: Goals!

- [ ] Enumerate all of the functions that already exist
- [ ] Enumerate all of the things that the functions need to do: flags, I/O

From that, we can figure out which language is best. (Go may not be best, because of streaming interfaces.). From there:
    
- [ ] Pick one of these languages and go from there. 

So, start with the core, and then go from there. `init`, for instance, isn't in the core. But maybe it should be. Maybe there's an argument for one api - client API, and library apis. 

@dignifiedquire: I think it would be good to have them all in the same spec. Let's just make a huge list of makrdown in ipfs/api right now. Also,

- [ ] Do research into other implementions
- [ ] Do better than ECMAScript, because... dayum... 

Talk in the https://github.com/ipfs/api/issues please!

##### Possible Solutions

Would be interesting if it was RESTful rather than RPC, but probably not worth the effort to design a whole new API. – ion

--- 

> Thanks everyone and sorry @diasdavid you couldn't be here :stuck_out_tongue:

**Comment by whyrusleeping** [comment]
## go-ipfs

#### Lead: @whyrusleeping

## Agenda

- commands lib
  - augment argument types (path)
  - cleanup in http client

- close-notify problems
  - try to get minimal test case
  - ask bradfitz? (last resort)

- no-sync flag for flatfs
  - may help s3-fuse-thing for kyle

- private networks:
  - implement shared-key swarms

- pubsub next steps: 
  - scour pub/sub + multicast literature
  - list out links to papers + implementations
  - pick a couple implementations we like
  - figure out hierarchical channels
  - figure out channel-joining protocol
  - figure out authenticated (signed) and encrypted channel

- chunking + dag layouts
  - move things out into own repo first
  - many real workload dataset benchmarks
  - generate stats + graphs to pick algos
  - maybe: heuristic to pick algos eventually
  - come up with a naming convention for them
  - eventually, a heuristic
  - new defaults in 0.4.0?

## Participants
- @jbenet
- @whyrusleeping
- @ion1
- @dignifiedquire

## potentially interested:
- @rht 
- @lgierth 
- @BrendanBenshoof

**Comment by diasdavid** [comment]
## libp2p and js-ipfs

#### Lead: David Dias

## Agenda

- 
- libp2p interop at the swarm level
- libp2p APIs
- js-ipfs
- js-ipfs docs
  - https://github.com/ipfs/js-ipfs-api/pull/132
  - https://github.com/ipfs/js-ipfs-api/pull/104
  - https://github.com/ipfs/js-ipfs-api/pull/105
- commit conventions and changelog https://github.com/ipfs/js-ipfs-api/issues/143
- registry-mirror release
- js-ipfs delegated node
- js-ipfs next steps?

**You have 30 minutes for this agenda**, 5 minutes before the meeting ends, consider moving the remaining items to a github discussion thread so that all the other sprint meetings can start in time.

## Participants (write your name on the list)

- David Dias
- Friedel Ziegelmayer (@dignifiedquire)
- Juan Benet
- Kyle Drake
- Javier Candeira (@candeira on github, @kandinski on irc)
- Nicola Greco
- Johan Kiviniemi (ion)

## Notes

- Hangout link - https://hangouts.google.com/call/gyafa4mpgz7g6jntijoxshfe3ma

- go-libp2p builds now (using gx)
- https://github.com/diasdavid/js-libp2p
- libp2p website update (kyle)
- Update on registry-mirror (david)

- libp2p interface descriptions (juan)
- https://github.com/diasdavid/abstract-peer-routing
- https://github.com/ipfs/specs/blob/master/protocol/network/6-interfaces.md

@jbenet: I pulled the libp2p slides out of my qconf talk 
  https://ipfs.io/ipfs/QmRthja4NnZEwXcUNgTKpX86dtGMQxstMbhgnTzmVhrW4D/libp2p-part/ipfs-018.libp2p-part.pdf

- announce what the end UX is (or what we expect it to be) and get feedback
- look at network simulators

should this be in the agenda, or is it for the github issue:
    - which bits are already stable enough for other teams like py-ipfs to start on?
    - which bits are still in flux so we (py-ipfs team) should approach with caution?
    - which bits are out of sync with the spec so we (py-ipfs) can help write spec as we implement?
    
---
 
 js-ipfs
 
- Help please: https://github.com/ipfs/js-ipfs/pull/35   
- cors-headers blocking, will be in 0.3.10
- js-repo implementation, specs
- btw, Andres Gutgon is doing great progress on ipscend https://github.com/diasdavid/ipscend/issues/2#issuecomment-159011533

js-ipfs-api
- make timeout a global var
- mocha API docs is the way :) https://github.com/ipfs/js-ipfs-api/pull/105

**Comment by RichardLitt** [comment]
My Todos:

- [ ] Enumerate all of the functions that already exist, in ipfs/api
- [ ] Suggest community infrastructure for meetups
- [ ] Make the documentation around Commit Sign-Offs more friendly
- [ ] Add a PR to ipfs.io/docs/api about how the commands there are not all-inclusive.
- [ ] Sprint management.
- [ ] Remove video links from the readme. ipfs/pm/issues/57

**Comment by Dignifiedquire** [comment]
**TODO(@dignifiedquire)**

- [ ] Spec all the APIs

> I am not allowed to commit any code unrelated to spec writing and tooling around that.

**Comment by harlantwood** [comment]
## Testing + CI

#### Lead: @jbenet??? anyobdy else?

## Agenda

- ci dashboard
- go-ipfs heisentests / unreliable test suite 

## Participants

@harlantwood, @lgierth, @jbenet

## Notes

### ci-status

- @harlantwood made http://ipfs.github.io/ci-status/
- roadmap: https://github.com/ipfs/ci-status/issues/1
- It works! check it out: http://ipfs.github.io/ci-status/
- real-time, columns sort
- Would be good to add:
  - stars
  - issues (open / total)
  - PRs (open / total)
- discuss adding project-directory? 
  - dont want to stretch across org boundary, so let's not for now.
- Regarding deployment to ci-status.ipfs.io:
    - @lgierth suggests using IPNS hash for DNS link 
    - thereby no digital ocean keys needed on deploying server 
    - therefore we should be able to deploy from CI, instead of creating a githook handling server, which is simpler
    - store IPFS node private key in Travis or Circle
    
### Random topics
- @lgierth will open a pathway to access the git hash that is deployed on an IPFS gateway

**Comment by harlantwood** [comment]
### @harlantwood

- [ ] keep moving forward on CI Status Board: ipfs/ci-status#1

**Comment by jbenet** [comment]
Frozen from: https://public.etherpad-mozilla.org/p/nov-23-data-structures

## Data Structures
#### Lead: @jbenet
## Agenda

- short intro of POST
- go through inidividual use cases to align perspectives
- @fazo96 ipfs-boards
- @nginnever swarmchan
- https://activestrea.ms
- other "questions" and datastructures
- POST message format
- Extension specs
- Come up with strategy + todos

## Participants
- @davidar
- @diasdavid 
- @Dignifiedquire
- @fazo96
- @harlantwood 
- @jbenet
- @mekarpeles
- @nginnever
- @nicolagreco
- cc @haadcode

## Notes

- POST - https://github.com/ipfs/POST/
- a datastructure to model human communication on top of IPLD (@jbenet)
- keep in mind use cases
- keep in mind value proposition
- notes earlier (between @jbenet and @mekarpeles)
- https://public.etherpad-mozilla.org/p/ipfs-needs
- @harlantwood: check out the activity streams data format:
        - http://activitystrea.ms/
        - http://www.w3.org/TR/activitystreams-core/

Does a POST have some sort of application ID (if there are multiple versions of an application)?

@fazo96 -- ipfs-boards:
- https://github.com/fazo96/ipfs-boards
- all the aggregation is done on the client
- use ipns for all the heads
- personal filters + config per "board"
- similar to haadcode's
- define things in markdown files
- api over ipfs/api to easily grab the data
- **biggest challenge**:
  - aggregation-- boards with 100s of users, speed - CRDT magic!
  - how do i get the posts? the latest? the most interesting?
  - biggest issue: performance.
    - pub/sub would help
    - ipns is slow-- make it faster (pub/sub)
  - privacy concerns
  - DOSing the network

@nginnever -- SwarmChan:
- http://voxelot.us/ipfs/QmdoPvvgxHFBEahCECfSVrq62x9v4JjTr7SWYwuu1tjTrp
- https://github.com/nginnever/swarmchan
- using ethereum for consensus/aggregation
- Problem: centralization
  - being able to fork
  - specifying preferred administration
  - can use IPNS to keep own logs per thread
  - can use ipns hierarchically
  - can aggregate information still
- Problem: secure time
  - dicuss more in depth later
  - use only for UI for now
  - aggregations through ancestry + indexing
  - see also CRDTs
  - calendaring / chandlr

Keychain:
- digital signatures of content
- timestamping into secure time chains
- UI will be paramount

Other Questions -- a set of other datastructures we can parametrize or stub-out. don't need to solve them in POST.
- Keychain
- Identity
- blockchain-related (persona in ethereum)
- http://weboftrust.info (+ DPKI) 
- Sharing
- Groups
- Capabilities (privacy)
- Common Formats
- Time + Secure Time 
- Timestamping
- Notifications
- Forks/branches of the conversation

Important requirements:
- felxible formatting (body various fmts)
- Search:
  - encourage indexing + post-processing that generates 
  more data that links back to original data.
  - various other index trees/structs

IPLD 
- https://github.com/ipfs/specs/blob/ipld-spec/merkledag/ipld.md
- gives you ability to self-describe formats
- can get the types, the parsers, the vms, virtualize all the things
- self-description, virtualization, digital vellum / vint cerf

Large-scale processing 
- for search and other systems
- Centralized processing WITHOUT Central Control
- sub-networks like bitcoin, where users can participate
- still "centralized", but without control over the data

yacy
- https://en.wikipedia.org/wiki/YaCy
- The index can be stored "centrally" in IPFS (IPLD), but how does it get calculated in the first place? (a la SETI at home)



Things to do:
- outline all the abstractions (posts, boards, users, groups, ...) 
- create POST repo and open a issue for each of the *Questions*
- figure out all the specs out there to review (W3C, WebDAV, XMPP, matrix.org, ..., etc)

Other organizations to involve
- W3C (WebDAV, activitystrea.ms) @mekarpeles
- OpenAnnotation @mekarpeles
- matrix.org @davidar
- Diaspora
- XMPP
- &yet https://github.com/fritzy/pie
- HTTP (Roy Fielding, via Whitehead) @mekarpeles
- Ethereum / Persona (Whisper)
- BitMessage, Bleep (bittorent's chat)

TODOs:
- start core + extension spec skeletons:
  - core spec (@jbenet, @mekarpeles)
  - bb/forum ext spec (@fazo96)
  - blog ext spec
  - todo (@mekarpeles)
  - chat ext spec
  - annotation ext spec
  - micro-blog ext spec
  - status updates
  - ToDos
  - Calendar Event/Notification/Invitation
- modalities
  - like / favorite
  - republishing / retweet / reblog
  - replying
  - embedding attachments
  - cite
  - quote
- Note: store things like mentions, citations, etc as IDs so they can be fetched and ranked 


#### stay close to reality: use the apps already being built to play with datastructs and make sure these things are actually good + fun to program with! if not, wont work.


- (see notes from other doc)
- References: map of merkle-links
- link w/ (opt) type [cite | mentions | response | edit]
- OpenAnnotations? See IIIF's spec

**Comment by masylum** [comment]
TODO @masylum

- [ ] Keep working on `js-repo`

**Comment by rht** [comment]
- [ ] Fix `go-ipfs` mem leaks so that only 1 C-c is required to shutdown the daemon

**Comment by whyrusleeping** [comment]
TODO:
- [ ] ipfs-update :ship: 
- [ ] fs-repo-migrations (needs CR to merge)
- [ ] commands lib path argument type
- [ ] write layout and chunking algo to root block of created dags.
- [ ] say "pub sub" out loud three times
- [ ] eat turkey

**Comment by jbenet** [comment]
### jbenet TODOs:

- [ ] CR ipfs-update
- [ ] CR fs-repo-migrations
- [ ] CR @rht's stuff (sorry, my CR is lagging)
- [ ] start draft of POST spec
- [ ] list some pub/sub papers/specs

I'll add some more later today/tomorrow.

**Comment by diasdavid** [comment]
If you feel your task list isn't puffed enough, you can always add this one:
- [ ] Review and give feedback on registry-mirror https://github.com/diasdavid/registry-mirror/issues/10

:D

**Comment by lgierth** [comment]
### @lgierth

- go-ipfs
  - [~] X-Ipfs-Gateway-Prefix hardening ipfs/go-ipfs#1988
  - [~] add commit to :8080/version ipfs/go-ipfs#2002
  - [ ] investigate red builds ipfs/go-ipfs#2001
- infrastructure
  - [~] open up cors on gateways (allow origin *) ipfs/infrastructure#109
  - [x] OVH renewal of castor
  - [x] profile zfs performance
  - [x] enable nosync on castor
  - [ ] test automatic gc (venus, mercury, earth)
- cjdns
  - [~] discover peers from cjdns ipfs/go-ipfs#1316
  - [~] invite to fc00 development (aka go-cjdns) https://github.com/fc00/spec
- hope
  - [ ] writable gateway
  - [ ] mfs api 500 responses
  - [ ] build a prometheus exporter using :5001

**Comment by diasdavid** [comment]
On the continuous endeavour to improve the libp2p spec, I've summited some PR and categorised issues on the ipfs/specs repo, which would be great if people interested could review :)  https://github.com/ipfs/specs/labels/libp2p

**Comment by jbenet** [comment]
### @jbenet's update

Hey everyone, not sure i can make irc sync this morning. Am pretty sick, and still recovering. I'll try to-- but stayed up late catching up with some stuff. (this week was hosed for me-- between family time, getting sick, and org todos, i didnt have much time for my dev todos)

- [x] CR ipfs-update - https://github.com/ipfs/ipfs-update/issues/4
- [ ] CR fs-repo-migrations -- is this even doable yet? we're not settled in the format for dev0.4.0 repo
- [~] CR @rht's stuff (did some, not all. please list them here if any are pressing)
- [ ] start draft of POST spec
- [~] list some pub/sub papers/specs
- [x] ipfs/ipfs/readme fixes https://github.com/ipfs/ipfs/pull/128
- [x] more on ipld spec https://github.com/ipfs/specs/pull/37
- [x] more on fs-repo spec https://github.com/ipfs/specs/pull/43

---

- [x] out with family for thanksgiving :poultry_leg: 
- [x] got very sick :sick: -- out for a few days

**Comment by Dignifiedquire** [comment]
@jbenet get well soon 😷

**Comment by Dignifiedquire** [comment]
@dignifiedquire update

* [~] http-api spec: https://github.com/ipfs/api/issues/7
* [x] Switch js-ipfs-api to use expect instead of assert https://github.com/ipfs/js-ipfs-api/pull/153

**Comment by diasdavid** [comment]
@jbenet get better soon! 

### SPRINT UPDATE

- libp2p
  - [~]() get Castor juiced up with all of the modules
  - [x] review and merge https://github.com/diasdavid/libp2p-website/pull/3/files
  - [x] add ipscend to libp2p-website https://github.com/diasdavid/libp2p-website/pull/5
  - [x] Write is the libp2p expected UX https://github.com/ipfs/specs/commit/340e98dd1495fe26cf1c78af2c6b6fb86e98e9d8
  - [x] Update and add more detail to the libp2p interfaces https://github.com/ipfs/specs/pull/48
  - [x] Update the libp2p implementations chapter https://github.com/ipfs/specs/pull/49
  - [x] Update libp2p datastructures https://github.com/ipfs/specs/pull/50
- npm on IPFS
  - [x] Clone the MerkleDAG node pointed by Castor IPNS https://github.com/diasdavid/registry-mirror/issues/5
  - [x] modularize https://github.com/diasdavid/registry-mirror/pull/9
  - [x] ~~cry for love~~🎵😜 Ask feedback on https://github.com/diasdavid/registry-mirror/issues/10
  - [ ] collect stats 
    - [x] npm on fs
- ipscend
  - [x] CR and merge https://github.com/diasdavid/ipscend-screenshot-visualizer/pull/1
  - [x] made a blog post http://blog.daviddias.me/2015/11/27/ipscend
  - [x] get in touch with surge people :) 
- js-ipfs-api
  - [x] Set a global timeout variable for mocha tests https://github.com/ipfs/js-ipfs-api/pull/145
  - [x] fix DHT bug on js-ipfs-api https://github.com/ipfs/js-ipfs-api/pull/153
  - [0] Rebase and merge mocha auto generated tests in https://github.com/ipfs/js-ipfs-api/pull/146 (__blocked__ due to identified bug on https://github.com/mochajs/mocha/issues/1978)
- extra
  - [x] travel logistics for Node.js Interactive 
  - [~]() prepare talk for Node.js Interactive (Got slides ready, need to practice and make sure it only takes 20 minutes.. which is soo hard!)

**Comment by RichardLitt** [comment]
### Officially this week:

- [x] Sprint management.
- [x] Remove video links from the readme. Issue: ipfs/pm/issues/57. PR: ipfs/pm/pull/59.
- [x] Add a PR to ipfs.io/docs/api about how the commands there are not all-inclusive. PR: ipfs/website/pull/81.
- [x] Suggest community infrastructure for meetups. Comment: ipfs/community/issues/64#issuecomment-160335959
- [x] Make the documentation around Commit Sign-Offs more friendly. PR ipfs/community/pull/82

#### Extra
- [x] Discussed the Readme doever at length, ending with jbenet's ipfs/ipfs/pull/128.
- [x] Pulled TODOS out of https://github.com/ipfs/ipfs/pull/125 and related threads.
- [x] Remove duplicate, capitalize, change link, and add description to FAQ. PR: ipfs/ipfs/pull/130
- [x] Linked awesome-ipfs in main readme. PR: ipfs/ipfs/pull/131, ipfs/community/pull/83
- [x] Make sure old ipfs/ipfs/FAQ questions are still answered by the current README
- [x] Add a TOC to ipfs/community/README.md, removed project.md. PR: ipfs/community/pull/85
- [x] Removed ipfs/community/issues-guide.md. PR ipfs/community/pull/86
- [x] Clarify sprint process a bit ipfs/pm/pull/62
- [ ] Add HTTP API docs with @Dignifiedquire

**Comment by whyrusleeping** [comment]
- [ ] ipfs-update :ship: 
- [ ] fs-repo-migrations (needs CR to merge)
- [ ] commands lib path argument type
- [ ] write layout and chunking algo to root block of created dags.
- [x] say "pub sub" out loud three times
- [x] eat turkey
- [x] provide-many mechanism, yay bandwidth savings!

**Comment by lgierth** [comment]
My week was kinda dominated by the NPM import (a.k.a. registry-mirror) and its performance issues. On the other hand got a couple of smaller things done. Also got p2p/discovery/cjdns.go to work, (it's lovely,) just need to add tests.

- npm
  - [x] enable nosync on dev040 nodes ipfs/infrastructure@ca1454a
  - [x] test registry-mirror
  - [x] profile zfs performance on castor
  - [x] start mirroring on pollux too
- go-ipfs
  - [~] RFM X-Ipfs-Gateway-Prefix hardening ipfs/go-ipfs#1988
  - [~] RFM add commit to :8080/version ipfs/go-ipfs#2002
  - [x] test automatic gc with @rht ipfs/infrastructure#125
  - [ ] investigate red builds ipfs/go-ipfs#2001
  - [ ] test fs-repo-migrations
- infrastructure
  - [x] open up cors on gateways (allow origin *) ipfs/infrastructure#109
  - [x] OVH renewal of castor
  - [x] increase metrics retention ipfs/infrastructure@49295a9
  - [x] reactivate logs from all docker containers ipfs/infrastructure#127
- cjdns
  - [~] discover peers from cjdns (todo: tests) ipfs/go-ipfs#1316
  - [~] invite to fc00 development (aka go-cjdns) https://github.com/fc00/spec
- hope
  - [ ] writable gateway
  - [ ] files api response status codes
  - [ ] ~~build a prometheus exporter using :5001~~

**Comment by lgierth** [comment]
Sorry for my lack of presence :( not cool to be absent without any notice

**Comment by rht** [comment]
Merging https://github.com/ipfs/go-ipfs/pull/1964 & https://github.com/ipfs/go-ipfs/pull/1973 are needed to unclog distributed archival of content larger than 50 GB (e.g. wikipedia), otherwise it takes ages for those who attempted.

**Comment by RichardLitt** [comment]
thanks @lgierth: no worries. :)
