### ISSUE TITLE
Sprint Nov 30

### ISSUE THREAD

**Issue by diasdavid** [ipfs/pm#60]
# Sprint Nov 30

## Sprint Goals

- Make registry-mirror really nice for Node.js Interactive

## Sprint Discussions

[Schedule](https://github.com/ipfs/pm#sprint-discussion-schedule)

Please take notes in a separate pad, if you can, and link it here.

Endeavour         | Lead           | Pad    | Permanent Link
:---------------: | :------------: | :----: | :------------:
Apps on IPFS      | Juan Benet and Friedel Ziegelmayer | https://public.etherpad-mozilla.org/p/nov-30-apps-on-ipfs |  
infrastructure    | Lars Gierth    | https://public.etherpad-mozilla.org/p/nov-30-infrastructure |  
libp2p            | David Dias     | https://public.etherpad-mozilla.org/p/nov-30-libp2p |  
js-ipfs         | David Dias     | https://public.etherpad-mozilla.org/p/nov-30-js-ipfs |  
go-ipfs           | Jeromy Johnson | https://public.etherpad-mozilla.org/p/nov-30-go-ipfs | 
testing + ci      | Jeromy Johnson | https://public.etherpad-mozilla.org/p/nov-30-testing-ci |  
protocol + specs  | Juan Benet     | https://public.etherpad-mozilla.org/p/nov-30-protocol-specs |  
bitswap ml        | Juan Benet     | https://public.etherpad-mozilla.org/p/nov-30-bitswap-ml |  
Data Structures   | Juan Benet     | https://public.etherpad-mozilla.org/p/nov-30-data-structures |  

Please add the Agenda to the Pad before the endeavour sprint starts.

## Sprint Deliverables

- Add yourself below, that way we only have people listed who are really in the sprint
- Add links to issues down here. Only add things you can finish this sprint.

## @diasdavid

This week I'll be focusing mostly on:
  - Getting registry-mirror really nice
  - Practice and Polish talk
  - Being a prof (have to give classes full day on Tuesday and Thursday

Tasks:
- libp2p
- js-ipfs
- npm on IPFS
  - [ ] Automate "update IPNS process" for Castor https://github.com/diasdavid/registry-mirror/issues/4
  - [ ] collect stats
    - [x] npm on fs
    - [ ] npm on ipfs
    - [ ] npm on ipfs with ipfs tar
    - [ ] npm on ipfs with rabin
    - [ ] time registry.npmjs.org to registry-mirror

### @lgierth

- infrastructure
  - [x] castor support
  - [ ] ipv6 for gateway and swarm ipfs/infrastructure#88
  - [ ] order yubikeys ipfs/infrastructure#122
  - [x] ~~automatic OVH renewal~~
- cjdns
  - [~] discover peers from cjdns (todo: tests) ipfs/go-ipfs#1316
  - [~] invite to fc00 development (aka go-cjdns) https://github.com/fc00/spec
- go-ipfs
  - [~] investigate red builds ipfs/go-ipfs#2001
  - [ ] gateway prefix hardening https://github.com/ipfs/go-ipfs/pull/1988/files#r46498115
  - [ ] test fs-repo-migrations
  - [ ] files api response status codes
  - [~] RFM assets: fix gc example ipfs/go-ipfs#2029
- hope
  - writable gateway ipfs/infrastructure#105
  - build a prometheus exporter using :5001

**Comment by diasdavid** [comment]
@ipfs/pm please add your Agenda items to the etherpads for tomorrow

@ipfs/contributors if you have any question or contribution you would like to bring to one of the discussions, you are very welcome to add them to the agenda so that we don't miss them

Thank you :)

**Comment by kyledrake** [comment]
- [ ] work on libp2p-website improvements
- [ ] data persistence guide for IPFS site
- [ ] preparations for BW talk and panel
- [ ] S3 integration research and testing

I may be late for the sprint. I just wanted to say it would be great to see an update to the proposed S3 library if it wasn't too much work, to give an idea of performance. Some optimizations (such as local caching of hash keys) may be needed.

**Comment by whyrusleeping** [comment]
- [ ] ipfs-update :ship: 
- [ ] fs-repo-migrations (needs CR to merge)
- [ ] commands lib path argument type
- [ ] write layout and chunking algo to root block of created dags.
- [x] say "pub sub" out loud three times
- [x] eat turkey
- [x] provide-many mechanism, yay bandwidth savings!

**Comment by whyrusleeping** [comment]
- [ ] ipfs-update :ship: 
- [ ] fs-repo-migrations (needs CR to merge)
- [ ] commands lib path argument type
- [ ] write layout and chunking algo to root block of created dags.
- [x] say "pub sub" out loud three times
- [x] eat turkey
- [x] provide-many mechanism, yay bandwidth savings!

**Comment by RichardLitt** [comment]
## This Week
- [ ] Spec out http api `bootstrap` api/issues/7
- [ ] Spec out http api `cat` api/issues/7
- [ ] Make community/pull/65 work again
- [ ] Try out registry-mirror/issues/10, and specs/labels/libp2p
- [ ] Make sure that each IPFS repository has a README.
- [ ] Find the old Copyright stuff community/issues/79
- [ ] Spring management

**Comment by diasdavid** [comment]
## libp2p

#### Lead: David Dias

## Agenda

- new specs PRs
- interface bikeshedding
- welcome to new contributions
- python libp2p update
- CI
- libp2p website

**You have 30 minutes for this agenda**, 5 minutes before the meeting ends, consider moving the remaining items to a github discussion thread so that all the other sprint meetings can start in time.

## Participants

## Notes

- libp2p Interfaces bikeshedding needed
  - https://github.com/ipfs/specs/pulls

- go-libp2p
- Get vendoring nice (week Nov 30)
- Separated by repos (week Nov 30)

- we need a libp2p example demo
- simple chat app (perhaps)
- something really simple that can be used in go-libp2p and js-libp2p

- all of libp2p discussions
 https://github.com/ipfs/specs/labels/libp2p

Update https://github.com/ipfs/specs/pull/49/files to list all the current implementations of each module directly https://github.com/ipfs/specs/pull/49/files#discussion_r46009100

- "Jeromy coffee talks" start on Wednesday

**Comment by whyrusleeping** [comment]
## go-ipfs

#### Lead: @whyrusleeping

## Agenda

- ipfs update
  - ipfs dists

- 0.3.10
  - once it merges, master is frozen for 0.4.0

- provideMany
  - saves lots of bandwidth, yay!

- providing roots sooner
  - may not be needed right now, but later on, using a stack would be good
  - normally, when you add a huge dag, we provide in-order, which means we provide the root last. on the other hand when you request a dag, you request from the root-- this creates a big lag between "finished adding" and "starting to download"

- bitswap path notation
  - @jbenet still working on language
  - @whyrusleeping onboard mysteriously

- TODO this week:
- ipfs update
- dist.ipfs.io
- content headers (go-ipfs#1979)
- ndjson fix (js-ipfs-api#135)
- ship 0.3.10 !!!!!!!


**You have 30 minutes for this agenda**, 5 minutes before the meeting ends, consider moving the remaining items to a github discussion thread so that all the other sprint meetings can start in time.

## Participants

## Notes

also-- are we providing roots sooner yet?

we talked about this in the past and we figured we could provide the root as soon as we see it-- or more generally, provide with a stack
but each stack is separate-- meaning that a new dag should still be provided after the previous one
ok
maybe one goroutine per dag added?
im still coming up with a language
yeah-- more generally, there
there's "an agent" that decides what to do at all times.
like-- there's more, agents that may optimistically download more to share it
let's add all of this to notes-- hangout almost over
we can probably go over a bit--
- wait-- lets get notes for go-ipfs

Perhaps serve kind of sharded views of the wantlist to peers. For any given object in the wantlist, start by telling just one peer about it and add further peers when it seems like the current ones are not managing to send anything. –ion

##### After sprint meeting is finished, create the respective action items on the Github sprint issue

**Comment by diasdavid** [comment]
## js-ipfs

#### Lead: David Dias

## Agenda

- js-ipfs-repo
- finish that spec
- js-ipfs-api
- HTTP API spec
- move to Chai
- js-ipfs
- HTTP API spec
- Writable gateways https://github.com/ipfs/js-ipfs/pull/35#issuecomment-160182079
- Hangouts with Jeromy™


**You have 30 minutes for this agenda**, 5 minutes before the meeting ends, consider moving the remaining items to a github discussion thread so that all the other sprint meetings can start in time.

## Participants

## Notes

js-ipfs-repo
- https://github.com/ipfs/js-ipfs/issues/36
- https://github.com/ipfs/js-ipfs-repo/pull/1
- spec https://github.com/ipfs/specs/issues/41
- spec PR https://github.com/ipfs/specs/pull/43
- [ ] @whyrusleeping specifiy params of flatfs (width and depth) for IPFS Repo

js-ipfs-api
js-ipfs
- Finish apiary for /api/v0 https://github.com/Dignifiedquire/ipfs-http-api
- Jeromy Coffee Talks will help get this more quickly
- cp /api/v0 /api/v1 
- upgrade the /api/v1 from there
     - fix https://github.com/ipfs/js-ipfs-api/issues/135

note from hangout chat - js-ipfs-api + delegated node (writable node in the network //cc @lgierth) would work today to get a "JS IPFS Node" running on a browser, however, for us to commit to any kind of specific IPFS interface (the one that we 'promise' not to break), we will the the API + HTTP spec solified //cc @jbenet 

##### After sprint meeting is finished, create the respective action items on the Github sprint issue

**Comment by Dignifiedquire** [comment]
## Apps on/with IPFS

#### Lead: Juan Benet and Friedel Ziegelmayer

## Agenda

- ipscend
- registry-mirror
- http-api

## Participants

- David Dias (@diasdavid)
- Friedel Ziegelmayer (@dignifiedquire)
- Johan Kiviniemi
- Con Fiks

## Notes

### ipscend

- Nice interface: https://github.com/diasdavid/ipscend/issues/2#issuecomment-159011533
- Need versioning in IPFS for the next steps
- Reaching out to surge (http://surge.sh/)

### registry-mirror

- Still cloning
- Make it more efficient by first downloading and then adding, rather than adding on the fly (space issues)

### http-api


### Links from the chat

- https://github.com/diasdavid/ipscend/issues/2#issuecomment-159011533
- https://github.com/ipfs/notes/issues/23
- https://www.npmjs.com/package/registry-mirror
- https://github.com/ipfs/api/issues/7
- http://docs.ipfs.apiary.io/#
- https://github.com/ipfs/notes/issues/64


### Recorded Stream
http://youtu.be/m2dDOtp1PK4

**Comment by lgierth** [comment]
- infrastructure
  - [ ] writable gateway ipfs/infrastructure#105
  - [ ] automatic OVH renewal
- cjdns
  - [~] discover peers from cjdns (todo: tests) ipfs/go-ipfs#1316
  - [~] invite to fc00 development (aka go-cjdns) https://github.com/fc00/spec
- go-ipfs
  - [ ] investigate red builds ipfs/go-ipfs#2001
  - [ ] test fs-repo-migrations
  - [ ] files api response status codes
- hope
  - [ ] build a prometheus exporter using :5001

**Comment by Dignifiedquire** [comment]
- [ ] More spec work for http-api
- [ ] Make ipfs/distributions pretty
- [ ] Look at improving ipfs/dataviz

**Comment by whyrusleeping** [comment]
- [ ] libp2p vendor pathing fixes
  - fix pathing in gx itself first
- [ ] ipfs/go-ipfs#1966
- [ ] ipfs-update tests and feedback
- [ ] osx test failuires
- [ ] dist.ipfs.io work
- [ ] ipfs files perf for @diasdavid

**Comment by rht** [comment]
@whyrusleeping https://github.com/ipfs/go-ipfs/pull/1966 -> https://github.com/ipfs/go-ipfs/pull/2021

**Comment by harlantwood** [comment]
Coming in late...

- [ ] push first version of http://ipfs.github.io/ci-status/ to some-subdomain.ipfs.io, using ipns, from CI.
- [ ] ongoing work on IPFS based app: Core Network -- dokku on digital ocean pushing nodejs proxy to IPFS serving threejs front end.  Pic: https://ipfs.io/ipfs/QmPPhwiGnspjYkAdjrf9qReuGxt9hXRFYVitsdiGn46TcD

**Comment by Dignifiedquire** [comment]
### Sprint Update for @dignifiedquire

- [~] Work on ipfs/distributions
  - [~] Design https://github.com/ipfs/distributions/issues/11
  - [~] Implementation https://github.com/Dignifiedquire/distributions/tree/fresh
- [~] Windows CI for go-ipfs (https://github.com/ipfs/go-ipfs/pull/2042)

**Comment by diasdavid** [comment]
## SPRINT UPDATE

This last week was filled by registry-mirror, Node.js Interactive and being giving classes (which took full Tuesday and Thursday)

- [x] Delivering Computation for the Web classes
- npm on IPFS
  - [x] Got demo working + video (with extra router, antenas and everything, it is pretty sweet I think)
  - [x] Add npm to IPFS stravaganza. Much <3 to @whyrusleeping @lgierth and @jbenet for being super present and offloading some of their time to help me get things going faster
  - [x] ~70000 modules on Castor
  - [~] Adding complete npm on Pollux 
  - [~] Adding complete npm in @whyrusleeping machine with ipfs --chunker=rabin
- node interactive
  - [x] preparation of talk  
  - [x] flights + logistics

**Comment by RichardLitt** [comment]
Update.

Some community and pr management this week, but didn't get to do all the things I had hoped to do. Better placed as of this morning to do more work on the API - thanks dig.

## This Week
- [x] Make ipfs/community/pull/65 work again
- [~] Spec out http api `bootstrap` ipfs/api/issues/7
- [ ] Spec out http api `cat` ipfs/api/issues/7
- [ ] try out diasdavid/registry-mirror/issues/10, and ipfs/specs/labels/libp2p
- [ ] Make sure that each IPFS repository has a README.
- [ ] Find the old Copyright stuff ipfs/community/issues/79
- [~] Sprint Management

## Extra
- [x] Added IRC to ipfs/pm list of people ipfs/pm/pull/64
- [x] Proposed shift in sprint todos list ipfs/pm/issues/65
- [x] Edited sprint master's role ipfs/pm/pull/66

**Comment by kyledrake** [comment]
- [X] work on libp2p-website improvements
- [~] data persistence guide for IPFS site
- [ ] preparations for BW talk and panel
- [X] S3 integration research and testing

Will be reviewing the libp2p site with David while he's in town this week.

**Comment by whyrusleeping** [comment]
- [ ] libp2p vendor pathing fixes
  - [x] fix pathing in gx itself first
- [ ] ipfs-update tests and feedback
- [ ] osx test failuires
- [ ] dist.ipfs.io work
- [x] ipfs files perf for @diasdavid 
- [x] fix go-peerstream deadlock (jbenet/go-peerstream#21)
got completely sidetracked and ended up just making ipfs add really fast:
- [x] ipfs add superfast

**Comment by jbenet** [comment]
### Sprint update for @jbenet

- [x] stellar talk with dm
- [x] call with &yet re apps/post
- [x] discussion with openbazaar
- [x] various org things
- [x] prog-fs demo https://github.com/jbenet/prog-fs
- [x] go-reuseport bugfix https://github.com/jbenet/go-reuseport/pull/11
- [x] AppVeyor setup https://github.com/ipfs/go-ipfs/pull/2042
- [x] Space issue: discuss, move stuff for @daviddias, monitor
- [x] Code Review + Merges:
  - [x] CR https://github.com/ipfs/go-ipfs/pull/2039
  - [x] CR https://github.com/ipfs/go-ipfs/pull/2037
  - [x] CR https://github.com/ipfs/go-ipfs/pull/2032
  - [x] CR https://github.com/ipfs/go-ipfs/pull/2019
  - [x] CR https://github.com/ipfs/go-ipfs/pull/2019
  - [x] CR+M https://github.com/jbenet/go-peerstream/pull/21
  - [x] CR+M https://github.com/ipfs/go-ipfs/pull/2040
  - [x] CR+M https://github.com/ipfs/go-ipfs/pull/2029
  - [x] CR+M https://github.com/ipfs/go-ipfs/pull/2020
  - [x] CR+M https://github.com/ipfs/go-ipfs/pull/2010
  - [x] CR+M https://github.com/ipfs/go-ipfs/pull/2007
  - [x] CR+M https://github.com/ipfs/go-ipfs/pull/2001
  - [x] CR+M https://github.com/ipfs/go-ipfs/pull/2000
  - [x] CR+M https://github.com/ipfs/go-ipfs/pull/1999

**Comment by lgierth** [comment]
### @lgierth sprint update

Lots if interruptions this sprint -- NPM and storage in general are on a good way now,
discovery-cjdns is working too (lacks tests).

- infrastructure
  - [x] castor support
  - [x] castor/npm firefighting
  - [ ] ipv6 for gateway and swarm ipfs/infrastructure#88
  - [x] order yubikeys ipfs/infrastructure#122
  - [x] order 2 more hetzner storage hosts
  - [x] ~~automatic OVH renewal~~
- cjdns
  - [~] discover peers from cjdns (todo: tests) ipfs/go-ipfs#1316
  - [~] invite to fc00 development (aka go-cjdns) https://github.com/fc00/spec
- go-ipfs
  - [~] investigate red builds ipfs/go-ipfs#2001
  - [ ] gateway prefix hardening https://github.com/ipfs/go-ipfs/pull/1988/files#r46498115
  - [ ] test fs-repo-migrations
  - [ ] files api response status codes
  - [~] RFM assets: fix gc example ipfs/go-ipfs#2029
- hope
  - writable gateway (blocked) ipfs/infrastructure#105
  - build a prometheus exporter using :5001

**Comment by jbenet** [comment]
@rht could you drop an update here for your stuff this week?

**Comment by harlantwood** [comment]
Sprint update

- [x] ongoing work on IPFS based app: [Core Network](https://github.com/core-network/core-network)
- [ ] push first version of http://ipfs.github.io/ci-status/ to some-subdomain.ipfs.io, [using ipns, from CI] __(not yet, but hope: soon)__
