### ISSUE TITLE
Sprint Dec 7

### ISSUE THREAD

**Issue by RichardLitt** [ipfs/pm#67]
## Sprint Goals

- Push 0.3.10
- Completed IPFS API Spec (core + transports) by Jan 1

## Sprint Discussions

[Schedule](https://github.com/ipfs/pm#sprint-discussion-schedule)

Please take notes in a separate pad, if you can, and link it here.

Endeavour         | Lead           | Pad   
:---------------: | :------------: | :----:
Apps on IPFS      | Juan Benet     |          https://public.etherpad-mozilla.org/p/dec-7-apps-on-ipfs 
infrastructure    | Lars Gierth    |          https://public.etherpad-mozilla.org/p/dec-7-infrastructure 
libp2p            | David Dias     |          https://public.etherpad-mozilla.org/p/dec-7-libp2p 
js-ipfs         | David Dias     |         https://public.etherpad-mozilla.org/p/dec-7-js-ipfs 
go-ipfs           | Jeromy Johnson |          https://public.etherpad-mozilla.org/p/dec-7-go-ipfs 
api      | Juan Benet |          https://public.etherpad-mozilla.org/p/dec-7-api 
Please add the Agenda to the Pad before the endeavour sprint starts.

## Sprint Deliverables

- Add your tasks below in a comment, that way we only have people listed who are really in the sprint
- Add links to issues down here. Only add things you can finish this sprint.

**Comment by chriscool** [comment]
@RichardLitt you mean "Dec 7", not "Nov 7", right?

**Comment by jbenet** [comment]
i changed the sprint title -- @RichardLitt maybe fix the sprint pad urls

**Comment by RichardLitt** [comment]
D'oh!

**Comment by Dignifiedquire** [comment]
Shouldn't we drop the perma link column? or what purpose does it serve now?

**Comment by RichardLitt** [comment]
Doesn't serve any, could be dropped.

**Comment by lgierth** [comment]
deleting the comments re: sprint title and permalink column

**Comment by lgierth** [comment]
## Infrastructure

#### Lead: lgierth

## Agenda

- ops levelup
- writable gateway
- more hetzner hosts
- distributions

## Participants

- @lgierth
- @dignifiedquire
- @jbenet
- @diasdavid

## Notes

- issues tracking for ops requests
  - repo /ipfs/ops-request
  - lars might revisit waffle/trello
- writable gateway PR needs CR https://github.com/ipfs/go-ipfs/pull/1917
- storage
  - hetzner nodes not today
  - one host needed for ipfs tar add test
  - no more OVH hosts, we're moving away from that
  - get an ec2 instance for daviddias

**Comment by Dignifiedquire** [comment]
## Apps On IPFS

#### Lead: @dignifiedquire

## Agenda

### Station
- How to get people to contribute more, as @dignifiedquire needs help
- station bugs (crash on exit)

### Package Managers
- npm on IPFS - registry-mirror
- Pacman

### Pub/Sub

### Webui

### Thoughts on ipscend?

### ipfs/distributions (moved to infrastucture)

### Core Network

## Participants

- Friedel Ziegelmayer (@dignifiedquire)
- David Dias (@diasdavid)
- Harlan T Wood (@harlantwood)
- Juan (@jbenet)

## Notes

### Station
- road to 1.0.0 https://github.com/ipfs/station/milestones/1.0.0
- [ ] finishing the packaging
- pick the right architecture for each package
- [ ] make sure that it always runs (not everyone are having the same experience)
- [ ] `ipfs-install` npm module
- pick a version and a path where to install the IPFS binary from gobuilder (instead of using go-ipfs, which always install in a postinstall script IPFS for the current architecture)
- something like require('ipfs-install')(<version>, <path>)
- make a strategy about how to handle multiple IPFS installations
- detail strategy about running/installed daemons in https://github.com/ipfs/station/issues/19

### Package Managers
- npm on IPFS
- Still wip
- Large overhead when adding all the npm modules (merkle dag links)
- Using a trie (hacky way from @jbenet)
- write a issue with learnings from this experience (challenges seen when adding all of this data)

### Webui
- Update
  - Merge internationalizations
- [ ] Detail in an issue ways to update the webui independent of go-ipfs

### Core Network
- Visual demo
- source: https://github.com/core-network/client
- Interested in what emerges from POST format
- Interested in collaborating with others doing similar apps

**Comment by diasdavid** [comment]
## libp2p

#### Lead: David Dias

## Agenda

- vendoring go-libp2p (separed by repos)
- specs 
https://github.com/ipfs/specs/labels/libp2p
- libp2p website
- define plan for this week sprint
- websockets transport

**You have 30 minutes for this agenda**, 5 minutes before the meeting ends, consider moving the remaining items to a github discussion thread so that all the other sprint meetings can start in time.

## Participants

- David Dias


## Notes

go-libp2p
- vendoring is "on going"
- Jeromy is solving multipart issue, which gx uses and blocks the vendoring from go-libp2p/separate it on smaller repos

- This week plan
  - Make demos
    - connecting two peers using swarm for a chat app
    - Using the DHT to find peers 
    - Store a record 
    - make go-libp2p and js-libp2p swarm interop demo
  - update interfaces from `abstract` to `interface`
  - interop between go-libp2p-swarm and js-libp2p-swarm
  - very full roadmap for libp2p, js-ipfs, go-ipfs

**Comment by diasdavid** [comment]
## js-ipfs

#### Lead: David Dias

## Agenda

- specs
- ipfs-repo https://github.com/ipfs/specs/pull/43 <-
- http-api
- define plan for this week sprint

## Participants

- David Dias

## Notes

roadmap
  milestone 0.1.0 - js-ipfs with delegated nodes
    - writable gateways
    ipfs-repo
    IPLD - update to the latest state of IPLD spec
    IPRS - 
    DagStore
    IPLD store on top ipfs-repo
    a config 
    Importer
        How to turn a file into a DAG (normal, tar, rabin)

"delegated node can't delegate its identity"

- This week plan
- Writable gateways
- Ship js-ipfs with writable gateways and a 'unstable interface' warning, as it m

**Comment by lgierth** [comment]
### @lgierth

- infrastructure
  - [ ] bootstrap new storage hosts (nihal and biham)
    - An-Nihal -- The camels quenching their thirst (https://en.wikipedia.org/wiki/Beta_Leporis)
    - S'ad al-Biham -- Lucky Star of the Young Beasts (https://en.wikipedia.org/wiki/Theta_Pegasi)
  - [ ] ops-requests repo
  - [ ] gandi account
  - [ ] start moving domains
- cjdns
  - [~] discover peers from cjdns (todo: tests) ipfs/go-ipfs#1316
  - [~] invite to fc00 development (aka go-cjdns) https://github.com/fc00/spec
- go-ipfs
  - [ ] gateway prefix hardening https://github.com/ipfs/go-ipfs/pull/1988/files#r46498115
  - [ ] test fs-repo-migrations
  - [ ] files api response status codes
- hope
  - ipv6 for gateway and swarm ipfs/infrastructure#88
  - writable gateway (blocked) ipfs/infrastructure#105

**Comment by diasdavid** [comment]
### David Dias TODO

libp2p
  - [ ] write throughout roadmap
  - demos
    - [ ] connecting two peers using swarm for a chat app
    - [ ] Using the DHT to find peers
    - [ ] store a record
    - [ ] make go-libp2p and js-libp2p swarm interop demo
  - [ ] update `abstract` to `interface` 
js-ipfs
  - [ ] write throughout roadmap  
npm-on-ipfs
  - stats
    - [ ] ipfs
    - [ ] ipfs tar
    - [ ] ipfs with rabin
    - [ ] ipfs tar with rabin
extra
  - [ ] Deliver talk at Node.js Interactive

**Comment by harlantwood** [comment]
@harlantwood todo:

- [ ] https://github.com/ipfs/ci-status/issues/8 subdomain bikeshedding
- [ ] @jbenet or someone plz make me an admin of the https://github.com/ipfs/ci-status repo (requested a month ago: https://github.com/ipfs/ci-status/issues/2#issuecomment-155534142)
- [ ] https://github.com/ipfs/ci-status/issues/9 push first version of CI build board to some-subdomain.ipfs.io

**Comment by RichardLitt** [comment]
My todos:

## This Week
- [ ] Spec out http api `bootstrap` ipfs/api/issues/7 Dignifiedquire/ipfs-http-api/pull/1
- [ ] Spec out http api `cat` ipfs/api/issues/7
- [ ] Make sure that each IPFS repository has a README.
- [ ] Find the old Copyright stuff ipfs/community/issues/79
- [ ] Sprint Management

**Comment by whyrusleeping** [comment]
- [x] ship 0.3.10
- [x] ship super fast [~~jellyfish~~](https://www.youtube.com/watch?v=G6zPvkP5uVI) add
- [ ] take a deep breath

**Comment by eminence** [comment]
Hi all.  As an experiment, I'd like to make the following proposal:

At the end of this sprint (next Monday), try to pick 1 thing that you accomplished that you would like to call attention to.  I think a simple annotation with an asterisk will do (though if you want to say a few things about it, feel free).  The idea is that someone (I volunteer for this sprint) will gather these things together and produce a short summary/blog designed to be read by the wider IPFS community (not just people closely following development).  This idea is modeled after https://this-week-in-rust.org/.

It will be TDB how to publish this summary/blog, but perhaps we can make use http://ipfs.io/blog/ or another repo in the ipfs org.  Let's start simple, get feedback, and iterate!

If you have any idea on this idea itself, I think it might be best to discuss elsewhere (as not to go off topic in this issue).  I am `achin` on IRC.

Thanks!

**Comment by RichardLitt** [comment]
I think this is a great idea! I'd be happy to help write these up, too. Let's open an issue for discussion.

**Comment by Dignifiedquire** [comment]
- [ ] ipfs/distributions

**Comment by lgierth** [comment]
removing the roundup comments in favor of #73 -- @RichardLitt just to keep this issue concise

**Comment by RichardLitt** [comment]
## Update

### This Week
- [x] Spec out http api `bootstrap`. PR Dignifiedquire/ipfs-http-api/pull/1
- [x] Spec out http api `cat`. PR Dignifiedquire/ipfs-http-api/pull/2
- [x] Make sure that each IPFS repository has a README. PR examples/pull/42, CR py-ipfs/pull/22
- [x] Find the old Copyright stuff. community/issues/79
- [x] Sprint Management

###  Also Done
- [x] Limit video quality. PR pm/pull/70
- [x] Update ipfs-update readme. PR ipfs-update/pull/6
- [x] Weigh in on distro page. Comment distributions/issues/11
- [x] Moved api specs around. specs/pull/51 api/pull/12
- [x] Added images to contributing. community/pull/89
- [x] Closed go-ipfs/issues/1706.
- [x] Opened PR for api: Speced out add, put, config, daemon, and dht so far. PR api/pull/13

**Comment by Dignifiedquire** [comment]
### Update

- [~] ipfs/distributions (https://github.com/ipfs/distributions/pull/19 and https://github.com/ipfs/distributions/pull/14)
- [~] rust-multiaddr (https://github.com/Dignifiedquire/rust-multiaddr)

**Comment by lgierth** [comment]
### @lgierth sync update

Bouncing between all kinds of different tasks, but got through it okay

- infrastructure
  - [x] bootstrap new storage hosts (nihal and biham) ipfs/infrastructure#135
    - An-Nihal -- The camels quenching their thirst (https://en.wikipedia.org/wiki/Beta_Leporis)
    - S'ad al-Biham -- Lucky Star of the Young Beasts (https://en.wikipedia.org/wiki/Theta_Pegasi)
  - [x] ops-requests repo ipfs/ops-requests#2
  - [x] gandi account
  - [ ] ~~start moving domains~~
  - [x] go-ipfs 0.3.10 and go1.5.2 ipfs/infrastructure#131
  - [x] project-repos.ipfs.io ipfs/ci-status#9
  - [x] ipfs.io/blog ipfs/blog#11
  - [~] more dev040 bootstrappers ipfs/ops-requests#3
- cjdns
  - [~] ~~discover peers from cjdns (todo: tests) ipfs/go-ipfs#1316~~
  - [~] ~~invite to fc00 development (aka go-cjdns) https://github.com/fc00/spec~~
- go-ipfs
  - [ ] gateway prefix hardening https://github.com/ipfs/go-ipfs/pull/1988/files#r46498115
  - [ ] test fs-repo-migrations
- hope
  - ~~files api response status codes~~
  - ~~writable gateway (blocked) ipfs/infrastructure#105~~

**Comment by whyrusleeping** [comment]
- [x] ship 0.3.10
- [x] ship super fast add
- [x] fix ipfs-update install issue (#8)
- [x] improve flatfs query speed
- [x] misc gx work

**Comment by diasdavid** [comment]
### David Dias Check In

- libp2p
  - [x] Roadmap https://github.com/ipfs/pm/pull/72
  - demos
    - [x] connecting two peers using swarm https://github.com/diasdavid/js-libp2p/pull/3
  - [x] update `abstract` to `interface` 
    - peer-routing 
    - record-store 
    - connection
    - transport
    - stream-muxer
  - specs Implementations merge https://github.com/ipfs/specs/pull/49
  - specs Interfacesmerge https://github.com/ipfs/specs/pull/48
- js-ipfs
  - [x] Wrote a Roadmap https://github.com/ipfs/pm/pull/71 which lead me to update https://github.com/ipfs/js-ipfs. I would prefer to merge both, but it is definitely nice to understand what is the list of all the things that need to be done and the subset of those that are our core priority
  - js-ipfs-repo - refactor js-ipfs-repo to enable a new Arch + implement locks 
    - https://github.com/masylum/js-ipfs-repo/pull/1
    - https://github.com/ipfs/js-ipfs-repo/pull/2
    - https://github.com/ipfs/js-ipfs-repo/pull/10
    - https://github.com/ipfs/js-ipfs-repo/issues/9 
    - locks https://github.com/ipfs/js-ipfs-repo/pulls
  - [x] `$ jsipfs id` https://github.com/ipfs/js-ipfs/pull/39
  - [x] `$ jsipfs version` 
  - [x] `$ jsipfs repo version`
- npm-on-ipfs
  - stats - I was unable to get any stats as I am always filling up disks 'disk full'. I'm using now straight registry-mirror on Pollux, so that I can pause and resume anywhere and not be surprised by a massive overhead from ipfs add -r
  - [x] write issue with learnings (post mortem analysis) made with registry-mirror
  - [x] transfer out repos from aws and stop that machine
  - [x] blog post for registry-mirror http://blog.daviddias.me/2015/12/08/stellar-module-management
- extra
  - [x] Deliver talk at Node.js Interactive
  - [x] cp blog posts to ipfs/blog https://github.com/ipfs/blog/pull/10
  - [x] improve blog posts - https://github.com/ipfs/blog/pull/12
  - [x] Jeromy Coffee Talks
  - [x] 32c3 + NYE + Berlin Logistics

**Comment by jbenet** [comment]
### @jbenet update

- [x] :star: made dnslink tool: https://github.com/jbenet/go-dnslink
- [x] added gobuilder to go-ipfs release checklist
- [x] bumped new go-ipfs gobuilder builds to start
- [x] bump go-ipfs travis-ci to go1.5.2
- [x] blog fixing, reverting stellar modules post
- [x] temp go-ipfs asciinema https://github.com/ipfs/distributions/issues/17
- [x] gobuilder dl badge https://github.com/Luzifer/gobuilder/issues/67
- [x] npm-on-ipfs last push
- [x] dist progress and PRs
- Code Review + Merges:
  - [x] CR + M https://github.com/ipfs/go-ipfs/pull/1961
  - [x] CR + M https://github.com/ipfs/go-ipfs/pull/2048
  - [x] CR + M https://github.com/ipfs/go-ipfs/pull/2049
  - [x] CR + M https://github.com/ipfs/go-ipfs/pull/2019
  - [x] CR + M https://github.com/ipfs/go-ipfs/pull/2041
  - [x] CR + M https://github.com/ipfs/go-ipfs/pull/2065
  - [x] CR + M https://github.com/ipfs/go-ipfs/pull/2066
  - [x] CR + M https://github.com/ipfs/specs/pull/51
  - [x] CR + M https://github.com/ipfs/api/pull/9
  - [x] CR + M https://github.com/ipfs/fs-repo-migrations/pull/9
  - [x] CR + M https://github.com/ipfs/blog/pull/14
  - [x] CR + M https://github.com/ipfs/distributions/pull/14
  - [x] CR + M https://github.com/ipfs/npm-go-ipfs/pull/5
  - [x] CR + M https://github.com/ipfs/ipfs-update/pull/10
  - [x] CR + M https://github.com/jbenet/go-datastore/pull/34
  - [x] CR https://github.com/ipfs/blog/pull/15
  - [x] CR https://github.com/ipfs/blog/pull/10
  - [x] CR https://github.com/ipfs/blog/pull/12
  - [x] CR https://github.com/ipfs/distributions/pull/19
- Discussions
  - [x] :star: pacman https://github.com/ipfs/notes/issues/84
  - [x] files api mount https://github.com/ipfs/go-ipfs/issues/2060
  - [x] blocks wrapping https://github.com/ipfs/go-ipfs/issues/2053
  - [x] https://github.com/ipfs/faq/issues/81
  - [x] https://github.com/ipfs/faq/issues/82
  - [x] some ipfs-users posts

**Comment by harlantwood** [comment]
@harlantwood update

@harlantwood todo:

- [x] https://github.com/ipfs/ci-status/issues/8 subdomain bikeshedding
- [x] get admin on the https://github.com/ipfs/ci-status repo 
- [~] https://github.com/ipfs/ci-status/issues/9 push first version of CI build board to some-subdomain.ipfs.io
