### ISSUE TITLE
Sprint F

### ISSUE THREAD

**Issue by jbenet** [ipfs/pm#7]
**Sprint Goals** 

1. Wire protocol + interop with node
2. FIx all these bugs!

**Sprint Participants**:

- @whyrusleeping @krl @cryptix @wking @dylanPowers @jbenet

### **Sprint Deliverables**

- Bugs to fix:
  - [ ] https://github.com/ipfs/go-ipfs/issues/1082 @wking
  - [ ] https://github.com/ipfs/go-ipfs/issues/1050 @cryptix
  - [ ] https://github.com/ipfs/go-ipfs/issues/964 @whyrusleeping
  - [x] https://github.com/ipfs/go-ipfs/issues/1150 @cryptix
  - [ ] Better resolution tests (@jbenet, @whyrusleeping)
  - [x] merge @chriscool's PR (@jbenet)
  - [ ] http://godoc.org/net/http#CloseNotifier (@cryptix)
  - [x] https://github.com/jbenet/go-peerstream/issues/5 (@jbenet)

- webui
  - [x] https://github.com/ipfs/webui/issues/42 (@krl)
  - [ ] https://github.com/ipfs/webui/issues/43 (@krl)

- interop with node
  - [x] Protocol wire spec (@jbenet)
  - [ ] swapping out the stream muxer (or having multiplex in go) (@jbenet)
  - [ ] option (or build) to disable encryption for interop with node (@whyrusleeping)

- perf/bugs:
  - [x] change the memory profiling (@whyrusleeping)
  - [ ] save memory profile + binary to ipfs (@whyrusleeping)

- Specs / scoping out
  - [ ] DHT spec (@jbenet)
  - [ ] Keystore spec (@jbenet, @whyrusleeping)

- Blog
  - [x] make blog (@jbenet)
  - [x] prep hello world post (@jbenet)
  - [x] add blog to website (@jbenet)

### backlog

- [ ] github.com/krl/ipfs-geoip - we need to add attribution for the GeoLite data in the webui as well.
- [ ] https://github.com/ipfs/webui/issues/20
- [ ] https://github.com/ipfs/go-ipfs/issues/1179 (waiting for archive)
- [ ] https://github.com/ipfs/webui/issues/41 (needs better definition on what we want to do with files (without names) in the webui)
- [ ] https://github.com/ipfs/webui/issues/38 (involved)

- make it easy to work with gateways 
  - [ ] remove docker, init script, auto-rebooting (@jbenet) 
  - [ ] cpu + mem profiling on gateways (@whyrusleeping)
  - [ ] change nginx to do fallback (not round robin) (@jbenet)

- [ ] make all adds add to an object representing local state
- [ ] scope out init + daemon sprint (@jbenet)
- [ ] reimplement goprocess without mem leak (@whyrusleeping)
- [ ] Address memory leak (likely culprit is goprocess)
- [ ] json encoding for add (@travisperson)

- specs:
  - [ ] shell / core api
  - [ ] scoping out how signed binaries + autoupdate will work (@jbenet)
  - [ ] scope out how testing will be done on both webui and api (@travisperson, @jbenet)

**Comment by cryptix** [comment]
Fixed as well:
- [x] ipfs/go-ipfs#1202
- [x] ipfs/go-ipfs#1209

**Comment by jbenet** [comment]
Merged many PRs this week, so far:
- https://github.com/ipfs/go-ipfs/pull/1193
- https://github.com/ipfs/go-ipfs/pull/1194
- https://github.com/ipfs/go-ipfs/pull/1198
- https://github.com/ipfs/go-ipfs/pull/1199
- https://github.com/ipfs/go-ipfs/pull/1200
- https://github.com/ipfs/go-ipfs/pull/1202
- https://github.com/ipfs/go-ipfs/pull/1205
- https://github.com/ipfs/go-ipfs/pull/1206
- https://github.com/ipfs/go-ipfs/pull/1209
- https://github.com/ipfs/go-ipfs/pull/1189
- https://github.com/ipfs/go-ipfs/pull/1212 (important hotfix, thanks @wking!) 
- https://github.com/ipfs/webui/pull/47
- https://github.com/ipfs/webui/pull/45
- https://github.com/ipfs/webui/pull/44
- https://github.com/ipfs/node-ipfs-api/pull/15

**Comment by cryptix** [comment]
The `putHandler` of the writable gateway ate a lot of time.. In oder to fix ipfs/go-ipfs#1150 now, we decided to disable it and it's sharness tests (`t0111-writeable-gateway.sh`) and fix the PUT method next week.

**Comment by jbenet** [comment]
I also cut the 0.3.4 release, cause it was time pressing the get these bugs fixed for users in a way they could feel sure about the fix (ipfs version). 




Will be updating changelog later today (unless someone beats me to it).



—

**Comment by jbenet** [comment]
hey all -- would be great if you could:
- list all the thins that got fixed / worked on this week
- take a look at the assigned things and see where they are (maybe write any needed notes here)
- comment about the things you'd like to see pulled into the next sprint(s). 

we can use this as a way to pre-discuss the status, and the things desired things for the next sprint. 

cc @whyrusleeping @cryptix @tv42 @krl @travisperson @dylanPowers

**Comment by cryptix** [comment]
Sprint F


I got hung up on the PUT handler  while working on #1091 and didn't make any meaningful progress on the others I wanted to work on.

I commented on #1050 about my findings and suggestions for proceeding with it.

The `http.CloseNotifier` addition is fairly easy and I'd like to pull it over to next week.

**Comment by whyrusleeping** [comment]
I don't recall everything I got done, but I diagnosed a bitswap perf issue and am working on a significant refactor to address the problem, low bandwidth this week with moving out.

**Comment by jbenet** [comment]
- published blog: http://ipfs.io/blog (maybe it should be blog.ipfs.io ?? and use CNAME trick?) 
- Made several updates to website (added examples, added blog, ...) and [published new version](http://gateway.ipfs.io/ipfs/Qmb8tKfz3RFiasE5yoaaU3d4CF7SaCEh8h2z3g6ZoYGvw6/)

**Comment by tv42** [comment]
I've been redoing the pinning so that it stores data in IPFS objects. I have the first version of that about working, but need to do a series of commits first to clean up pinning bugs and API warts, and then make the relevant sharness tests be less explicit as they used to dictate behavior not results. I don't expect the actual code to change much for this iteration, anymore.

**Comment by jbenet** [comment]
Participants of Sprint F: could you look over the unchecked boxes above and point out anything that should be checked? (i'll go through these with people when we check in, too).

**Comment by jbenet** [comment]
Addressed the handshake / listener issue in https://github.com/ipfs/go-ipfs/pull/1227
