### ISSUE TITLE
Sprint Dec 21

### ISSUE THREAD

**Issue by RichardLitt** [ipfs/pm#76]
# Sprint Dec 21

## Sprint Goals

- Completed IPFS API Spec (core + transports) by Jan 1

## Sprint Discussions

[Schedule](https://github.com/ipfs/pm#sprint-discussion-schedule)

Please take notes in a separate pad, if you can, and link it here.

Endeavor          | Lead           | Time (PDT - **UTC/Z** - CET) | Pad
:---------------: | :------------: | :--------------------------: |  :----:
Apps on IPFS      | Juan Benet     | 10:30PDT **18:30Z** 19:30CET | https://public.etherpad-mozilla.org/p/ipfs-dec-21-apps-on-ipfs 
libp2p            | David Dias     | 11:30PDT **19:30Z** 20:30CET | https://public.etherpad-mozilla.org/p/ipfs-dec-21-libp2p 
js-ipfs           | David Dias     | 12:00PDT **20:00Z** 21:00CET | https://public.etherpad-mozilla.org/p/ipfs-dec-21-js-ipfs 

Please add the Agenda to the Pad before the endeavor sprint starts.

## Sprint Deliverables

- Add your tasks below in a comment, that way we only have people listed who are really in the sprint
- Add links to issues down here. Only add things you can finish this sprint.

**Comment by whyrusleeping** [comment]
## @whyrusleeping todo
- [ ] ipfs/go-ipfs#2032
- [ ] distributions build ourselves

**Comment by diasdavid** [comment]
## Apps on IPFS

#### Lead: dignifiedquire and diasdavid

## Agenda

- station
- webui
- npm on ipfs
  - Improving update process
  - 100K modules mark :D

**You have 30 minutes for this agenda**, 5 minutes before the meeting ends, consider moving the remaining items to a github discussion thread so that all the other sprint meetings can start in time.

## Participants

## Notes

### Station

- ipfs-geoip is unstable (unusable)
  - crashes webui + station https://www.npmjs.com/package/ipfs-geoip
  - how to repro the bug
  - add tests (please)
- drag and drop issue
  - tray still works
  - dragging to the window breaks (react!!!!)
- shrinkwrap was added (because everyone having different experiences while running)
- use a repo+ipfs binary+js-ipfs-api bundle strict for station and do not attempt to use what is already available (while js-ipfs-api is still chasing ipfs HTTP APi and ipfs is chasing IPFS Repo)
  - http://electron.atom.io/docs/v0.36.0/api/app/#app-getpath-name
  - make an action item for this

http://standards.freedesktop.org/basedir-spec/basedir-spec-latest.html

> $XDG_DATA_HOME defines the base directory relative to which user specific data files should be stored. If $XDG_DATA_HOME is either not set or empty, a default equal to $HOME/.local/share should be used.
> $XDG_CONFIG_HOME defines the base directory relative to which user specific configuration files should be stored. If $XDG_CONFIG_HOME is either not set or empty, a default equal to $HOME/.config should be used.
> $XDG_CACHE_HOME defines the base directory relative to which user specific non-essential data files should be stored. If $XDG_CACHE_HOME is either not set or empty, a default equal to $HOME/.cache should be used.

The norm is to use a subdirectory named after your application under each one.

https://www.npmjs.com/package/xdg-basedir

### Webui

- In order to support the multitude of webui + js-ipfs-api versions and to suport fast update on already released IPFS versions, we will
  - have webui.ipfs.name pointing to the latest hash of webui
  - have webui-0310.ipfs.name pointing to the hash respective to webui for 0.3.10 (and other subdomains for respective hashes of other versions)
  - each published version is tagged on github
  - we only support bug fixes and new features in latest 
- We need tests (really, webui is so old, go-ipfs should have integration tests before it is released)

Help: https://github.com/ipfs/webui/issues/90 and https://github.com/ipfs/webui/issues/87

**Comment by diasdavid** [comment]
## libp2p

#### Lead: David Dias

## Agenda

- needs to happen: bikeshed libp2p interfaces:
  - https://github.com/diasdavid/js-libp2p-swarm#usage
  - https://github.com/diasdavid/interface-transport
  - https://github.com/diasdavid/interface-connection
  - https://github.com/diasdavid/interface-stream-muxer
  - https://github.com/diasdavid/interface-record-store (less urgent)
  - https://github.com/diasdavid/interface-peer-routing (less urgent)
- factoring go-libp2p
- transports:
    - utp https://github.com/diasdavid/js-libp2p/issues/7
    - udt https://github.com/diasdavid/js-libp2p/issues/8
- crypto channels:
    - https://github.com/diasdavid/js-libp2p/issues/10
    - https://github.com/diasdavid/js-libp2p/issues/9

**You have 30 minutes for this agenda**, 5 minutes before the meeting ends, consider moving the remaining items to a github discussion thread so that all the other sprint meetings can start in time.

## Participants

## Notes

- bikeshed glossary (bikespec)
- 19:34 <@whyrusleeping> my only input on libp2p is that i have vendoring working a lot better, and will push the changes to gx for that very soon

- some of the discussion items will be revisited again on when go-ipfs hangout happens this week

- [ ] Write Captain.log entry

##### After sprint meeting is finished, create the respective action items on the Github sprint issue

**Comment by diasdavid** [comment]
## js-ipfs

#### Lead: David Dias

## Agenda

- levelDB repo https://github.com/ipfs/js-ipfs-repo/issues/21
- `ipfs init` https://github.com/ipfs/js-ipfs/issues/42
- IPLD
  - specs for Importers, Layouts and Chunkers https://github.com/ipfs/js-ipfs/issues/41#issuecomment-164370167
  - directory sharding https://github.com/ipfs/specs/issues/32
- Exchange
  - Bitswap spec https://github.com/ipfs/specs/pull/53
  - Need a clear path how we are deciding to make all of this Interop (protobuf + IPLD) (more context https://github.com/ipfs/js-ipfs-repo/issues/13#issuecomment-165044619)

**You have 30 minutes for this agenda**, 5 minutes before the meeting ends, consider moving the remaining items to a github discussion thread so that all the other sprint meetings can start in time.

## Participants

## Notes

- js-ipfs-repo
  - indexedDB is not available everywhere   - http://caniuse.com/#search=indexdb probable polyfill ontop of websql http://nparashuram.com/IndexedDBShim/
  - there are polyfills (indexedDB interface on WebSQL)
  - we need this https://github.com/ipfs/js-ipfs-repo/issues/21


- some of the discussion items will be revisited again on when go-ipfs hangout happens this week

- [ ] Write Captain.log entry

**Comment by diasdavid** [comment]
###  David Dias TODO

- npm on IPFS
    - [ ] Try `ipfs add -r` with Rabin again with latest 0.4.0 on Jeromy Machine
    - [ ] Check with Jeromy when ipfs tar -r will be ready
    - [ ] Improve installation process, with ipfs update (check with Jeromy) https://github.com/diasdavid/registry-mirror/issues/24
- js-ipfs-api
  - [ ] Update feat/files-api https://github.com/ipfs/js-ipfs-api/pull/74#discussion_r48093673
- libp2p
    - [ ] TLS
    - [ ] uTP
- (hope) ipfs levelDOWN
  - https://github.com/ipfs/notes/issues/72
- extra
  - [ ] Celebrate Christmas 🎄🎅

**Comment by RichardLitt** [comment]
## To Do
- [x] Sprint Management
- [ ] QC the API PR
- [ ] Write the weekly roundup

**Comment by whyrusleeping** [comment]
I would like to note that the next sprint meeting will be on January 4th, 2016. We not be having a sprint meeting on the 28th of December due to @jbenet being in middle earth, and most of the rest of us being at 32C3. Have a wonderful holiday everyone!

**Comment by lgierth** [comment]
@lgierth TODO

- dev0.4.0
  - [ ] discuss migration strategy
  - [ ] more dev0.4.0 bootstrappers
- go-ipfs
  - [x] RFM remove dead jenkins code ipfs/go-ipfs#2114
  - [x] labeled all pull requests
- infrastructure
  - [~] empty and scrub sirius and castor

**Comment by diasdavid** [comment]
### SPRINT CHECKIN

- npm on IPFS
    - [x] Work and test with @whyrusleeping to registry-mirror working nicely with the latest features of 0.4.0 (no flush on mkdir and write). Start again registry-mirror on Biham (130000 modules and going strong)
- js-ipfs-api
  - [x] Update feat/files-api to latest 0.4.0 https://github.com/ipfs/js-ipfs-api/pull/74#discussion_r48093673
  - [x] CR https://github.com/ipfs/js-ipfs-api/pull/177/files
- webui
  - [x] CR https://github.com/ipfs/webui/pull/130
- libp2p
    - [x] Wrote interop tests for uTP https://github.com/diasdavid/utp. 
- js-ipfs
  - js-ipfs-data-importing
    - [~] Data Importing spec https://github.com/ipfs/specs/pull/57
    - [x] Fixed-Size-Chunker https://github.com/ipfs/js-ipfs-data-importing/tree/feat/chunker-fixed-size
  - [~] exchange spec https://github.com/ipfs/specs/pull/53
- extra
  - [x] Celebrate Christmas 🎄🎅
  - [x] 32c3 and all of the awesomeness 
  - [x] Intensive travel logistics (specially with all the detours)
  - [x] "The great go-ipfs issue party of 2016"
  - [~] Working to get 6 extra IPFS nodes in the machines I've available at Univ
  - [x] Interesting discussions with Tahoe-LAFS people and what we can build together

**Comment by RichardLitt** [comment]
## This Week

Uh, I did a lot this past two weeks. Largely this is because I went through a ton of repos - see the last thing - and tried to clean a lot of them up.  Lots of triaging, commenting, CR, and a ton of small PRs. So, the main things to take away: The API is basically at  a standstill, because I can't get anyone to CR it and to help me out with figuring out whether it is a spec or a mirror of what is possible. Also, our community weekly roundups are a failure at the moment, due to a lack of community involvement. This week, I plan to change that by writing up something, and just publishing it after a day of review, regardless if anyone finds time to review it. 

A LOT of these PRs are still open: if they are linked, it would be good if people could CR them. 

- [x] Sprint Management
  - [x] Prepare sprint, sync lead, follow up with people
  - [x] Remove Dec 28 sprint from Calendar
  - [x] Moved sprint to Jan 5th from Jan 4th
- [x] Write the weekly roundup. PR ipfs/weekly/pull/4. **Need**: We need to do this as a community. So far, two have been written, and none published.
- [x] QC the API PR. (Needs to be redone, again, pending conversations happening in the issues.)

## Extra
- Awesome-IFPS
  - [x] Embedded awesome-ipfs into ipfs/website. PR website/pull/84
  - [x] Added note about dates to awesome-ipfs contrib.
  - [x] Added webapps to awesome-ipfs. PR awesome-ipfs/pull/35
  - [x] Added apps from community/issues/12. PR awesome-ipfs/pull/37. Closes community/issues/12.
- community
  - [x] Added a swag section to ipfs/community. PR community/pull/91, ipfs/community/issues/11, ipfs/community/issues/50
  - [x] Set up Javascript guideline files community/issues/59. PR community/pull/92
  - [x] Change 'freejs' to 'freenode' on all repos. community/issues/93
- dnslink-deploy
  - [x] Added hash validifier for dnslink-deploy. PR dnslink-deploy/pull/8
  - [x] Added license, shields, contribute section
- project-repos
  - [x] Change project-repos to not have checks and crosses project-repos/issues/18. PR project-repos/pull/20
  - [x] Added contribute section. PR project-repos/pull/31
- webui
  - [x] Convert all bootstrap components to use react-bootstrap webui/issues/140. PR webui/pull/142
  - [x] webui readme webui/issues/141. PR webui/pull/147
  - [x] Added log. PR webui/pull/160
- go-ipfs
  - [x] Added quotes around command in go-ipfs long description. PR go-ipfs/pull/2157
  - [x] Added a shutdown note to `ipfs daemon` long description. PR go-ipfs/pull/2159
- random
  - [x] Edited ipfs project dir for readability. PR ipfs/pull/142
  - [x] Changed log in ipfs-update. Closed ipfs-update/issues/13 with PR ipfs-update/pull/15.
  - [x] Edited data example. PR examples/pull/44
  - [x] Downgrading IPFS doc for fs-repo-migrations. PR fs-repo-migrations/pull/10.
  - [x] Added note about spec issues and PRs. PR specs/pull/56, closes specs/issues/39
  - [x] Added FAQ link to ipfs.io/docs. PR website/pull/86
- New modules
  - [x] Worked on ipfs-readme-standards by creating [remark-title](https://github.com/RichardLitt/remark-title) and finalising a [roadmap](ipfs-readme-standard/issues/1)
  - [x] Created react-linkhandler module. https://github.com/RichardLitt/react-linkhandler
- Code Review
  - [x] CR+M awesome-ipfs/pull/34
  - [x] CR+M ipfs/examples/pull/21
  - [x] CR+M webui/pull/156
  - [x] CR+M webui/pull/155
  - [x] CR examples/pull/40
  - [x] CR ipfs/pull/84
  - [x] CR webui/pull/130
- Just Comments
  - [x] Numbering examples examples/issues/4
  - [x] Republishing examples examples/issues/13
  - [x] Attempted to close, on our Sprint system community/issues/28
  - [x] Webui new build system webui/issues/87
  - [x] Changing the checks and crosses on project-repos project-repos/issues/18
  - [x] Add a list of non-IPFS organization repos to check project-repos/issues/21
  - [x] API docs api/issues/1
  - [x] API Spec => Specs Repo api/issues/11
- Closed these old issues:
  - [x] awesome-ipfs/issues/28,  ipfs/issues/79,  examples/issues/,  community/issues/15,  community/issues/63,  community/issues/62,  api/issues/,  website/issues/35,  website/issues/43,  website/issues/7,  website/issues/77
- End-of-year Cleanup, finding relevant issues that I can do fast or close. This mostly means find them and document them internally for fixing later.
  - [x] Repos: ipfs/pm, ipfs/community, ipfs/specs, ipfs/examples, ipfs/awesome-ipfs, ipfs/ipfs, ipfs/weekly, ipfs/dnslink-deploy, ipfs/infrastructure, ipfs/starlog, ipfs/blog, ipfs/webui, ipfs/api, ipfs/website, ipfs/project-repos

**Comment by jbenet** [comment]
I'm back from NZ travels. lots of fun pictures coming later :)

**Comment by lgierth** [comment]
### @lgierth sprint update

- 32c3!!!
- infrastructure
  - [x] decomission castor ipfs/infrastructure#143
  - [x] * set up namaka and hiiaka (NUC nodes at our table at 32c3) ipfs/infrastructure#142
  - [x] regenerate hetzner SSH host keys in response to advisory http://wiki.hetzner.de/index.php/Ed25519/en
  - [~] write post mortem about this ^ https://github.com/ipfs/ops-private
  - [~] set up osx buildbot worker for Zooko/Tahoe
- go-ipfs
  - [x] pull request triage (tagging)
  - [ ] dev040 migration plan
- fc00
  - [x] discuss ehmry's cryptoauth spec draft with cjd
  - [~] continue cryptoauth spec https://github.com/fc00/spec/compare/master...cryptoauth-notes
  - [~] start switch spec https://github.com/fc00/spec/compare/master...switch

**Comment by RichardLitt** [comment]
## Sprint Summary @dignifiedquire

### Webui

* [Improve Build Process (webpack, hot reloading and test setup)](https://github.com/ipfs/webui/pull/130)
* [refactor: Improve style setup](https://github.com/ipfs/webui/pull/152)
* [feat: Replace `console.log` with `debug`](https://github.com/ipfs/webui/pull/155)
* [refactor: Upgrade to `react-router@2`](https://github.com/ipfs/webui/pull/156)
* [WIP fix and refactor `view/object.js`](https://github.com/ipfs/webui/pull/166)
* Continue work on new design for the webui
* [Discuss webui release plan with @whyrusleeping and @diasdavid](https://github.com/ipfs/webui/issues/167)
* CR
  * https://github.com/ipfs/webui/pull/160
  * https://github.com/ipfs/webui/pull/158
  * https://github.com/ipfs/webui/pull/147
  * https://github.com/ipfs/webui/pull/143
  * https://github.com/ipfs/webui/pull/142 

### JS-IPFS-API

* Refactor `add` to drop `vinyl`, resulting in a minified bundle size reduction of a 100Kb [PR 1](https://github.com/ipfs/js-ipfs-api/pull/179) [PR 2](https://github.com/ipfs/js-ipfs-api/pull/180) This fixed the before broken multipart upload for recursive uploads (`0.4.0` only though)

### Rust libp2p

* Release [rust-multiaddr](https://github.com/Dignifiedquire/rust-multiaddr)
* Release [rust-multihash](https://github.com/Dignifiedquire/rust-multihash)

### Misc

* Start downloading https://archive.org/download/stackexchange to add to IPFS

### Events

* Meetup with @lgierth @diasdavid @whyrusleeping and many more at 32C3 in Hamburg

**Comment by whyrusleeping** [comment]
- [x] CCC
- [x] berlin shenanigans
- [x] improve performance of files api for registry mirror
- [x] met lots of peoples
- [x] mass issue cleanup with @diasdavid 
- [x] refactored object patch to not embed data in url
- [x] added testing for http requests so we can ensure the cmds lib is right
- [x] began prep for 0.3.11 release and subsequent 0.4.0 merge to master
- [x] reenabled ipns sharness tests
- [x] gx is nearly ready for prime time
- [x] wrote libp2p swarm demo for daviddias
- [x] fixed race condition in go-datastore
