### ISSUE TITLE
Sprint January 5th

### ISSUE THREAD

**Issue by RichardLitt** [ipfs/pm#77]
# Sprint January 5th

## Sprint Goals

TBD

## Sprint Discussions

[Schedule](https://github.com/ipfs/pm#sprint-discussion-schedule)

Please take notes in a separate pad, if you can, and link it here.

Endeavour         | Lead           | Time (PDT - **UTC/Z** - CET) | Pad
:---------------: | :------------: | :--------------------------: | :----:
Apps on IPFS      | Juan Benet     | 10:30PDT **18:30Z** 19:30CET | https://public.etherpad-mozilla.org/p/ipfs-jan-5-apps-on-ipfs
api | Richard Littauer | 11:00PDT **19:00Z** 20:00CET | https://public.etherpad-mozilla.org/p/ipfs-jan-5-api
libp2p            | David Dias     | 11:30PDT **19:30Z** 20:30CET | https://public.etherpad-mozilla.org/p/ipfs-jan-5-libp2p
js-ipfs         | David Dias     | 12:00PDT **20:00Z** 21:00CET | https://public.etherpad-mozilla.org/p/ipfs-jan-5-js-ipfs
go-ipfs           | Jeromy Johnson | 12:30PDT **20:30Z** 21:30CET | https://public.etherpad-mozilla.org/p/ipfs-jan-5-go-ipfs

### January 6th, Wednesday

Infrastructure has been moved to Wednesday due to @lgierth not being able to make Tuesday.

Endeavour         | Lead           | Time (PDT - **UTC/Z** - CET) | Pad
:---------------: | :------------: | :--------------------------: | :----:
infrastructure    | Lars Gierth    | 11:00PDT **19:00Z** 20:00CET | https://public.etherpad-mozilla.org/p/ipfs-jan-6-infrastructure

Please add the Agenda to the Pad before the endeavour sprint starts.

## Sprint Deliverables

- Add your tasks below in a comment, that way we only have people listed who are really in the sprint
- Add links to issues down here. Only add things you can finish this sprint.

---
**Before edit**: Is it ok if we switch the sprint to Tuesday this week, so that @jbenet can make it? Please let us know here.

**Comment by Dignifiedquire** [comment]
Fine with me

**Comment by kyledrake** [comment]
That works better for me too, I'm heading back on Monday.

**Comment by lgierth** [comment]
I'll be visiting my grandma all of tuesday (she's turning 80) -- we can do infrastructure on wednesday?

**Comment by diasdavid** [comment]
SGTM :)

**Comment by RichardLitt** [comment]
@lgierth Infrastructure on Wednesday sounds fine to me. Same time?

**Comment by RichardLitt** [comment]
Alright. Sprint officially moved to January 5th. 

![](http://www.reactiongifs.us/wp-content/uploads/2013/03/so_say_we_all1.gif)

**Comment by RichardLitt** [comment]
## This Week

- [x] Sprint Management
  - [x] Prepare sprint, sync lead, follow up with people
  - [x] Remove Dec 28 sprint from Calendar
  - [x] Moved sprint to Jan 5th from Jan 4th
- [x] Write the weekly roundup. PR ipfs/weekly/pull/4. **Need**: We need to do this as a community. So far, two have been written, and none published.
- [x] QC the API PR. (Needs to be redone, again, pending conversations happening in the issues.)

## Extra
- Awesome-IFPS
  - [x] Embedded awesome-ipfs into ipfs/website. PR website/pull/84
  - [x] Added note about dates to awesome-ipfs contrib.
  - [x] Added webapps to awesome-ipfs. PR awesome-ipfs/pull/35
  - [x] Added apps from community/issues/12. PR awesome-ipfs/pull/37. Closes community/issues/12.
- community
  - [x] Added a swag section to ipfs/community. PR community/pull/91, ipfs/community/issues/11, ipfs/community/issues/50
  - [x] Set up Javascript guideline files community/issues/59. PR community/pull/92
  - [x] Change 'freejs' to 'freenode' on all repos. community/issues/93
- dnslink-deploy
  - [x] Added hash validifier for dnslink-deploy. PR dnslink-deploy/pull/8
  - [x] Added license, shields, contribute section
- project-repos
  - [x] Change project-repos to not have checks and crosses project-repos/issues/18. PR project-repos/pull/20
  - [x] Added contribute section. PR project-repos/pull/31
- webui
  - [x] Convert all bootstrap components to use react-bootstrap webui/issues/140. PR webui/pull/142
  - [x] webui readme webui/issues/141. PR webui/pull/147
  - [x] Added log. PR webui/pull/160
- go-ipfs
  - [x] Added quotes around command in go-ipfs long description. PR go-ipfs/pull/2157
  - [x] Added a shutdown note to `ipfs daemon` long description. PR go-ipfs/pull/2159
- random
  - [x] Edited ipfs project dir for readability. PR ipfs/pull/142
  - [x] Changed log in ipfs-update. Closed ipfs-update/issues/13 with PR ipfs-update/pull/15.
  - [x] Edited data example. PR examples/pull/44
  - [x] Downgrading IPFS doc for fs-repo-migrations. PR fs-repo-migrations/pull/10.
  - [x] Added note about spec issues and PRs. PR specs/pull/56, closes specs/issues/39
  - [x] Added FAQ link to ipfs.io/docs. PR website/pull/86
- New modules
  - [x] Worked on ipfs-readme-standards by creating [remark-title](https://github.com/RichardLitt/remark-title) and finalising a [roadmap](ipfs-readme-standard/issues/1)
  - [x] Created react-linkhandler module. https://github.com/RichardLitt/react-linkhandler
- Code Review
  - [x] CR+M awesome-ipfs/pull/34
  - [x] CR+M ipfs/examples/pull/21
  - [x] CR+M webui/pull/156
  - [x] CR+M webui/pull/155
  - [x] CR examples/pull/40
  - [x] CR ipfs/pull/84
  - [x] CR webui/pull/130
- Just Comments
  - [x] Numbering examples examples/issues/4
  - [x] Republishing examples examples/issues/13
  - [x] Attempted to close, on our Sprint system community/issues/28
  - [x] Webui new build system webui/issues/87
  - [x] Changing the checks and crosses on project-repos project-repos/issues/18
  - [x] Add a list of non-IPFS organization repos to check project-repos/issues/21
  - [x] API docs api/issues/1
  - [x] API Spec => Specs Repo api/issues/11
- Closed these old issues:
  - [x] awesome-ipfs/issues/28,  ipfs/issues/79,  examples/issues/,  community/issues/15,  community/issues/63,  community/issues/62,  api/issues/,  website/issues/35,  website/issues/43,  website/issues/7,  website/issues/77
- End-of-year Cleanup, finding relevant issues that I can do fast or close. This mostly means find them and document them internally for fixing later.
  - [x] Repos: ipfs/pm, ipfs/community, ipfs/specs, ipfs/examples, ipfs/awesome-ipfs, ipfs/ipfs, ipfs/weekly, ipfs/dnslink-deploy, ipfs/infrastructure, ipfs/starlog, ipfs/blog, ipfs/webui, ipfs/api, ipfs/website, ipfs/project-repos

**Comment by Dignifiedquire** [comment]
## Sprint Summary @dignifiedquire

### Webui

* [Improve Build Process (webpack, hot reloading and test setup)](https://github.com/ipfs/webui/pull/130)
* [refactor: Improve style setup](https://github.com/ipfs/webui/pull/152)
* [feat: Replace `console.log` with `debug`](https://github.com/ipfs/webui/pull/155)
* [refactor: Upgrade to `react-router@2`](https://github.com/ipfs/webui/pull/156)
* [WIP fix and refactor `view/object.js`](https://github.com/ipfs/webui/pull/166)
* Continue work on new design for the webui
* [Discuss webui release plan with @whyrusleeping and @diasdavid](https://github.com/ipfs/webui/issues/167)
* CR
  * https://github.com/ipfs/webui/pull/160
  * https://github.com/ipfs/webui/pull/158
  * https://github.com/ipfs/webui/pull/147
  * https://github.com/ipfs/webui/pull/143
  * https://github.com/ipfs/webui/pull/142 

### JS-IPFS-API

* Refactor `add` to drop `vinyl`, resulting in a minified bundle size reduction of a 100Kb [PR 1](https://github.com/ipfs/js-ipfs-api/pull/179) [PR 2](https://github.com/ipfs/js-ipfs-api/pull/180) This fixed the before broken multipart upload for recursive uploads (`0.4.0` only though)

### Rust libp2p

* Release [rust-multiaddr](https://github.com/Dignifiedquire/rust-multiaddr)
* Release [rust-multihash](https://github.com/Dignifiedquire/rust-multihash)

### Misc

* Start downloading https://archive.org/download/stackexchange to add to IPFS

### Events

* Meetup with @lgierth @diasdavid @whyrusleeping and many more at 32C3 in Hamburg

**Comment by whyrusleeping** [comment]
- [x] CCC
- [x] berlin shenanigans
- [x] improve performance of files api for registry mirror
- [x] met lots of peoples
- [x] mass issue cleanup with @diasdavid 
- [x] refactored object patch to not embed data in url
- [x] added testing for http requests so we can ensure the cmds lib is right
- [x] began prep for 0.3.11 release and subsequent 0.4.0 merge to master
- [x] reenabled ipns sharness tests
- [x] gx is nearly ready for prime time
- [x] wrote libp2p swarm demo for daviddias
- [x] fixed race condition in go-datastore

**Comment by lgierth** [comment]
- 32c3!!!
- infrastructure
  - [x] decomission castor ipfs/infrastructure#143
  - [x] * set up namaka and hiiaka (NUC nodes at our table at 32c3) ipfs/infrastructure#142
  - [x] regenerate hetzner SSH host keys in response to advisory http://wiki.hetzner.de/index.php/Ed25519/en
  - [~] write post mortem about this ^ https://github.com/ipfs/ops-private
- go-ipfs
  - [x] pull request triage (tagging)
- fc00
  - [x] discuss ehmry's cryptoauth spec draft with cjd
  - [~] continue cryptoauth spec https://github.com/fc00/spec/compare/master...cryptoauth-notes
  - [~] start switch spec https://github.com/fc00/spec/compare/master...switch

**Comment by jbenet** [comment]
I'm back from NZ travels. lots of fun pictures coming later :)

**Comment by diasdavid** [comment]
## Apps on IPFS

#### Lead: @jbenet, @Dignifiedquire

## Agenda

- registry-mirror
- waiting on 0.4.0 rc-1
- python-ipfs-api
  - needs to get updated to know how to use the Files-API
  - unblock https://github.com/ipfs/notes/issues/93
- webui
- Release Process https://github.com/ipfs/webui/issues/167
- station
- plan for 1.0.0
- bundle IPFS daemon + js-ipfs-api to avoid avoc of version incompatibility (also use $HOME/.ipfs-station as default repo)


**You have 30 minutes for this agenda**, 5 minutes before the meeting ends, consider moving the remaining items to a github discussion thread so that all the other sprint meetings can start in time.

## Participants

- @jbenet
- @whyrusleeping
- @richardlitt
- @diasdavid

## Notes

- registry-mirror plans
- post install script

- Tahoe-LAFS using IPFS as a Storage Backend
- https://github.com/ipfs/notes/issues/93

- webui
- release channels
- https://github.com/ipfs/webui/issues/167
- match webui to API versions

- station
- bundle and ship 🚢

TODOs:
- ask py-ipfs team to help get python-ipfs-api updated
- outline pros of tahoe/ipfs integrations
- pick up tor+ipfs work (cc david415)
- latest vs stable webui comments (@jbenet) in https://github.com/ipfs/webui/issues/167

**Comment by diasdavid** [comment]
## IPFS API

#### Lead: Richard Littauer

## Agenda

- API spec and API functionality disparity https://github.com/ipfs/api/issues/14
"It's hard, because I'm not always sure whether something is either not fully specified in the CLI, not available as an easy curl request and I can't make it work, not available at all in go-ipfs (but it should be), or simply something that shouldn't be in the API (why would you want a daemon to run, for instance?). I'm still not sure how to adequately answer this question for these cases."
- Moving to Specs Repo https://github.com/ipfs/api/issues/11
- Adding curl to descriptions https://github.com/ipfs/api/pull/13#discussion_r48444217
- Code Review in general https://github.com/ipfs/api/pull/13#discussion_r48444217

**You have 30 minutes for this agenda**, 5 minutes before the meeting ends, consider moving the remaining items to a github discussion thread so that all the other sprint meetings can start in time.

## Participants

- @jbenet
- @whyrusleeping
- @richardlitt
- @diasdavid

## Notes

- CR the API PR https://github.com/ipfs/api/pull/13 (priority)
- move to specs repo
- add curl to descriptions
- Add possibility to have mult langauges (multilang or multisource) for each test case
- add tests
- Move into another branch for spec, current will be in main branch
- @chriscool: see if we can get sharness test for curl
- Go through and standardise formatting for go-ipfs helps
- Make sure headers and everything is cool

**Comment by diasdavid** [comment]
## libp2p

#### Lead: David Dias

## Agenda

- go-libp2p 
- has been factored and vendoring works nicely now! :D
- swarm example
- interface bikeshedding
- https://github.com/diasdavid/js-libp2p-swarm#usage
- https://github.com/diasdavid/interface-transport
- https://github.com/diasdavid/interface-connection
- https://github.com/diasdavid/interface-stream-muxer
- https://github.com/diasdavid/interface-record-store (less urgent)
- https://github.com/diasdavid/interface-peer-routing (less urgent)
- transports
- utp
- https://github.com/diasdavid/utp
- https://github.com/anacrolix/utp
- https://github.com/diasdavid/js-libp2p/issues/7
- curveCP https://github.com/diasdavid/js-libp2p/issues/10
- webrtc
- wrtc is broken (still)
- new endeavour to make a full JS impl (awesome!) https://github.com/nickdesaulniers/node-rtc-peer-connection
- connection upgrades
- tls
- secio
- Tahoe-LAFS and libp2p
- https://github.com/ipfs/notes/issues/94
- extra
- does anyone have any input on CurveCP? https://github.com/diasdavid/js-libp2p/issues/10

**You have 30 minutes for this agenda**, 5 minutes before the meeting ends, consider moving the remaining items to a github discussion thread so that all the other sprint meetings can start in time.

## Participants

- @jbenet
- @whyrusleeping
- @richardlitt
- @diasdavid

## Notes

- vendor go-libp2p for 0.4.0
- protobuf is huge, but we can have a -lite version just for JS (check Mathias version)
- roadmap now is to get swarm to interop, then Peer Routing interop
- secio is going to be deprecated, no need to implement in JS
- the first CurveCP implementation, incorporated into the Networking and Cryptography library (NaCl), entered public alpha testing on 21 February 2011


- [ ] write captain.log

**Comment by diasdavid** [comment]
## js-ipfs

#### Lead: David Dias

## Agenda

- data-importing
- spec https://github.com/ipfs/specs/pull/57
- js-ipfs-data-importing https://github.com/ipfs/js-ipfs-data-importing
- bitswap
- how to support IPLD and protobufs? (specifically, on the wire?)
- discussion https://github.com/ipfs/js-ipfs/issues/17
- repo https://github.com/ipfs/js-ipfs-bitswap
- init https://github.com/ipfs/js-ipfs/issues/42 (spec it out)
- Itemsize things on the levelDB repo https://github.com/ipfs/js-ipfs-repo/issues/21

**You have 30 minutes for this agenda**, 5 minutes before the meeting ends, consider moving the remaining items to a github discussion thread so that all the other sprint meetings can start in time.

## Participants

- @jbenet
- @whyrusleeping
- @richardlitt
- @diasdavid

## Notes

- data-importing
- tar importer and not chunker
- we should be able to do perf benchmarks
- dedup tests
- linux kernel
- npm modules
- .app example
- bitswap
IPLD spec https://github.com/ipfs/specs/pull/37
- https://github.com/ipfs/specs/pull/37#issuecomment-158766176
implement in JS the same thing that bitswap does in go currently
in 0.4.0 add multicodec on the wire on bitswap (@whyrusleeping to check this)
- kv on top of the MerkleDAG (like the files-api) (discuss)

- [ ] write captain.log

**Comment by diasdavid** [comment]
### David Dias TODO

- js-ipfs
  - [ ] js-ipfs (cli + http api)
    - [ ] /block
    - [ ] /bootstrap
    - [ ] /config
    - [ ] /id
    - [ ] /version
  - [ ] js-ipfs init
  - js-ipfs-data-importing
    - [ ] fixed-size-chunker
- bitswap
  - [ ] work towards feature parity with go-ipfs first (protobufs style)
- libp2p
  - utp
  - [ ] interop go-js swarm (with tests -> libp2p-ci) 
- npm on ipfs
  - [ ] update install process with 0.4.0 rc-1
  
Note: Due to traveling to 3 countries during this Sprint and the fact that it is starting one day late, my predictions are probably off off

**Comment by lgierth** [comment]
@lgierth TODO

- 0.4.0
  - [ ] v04x.ipfs.io and v03x.ipfs.io
  - [ ] have ipfs.io resolve both v03x and v04x (whichever responds success fast)
  - [ ] discuss migration plan with users
- infrastructure
  - [ ] decomission sirius
  - [~] hetzner SSH post-mortem

**Comment by Dignifiedquire** [comment]
@dignifiedquire Todo

### Webui

- [ ] More tests
- [ ] CR contributions
- [ ] Work on the new design

### Distributions

- [x] Add build step for the new site
- [ ] Finish missing design implementations
- [ ] Ship it

**Comment by RichardLitt** [comment]
## go-ipfs

#### Lead: @whyrusleeping

## Agenda

- release process
- create a concrete plan for what has to happen during a release, things like:
- notify users with new features, bug fixes, etc)
- always make a release candidate so that all the client libraries can be upgraded accordingly
- write this process on the go-ipfs API
- sharding discussion
- https://github.com/ipfs/specs/issues/32

**You have 30 minutes for this agenda**, 5 minutes before the meeting ends, consider moving the remaining items to a github discussion thread so that all the other sprint meetings can start in time.

## Participants

## Notes

fix deadlock
more speed!

0.3.11 RC-1

0.4.0 release

##### After sprint meeting is finished, create the respective action items on the Github sprint issue

**Comment by RichardLitt** [comment]
To Do

- [ ] Sprint Management
- [ ] IPFS API
  - [ ] Split into current functions `master` branch and `expected` spec branch
  - [ ] Add `curl` commands to all method descriptions
  - [ ] Check all responses have maximal entries
  - [ ] Standardize formatting for `ipfs --help` entries
  - [ ] Open an issue about sharness testing
- [ ] Research `PATENTS.md` strategies

**Comment by RichardLitt** [comment]
## This Week

Summary: Not a very productive week for me this week, for a variety of reasons, mostly travel related and because it was a short week and I had a lot of admin stuff. I know what I'm doing, just running behind a bit.

- [x] Sprint Management
- [~] Write the weekly roundup; launch it.
- [ ] IPFS API
  - [x] Split into current functions `master` branch and `expected` spec branch.
    - [ ] Add a link to the api from the specs repo
  - [ ] Add `curl` commands to all method descriptions
  - [ ] Check all responses have maximal entries
    - [ ] Log any errors in go-ipfs
  - [ ] Standardize formatting for `ipfs --help` entries, basing on 0.4
  - [ ] Open an issue about sharness testing.
  - [ ] Open a feature issue about having multiple language implementations for curl requests
  - [ ] **Hope** Get sharness testing working
- [ ] **Hope** Research `PATENTS.md` strategies

## Extra

- [x] Built module to open ipfs/go-ipfs notifications from the CLI after the great "go-ipfs issue party". https://github.com/RichardLitt/open-github-notifications
- [x] CR
  - https://github.com/ipfs/webui/pull/166
  - https://github.com/ipfs/weekly/pull/5
  - + M https://github.com/ipfs/awesome-ipfs/pull/38
- [x] Build GitHub Notification checker
- [x] Overhaul "Modified Sprint and GitHub master roles" PR pm/pull/66
- [x] Lots of go-ipfs issue review following the "great go-ipfs issue party"
- [x] Met up with @jbenet in NY and merged some open PRs together
- [x] Bought tickets to http://arcticjs.club; planned trip to Svalbard to meet @whyrusleeping and @diasdavid
- [x] Closed js-guidelines https://github.com/ipfs/community/pull/92

**Comment by Dignifiedquire** [comment]
@dignifiedquire Sprint Update

### Webui

- [~] More tests
- [~] CR contributions
- [ ] Initiate new distribution setup
- [ ] Work on the new design
- [x] Fix issues due to babel upgrade (https://github.com/ipfs/webui/commit/208e5d164277467925e58b1732054dd7c137d3e7)

### Distributions

- [x] Add build step for the new site
- [x] Finish missing design implementations
- [ ] Ship it

### Archives

- [~] Stackoverflow archive
- [~] Research into wikipedia dump mirrors

**Comment by lgierth** [comment]
@lgierth sprint update

- 0.4.0
  - [x] v04x.ipfs.io and v03x.ipfs.io
  - [x] more v03x nodes (3 out of 8 now) ipfs/ops-requests#3
  - [ ] discuss migration plan with users
  - [ ] have ipfs.io resolve both v03x and v04x (whichever responds success fast)
    - [x] dead-simple replacement for ansible (aka Provsn)
    - [~] deploy ipfs using provsn
- infrastructure
  - [x] hetzner SSH post-mortem ipfs/ops-private#2
  - [x] decomission sirius ipfs/infrastructure#134
  - [x] project-repos.ipfs.io dns ipfs/ops-requests#9
- wishlist
  - ~~set up buildbot worker for Tahoe-LAFS~~ (didn't hear back)

**Comment by whyrusleeping** [comment]
- [x] libp2p example for @diasdavid 
- [x] fix and test set/append data for ipfs object patch
- [x] cleanup mfs code a bit, refactoring how it pins
- [~] ipfs files flush
- [x] let @mafintosh convince me to go to svalbard for arcticphp
- [x] paris?

**Comment by diasdavid** [comment]
### SPRINT CHECK IN

- js-ipfs
    - [x] /bootstrap https://github.com/ipfs/js-ipfs/pull/45
      - [x] cli
      - [x] core
      - [x] tests on all
    - [x] /id https://github.com/ipfs/js-ipfs/pull/44
      - [x] cli
      - [x] api
      - [x] core
      - [x] tests on all
    - [x] /version https://github.com/ipfs/js-ipfs/pull/43
      - [x] cli
      - [x] api
      - [x] core
      - [x] tests on all
  - js-ipfs-data-importing
    - [x] fixed-size-chunker https://github.com/ipfs/js-ipfs-data-importing/pull/1
  - js-ipfs-repo
    - [x] fix overloaded function https://github.com/ipfs/js-ipfs-repo/pull/22
  - [x] CR https://github.com/diasdavid/js-multistream/pull/6
- Invest time on API documentation, organize things, CR PR's, issues and so on
- npm on ipfs
  - [x] work and debug with @whyrusleeping files api (which affects npm on IPFS).  
- webui
  - [x] CR https://github.com/ipfs/webui/pull/166/files
- specs
  - [x] CR API Spec Add https://github.com/ipfs/api/pull/17
- extra
  - [x] Copenhagen IPFS Meetup - It was great, more users of IPFS (and following close libp2p and js-ipfs) than I imagined

This week hasn't been super productive for me code wise, missing a flight, losing my bag, having to buy some cloths (not knowing when my bag was going to get back) and travelling to two countries in a sprint that was shortened by one day made me feel that I was leaking time everywhere.

**Comment by jbenet** [comment]
This week I've been working through my large holiday backlog, reconnecting with various people in the IPFS periphery, and handling many start of year organizational things. Lots of email. Haven't made it to github proper yet. Sorry-- if any PRs need my pressing comments, CR, please bring them up to me via IRC or https://github.com/jbenet/todo
- [x] whittled backlog
- [x] lots of IPFS related email
- [x] worked on PRs with @richardlitt, discussed various community things
- [~] IPLD spec work with @mildred -- i still need to do more here this.
  - [ ] finalize IPLD
- [ ] latest vs stable webui comments (@jbenet) in ipfs/webui#167 -- didnt get to this
- [x] lots of protocol labs org things

**Comment by noffle** [comment]
I've just been trying to ramp up on everything (reading lots of specs over the holidays!), and figure out what I'm going to be focusing my efforts on for Q1. I expect to be bugging you all a lot over the coming weeks!

**Comment by jbenet** [comment]
@noffle :+1:  :)

**Comment by diasdavid** [comment]
@RichardLitt getting back to you on the star:

🌟Now you can do npm i -g js-ipfs and use jsipfs bootstrap + id + version commands, fully compatible with go-ipfs repo

:)

**Comment by RichardLitt** [comment]
Thanks @diasdavid. @Dignifiedquire @lgierth @whyrusleeping: what's yours?

**Comment by whyrusleeping** [comment]
no star, i don't do anything that interesting

**Comment by Dignifiedquire** [comment]
:star: distributions page

**Comment by noffle** [comment]
@diasdavid that's awesome! Just tried it! +:100:

**Comment by lgierth** [comment]
> @lgierth what's yours?

added - the work-in-progress dev040 migration

**Comment by jbenet** [comment]
- :star: (specs) much debate in the [IPLD spec](https://github.com/ipfs/specs/pull/37) about pathing notation.

**Comment by chriscool** [comment]
- :star: IPFS Docker image is now tested automatically on Travis, thanks to  @ChristianKniep and @whyrusleeping, see PR #2064 (Docker image volume fix and Sharness tests)
