### ISSUE TITLE
Sprint January 11th

### ISSUE THREAD

**Issue by RichardLitt** [ipfs/pm#79]
# Sprint January 11

## Sprint Goals

TBD

## Sprint Discussions

[Schedule](https://github.com/ipfs/pm#sprint-discussion-schedule)

Please take notes in a separate pad, if you can, and link it here.

Endeavour         | Lead           | Time (PDT - **UTC/Z** - CET) | Pad
:---------------: | :------------: | :--------------------------: | :----:
apps on ipfs      | Juan Benet     | 10:30PDT **18:30Z** 19:30CET | https://public.etherpad-mozilla.org/p/ipfs-jan-11-apps-on-ipfs
infrastructure    | Lars Gierth    | 11:00PDT **19:00Z** 20:00CET | https://public.etherpad-mozilla.org/p/ipfs-jan-11-infrastructure

Please add the Agenda to the Pad before the endeavour sprint starts.

## Sprint Deliverables

- Add your tasks below in a comment, that way we only have people listed who are really in the sprint
- Add links to issues down here. Only add things you can finish this sprint.

**Comment by diasdavid** [comment]
I've pushed libp2p to the end of the queue, 21:00Z today, so that me and @jbenet can make it

**Comment by RichardLitt** [comment]
@diasdavid Sounds good, thanks for taking the initiative.

**Comment by Dignifiedquire** [comment]
@diasdavid does that mean that you and @jbenet are not around for the others before?

**Comment by jbenet** [comment]
there's a meeting @diasdavid and i are attending (about libp2p related
things actually) during both the infra + libp2p hangouts. we decided to
move libp2p to the end. i'll just catch up with the infra notes later
(unless im needed, in which case maybe move to end too?)

**Comment by Dignifiedquire** [comment]
Moved from the Etherpad:

## Apps On IPFS
 
#### Lead: @dignifiedquire
 
#### Participants
 
- @RichardLitt
- @noffle
- @Kubuxu
- @diasdavid
-@whyrusleeping
-@jbenet
 
## Agenda
 
* Webui
* Distributions
* Station status
* Github repos ipfs-improve thing
* Package Managers in general
  * registry-mirror lessons
  * nailing npm and pacman 
  * pypi, apt, nix after
* ipget - solid + packaged (npm, apt, brew, etc)
  * current issues: https://github.com/noffle/ipget/issues
 
 
**You have 30 minutes for this agenda**, 5 minutes before the meeting ends, consider moving the remaining items to a github discussion thread so that all the other sprint meetings can start in time.
 
 
 
## Notes
 
 
##### After sprint meeting is finished, create the respective action items on the Github sprint issue

**Comment by lgierth** [comment]
## Infrastructure

#### Lead: @lgierth

#### Participants

- @Dignifiedquire
- @whyrusleeping
- @lgierth
- @RichardLitt

## Agenda

- dev040 migration
- ipv6
- ansible/provsn
- more storage
- multiple ipfs instances to avoid data loss, e.g. restart before files api flush

## Notes

- storage
  - wikipedia is a bit weird to mirror
  - storage in the u.s. would be really useful
  - @whyrusleeping is going to build a massive array at home -- 72TB and hopefully 1Gb/s
- dev040 migration
  - all the bootstrap/gateway hosts will run both v03x and v04x
    - both instances share the private key
    - either the v03x or v04x instance gets to claim the default ports 4001, 5001, 8080
    - right now it 5 * v03x and 3 * v04x, over time we'll gradually phase out v03x
- ipv6
  - people have been asking for this for a while https://github.com/ipfs/infrastructure/issues/88
  - bootstrap needs to deal with multiple addresses for the same node (@whyrusleeping)
  - possible addresses per node:
    - /ip4/tcp
    - /ip4/utp
    - /ip6/tcp
    - /ip6/utp
    - /ip6/tcp with fc00::/8 address
    - /ip6/utp with fc00::/8 address
- ansible
  - all of the big three (chef, puppet, ansible) are really annoying
    - code tends to become a mess if you don't pay really close attention
    - layers of indirection make it hard to test and debug stuff
    - sloooow
  - provsn solves these problems by using plain shell scripts
    - includes file templating and variable inheritance
    - will be published as an independent tools next week or so
    - less than 100 lines of bash at the moment
    - testing with ipfs deployment, will port other stuff too (cjdns, nginx, metrics, pinbot)

**Comment by lgierth** [comment]
### @lgierth TODO

- dev040
  - [ ] discuss migration plan with users
  - [ ] have ipfs.io resolve via both v03x and v04x
- infrastructure
  - [ ] convert all of infrastructure.git to using provsn
- go-ipfs
  - [ ] harden path prefix ipfs/go-ipfs#1988
  - [ ] rebase: remove dead jenkins code ipfs/go-ipfs#2114
  - [ ] CR resolve _dnslink.example.com ipfs/go-ipfs#2184
  - [ ] multiaddr /dns support jbenet/go-multiaddr#7

**Comment by whyrusleeping** [comment]
# @whyrusleeping TODO

- [ ] work on ipfs files read hanging when blocks don't exist
- [ ] fix bootstrapping to allow multiple addresses
- [ ] private networks
- [ ] ship 0.3.11
- [ ] merge 0.4.0 into master

**Comment by jbenet** [comment]
@diasdavid @whyrusleeping reminder post your etherpad's notes here

**Comment by Dignifiedquire** [comment]
## @dignifiedquire TODO

- [ ] PR updated webui for `0.3.11`
- [ ] Bug fixes for the webui
- [ ] New deployment setup for the webui
- [ ] Ship distributions

**Comment by diasdavid** [comment]
## David Dias TODO

- js-ipfs
  - [ ] js-ipfs (cli + http api)
    - [ ] block
    - [ ] config
    - [ ] init
  - js-ipfs-data-importing
    - [ ] Create a protobuf version of the layouting (similar to what go-ipfs does) (a good test is creating it, adding to the repo and then let go-ipfs use it <- this will be so sweet)
    - [ ] Extrapolate learnings and merge them into the spec - https://github.com/ipfs/specs/pull/57
  - bitswap
    - [ ] work towards feature parity with go-ipfs first (protobufs style)
- api documentation
- libp2p
  - utp
  - interop go-js swarm (with tests -> libp2p-ci) 
- npm on ipfs
  - [ ] debug and solve with @whyrusleeping latests issues on files API to get it completely ready
  - [ ] update install process with 0.4.0 rc-1
- specs
- extra

**Comment by whyrusleeping** [comment]
## go-ipfs

#### Lead: @whyrusleeping

#### Participants

- @jbenet 
- @whyrusleeping
- @lgierth
- @Dignifiedquire 
- @diasdavid 

## Agenda

- 0.3.11 ship
- PR CR
- 0.4.0 merge into master
- start discussing ipfs cluster

## Notes

- ipld still a bit far out for 0.4.0
- 0.4.0 merge big deal!

**Comment by RichardLitt** [comment]
I have added an IPFS Weekly roundup for last week. https://github.com/ipfs/weekly/pull/12 Feedback due by this time tomorrow.

**Comment by RichardLitt** [comment]
## TODO 

- [x] Sprint Management
- [x] Write the weekly roundup
- [ ] IPFS API
  - [x] Split into current functions `master` branch and `expected` spec branch.
    - [ ] Add a link to the api from the specs repo
  - [ ] Add `curl` commands to all method descriptions
  - [ ] Check all responses have maximal entries
    - [ ] Log any errors in go-ipfs
  - [ ] Standardize formatting for `ipfs --help` entries, basing on 0.4
  - [ ] Open an issue about sharness testing.
  - [ ] Open a feature issue about having multiple language implementations for curl requests
  - [ ] **Hope** Get sharness testing working
- [ ] **Hope** Research `PATENTS.md` strategies

**Comment by diasdavid** [comment]
## js-ipfs

#### Lead: @diasdavid

#### Participants


## Agenda

- js-ipfs update
- Data Importing
- The Spec
- The Implementation
- State of IPLD (jbenet?)
- API specs - https://github.com/ipfs/specs/pull/65
- Core
- HTTP (weird mix of RPC vs REST)
- CLI
- Bitswap
- https://github.com/ipfs/specs/pull/53
- Other stuff that can use review
- https://github.com/ipfs/js-ipfs/issues/42

**Comment by diasdavid** [comment]
## libp2p

#### Lead: @diasdavid

#### Participants

## Agenda

- update
- js and go libp2p interop
  - (priority) 1st milestone - level up go-libp2p swarm and have tests between both
  - 2nd milestone - Peer Routing interop
  - 3rd milestone - Record Store interop
- transports
  - utp
- 

**You have 30 minutes for this agenda**, 5 minutes before the meeting ends, consider moving the remaining items to a github discussion thread so that all the other sprint meetings can start in time.

## Notes


https://github.com/nickdesaulniers/node-rtc-peer-connection

**Comment by jbenet** [comment]
### @jbenet TODO

- [ ] make decisions for IPLD spec 
- [x] dht discussion with other p2p systems
- [x] discuss [uPort](https://medium.com/@ConsenSys/uport-the-wallet-is-the-new-browser-b133a83fe73#.mhzy6zxxy), ipld, keychain, and more with chris at ConsenSys
- [x] review weekly
- [ ] backlog

(will add more)

**Comment by jbenet** [comment]
@diasdavid what work do you need from me the most? i know there's some importer/chunker stuff to spec out. what else? what's highest prio?

@whyrusleeping @lgierth same question

**Comment by noffle** [comment]
# TODO
- [x] ramping up on ipfs pm and logistics
- [ ] tackle some small go-ipfs issues to ramp up + help with 0.4.0
  - [ ] https://github.com/ipfs/go-ipfs/issues/2155
  - [ ] https://github.com/ipfs/go-ipfs/issues/2145
  - [ ] https://github.com/ipfs/go-ipfs/issues/2187
- [ ] BONUS: work on getting [`ipget`](https://github.com/noffle/ipget) production ready
  - [ ] sharness tests
  - [ ] custom bootstrap list
  - [ ] more informative readme

**Comment by diasdavid** [comment]
@jbenet other than the chunker spec, is getting the exchange spec to a point where it is clear what to do to support both protobufs and IPLD

**Comment by rht** [comment]
- [ ] Add http(s) scheme, e.g. `ipget /https/ipfs.com`

**Comment by whyrusleeping** [comment]
- [ ] debug random multistream goroutines...
- [ ] fix ipfs files 'deadlocks'
  - thought we were good, actually not
- [~] private networks
  - implement 'encrypted transport' thing
- [ ] thin out go-libp2p deps
  - go-net needs to die
- [~] directory sharding pls

**Comment by RichardLitt** [comment]
### This Week

This week I spent a lot of time working on the Weekly roundup contributor code. It's not done, but it is very close, and I had a ton of fun doing it. Now that I am with @diasdavid and @whyrusleeping and @noffle in Svalbard for [arcticjs](//arcticjs.club), I hope to make really significant inroads on the API this week in person with them. 

- [x] Sprint Management
- [x] Write the weekly roundup
- [ ] IPFS API
  - [x] Split into current functions `master` branch and `expected` spec branch.
    - [ ] Add a link to the api from the specs repo
  - [ ] Add `curl` commands to all method descriptions
  - [ ] Check all responses have maximal entries
    - [ ] Log any errors in go-ipfs
  - [ ] Standardize formatting for `ipfs --help` entries, basing on 0.4
  - [ ] Open an issue about sharness testing.
  - [ ] Open a feature issue about having multiple language implementations for curl requests
  - [ ] **Hope** Get sharness testing working
- [ ] **Hope** Research `PATENTS.md` strategies

  - Linux Patents DCO - how do they do it? Docker, Git. Is the DCO all you need? Apache. Does GPL have a patents section? CLAHub

## Extra

- [x] CR
  - CR+M https://github.com/ipfs/support/pull/14
  - CR https://github.com/ipfs/fs-repo-migrations/pull/19/files
  - CR https://github.com/ipfs/webui/pull/188
  - CR+M https://github.com/ipfs/py-ipfs/pull/22
  - CR+M https://github.com/ipfs/awesome-ipfs/pull/41
- [x] Closed all open issues and PRs on awesome-ipfs, added note about usable products only. PR awesome-ipfs/pull/40
- [x] Edited pm templates slightly. PR pm/pull/81
- [x] Worked on the weekly blog. PR blog/pull/16, blog/pull/17, blog/pull/18
- [x] Worked on the shutdown notice for go-ipfs. PR go-ipfs/pull/2180
- [x] Authored IPFS Weekly #2, improved workflow and docs considerable. #2
- [x] Created tinyletter.com/ipfsweekly.
- [x] Edited dist descriptions. PR distributions/pull/25
- [x] Reversed order of blog. PR blog/pull/20
- [x] Tooling modules:
  - [x] RichardLitt/ignore-github-users for ignoring @greenkeeperio-bot
  - [x] RichardLitt/gh-upstream for going to a GitHub upstream repository
  - [x] RichardLitt/git-remote-upstream-url to get remote upstream url
  - [x] PRed sindresorhus/gh-home adding gh-upstream check
  - [x] Trivial PR to novaugust/top-gh-contribs.
  - [x] RichardLitt/generator-nms as a yeoman generator for node modules using standard
- [x] Added note to go-ipfs/contribute about squashing commits. https://github.com/ipfs/go-ipfs/compare/feature/squash-note?expand=1
- [x] Opened https://github.com/ipfs/community/issues/94
### ipfs/api
- [x] Opened: api#22, api#21, go-ipfs#2190, go-ipfs#2189
- [x] Added awesome_bot to ipfs/weekly

**Comment by noffle** [comment]
Up at ArcticJS with @RichardLitt, @diasdavid, and @whyrusleeping! Lots of ramping up this week, and took on two issues: one merged, one needing another small revision.

- [x] ramping up on ipfs pm and logistics
- [x] tackle some small go-ipfs issues to ramp up + help with 0.4.0
  - [x] https://github.com/ipfs/go-ipfs/issues/2155
  - [x] https://github.com/ipfs/go-ipfs/issues/2145
  - [ ] https://github.com/ipfs/go-ipfs/issues/2187

**Comment by diasdavid** [comment]
- js-ipfs
  - [x] Clean up and Organize the Project Status, make it easy to understand (hopefully helping other 
  - js-ipfs impl
    - block
       - [x] get 
    - [x] config
      - [x] show (core + cli + tests)
      - [x] replace (core + tests)
    - [x] CR+M https://github.com/ipfs/js-ipfs/pull/53 (thank you @xicombd for the PR :) )
  - js-ipfs-merkle-dag
    - [x] Make it conform with IPFS JS guidelines https://github.com/vijayee/ipfs-merkle-dag/pull/1
    - [x] Move it to use IPFS Repo https://github.com/vijayee/ipfs-merkle-dag/pull/3
    - [x] more stuff on https://github.com/vijayee/ipfs-merkle-dag/pull/3
  - js-ipfs-repo
    - [x] feature: remove block
    - [x] feature: block exists
    - [x] es6'ify plus fix lil things https://github.com/ipfs/js-ipfs-repo/pull/23
  - js-ipfs-data-importing
language implementations) https://github.com/ipfs/js-ipfs/pull/47
- npm on ipfs
  - get registry-mirror up again (hit another deadlock, still working through that with @whyrusleeping )

**Comment by jbenet** [comment]
### @jbenet TODO

- [ ] make decisions for IPLD spec 
- [x] dht discussion with other p2p systems
- [x] discuss [uPort](https://medium.com/@ConsenSys/uport-the-wallet-is-the-new-browser-b133a83fe73#.mhzy6zxxy), ipld, keychain, and more with chris at ConsenSys
- [x] review + publish weekly 2
- [x] distributions site feedback https://github.com/ipfs/distributions/issues/24
- [~] backlog
- [x] published 0.3.11 to npm-go-ipfs
- [x] improved npm-go-ipfs publish.sh
- [x] merge https://github.com/ipfs/go-ipfs/pull/2137 -- windows CI now works. doesn't pass yet though. (:star:)
- CR + Merges 
  - [x] CR + M https://github.com/ipfs/go-ipfs/pull/2213 container bug
  - [x] CR + M https://github.com/ipfs/go-ipfs/pull/2210 bootstrapping bug
  - [x] CR + M https://github.com/ipfs/go-ipfs/pull/2209 files stat print node type
  - [x] CR https://github.com/ipfs/go-ipfs/pull/2208
  - [x] CR + M https://github.com/ipfs/go-ipfs/pull/2206 test-lib improvement
  - [x] CR + M https://github.com/ipfs/go-ipfs/pull/2204 test-lib improvement
  - [x] CR + M https://github.com/ipfs/go-ipfs/pull/2202 ipfs add hidden files directly
  - [x] CR + M https://github.com/ipfs/go-ipfs/pull/2199 multiple bootstrap addrs per peer (caused bootstrapping bug)
  - [x] CR + M https://github.com/ipfs/go-ipfs/pull/2197 resolve ops concurrently
  - [x] CR + M https://github.com/ipfs/go-ipfs/pull/2195 env var info to init, daemon help
  - [x] CR https://github.com/ipfs/go-ipfs/pull/2193 remove old dns txt schema
  - [x] CR + M https://github.com/jbenet/go-multicodec/pull/9 cbor & json: add HeaderPath variable
  - [x] CR + M https://github.com/ipfs/blog/pull/19 blog: weekly 2
  - [x] CR + M https://github.com/jbenet/go-datastore/pull/35 datastore: sync batch
  - [x] CR + M https://github.com/ipfs/infrastructure/pull/144 infra pinned webui

**Comment by Dignifiedquire** [comment]
@dignifiedquire Sync Update

## Webui
- [x] Ship latest webui with 0.3.11(https://github.com/ipfs/go-ipfs/pull/2188)
- [x] Misc bug fixes (https://github.com/ipfs/webui/pull/188)
- [~] CR and help with https://github.com/ipfs/webui/pull/195

## Distributions

- [x] Improvements based on feedback https://github.com/ipfs/distributions/pull/26 (close to shipping)

## Misc

- [x] Get appveyor tests for go-ipfs finally merged (https://github.com/ipfs/go-ipfs/pull/2137)

**Comment by lgierth** [comment]
### @lgierth sync update

- dev040
  - [~] have ipfs.io resolve via both v03x and v04x
  - [~] discuss migration plan with users
  - [ ] automatic docker hub build of ipfs/go-ipfs image
- infrastructure
  - [x] fix ownership of sirius and castor directories ipfs/ops-requests#11 
- go-ipfs
  - [ ] harden path prefix ipfs/go-ipfs#1988
  - [ ] ~~rebase: remove dead jenkins code ipfs/go-ipfs#2114~~
  - [x] CR resolve _dnslink.example.com ipfs/go-ipfs#2184
  - [x] CR combine multiple bootstrap addrs ipfs/go-ipfs#2199
  - [x] discuss recognizing gateways on websites ipfs/notes#92
- archives
  - [x] start mirroring cdn.media.ccc.de
  - [x] debug wikispecies archive with @eminence https://github.com/ipfs/archives/issues/20#issuecomment-170539524
- whislist
  - [~] convert ipfs playbooks to using provsn
  - [ ] multiaddr /dns support jbenet/go-multiaddr#7
  - [ ] convert all of infrastructure.git to using provsn
