### ISSUE TITLE
Sprint January 25th

### ISSUE THREAD

**Issue by RichardLitt** [ipfs/pm#84]
# Sprint January 25

## Sprint Discussions

[Schedule](https://github.com/ipfs/pm#sprint-discussion-schedule)

Please take notes in a separate pad, if you can, and link it here.

Endeavour         | Lead           | Time (PDT - **UTC/Z** - CET) | Pad
:---------------: | :------------: | :--------------------------: | :----:
apps on ipfs      | Juan Benet     | 10:30PDT **18:30Z** 19:30CET | https://public.etherpad-mozilla.org/p/ipfs-Jan-25-apps-on-ipfs
infrastructure    | Lars Gierth    | 11:00PDT **19:00Z** 20:00CET | https://public.etherpad-mozilla.org/p/ipfs-Jan-25-infrastructure
libp2p            | David Dias     | 11:30PDT **19:30Z** 20:30CET | https://public.etherpad-mozilla.org/p/ipfs-Jan-25-libp2p
js-ipfs           | David Dias     | 12:00PDT **20:00Z** 21:00CET | https://public.etherpad-mozilla.org/p/ipfs-Jan-25-js-ipfs
go-ipfs           | Jeromy Johnson | 12:30PDT **20:30Z** 21:30CET | https://public.etherpad-mozilla.org/p/ipfs-Jan-25-go-ipfs

Please add the Agenda to the Pad before the endeavour sprint starts.

## Sprint Deliverables

- Add your tasks below in a comment, that way we only have people listed who are really in the sprint
- Add links to issues down here. Only add things you can finish this sprint.

**Comment by diasdavid** [comment]
## libp2p

#### Lead: @diasdavid
## Agenda

- utp-native

## Notes

- Current focus in more on js-ipfs
- We know have an utp implementation that uses libutp (propts to @maffintosh)
- ucat module https://www.npmjs.com/package/ucat like netcat, but with utp
- [ ]  Jeromy Coffee Talks this Wednesday about gx

**Comment by noffle** [comment]
## @noffle

- [ ] pm
  - [ ] meet up & work with @jbenet in PA on Thursday
  - [ ] chat with @diasdavid re: helping out on js-ipfs
  - [ ] share upcoming summer vacation dates
- [ ] go-ipfs
  - [ ] LGTM+merge https://github.com/ipfs/go-ipfs/pull/2201
  - [ ] mounting only /ipfs (https://github.com/ipfs/go-ipfs/issues/2187)
- [ ] ipget
  - [ ] LGTM+merge https://github.com/ipfs/distributions/pull/42
  - [ ] start on sharness tests
  - [ ] support custom bootstrap list
  - [ ] improve readme

**Comment by diasdavid** [comment]
- js-ipfs
   - [ ] Write Captain.log entry
   - [ ] Open issues for each component that can be already made
  - js-ipfs-repo
  - js-ipfs-merkle-dag
    - [ ] dag-service
  - js-ipfs-data-importing
    - [ ] `files add`
- api documentation
- js-ipfs-api 
- libp2p
  - utp
    - [ ] Make tests for utp-native
- npm on ipfs
  -[ ] log latest folder hash by creating a record of `files stat /npm-registry`
- specs
- extra
  - [ ] Document what is captain.log in ipfs/community
  - [ ] Jeromy Coffee Talks on GX this Wednesday

**Comment by diasdavid** [comment]
#### DAVID DIAS TODO

- js-ipfs
   - [ ] Write Captain.log entry
   - [ ] Open issues for each component that can be already made
  - js-ipfs-repo
  - js-ipfs-merkle-dag
    - [ ] dag-service
  - js-ipfs-data-importing
    - [ ] `files add`
- api documentation
- js-ipfs-api 
- libp2p
  - utp
    - [ ] Make tests for utp-native
- npm on ipfs
  -[ ] log latest folder hash by creating a record of `files stat /npm-registry`
- specs
- extra
  - [ ] Document what is captain.log in ipfs/community
  - [ ] Jeromy Coffee Talks on GX this Wednesday

**Comment by diasdavid** [comment]
#### DAVID DIAS TODO

- js-ipfs
   - [ ] Write Captain.log entry
   - [ ] Open issues for each component that can be already made
  - js-ipfs-repo
  - js-ipfs-merkle-dag
    - [ ] dag-service
  - js-ipfs-data-importing
    - [ ] `files add`
- api documentation
- js-ipfs-api 
- libp2p
  - utp
    - [ ] Make tests for utp-native
- npm on ipfs
  -[ ] log latest folder hash by creating a record of `files stat /npm-registry`
- specs
- extra
  - [ ] Document what is captain.log in ipfs/community
  - [ ] Jeromy Coffee Talks on GX this Wednesday

**Comment by whyrusleeping** [comment]
@whyrusleeping TODO:

TODO:
- [ ] 0.3.11 changelog
- [ ] modtimes in files api
- [ ] fix ipfs files 'deadlocks'
- [ ] private networks
  -  [ ] implement 'encrypted transport' thing
- [ ] thin out go-libp2p deps
  - go-net needs to die
- [ ] directory sharding
- [ ] node aliases (should be easy to add to config)
  - keep map in IpfsNode object, maybe in resolver too
- [ ] docker testing networks (with routers, upnp, nat-pmp, etc)
- [ ] progress bar lib

**Comment by lgierth** [comment]
### @lgierth todo

- dev040
  - [x] ipfs.io v03x/v04x multiplexing
  - [ ] review monday's post mortem
  - [ ] migrate pinbot to v04x
- infrastructure
  - [ ] captain's log
  - [ ] merge ng branch
  - [ ] consolidate, it's a bit messy at the moment
- misc
  - [ ] set up yubikey
  - [ ] work through github notifications backlog
- wishlist
  - ipv6 for ipfs.io
  - make use of _dnslink and cname
  - wildcart cert for *.ipfs.io

**Comment by Dignifiedquire** [comment]
@dignifieqquire TODO

- [ ] Fight with node streams
- [ ] Improve data flow in the webui

**Comment by RichardLitt** [comment]
### To do

- [ ] Sprint Management
- [ ] Write the weekly roundup, plan the next one
- [ ] IPFS API
  - [ ] Add `curl` commands to all method descriptions
  - [ ] Check all responses have maximal entries
  - [ ] Open a feature issue about having multiple language implementations for curl requests

**Comment by whyrusleeping** [comment]
## Go-ipfs notes:

#### Lead: @whyrusleeping

#### Participants
@RichardLitt
@jbenet
@kyledrake
@dignifiedquire

## This Week

gx vendoring of go-libp2p
  - will need others to try it out
- 0.4.0 release
  - mark release canidate
  - testing testing testing
  - taking more time is okay
- networking tests
  - CORE
  - imunes
  - want to have it CLI based
- webui updates
  - automated
  - version checks

**Comment by Kubuxu** [comment]
### @Kubuxu TODO:
- [x] - resolving dnslink under `_dnslink.` - ipfs/go-ipfs#2191
- [x] - bought ipfs.ovh to dnslink random things (if you need anything linked, just ping me on IRC)
- [ ] - changing (again) domain of my codebin to https://ipfs.io/ipns/bin.ipfs.ovh/ - ipfs/awesome-ipfs#44
- [ ] - restructuring the codebin (it is a complete mess) - https://github.com/kubuxu/hasteipfs
- [ ] - vectorised logo - ipfs/logo#5
- [ ] - migrating my nodes to 0.4 - one test node already is migrated, everything seems to work

**Comment by diasdavid** [comment]
#### DAVID DIAS CHECK IN

#### js-ipfs
   - [x] write a captain.log entry https://github.com/ipfs/js-ipfs/issues/30
   - [x] document possible good contributions, tag them by difficulty level https://github.com/ipfs/js-ipfs/issues
   - [x] CR+M https://github.com/ipfs/js-ipfs/pull/62
   - [x] update to latest repo (and enable browser tests) https://github.com/ipfs/js-ipfs/pull/61
  - js-ipfs-repo
   - [x] CR+M https://github.com/ipfs/js-ipfs-repo/pull/27
   - [x] CR+M https://github.com/ipfs/js-ipfs-repo/pull/28
   - [x] Create an architecture overview to help everyone understand how pieces tie together https://github.com/ipfs/js-ipfs/pull/64
  - js-ipfs-merkle-dag
    - dag-service 
      - [x] refactor https://github.com/vijayee/js-ipfs-merkle-dag/pull/10
      - [x] fix bugs + complete impl + finish tests https://github.com/vijayee/js-ipfs-merkle-dag/pull/14
      - [x] fix serialisation (to right block size) https://github.com/vijayee/js-ipfs-merkle-dag/pull/15
    - [x] es6ify + mochaify https://github.com/vijayee/js-ipfs-merkle-dag/pull/13
  - js-ipfs-blocks
    - [x] factor it out from merkle-dag module https://github.com/ipfs/js-ipfs-blocks
    - [x] mochafy https://github.com/ipfs/js-ipfs-blocks/pull/1
    - [x] es6ify https://github.com/ipfs/js-ipfs-blocks/pull/2
  - js-ipfs-data-importing
    - [x] file -> merkledag works and I can move it around with IPFS, but I was seeing some weird encoding, so went back and did all of the above to improve ipfs-blocks and merkle-dag, fixing problems along the way

#### js-ipfs-api 
  - [x] rebase master on files-api ipfs/js-ipfs-api#74


#### npm on ipfs
  - [x] update ipfs-blob-store to latest js-ipfs-api + add more docs + add option to set the flush flag https://github.com/ipfs/ipfs-blob-store/pull/9
  - [x] pick custom repo path and option to init it or not https://github.com/ipfs/js-ipfsd-ctl/pull/48
  - [x] refactor a bunch + adding more tests https://github.com/diasdavid/registry-mirror/pull/30
  - [x] log latest folder hash by creating a record of `files stat /npm-registry` https://github.com/diasdavid/registry-mirror/pull/31


#### extra
  - [x] Document what is captain.log in ipfs/community https://github.com/ipfs/community/pull/100
  - [x] Jeromy Coffee Talks on GX this Wednesday
  - [x] R https://github.com/ipfs/http-api-spec/pull/25
  - [x] R https://github.com/ipfs/http-api-spec/pull/24
  - [x] Host an IPFS Hack Day in Lisbon https://github.com/ipfs/community/issues/103
  - [x] Check "needs review" label everyday and give my input
  - [x] Send proposal to http://icwe2016.inf.usi.ch/ for a Tutorial

**Comment by dignifiedquire** [comment]
## @dignifiedquire Sprint Update

## JS IPFS
- [x] **Won** fight with node streams (https://github.com/dignifiedquire/idb-plus-blob-store)
- [x] CR
  - [x] https://github.com/ipfs/js-ipfs-repo/pull/28
  - [x] https://github.com/ipfs/js-ipfs/pull/62
- [x] Find and file bug in webpack https://github.com/webpack/webpack/issues/1944

### Webui
- [ ] Improve data flow in the webui
  - [x] Research into redux and co
  - [x] Settled on [redux](http://redux.js.org/) + [redux-saga](https://github.com/yelouafi/redux-saga)
  - [~] Start conversion https://github.com/ipfs/webui/pull/229
- [x] Update dependencies to lates

### dist.ipfs.io

- [x] CR and merge https://github.com/ipfs/distributions/pull/47
- [x] Build and release new dist.ipfs.io

### Misc

- [x] Record CoffeeTalk about `gx`

**Comment by noffle** [comment]
## noffle sync update

I went down an 'ipfs mount` rabbit hole when looking at https://github.com/ipfs/go-ipfs/issues/2187. I realized that we were letting users publish manually while /ipns was mounted. Then I realized that we don't do state cleanup after a user 'ipfs mount's -- we assume it's still mounted as long as the daemon is running. In fixing that I realized that test nodes often fail to publish (since we try to pull their pubkey from the dht, which is often not yet populated by a fresh node). And then in this I felt that 'ipfs mount' as a command could benefit from some improvements, and so I started a discussion on this (https://github.com/ipfs/notes/issues/105).

- [~] pm
  - [x] meet up & work with @jbenet in PA on Thursday
  - [ ] chat with @diasdavid re: helping out on js-ipfs
  - [x] share upcoming summer vacation dates
- [~] go-ipfs
  - [x] LGTM+merge https://github.com/ipfs/go-ipfs/pull/2201
  - [~] mounting only /ipfs (https://github.com/ipfs/go-ipfs/issues/2187)
    - [~] error out on 'ipfs name publish' if /ipns is already mounted
      - [~] do proper state clean-up when the user unmounts /ipfs or /ipns
        - [~] fix sharness tests from failing when a new node tries to mount (https://github.com/ipfs/go-ipfs/pull/2266)
    - [x] research what a 'mount'-compatible 'ipfs mount' cmd looks like + [start discussion](https://github.com/ipfs/notes/issues/105)
- [~] ipfs/distributions
  - [x] PR: support custom repo owners for apps
  - [~] CR+M: [ipget on dist.ipfs.io](https://github.com/ipfs/distributions/pull/42)
- [ ] ipget
  - [ ] start on sharness tests
  - [ ] support custom bootstrap list
  - [ ] improve readme
- [x] mentor @ NodeSchool SF

**Comment by lgierth** [comment]
### @lgierth update

- dev040
  - [x] ipfs.io v03x/v04x multiplexing via multireq
  - [x] review monday's post mortem
  - [x] stop multireq from following redirects
  - [x] make multireq more robust
  - [ ] migrate pinbot to v04x
- infrastructure
  - [x] merge ng branch
  - [x] stop using docker networking (no more bootstrappers behind NAT)
  - [~] consolidate, it's a bit messy at the moment
  - [ ] captain's log
- misc
  - [x] set up sundial
  - [x] set up yubikey / 2-factor-auth
  - [~] work through github notifications backlog
- wishlist
  - ~~ipv6 for ipfs.io~~
  - ~~make use of _dnslink and cname~~
  - ~~wildcart cert for *.ipfs.io~~### @lgierth todo

**Comment by RichardLitt** [comment]
## This Week

- [x] Sprint Management
- [x] Write the weekly roundup
- [ ] IPFS API
  - [x] bitswap https://github.com/ipfs/http-api-spec/pull/24
  - [x] block https://github.com/ipfs/http-api-spec/pull/25
  - [x] bootstrap https://github.com/ipfs/http-api-spec/pull/26
  - [x] Added an Error datastructure https://github.com/ipfs/http-api-spec/pull/27
  - [ ] Add `curl` commands to all method descriptions
  - [ ] Check all responses have maximal entries
  - [ ] Open a feature issue about having multiple language implementations for curl requests

## Extra

- [x] Edited the Docs styleguide https://github.com/ipfs/community/pull/101
- [x] go-ipfs docs https://github.com/ipfs/go-ipfs/pull/2265, https://github.com/ipfs/go-ipfs/pull/2270
- [x] Wrote a dist.ipfs.io intro blogpost https://github.com/ipfs/blog/pull/23
- [x] CR https://github.com/ipfs/go-ipfs/pull/2191
- [x] CR https://github.com/ipfs/js-ipfs/pull/63/
- [x] CR https://github.com/vijayee/js-ipfs-merkle-dag/pull/14
- [x] CR + Edits on go-ipfs changelog. https://github.com/ipfs/go-ipfs/pull/2248
- [x] CR + Edits https://github.com/ipfs/community/pull/100
- [x] CRM https://github.com/ipfs/py-ipfs/pull/27
- [x] CRM https://github.com/ipfs/specs/pull/70
- [x] CRM https://github.com/ipfs/ipfs/pull/155
- [x] Plan the NYC IPFS meetup for February.

**Comment by whyrusleeping** [comment]
DONE (week of Jan 25):
- [ ] docker test networks
  - spent a solid day and a half here.. made a miniscule amount of progress
- [x] 0.3.11 changelog
- [x] review/merge cbor#3
- [ ] fix ipfs files 'deadlocks'
  - this is probably done, just hard to confirm
- [ ] gx to vendor libp2p in go-ipfs
  - 98% done! now just working on getting CI to run properly
- [x] reviewed every PR, closing old ones, and merging ready ones
- [x] some fixes for distributions
  - [ ] once that ships, make ipfs-update use it (just waiting on it to ship now)
