### ISSUE TITLE
Sprint: February 1

### ISSUE THREAD

**Issue by RichardLitt** [ipfs/pm#88]
# Sprint February 1st

## Sprint Discussions

[Schedule](https://github.com/ipfs/pm#sprint-discussion-schedule)

**Note: There is no libp2p talk this week, so we've moved go-ipfs up**

Please take notes in a separate pad, if you can, and link it here.

Endeavour         | Lead                | Time (PDT - **UTC/Z** - CET) | Pad
:---------------: | :-----------------: | :--------------------------: | :----:
sync              | Rich Littauer       | 9:00pDT **17:00Z** 18:00CET  | IRC: #ipfs on Freenode
apps on ipfs      | Friedel Ziegelmayer | 10:30PDT **18:30Z** 19:30CET | https://public.etherpad-mozilla.org/p/ipfs-feb-1-apps-on-ipfs
infrastructure    | Lars Gierth         | 11:00PDT **19:00Z** 20:00CET | https://public.etherpad-mozilla.org/p/ipfs-feb-1-infrastructure
go-ipfs           | Jeromy Johnson      | 11:30PDT **19:30Z** 20:30CET | https://public.etherpad-mozilla.org/p/ipfs-feb-1-go-ipfs
js-ipfs           | David Dias          | 12:00PDT **20:00Z** 21:00CET | https://public.etherpad-mozilla.org/p/ipfs-feb-1-js-ipfs

Please add the Agenda to the Pad before the endeavour sprint starts.

## Sprint Deliverables

- Add your tasks below in a comment, that way we only have people listed who are really in the sprint
- Add links to issues down here. Only add things you can finish this sprint.

**Comment by dignifiedquire** [comment]
## Apps on IPFS

#### Lead: @dignifiedquire

#### Participants

- @dignifiedquire
- @noffle
- @richardlitt
- @whyrusleeping
- @diasdavid

## Agenda

- registry-mirror
- removing a lot of technical debt (from glue code to actual code)
- adding more features (the requested ones)
- making it nicer to contribute (more proper testing!)
- webui
  - lots of research cumulating in starting to use redux + redux-saga (no more `setInterval` soon)
- distributions
  - new version with fixed containing folder

## Notes

### Registry Mirror

- diasdavid is working on a big code refactoring
- Daemon in biham died and hung, still need to do research into why
- new features: 
    - logging the root hash from time to time, to help with debugging and crashes
    - remove different blob stores (part of the refactor) we just use ipfs
    - if statements --
- Adding debug logs for api requests, to easier figure out which commands fail

### Webui

- research -> redux + redux-saga
- short demo of redux-devtools
- TODO: migrate ipfs-geoip data to 0.4
- TODO: make progress on the migration to redux

### Distributions

- new version with containing folder fix

**Comment by diasdavid** [comment]
## IPFS implementation in JavaScript

#### Lead: David Dias

#### Participants

## Agenda

- update
- js-ipfs-blocks
- js-ipfs-merkle-dag
- js-ipfs-data-importing (managed to import a file)
- this week focus
- js-ipfs object
- js-ipfs files add
- js-ipfs-bitswap
- other things that can be done
     - check https://github.com/ipfs/js-ipfs/issues

**Comment by lgierth** [comment]
## Infrastructure

#### Lead: @lgierth

#### Participants

- @daviddias
- @dignifiedquire
- @jbenet
- @lgierth
- @richardlitt
- @whyrusleeping

## Agenda

- 0.4.0
  - multireq
  - documentation
  - pinbot
- testing
  - idea https://github.com/ipfs/infrastructure/issues/150
  - another idea is acceptance testing of the website(s)
- connectivity work
  - ipv6
  - domains & redirects
  - ssl cert

## Notes

- 0.4.0
  - blog post about the migration /cc richardlitt
  - pinbot
    - ipfs-shell => go-ipfs-api
- docker & gx
  - with gx, the dependencies are no longer within the source tree, but instead in GOPATH
  - build outside docker and just copy the ipfs daemon in?
  - an export/import step at the end to get rid of intermediary images?
- testing
  - https://github.com/ipfs/infrastructure/issues/150 /cc whyrusleeping
  - acceptance tests phantomjs /cc dignifiedquire
- pages deploy
  - multipublish tool /cc jbenet
- ipns perf
  - deploy a few instances of https://github.com/whyrusleeping/ipfs-dht to increase the size of the network and improve IPNS performance
- TODO RIGHT NOW
  - publish dist
  - publish website

**Comment by RichardLitt** [comment]
### To Do

- [ ] Sprint Management
- [ ] Write the weekly roundup
- [ ] IPFS API
  - [ ] cat
  - [ ] commands
  - [ ] config
  - [ ] daemon
  - [ ] dht
  - [ ] diag
  - [ ] dns
  - [ ] file
  - [ ] get
  - [ ] id
  - [ ] init
  - [ ] log
  - [ ] ls

**Comment by whyrusleeping** [comment]
## go-ipfs

![go-go-ipfs](http://new1.fjcdn.com/gifs/Power+rangers+swaggin+on+ya+power+rangers+thread+big+go+go+power_82a524_4884818.gif)

#### Lead: @whyrusleeping

#### Participants

## Agenda

- gx vendoring
- files hang debugging
- take a look at suspected memory leaks
- multistream seems to have some goroutine issues
- going through issues, gonna try and triage most of them
- files api inotify
- swarm peers notify
- improvements to 'ipfs mount'

**You have 30 minutes for this agenda**, 5 minutes before the meeting ends, consider moving the remaining items to a github discussion thread so that all the other sprint meetings can start in time.

## Notes

- figure out docker stuff with @lgierth
- stress tests on files api stuff for registry mirror
  - also look at https://github.com/ipfs/go-ipfs/issues/2276
- issue triage ftw
- discuss making mount a separate binary


##### After sprint meeting is finished, create the respective action items on the Github sprint issue

**Comment by whyrusleeping** [comment]
you know, i didnt add that gif in there. but i'm also not gonna remove it

**Comment by RichardLitt** [comment]
i did it was me

**Comment by whyrusleeping** [comment]
- [ ] debug files api hangs
  - add tests for this too
- [ ] debug random multistream goroutines...
  - too many goroutines open in yamux Read wait
  - likely an issue with readHandshake in go-multistream. (too many goroutines waiting)
- [ ] modtimes in files api
- [ ] fuse mount code as separate binary
  - files api as fuse mount
- [ ] private networks
  -  [ ] implement 'encrypted transport' thing
- [ ] directory sharding?
- [ ] node aliases (should be easy to add to config)
  - keep map in IpfsNode object, maybe in resolver too
- [ ] progress bar lib
- [ ] gx
  - [ ] writeup
  - [ ] command polishing

**Comment by diasdavid** [comment]
#### DAVID DIAS TODO

- js-ipfs
   - [ ] object
  - js-ipfs-repo
  - js-ipfs-merkle-dag
  - js-ipfs-blocks
  - js-ipfs-data-importing
    - [ ] `files add`
- api documentation
- js-ipfs-api 
- libp2p
  - utp
    - [ ] Make tests for utp-native
- npm on ipfs
  - [ ] big refactor clean up https://github.com/diasdavid/registry-mirror/pull/32
- specs
- extra

**Comment by noffle** [comment]
## noffle todo

- design
  - [ ] get feedback on ['ipfs mount' redesign](https://github.com/ipfs/notes/issues/105)
- go-ipfs
  - [ ] PR: offline pubkey resolution when mounting (to reduce test flakiness) (https://github.com/ipfs/go-ipfs/pull/2266)
  - [ ] PR: proper clean-up when /ipfs or /ipns is unmounted
  - [ ] PR: error out if user tries to 'ipfs name publish' while /ipns is mounted
  - [ ] PR: 'ipfs mount --read-only' flag for read-only /ipns mounting
- multireq
  - [ ] PR: handle N targets; various fixes (https://github.com/whyrusleeping/multireq/pull/2)
- distributions
  - [ ] PR: ipget on 'distributions'
- gx
  - [ ] work with @whyrusleeping on an article/tour of gx

**Comment by Kubuxu** [comment]
#### Kubuxu todo:

* go-ipfs
  - [ ] - PR: fix `ipfs resolve` returning `recursion limit exceeded` when running without recursion.
 * misc:
  - [ ] - clean-up vectorised logo, discuss possible changes - ipfs/logo#7
  - [x] - move hasteIPFS under new domain - ipfs/awesome-ipfs/pull/44

**Comment by dignifiedquire** [comment]
## @dignifiedquire todo

- [ ] Redux and the webui

**Comment by rht** [comment]
Can someone on go-ipfs look over and merge https://github.com/ipfs/go-ipfs/pull/2100, https://github.com/ipfs/go-ipfs/pull/2120, https://github.com/ipfs/go-ipfs/pull/2205, https://github.com/ipfs/go-ipfs/pull/2221, https://github.com/ipfs/go-ipfs/pull/2251 (in particular the last one)?

**Comment by whyrusleeping** [comment]
hey @rht, mind posting your weekly TODO's here too? It would help us get a better idea what everyone is working as a group and makes planning easier. (also posting an update at the end of the sprint cycle is super helpful!)

**Comment by lgierth** [comment]
### @lgierth todo

- 0.4.0
  - [ ] update pinbot
  - [ ] update dockerfile for libp2p/gx
  - [ ] docker image jbenet/go-ipfs => ipfs/go-ipfs
- infrastructure
  - [ ] live integration test ipfs/infrastructure#150
  - [ ] websites acceptance test
  - [ ] ssl wildcard cert for *.ipfs.io
  - [ ] redirect http: => https:
  - [ ] www.ipfs.io
  - [ ] redirect gateway.ipfs.io => ipfs.io
- ops
  - [x] deploy dist.ipfs.io
  - [x] deploy website/blog
  - [x] pin & pin & pin [& pin ...]
  - [ ] blog post about 0.4.0 migration
- whislist
  - [ ] proposal for simpler website deployments

**Comment by rht** [comment]
> hey @rht, mind posting your weekly TODO's here too?

Figure a way to properly fix bitswap duplicate blocks. I don't think this issue is present in torrent.

**Comment by rht** [comment]
> pin & pin & pin [& pin ...]

How should this be parsed?

**Comment by lgierth** [comment]
> How should this be parsed?

Sorry this should have been clearer: I had trouble pinning dist and website, the pin would eventually succeed, but the CLI hung forever.

**Comment by rht** [comment]
ic, I think this can be consistently reproduced with running the daemon with auto-gc enabled, with sufficiently low GCPeriod such that added blocks get gc-ed before the pinning starts.

**Comment by rht** [comment]
ic, the issue is in the CLI, but the pin completes just fine?

**Comment by whyrusleeping** [comment]
please move discussion to a relevant issue elsewhere, this issue is just for task tracking.

**Comment by noffle** [comment]
# noffle sync update

Lots of reading and thinking about records, freshness, and how the record routing layer will fit into IPFS. Started some discussions around 'ipfs mount' and app-layer pubsub. Big progress on improving fuse UX!

- notes
  - [x] started a ['ipfs mount' redesign discussion](https://github.com/ipfs/notes/issues/105)
  - [x] wrote a [application layer pubsub proposal](https://github.com/ipfs/notes/issues/108)
- reading
  - [x] [mediachain](https://medium.com/mine-labs/introducing-mediachain-a696f8fd2035)
  - [x] [iprs](https://github.com/ipfs/specs/tree/master/records)
  - [x] [How Routing and Resolution works in IPFS](https://github.com/ipfs/faq/issues/48#issuecomment-152917088)
- go-ipfs
  - [x] CR: [big gx merge](https://github.com/ipfs/go-ipfs/pull/2256)
  - [~] PR: [do proper clean-up when fuse connection is terminated](https://github.com/ipfs/go-ipfs/pull/2296)
- distributions
  - [~] PR: [get ipget ready to be on dist.ipfs.io](https://github.com/ipfs/distributions/pull/42)
  - [~] PR: support custom github owner paths
- multireq
  - [~] PR: [add N target support to multireq, general improvements](https://github.com/whyrusleeping/multireq/pull/2)

**Comment by RichardLitt** [comment]
## This Week

- [x] Sprint Management
- [x] Write the weekly roundup
- [x] IPFS API
  - [x] cat
  - [x] commands
  - [x] config
  - [x] daemon
  - [x] dht
  - [x] diag
  - [x] dns
  - [x] file
  - [x] get
  - [x] id
  - [x] init
  - [x] log
  - [x] ls
  - [x] mount
  - [ ] name
  - [x] object
  - [ ] pin
  - [ ] ping
  - [x] refs
  - [ ] repo
  - [ ] resolve
  - [ ] stats
  - [ ] swarm
  - [ ] tar
  - [ ] tour
  - [ ] update
  - [x] version

## Extra

- [x] Opened issue about conference and meetup suggestions in ipfs/community. https://github.com/ipfs/community/issues/105
- [x] CRM https://github.com/ipfs/awesome-ipfs/pull/44
- [x] Spruced up gx's readme. https://github.com/whyrusleeping/gx
- go-ipfs:
  - [x] Closed issue: [Add developer certificate of origin](https://github.com/ipfs/go-ipfs/pull/2254).
  - [x] go-ipfs questions: https://github.com/ipfs/go-ipfs/issues/2301
  - [x] Edited the Readme https://github.com/ipfs/go-ipfs/pull/2302
  - [x] Docs for go-ipfs: https://github.com/ipfs/go-ipfs/pull/2281, https://github.com/ipfs/go-ipfs/pull/2282, https://github.com/ipfs/go-ipfs/pull/2285, https://github.com/ipfs/go-ipfs/pull/2292, https://github.com/ipfs/go-ipfs/pull/2298, https://github.com/ipfs/go-ipfs/pull/2299, https://github.com/ipfs/go-ipfs/pull/2300, https://github.com/ipfs/go-ipfs/pull/2303, https://github.com/ipfs/go-ipfs/pull/2306, https://github.com/ipfs/go-ipfs/pull/2307, https://github.com/ipfs/go-ipfs/pull/2311, https://github.com/ipfs/go-ipfs/pull/2314
- CR https://github.com/ipfs/js-ipfs-api/pull/200, https://github.com/ipfs/blog/pull/27,

**Comment by lgierth** [comment]
### @lgierth sync update

I started off the week with blog and dist deployments, which were a bit hairy because pinning was/is buggy and tended to hang indefinitely. The gx dependencies support for the go-ipfs docker image took me a bit longer than I expected but it does work nicely now.

- go-ipfs & 0.4.0
  - [~] update pinbot
  - [x] update dockerfile for libp2p/gx ipfs/go-ipfs#2256
  - [x] automated docker image jbenet/go-ipfs => ipfs/go-ipfs ipfs/go-ipfs#2308
  - [~] figure out grace period for jbenet/go-ipfs image ipfs/go-ipfs#2308
  - [x] CR ipfs/go-ipfs#2277
- infrastructure
  - [ ] live integration test ipfs/infrastructure#150
  - [ ] websites acceptance test
  - [~] ssl wildcard cert for *.ipfs.io
  - [ ] redirect http: => https:
  - [ ] www.ipfs.io
  - [ ] redirect gateway.ipfs.io => ipfs.io
- ops
  - [x] 2x deploy dist.ipfs.io
  - [x] 2x deploy website/blog
  - [x] work through pinning troubles
  - [~] blog post about 0.4.0 migration ipfs/blog#27
- whislist
  - [ ] proposal for simpler website deployments

**Comment by whyrusleeping** [comment]
- [ ] 'verbose' mode for some commands to help debugging
  - getting pretty close to finishing this, pretty useful already
- [x] debug files api hangs
  - all the hangs i was previously seeing are accounted for
  - still an issue with 'too many open files' causing a block to be lost
- [ ] debug random multistream goroutines
  - didnt get time to look at this
- [x] shipped gx ipfs PR. Woo!
- [x] wrote tool to publish ipns records without the ipfs daemon
  - also a tool to generate private keys as needed to use with said tool
- [x] gx cleanup, fixed an issue that was reported and modified some UX after feedback in irc

**Comment by diasdavid** [comment]
### David Dias Check in

##### js-ipfs
   - [x] object features (with test and all :))
  - js-ipfs-repo
  - js-ipfs-merkle-dag
    - [x] https://github.com/vijayee/js-ipfs-merkle-dag/pull/18
    - [x] CR https://github.com/vijayee/js-ipfs-merkle-dag/pull/22
  - js-ipfs-blocks
  - js-ipfs-data-importing
    - [~] `files add` currently being able to add files and use them through go-ipfs (need to catch up on some new details of the Files API to finish the implementation)

##### api documentation
  - [x] R https://github.com/ipfs/http-api-spec/pull/26
  - [x] R(x2) https://github.com/ipfs/http-api-spec/pull/25
  - [x] R https://github.com/ipfs/http-api-spec/pull/30
  - [x] R https://github.com/ipfs/http-api-spec/pull/32
  - [x] R https://github.com/ipfs/http-api-spec/pull/35
  - [x] R https://github.com/ipfs/http-api-spec/pull/34
  - [x] R https://github.com/ipfs/http-api-spec/pull/31

##### js-ipfs-api 
  - [x] CR https://github.com/ipfs/js-ipfs-api/pull/200

##### libp2p
  - utp
    - [x] https://github.com/mafintosh/utp-native/pull/3
    - [x] Make tests for utp-native https://github.com/mafintosh/utp-native/pull/2 

##### npm on ipfs
  - [x] big refactor clean up https://github.com/diasdavid/registry-mirror/pull/32
  - [x] merge registry-static into registry-mirror and remove all of the unnecessary stuff (this was huge) https://github.com/diasdavid/registry-mirror/pull/33 

##### extra
  - [x] R https://github.com/ipfs/community/pull/106
  - [x] Submit a WebRTC talk to Kranky Geek Bengaluru (_Distributed Computing through Parasitic Algorithms on top of the Web Platform_)
  - [x] Apply and get accepted to give an IPFS Tutorial http://icwe2016.inf.usi.ch/
  - [x] Accept to talk at http://p2pvalue.eu/2nd-floss4p2p-workshop

**Comment by dignifiedquire** [comment]
## @dignifiedquire Sprint Update

### Webui
- [~] [Work on Redux](https://github.com/ipfs/js-ipfs-api/pull/200)

### Distributions

- [~] [Signed releases](https://github.com/ipfs/distributions/pull/51) :star:
- [x] [Reproducible builds (site)](https://github.com/ipfs/distributions/commit/7375b2c9942a280c5d84a91b90928c8bf4a72211)
- [x] [Dependency Updates](https://github.com/ipfs/distributions/commit/0684cc78ec661aa1071f0378e93837f5c9ff4bab)
- [x] [New release with ipget](https://github.com/ipfs/distributions/pull/42) :star:

### JS IPFS API

- [~] [Promise Api](https://github.com/ipfs/js-ipfs-api/pull/200) :star:
- [~] [Dependency Updates](https://github.com/ipfs/js-ipfs-api/pull/209)

### Misc 

- [x] [Fix nasty npm bug](https://github.com/npm/npm/pull/11433)
- [x] CR https://github.com/ipfs/http-api-spec/pull/25
- [x] CR https://github.com/ipfs/weekly/pull/16

**Comment by jbenet** [comment]
### @jbenet TODOs

My last week has been spent primarily in important meetings with people, discussing IPFS and other protocols. I had very little time for code or review. If i'm blocking something major, please ping me on IRC or here with what you need review on. (Sorry @whyrusleeping and @rht for go-ipfs laggg)

- [x] a TON of meetings about IPFS
- [x] NYU mazieres talk
- [x] tested out ipfs-update in prep for 0.4.0 (found UX bugs)
- [x] reviewed / improved weekly

**Comment by Kubuxu** [comment]
#### Kubuxu update:

* go-ipfs
  - [~] - PR: fix `ipfs resolve` returning `recursion limit exceeded` when running without recursion. -  ipfs/go-ipfs#2283
 - [x] - PR: change sample API origin settings from wildcard to example.com - ipfs/go-ipfs#2284
 - [~] - PR: add `resolve` and `dns` commands to RO Gateway - ipfs/go-ipfs#2291
* misc:
  - [~] - SVG logo - ipfs/logo#7
  - [x] - SVG2PNG generator for the logos ^
  - [x] - shading on logo, a refreshed look: https://ipfs.io/ipfs/QmTgtbb4LckHaXh1YhpNcBu48cFY8zgT1Lh49q7q7ksf3M/ (only hold up is legal works, afaik) :star: (maybe to early)
  - [x] - move hasteIPFS under new domain - ipfs/awesome-ipfs/pull/44
  - [~] - work on fs:/ipns/utils.ipfs.ovh
* gx:
  - [x] - gx-lua written in Lua 
  - [~] - rewrite gx-lua to Go, it is ugly in Lua
