### ISSUE TITLE
Sprint: February 8

### ISSUE THREAD

**Issue by RichardLitt** [ipfs/pm#89]
# Sprint February 8th

## Sprint Discussions

[Schedule](https://github.com/ipfs/pm#sprint-discussion-schedule)

Please take notes in a separate pad, if you can, and link it here.

Endeavour         | Lead                | Time (PDT - **UTC/Z** - CET) | Pad
:---------------: | :-----------------: | :--------------------------: | :----:
sync              | Rich Littauer       | 9:00pDT **17:00Z** 18:00CET  | IRC: #ipfs on Freenode
apps on ipfs      | Friedel Ziegelmayer | 10:30PDT **18:30Z** 19:30CET | https://public.etherpad-mozilla.org/p/ipfs-feb-8-apps-on-ipfs
infrastructure    | Lars Gierth         | 11:00PDT **19:00Z** 20:00CET | https://public.etherpad-mozilla.org/p/ipfs-feb-8-infrastructure
go-ipfs           | Jeromy Johnson      | 11:30PDT **19:30Z** 20:30CET | https://public.etherpad-mozilla.org/p/ipfs-feb-8-go-ipfs
js-ipfs           | David Dias          | 12:00PDT **20:00Z** 21:00CET | https://public.etherpad-mozilla.org/p/ipfs-feb-8-js-ipfs

Please add the Agenda to the Pad before the endeavour sprint starts.

## Sprint Deliverables

- Add your tasks below in a comment, that way we only have people listed who are really in the sprint
- Add links to issues down here. Only add things you can finish this sprint.

**Comment by dignifiedquire** [comment]
## Apps on IPFS

#### Lead: @dignifiedquire

#### Participants

- @dignifiedquire
- @jbenet
- @diasdavid
- @richardlitt
- @Noffle
- @whyrusleeping

## Agenda

- Webui
- JS IPFS API
  - New promise based api
- Website
  - https://ipfs.io/docs/install/ issues (https://github.com/ipfs/website/issues/95)
- registry-mirror

## Notes

### Webui

- WIP on Redux

### JS IPFS API

- Ship new promise based api

### Website

- Binary Installation: Link to dist.ipfs.io
- Update the version in descriptions
- no more go get!!
  - Alternatives: 
      - homebrew (other package managers??)
      - git clone && make install (Cyginw for windows!)
  - have some way of warning users who compile that they now need to make / use gx.
  (or find a go-get friendly work around for those dependents, as noffle suggests)
TODO: Create issue for updating package managers after release

TODO: Make sure consitency across all documenation!

### Registry Mirror
- Big refactoring by @diasdavid

**Comment by diasdavid** [comment]
## js-ipfs

#### Lead: David Dias

#### Participants

## Agenda

- Status Update
  - Object
  - Getting full interop with PeerInfo on Go (Voxelot)
  - Files
- Data Importing
- Goals of the week
  - finish files
  - get libp2p swarm up to js-ipfs (need a spdy build)
  - bitswap
- (extra) versioning?

**Comment by diasdavid** [comment]
#### DAVID DIAS TODO

- js-ipfs
  - js-ipfs-repo
  - js-ipfs-merkle-dag
  - js-ipfs-blocks
  - js-ipfs-data-importing
    - [ ] `files add`
- api documentation
- js-ipfs-api 
  - [x] CR + M https://github.com/ipfs/js-ipfs-api/pull/209
- libp2p
- npm on ipfs
- specs
- extra

**Comment by RichardLitt** [comment]
## 2dü

- [ ] Sprint Management
- [ ] Write the weekly roundup
- [ ] IPFS API
  - [ ] name
  - [ ] pin
  - [ ] ping
  - [ ] repo
  - [ ] resolve
  - [ ] stats
  - [ ] swarm
  - [ ] tar
  - [ ] tour
  - [ ] update

**Comment by dignifiedquire** [comment]
## TODO

### Webui
- [ ] Redux PR

### Distributions
- [ ] Code Signing
- [ ] Fix copyright notice https://github.com/ipfs/distributions/issues/52

**Comment by nginnever** [comment]
<h3> Nathan TODO</h3>

- js-peer-id
	- [x] generate public key from go-ipfs config
	- [ ] run karma + webpack tests
- js-ipfs
	- [x] ID command now uses new peer-id crypto
  	- [ ] node-forge noParsing with webpack 
  	- [ ] find more things to do :)

**Comment by noffle** [comment]
# noffle todo

- go-ipfs
  - [ ] PR: [prevent 'ipfs name publish' when /ipns is mounted](https://github.com/ipfs/go-ipfs/pull/2323)
- gx
  - [ ] figure out a way to keep `go get -u github.com/ipfs/go-ipfs` working with `gx`
  - [ ] get reproducible builds in `go-ipfs` / reproducible `gx` bootstrapping
- ipget
  - [ ] go over Q1 goals and prioritize ipget tasks / add them here

**Comment by whyrusleeping** [comment]
## go-ipfs

#### Lead: @whyrusleeping

#### Participants
@jbenet @diasdavid @noffle @lgierth @RichardLitt 

## Agenda

- gx transition
- CI needs to go green
- perf improvements
- 0.4.0 shipping requirements
- figuring out a way to not break downstream go-ipfs users (gx)

**You have 30 minutes for this agenda**, 5 minutes before the meeting ends, consider moving the remaining items to a github discussion thread so that all the other sprint meetings can start in time.

## Notes

- should try and make a website to generate git repos on the fly for gx packages

**Comment by lgierth** [comment]
## Infrastructure

#### Lead: @lgierth

#### Participants

- @diasdavid 
- @dignifiedquire 
- @jbenet
- @lgierth
- @RichardLitt 
- @whyrusleeping 

## Agenda

- Distributions
  - Signed releases 
- automated docker image ipfs/go-ipfs


## Notes

- signed releases on dist.ipfs.io
  - @dignifiedquire prepared https://github.com/ipfs/distributions/pull/51
  - we should specify the trust model here, so that we can audit it and reason about the edge cases
  - integration with ipfs-update
- security in general
  - assume we're targets
  - define a security policy for the community, with 
  - encrypted disks
  - gx feature request: sign off on diff when updating dependency
    - https://github.com/whyrusleeping/gx/issues/30
    - web-of-trust of dependency signatures
- better, more friendly gitcop
  - LXC uses jenkins for that https://github.com/lxc/lxc/pull/808#partial-pull-merging
  - ci step

**Comment by lgierth** [comment]
### @lgierth todo

- 0.4.0
  - [~] blog post about v04x/v03x
  - [ ] update pinbot
- docker
  - [ ] daily cronjob for jbenet/go-ipfs
  - [ ] blog post
  - [x] branches and tags
  - [ ] profile polishing
- infrastructure
  - [ ] captain's log
  - [ ] tests
  - [ ] simpler website deployments
- dnsaddr
  - [ ] spec it
    - `TXT bootstrap.ipfs.io dnsaddr=/ip4/104.131.131.82/udp/4002/utp/ipfs/QmSoLfoobar`
    - `dnsaddr -a /ip4/udp/utp/ipfs bootstrap.ipfs.io # => /ip4/104...`

**Comment by RichardLitt** [comment]
@whyrusleeping Can we have your to dos, too?

**Comment by Kubuxu** [comment]
#### @Kubuxu todo
go-ipfs:
* [ ] - PR: do not install gx if there is already one available in system - ipfs/go-ipfs/pull/2321
* [x] - PR: dns and resolve commands to ROAPI - ipfs/go-ipfs/pull/2291
gx:
* [x] - discuss gx-go and go get compat whyrusleeping/gx-go/issues/2
* [ ] - gx-lua written in go
specs:
* [x] - two stage  caching for IPNS/IPRS - ipfs/specs/issues/74
* [ ] - implement above in go-ipfs

**Comment by lgierth** [comment]
first!!! \o/

### @lgierth sprint update

This was a rather slow sprint for me -- plenty of good gateway debugging with @noffle and @whyrusleeping though.

- 0.4.0
  - [x] blog post about v04x/v03x, tweeted ipfs/blog#27
  - [x] fixed blog post ipfs/blog#28
  - [~] update pinbot
  - [x] refine multireq's status code precedence whyrusleeping/multireq@152e37c
  - [x] CR 
- docker
  - [ ] ~~daily cronjob for jbenet/go-ipfs~~ handed to @jbenet: ipfs/ops-requests#20
  - [~] blog post
  - [x] branches and tags
  - [ ] ~~profile polishing~~
- infrastructure
  - [x] debug gateway v03x hangs
  - [x] debug git + ipfs.io hangs
  - [ ] captain's log
  - [ ] tests
  - [ ] simpler website deployments
- others
  - [x] feedback on gx + go get whyrusleeping/gx-go#2
  - [ ] spec out dnsaddr
    - `TXT bootstrap.ipfs.io dnsaddr=/ip4/104.131.131.82/udp/4002/utp/ipfs/QmSoLfoobar`
    - `dnsaddr -a /ip4/udp/utp/ipfs bootstrap.ipfs.io # => /ip4/104...`
- fc00
  - [x] publish simple website http://fc00.io
  - [x] consolidate new fc00 irc network irc://irc.fc00.io
  - [x] plan trip to paris march 26th to april 6th (fc00 spec work and squatconf planning)

**Comment by Kubuxu** [comment]
#### @Kubuxu update
* go-ipfs:
 * [x] - PR: do not install gx if there is already one available in system - ipfs/go-ipfs/pull/2321
 * [x] - PR: dns and resolve commands to ROAPI - ipfs/go-ipfs/pull/2291
 * [~] - PR: update readme to mention gc - ipfs/go-ipfs/pull/2342
* gx:
 * [x] - discuss gx-go and go get compat whyrusleeping/gx-go/issues/2
 * [~] - gx-lua written in go
* specs:
 * [x] - two stage  caching for IPNS/IPRS - ipfs/specs/issues/74
 * [ ] - implement above in go-ipfs

**Comment by diasdavid** [comment]
## David Dias 🐔

#### js-ipfs
  - js-peer-id
    - [x] CRx2 + M https://github.com/diasdavid/js-peer-id/pull/4
  - js-ipfs-merkle-dag
    - [x] CR https://github.com/vijayee/js-ipfs-merkle-dag/pull/25
    - [x] CR https://github.com/vijayee/js-ipfs-merkle-dag/pull/28
  - js-ipfs-unixfs
    - [x] create, tests, release and stuff https://github.com/ipfs/js-ipfs-unixfs/pull/1 https://github.com/ipfs/js-ipfs-unixfs
  - js-ipfs-data-importing
    - [x] file + dir importing, unixfs style https://github.com/ipfs/js-ipfs-data-importing/pull/4
    - [~] fix bug on adding nested dirs, found a issue with go-ipfs https://github.com/ipfs/go-ipfs/issues/2348
  - js-peer-id
    - [x] CR+M https://github.com/diasdavid/js-peer-id/pull/4

#### js-ipfs-api 
  - [x] CR + M https://github.com/ipfs/js-ipfs-api/pull/209

#### libp2p
  - I listed this before as 'extra', but it really is part of libp2p, namely, the whole endeavour of packet switched networks over RTCDataChannels:
  - [x] https://github.com/diasdavid/piri-piri/pull/7 - upgrade piri-piri, the p2p browser testing thing, to use electron-spawn (so much more nice)
  - webrtc-explorer reboot
    - [~] https://github.com/diasdavid/webrtc-explorer/pull/10 - Almost there! Really really happy with the reboot, the amount of coverage, quality of the API and structure of the code, makes webrtc-explorer so much more useful 
    - [x] https://github.com/diasdavid/webrtc-explorer-peer-id/pull/1

#### npm on IPFS
  - [x] use and work with Jeromy at debugging problems in IPFS that were causing registry-mirror to crash. The last one was a oomd, but there is a patch on go-ipfs landing ['soon'](http://static.fjcdn.com/pictures/Soon_15db89_2831712.jpg)

#### specs
  - [x] fix typos, rebase master and M https://github.com/ipfs/specs/pull/65

**Comment by RichardLitt** [comment]
## This Week

- [x] Sprint Management
- [x] Write the weekly roundup
  - [ ] Send it out
- [x] IPFS API
  - [x] name
  - [x] pin
  - [x] ping
  - [x] repo
  - [x] resolve
  - [x] stats
  - [x] swarm
  - [x] tar
  - [x] tour
  - [x] update

## Extra
- [x] Change "interplanetary networks" notice https://github.com/ipfs/website/issues/96
- [x] Go docs: https://github.com/ipfs/go-ipfs/pull/2330
- [x] Community: cleaned up https://github.com/ipfs/community/pull/101, https://github.com/ipfs/community/pull/86, https://github.com/ipfs/community/pull/32
- [x] Submitted proposals for talking about name-your-contributors to csvconf and ScotlandJS
- [x] CR "docs: improve windows.md" https://github.com/ipfs/go-ipfs/pull/2337
- [x] Added "If You Are Ne"w section https://github.com/ipfs/pm/pull/92
- [x] Filled out contribution section for the weekly, and in the template. https://github.com/ipfs/weekly/pull/18, https://github.com/ipfs/weekly/pull/19

**Comment by noffle** [comment]
# noffle end-of-week

- pubsub
  - [x] [continued discussion](https://github.com/ipfs/notes/issues/108)
  - [x] wrote [ipfs-hyperlog](https://github.com/noffle/ipfs-hyperlog)
- go-ipfs
  - [x] PR: [prevent 'ipfs name publish' when /ipns is mounted](https://github.com/ipfs/go-ipfs/pull/2323)
  - [x] CR: ["allow promises to fail"](https://github.com/ipfs/go-ipfs/pull/2257/)
- js-ipfs
  - [x] wrote [ipfs-dag](https://github.com/noffle/ipfs-dag), a tiny simple ipfs dag module
- gx
  - [x] [figure out a way to keep `go get -u github.com/ipfs/go-ipfs` working with `gx`](https://github.com/whyrusleeping/gx-go/issues/2)
- ipget
  - [x] [1.0.0 roadmap](https://github.com/ipfs/ipget/issues/18)
  - [x] [cli design](https://github.com/ipfs/ipget/issues/21)
- multireq
  - [x] made some more [PR revisions](https://github.com/whyrusleeping/multireq/pull/2) for N-target support

**Comment by dignifiedquire** [comment]
## @dignifiedquire sprint update

### Webui
- Redux PR
  - [x] Streaming logs
  - [~] Peers page

### Distributions
- Code Signing
  - [x] Added document about the signing process for review
- [x] Fix copyright notice https://github.com/ipfs/distributions/issues/52

### Misc

- [x] Created https://github.com/dignifiedquire/karma-peer which will replace https://github.com/diasdavid/piri-piri and leverage karma for fully automated browser peer to peer testing. WebRTC and remote method execution are already working

**Comment by whyrusleeping** [comment]
- [x] make testing more reliable
  - [x] use port zero in sharness tests
  - [x] fix timing issue in t0065
  - although some gateway issues made gx unhappy and made tests fail
- [x] ipns a little faster
  - [x] increase dht K-Value to 20 (from 10)
  - [x] do publish steps in parallel
- [x] more gx vendoring
  - changed some deps from godeps to gx
- [ ] smarter gx updating
  - [ ] options to display diffs of changed deps
  - [x] check for similarly named deps in subdeps
- [x] CR+M: https://github.com/whyrusleeping/cbor/pull/4
- [x] help debug gateway out of disk space issue
- [~] patch memory issue registry mirror was having

**Comment by chriscool** [comment]
- [x] improved appveyor tests
- [x] rewrote Windows build documentation :star:
- [x] wrote script to check gx version
- [x] code reviewed using port zero for ipfs daemon in sharness tests

**Comment by nginnever** [comment]
<h3>Update</h3>
- js-ipfs
   - [x] ID command now uses new peer-id crypto
  - [x] find more things to do
  - [x] node-forge with webpack (ty dignifiedquire)
  - [ ] PR ID command (keygen part of issue #42)
  - [ ] remove github peer-id dep package

- js-ipfs-data-importing (js-ipfs issue #41)
 - [x] bufferImorter
 - [ ] streamImporter
 - [ ] browser / mocha tests

- js-peer-id
 - [x] run karma + webpack tests
 - [x] get PR merged (ty daviddias)
 - [ ] create issue / document forge build
 - [ ] republish npm package

- Webui
 - [ ] begin redux saga (issue #227)
 - [ ] research enzyme tests on components
 - [ ] document in contibuting.md

**Comment by RichardLitt** [comment]
Thanks all. Put any todos in the next sprint issue, #91.
