### ISSUE TITLE
Sprint H

### ISSUE THREAD

**Issue by jbenet** [ipfs/pm#9]
**Sprint Goals**:

This sprint is mainly about fixing lots of bugs/clunkiness. We've let some annoying issues creep in, and we need to fix them. IPFS must be -- above all -- robust, dependable, and useful.

**Sprint Participants**:

- @whyrusleeping @krl @cryptix @wking @jbenet @tv42 @gatesvp @chriscool @rht

**Sprint Deliverables**:

#### @whyrusleeping
- [x] https://github.com/ipfs/go-ipfs/issues/1050
  - [x] https://github.com/ipfs/go-ipfs/pull/1254
- [x] bitswap perf https://github.com/ipfs/go-ipfs/issues/1218
- [ ] better add perf https://github.com/ipfs/go-ipfs/issues/1223
  - [x] https://github.com/ipfs/go-ipfs/issues/1242
  - [ ] https://github.com/ipfs/go-ipfs/issues/1274
  - [ ] https://github.com/ipfs/go-ipfs/issues/1216 slow add of 155GB of data
- [x] https://github.com/ipfs/go-ipfs/issues/1130
- [ ] pinning migration https://github.com/ipfs/fs-repo-migrations/pull/7
- [ ] symlinks (ran into this again) (@whyrusleeping)
- [x] https://github.com/ipfs/go-ipfs/pull/1242 remove unnecessary flush
- [x] https://github.com/ipfs/go-ipfs/pull/1276
- [x] https://github.com/ipfs/go-ipfs/pull/1275
- [x] https://github.com/ipfs/go-ipfs/pull/1270
- [x] https://github.com/ipfs/go-ipfs/pull/1262
- [ ] https://github.com/ipfs/go-ipfs/issues/1246 Avoid dialing known local addresses when not in that network
  - posted iptables commands to help issue
- [ ] https://github.com/ipfs/go-ipfs/issues/1247 Config option to disable dialing specific subnets entirely

#### @krl
- [ ] https://github.com/ipfs/go-ipfs/issues/1153
- [ ] electron shell app https://github.com/ipfs/webui/54
- [ ] http://github.com/ipfs/webui/43 (have this somehow prepared already)

#### @jbenet
- [ ] https://github.com/ipfs/go-ipfs/issues/1214 (verify)
- [ ] https://github.com/ipfs/go-ipfs/issues/1197
- [x] swapping out the stream muxer (or having multiplex in go)
- [ ] get a build of go-ipfs for node-ipfs compatibility
- [ ] readme on how to implement ipfs on another lang
- [x] DTN Talk
- [x] IPFS Berlin meetup(s)
- [ ] DHT Records Spec!
- [ ] Keystore Spec!
- [ ] setup slack
- [x] meeting with onename folks

#### @tv42 
- [ ] pinning in blockstore (merge)
  - blocked on https://github.com/ipfs/fs-repo-migrations/pull/7
- [ ] pinning perf? log?
- [ ] s3 datastore

### @gatesvp
- [ ] https://github.com/ipfs/go-ipfs/issues/1211 ipfs refs --recursive --unique is not recursive
- [ ] https://github.com/ipfs/go-ipfs/pull/1232 - .ipfsignore support

### @chriscool
- [x] https://github.com/jbenet/git-push-each/issues/2
- [x] https://github.com/jbenet/git-push-each/pull/6

### @wking
- [x] landing namesys recursion (https://github.com/ipfs/go-ipfs/pull/1208)
- [ ] posting a list of possible add APIs for discussion (to help with https://github.com/ipfs/go-ipfs/pull/1136)
- [ ] start working on an IPFS storage driver for https://github.com/docker/distribution

### @rht
- [x] https://github.com/ipfs/go-ipfs/pull/1239 go fmt test check 
- [ ] https://github.com/ipfs/go-ipfs/issues/740
- [ ] https://github.com/ipfs/go-ipfs/issues/143
- [ ] https://github.com/ipfs/go-ipfs/issues/736
- [ ] CR bot (go lint & vet should be put here instead), constraint that commits can't fail the test at any point in history

#### @cryptix 
- ?

#### triage - anyone can pick these up
- [ ] https://github.com/ipfs/go-ipfs/issues/1248 fix fuse unmount
- [ ] https://github.com/ipfs/go-ipfs/issues/1241 network write latencies
- [ ] https://github.com/ipfs/go-ipfs/issues/1222 add uses a lot of ram and cpu
- [ ] daemon init cleanup?
- [ ] https://github.com/ipfs/go-ipfs/issues/1224 decimate eventlog 
- [ ] stable resolution (tests)

**Comment by whyrusleeping** [comment]
In the next sprint i'm going to investigate goquic and see if its viable for us yet. The hunch is that the latencies seen in 1241 are caused by tcp (likely) and using quic would solve that

**Comment by tv42** [comment]
Hoping for some kind soul to create a migration for https://github.com/ipfs/go-ipfs/pull/1225 (pinning) and merge that, then I'll rebase https://github.com/ipfs/go-ipfs/pull/1261 on that. Not much point in pushing forward before those get merged & I get more feedback.

**Comment by whyrusleeping** [comment]
@tv42 i'm waiting on some CR here: https://github.com/ipfs/fs-repo-migrations/tree/2-to-3
