### ISSUE TITLE
Sprint: February 16 (Tuesday)

### ISSUE THREAD

**Issue by RichardLitt** [ipfs/pm#91]
# Sprint February 16

Note that this sprint has been moved from the normal Monday February 15th sprint. 

The IPFS Weekly for this week is [here](https://github.com/ipfs/weekly/pull/21). Please add anything cool which happens over the course of this week to it. 

## Sprint Discussions

[Schedule](https://github.com/ipfs/pm#sprint-discussion-schedule)

Please take notes in a separate pad, if you can, and link it here.

Endeavour         | Lead                | Time (PDT - **UTC/Z** - CET) | Pad
:---------------: | :-----------------: | :--------------------------: | :----:
sync              | Rich Littauer       | 9:00pDT **17:00Z** 18:00CET  | IRC: #ipfs on Freenode
apps on ipfs      | Friedel Ziegelmayer | 10:30PDT **18:30Z** 19:30CET | https://public.etherpad-mozilla.org/p/ipfs-feb-16-apps-on-ipfs
infrastructure    | Lars Gierth         | 11:00PDT **19:00Z** 20:00CET | https://public.etherpad-mozilla.org/p/ipfs-feb-16-infrastructure
libp2p            | David Dias          | 11:30PDT **19:30Z** 20:30CET | https://public.etherpad-mozilla.org/p/ipfs-feb-16-libp2p
js-ipfs           | David Dias          | 12:00PDT **20:00Z** 21:00CET | https://public.etherpad-mozilla.org/p/ipfs-feb-16-js-ipfs

#### Wednesday

Endeavour         | Lead                | Time (PDT - **UTC/Z** - CET) | Pad
:---------------: | :-----------------: | :--------------------------: | :----:
go-ipfs           | Jeromy Johnson      | 10:30PDT **18:30Z** 19:30CET | https://public.etherpad-mozilla.org/p/ipfs-feb-16-go-ipfs

Please add the Agenda to the Pad before the endeavour sprint starts.

## Sprint Deliverables

- Add your tasks below in a comment, that way we only have people listed who are really in the sprint
- Add links to issues down here. Only add things you can finish this sprint.

**Comment by RichardLitt** [comment]
Added note about the Weekly for this week, which can be found here: https://github.com/ipfs/weekly/pull/21. Add stuff as it happens!

**Comment by lgierth** [comment]
## Infrastructure

#### Lead: @lgierth

#### Participants

- @diasdavid
- @dignifiedquire
- @richardlitt
- @whyrusleeping

## Agenda

- 0.4.0
  - multireq and gateway issues
  - utp port 4001 vs 4002

- metrics
  - no metrics for v03x yet
  - http response metrics are from go-ipfs's point of view, not nginx's
  - alerts


## Notes

- multireq/gateway issues should be resolved now, why says it looks better now
- utp, let's pick the official-ish port 4737
- let's also update the tcp port
  - come up with a list of stuff that needs to be updated, beforehand, so that we don't overlook anything important
  - what if more transports? 4737 is multistream in general, both tcp and udp
- pinbot
  - @whyrusleeping is gonna add comment requirement for pins
- metrics
  - nginx response status metrics
    - commercial module
    - parse logs?
  - adding metrics
    - add scraping target to prometheus.yml
    - experiment with queries at metrics.i.ipfs.io/prometheus
    - add to dashboard
- alerts
  - gateway availability
  - swarm availability
  - sms alerts
  - no on-call schedules for the foreseeable future

**Comment by diasdavid** [comment]
## Libp2p

#### Lead: David Dias

## Agenda

- webrtc-explorer
- piri-piri & karma-peer

## Notes

- NEXT
- [ ] finish webrtc-explorer reboot
- [ ] impl js-ipfs swarm connect
- [ ] karma-peer spawn browser on demand
- [ ] karma-peer electron-spawn
- [ ] go-libp2p connect request

**Comment by diasdavid** [comment]
## js-ipfs

#### Lead: David Dias

#### Participants

## Agenda

- Update
- UnixFS
  - should we have a thing to import directories?

## Notes

NEXT
- [ ] fix nested dir importing on data-importing
- [ ] data-importing bufferImporter
- [ ] data-importing streamImporter
- [ ] data-importing export (for ipfs files cat)
- [ ] bitswap
- [ ] core-api specs

**Comment by dignifiedquire** [comment]
## Apps on IPFS

#### Lead: Friedel (@dignifiedquire)

#### Participants

- @dignifiedquire
- @RichardLitt 
- @diasdavid 
- @noffle 
- @whyrusleeping 

## Agenda

- Webui Update
- ipget 1.0.0 roadmap (https://github.com/ipfs/ipget/issues/18)

## Notes

### Webui
- Demo of the new logs and peers page by @dignifiedquire
- Investigate bringing https://github.com/ipfs/dataviz/issues/8 into the webui

### ipget
- Update about the roadmap: https://github.com/ipfs/ipget/issues/18

**Comment by dignifiedquire** [comment]
# @dignifiedquires TODOs

## Content Work

### Update install instructions on the website

- [X] Binary Installations: Link to dist.ipfs.io
- [X] Update the version in descriptions
- [X] No more \`go get\`

### Check Needs Review

<https://github.com/issues?utf8=%E2%9C%93&q=is%3Aopen+org%3Aipfs+label%3A%22needs+review%22>
- [X] <https://github.com/ipfs/website/pull/97>
- [X] <https://github.com/ipfs/community/pull/106>
- [X] <https://github.com/ipfs/community/pull/32>
- [X] <https://github.com/ipfs/community/pull/86>
- [X] <https://github.com/ipfs/community/pull/101>
- [X] <https://github.com/ipfs/http-api-spec/pull/56>
- [X] <https://github.com/ipfs/http-api-spec/pull/55>
- [X] <https://github.com/ipfs/http-api-spec/pull/54>
- [X] <https://github.com/ipfs/http-api-spec/pull/53>
- [X] <https://github.com/ipfs/http-api-spec/pull/52>
- [X] <https://github.com/ipfs/http-api-spec/pull/51>
- [X] <https://github.com/ipfs/http-api-spec/pull/50>
- [X] <https://github.com/ipfs/http-api-spec/pull/49>
- [X] <https://github.com/ipfs/http-api-spec/pull/48>
- [X] <https://github.com/ipfs/http-api-spec/pull/47>
- [X] <https://github.com/ipfs/http-api-spec/pull/46>
- [X] <https://github.com/ipfs/http-api-spec/pull/45>
- [X] <https://github.com/ipfs/http-api-spec/pull/44>
- [X] <https://github.com/ipfs/http-api-spec/pull/43>
- [X] <https://github.com/ipfs/http-api-spec/pull/42>
- [X] <https://github.com/ipfs/http-api-spec/pull/41>
- [X] <https://github.com/ipfs/http-api-spec/pull/40>
- [X] <https://github.com/ipfs/http-api-spec/pull/39>
- [X] <https://github.com/ipfs/http-api-spec/pull/37>
- [X] <https://github.com/ipfs/http-api-spec/pull/36>
- [X] <https://github.com/ipfs/http-api-spec/pull/34>
- [X] <https://github.com/ipfs/http-api-spec/pull/32>
- [X] <https://github.com/ipfs/http-api-spec/pull/29>

### Review Blog Posts

- [ ] dist.ipfs.io release <https://github.com/ipfs/blog/pull/23>
- [ ] 0.4.0 release <https://github.com/ipfs/blog/pull/30>

### Post weekly details

- [x] Add IPFS Apps notes
- [x] Add weekly todos

## Webui

- [ ] Redux <code>[0/6]</code>
    - [ ] Split large \`index.js\` files into multiple parts <code>[0/3]</code>
        - [ ] Reducers
        - [ ] Sagas
        - [ ] actions
    - [ ] Split large containers into smaller ones <code>[/]</code>
        - [ ] Logs
        - [ ] Peers
    - [ ] Add location data to the home page
    - [ ] Peers <code>[0/2]</code>
        - [ ] Finish tests for cache
        - [ ] Add polling
    - [ ] Config editor
- [ ] Review PRs <code>[0/2]</code>
    - [ ] <https://github.com/ipfs/webui/pull/248>
    - [ ] <https://github.com/ipfs/webui/pull/247>

## Distributions

- [ ] Code Signing <code>[0/2]</code>
    - [ ] Review PR comments
    - [ ] Investigate The Update Framework

## IPFS GeoIP

- [ ] Add all the data to the 0.3 and 0.4 network

**Comment by nginnever** [comment]
<h3>@nginnever TODO</h3>
- js-ipfs
  - [ ] PR ID command (keygen part of issue #42)

- js-ipfs-data-importing (js-ipfs issue #41)
 - [ ] bufferImorter
 - [ ] streamImporter
 - [ ] browser / mocha tests

- js-peer-id
 - [ ] create issue / document forge build
 
- Webui
 - [ ] begin redux saga (issue #227)
 - [ ] research enzyme tests on components
 - [ ] document in contibuting.md

**Comment by diasdavid** [comment]
#### DAVID DIAS TODO

- js-ipfs
  - js-ipfs-data-importing
    - [x] fix nested dir bug https://github.com/ipfs/js-ipfs-data-importing/pull/5
- api documentation
  - [ ] internals API https://github.com/ipfs/specs/pull/78
- js-ipfs-api 
- libp2p
  - webrtc-explorer reboot https://github.com/diasdavid/webrtc-explorer/pull/10
- npm on ipfs
- specs
- extra
  - [ ] make a contribution to go-ipfs

**Comment by RichardLitt** [comment]
#### To Do
- [ ] Sprint Management
- [ ] Write the weekly roundup
- [ ] HTTP-API Group `files`: https://github.com/ipfs/http-api-spec/issues/57
- [ ] Review all of the HTTP API stuff
- [ ] CR:
  - [x] "feat: Setup code signing for all packages using opgenpgp" https://github.com/ipfs/distributions/pull/51
  - [ ] 0.4.0 blogpost https://github.com/ipfs/blog/pull/30, https://github.com/ipfs/blog/issues/28
- [ ] Publish the dist blog post https://github.com/ipfs/blog/pull/23

**Comment by Kubuxu** [comment]
#### @Kubuxu TODO:
* [ ] - gx-lua in go or maybe once more in Lua
* [ ] - two stage caching for IPNS

**Comment by whyrusleeping** [comment]
## Go-IPFS

#### Lead: Jeromy

#### Participants

## Agenda

- 0.4.0 testing
  - large long running tests
- get CI green
  - a few intermediate sharness failures
  - appveyor
- issue template (yay new github features)


**You have 30 minutes for this agenda**, 5 minutes before the meeting ends, consider moving the remaining items to a github discussion thread so that all the other sprint meetings can start in time.

## Notes

Actionables:
    - fix gx installs on appveyor (looks like gopath issues?)
    - fix sharness tests on appveyor (theres a lot here, every bit helps)
    - write up an issue template
    - modularize iptb code, for reuse in large testing environments
    - ALL: try out a new ipfs command (look in `ipfs commands`)

##### After sprint meeting is finished, create the respective action items on the Github sprint issue

**Comment by noffle** [comment]
# noffle todo

- go-ipfs
  - [ ] [PR](https://github.com/ipfs/go-ipfs/pull/2323): don't let users manually publish when /ipns is mounted
  - [ ] discuss pre-0.4.0-release [large stress testing](https://github.com/ipfs/go-ipfs/issues/2343) with @whyrusleeping 
- multireq
  - [ ] [PR](https://github.com/whyrusleeping/multireq/pull/2): support N requests
- gx-go
  - [ ] finish 'go get' [compatibility fixes](https://github.com/whyrusleeping/gx-go/issues/2
)
  - [ ] go-ipfs 'go get'-able again
- js-ipfs
  - [ ] rename [ipfs-dag](https://github.com/noffle/ipfs-dag) to ipfs-merkle-dag-node
  - [ ] add my notes/thoughts to @diasdavid's [internal API docs](https://github.com/ipfs/specs/pull/78)

**Comment by lgierth** [comment]
### @lgierth todo

- 0.4.0
  - [x] CR blog post https://github.com/ipfs/blog/pull/30
  - [x] add current website to v03x too
  - [ ] fix pinbot
  - [ ] port 4737?
- infrastructure
  - [~] resize droplets
  - [~] bring back ipfs metrics on master
  - [ ] v03x metrics
  - [ ] nginx metrics
  - [ ] migrate more ansible playbooks to provsn
- org stuff
  - [ ] weekly
  - [ ] infrastructure goals
  - [ ] set up & try out orbit

**Comment by dignifiedquire** [comment]
## @dignifiedquire SprintUpdate

### Content Work

- [-] Update install instructions on the website [3/4]
  - [x] Binary Installations: Link to dist.ipfs.io
  - [x] Update the version in descriptions
  - [x] No more `go get`
  - [ ] Wait for review and merge
- [x] Check Needs Review
  - [x] https://github.com/ipfs/website/pull/97
  - [x] https://github.com/ipfs/community/pull/106
  - [x] https://github.com/ipfs/community/pull/32
  - [x] https://github.com/ipfs/community/pull/86
  - [x] https://github.com/ipfs/community/pull/101
  - [x] https://github.com/ipfs/http-api-spec/pull/56
  - [x] https://github.com/ipfs/http-api-spec/pull/55
  - [x] https://github.com/ipfs/http-api-spec/pull/54
  - [x] https://github.com/ipfs/http-api-spec/pull/53
  - [x] https://github.com/ipfs/http-api-spec/pull/52
  - [x] https://github.com/ipfs/http-api-spec/pull/51
  - [x] https://github.com/ipfs/http-api-spec/pull/50
  - [x] https://github.com/ipfs/http-api-spec/pull/49
  - [x] https://github.com/ipfs/http-api-spec/pull/48
  - [x] https://github.com/ipfs/http-api-spec/pull/47
  - [x] https://github.com/ipfs/http-api-spec/pull/46
  - [x] https://github.com/ipfs/http-api-spec/pull/45
  - [x] https://github.com/ipfs/http-api-spec/pull/44
  - [x] https://github.com/ipfs/http-api-spec/pull/43
  - [x] https://github.com/ipfs/http-api-spec/pull/42
  - [x] https://github.com/ipfs/http-api-spec/pull/41
  - [x] https://github.com/ipfs/http-api-spec/pull/40
  - [x] https://github.com/ipfs/http-api-spec/pull/39
  - [x] https://github.com/ipfs/http-api-spec/pull/37
  - [x] https://github.com/ipfs/http-api-spec/pull/36
  - [x] https://github.com/ipfs/http-api-spec/pull/34
  - [x] https://github.com/ipfs/http-api-spec/pull/32
  - [x] https://github.com/ipfs/http-api-spec/pull/29

- [x] Review Blog Posts
  - [x] dist.ipfs.io release https://github.com/ipfs/blog/pull/23
  - [x] 0.4.0 release https://github.com/ipfs/blog/pull/30
- [x] Post weekly details
  - [x] Add IPFS Apps notes
  - [x] Add weekly todos

### Webui
- [-] Redux
  - [-] Split large `index.js` files into multiple parts
    - [ ] Reducers
    - [-] Sagas
    - [ ] actions
  - [-] Peers
    - [x] Finish tests for cache
    - [ ] Add polling
  - [ ] Config editor
- [-] Review PRs
  - [x] CR and Merge https://github.com/ipfs/webui/pull/248
  - [x] CR and Merge https://github.com/ipfs/webui/pull/252
  - [ ] CR and Merge https://github.com/ipfs/webui/pull/253
  - [x] CR and Merge https://github.com/ipfs/webui/pull/247

## IPFS GeoIP
- [x] Try and fail to generate the new data on the 0.4 network https://github.com/ipfs/ipfs-geoip/issues/6#issuecomment-185237212
- [x] Fix generate script
  - [x] Understand it
  - [x] Refactor
    - [x] Write tests
    - [x] Add all the data to the 0.4 network
    - [x] Add all the data to the 0.3 network
  - [x] Create PR: https://github.com/ipfs/ipfs-geoip/pull/7

### Bonus Things

- [x] CR https://github.com/ipfs/js-ipfs/pull/68
- [x] CR & Merge https://github.com/ipfs/js-ipfsd-ctl/pull/57
- [x] Help @diasdavid with https://github.com/ipfs/js-ipfs/pull/69, resolved in https://github.com/ipfs/js-ipfs-api/pull/215
- [-] Bad Website performance: https://github.com/ipfs/website/issues/100

### Station

- [x] Dependency updates: https://github.com/ipfs/station/pull/197
- [x] Fix file upload https://github.com/ipfs/station/pull/198

### dignified hacks

- [-] Twitch
  - [x] Sign up
  - [ ] Configure all the things
- [x] Find good screen recorder: OBS
- [ ] Test out
  - [ ] [OBS](https://obsproject.com/)
  - [ ] Live stream
  - [ ] [KeyCastr](https://github.com/keycastr/keycastr)
  - [ ] Archiving
- [ ] Plan first episode

**Comment by Kubuxu** [comment]
#### @Kubuxu sprint update:

**Comment by Kubuxu** [comment]
#### @Kubuxu sprint update:
* [ ] gx-lua in go or maybe once more in Lua
* [ ] two stage caching for IPNS
* [~] investigate CRDT over IPFS/IPLD
* [x] add cdnjs to my dedicated - available at fs:/ipns/cdnjs.ipfs.ovh/
* [x] host glowing-bear on IPFS (using cdnjs) and add `fs:/` handler to it. -  available at fs:/ipns/glowing-bear.ipfs.ovh/

**Comment by RichardLitt** [comment]
## This Week

- [x] Sprint Management
- [ ] Write the weekly roundup
- [x] HTTP-API Group `files`: https://github.com/ipfs/http-api-spec/issues/57
- [~] Review all of the HTTP API stuff
- [~] Publish the dist blog post https://github.com/ipfs/blog/pull/23
- [x] CR:
  - [x] "feat: Setup code signing for all packages using opgenpgp" https://github.com/ipfs/distributions/pull/51
  - [x] 0.4.0 blogpost https://github.com/ipfs/blog/pull/30, https://github.com/ipfs/blog/issues/28
  - [x] "Revise installation docs to reflect the latest changes" https://github.com/ipfs/website/pull/98

## Extra
- [~] Update the commands page on the website. Need help: https://github.com/ipfs/go-ipfs/issues/1735
- [x] CR "Add information about installing gx into readme" go-ipfs#2342
- [x] CRM "Idea: IPFS Community Events" https://github.com/ipfs/community/pull/46
- [x] Updated dist.ipfs.io blog draft https://github.com/ipfs/blog/pull/23
- [x] go-ipfs docs: https://github.com/ipfs/go-ipfs/pull/2351, https://github.com/ipfs/go-ipfs/pull/2352, https://github.com/ipfs/go-ipfs/pull/2353, https://github.com/ipfs/go-ipfs/pull/2362, https://github.com/ipfs/go-ipfs/pull/2363, https://github.com/ipfs/go-ipfs/pull/2364, https://github.com/ipfs/go-ipfs/pull/2366, https://github.com/ipfs/go-ipfs/pull/2367, https://github.com/ipfs/go-ipfs/pull/2369, https://github.com/ipfs/go-ipfs/pull/2377
- [x] update-ipfs doc fixes: https://github.com/RichardLitt/ipfs-update/tree/feature/doc-fixes
- [x] Update commands page on the website https://github.com/ipfs/website/pull/99
- [x] Opened issue about issue templates https://github.com/ipfs/community/issues/108
- [x] pm: use GitHub usernames and not real names https://github.com/ipfs/pm/pull/94
- [x] Added man-pages attribution to docs-styleguide. https://github.com/ipfs/community/pull/106

**Comment by whyrusleeping** [comment]
- fixed revert bug in fs-repo-migrations (#23)
- fixed a panic in argument parsing in go-ipfs (#2354)
- set up CI for go-libp2p (#16)
- add observed remote addr on handshake (#15)
- fix t0065 timing issue (#2346)
- reduce memory usage of request log (#2344)
- merged lars changes into multireq
- fix filepath checking for gx on windows
- CR/Merge #2333 #2377 #2372 #2373 #2374 #2366 #2362 #2363 #2364 #2367 #2365 #2369 #2353 #2352 #2351 #2342 #2298 #2299 #2321 #2337

**Comment by lgierth** [comment]
### @lgierth update

This week didn't quite go as planned either. Looked after stability problems with docker and the go-ipfs containers which made me decide to switch to runc+runit as a runtime, which is work-in-progress. Also threw a bit of hardware at the problem (resized our vhosts).

- 0.4.0
  - [x] CR blog post ipfs/blog#30
  - [x] CR install instructions ipfs/website#98
  - [x] add current website to v03x too
  - [~] geoip pinning ipfs/ipfs-geoip#7
  - [ ] fix pinbot
  - [ ] port 4737?
- infrastructure
  - [x] resize droplets
  - [~] bring back ipfs metrics on master
  - [x] v03x metrics
  - [~] migrate from docker to runc+runit
  - [ ] nginx metrics
  - [ ] migrate more ansible playbooks to provsn
- org stuff
  - [ ] weekly
  - [ ] infrastructure goals
  - [ ] amsterdam travels
  - [ ] u.s./canada travels
  - [ ] set up & try out orbit

**Comment by nginnever** [comment]
<h3>Update</h3>
- js-ipfs
  - [x] PR ID command (keygen part of issue #42)
- js-ipfs-data-importing (js-ipfs issue #41)
 - [x] bufferImorter
 - [~] streamImporter (more questions)
- js-peer-id
 - [x] create issue / document forge build
- Webui
 - [x] begin redux saga (issue #227)
 - [x] research enzyme tests on components

**Comment by noffle** [comment]
# noffle end of week

- go-ipfs
  - [~] [PR](https://github.com/ipfs/go-ipfs/pull/2323): don't let users manually publish when /ipns is mounted
  - Help out fixing test failures
    - [x] https://github.com/ipfs/go-ipfs/issues/2361
    - [~] https://github.com/ipfs/go-ipfs/issues/2347
    - [~] https://github.com/ipfs/go-ipfs/issues/1936
- multireq
  - [~] [PR](https://github.com/whyrusleeping/multireq/pull/2): support N requests
- gx-go
  - [x] 'go get' working using ipfs.io gateway
  - [ ] finish 'go get' [compatibility fixes](https://github.com/whyrusleeping/gx-go/issues/2
)
- [ipfs-hyperlog](https://github.com/noffle/ipfs-hyperlog)
  - [x] implement custom hashing on hyperlog
  - [x] rewrite ipfs-hyperlog as a tiny (73 line) module that composes hyperlog
- js-ipfs
  - [x] discuss [ipfs-dag](https://github.com/noffle/ipfs-dag) improvements with @diasdavid

**Comment by diasdavid** [comment]
### David Dias Check in

**js-ipfs**
  - [x] CR+M https://github.com/ipfs/js-ipfs/pull/68
  - [x] All the things listed on this PR https://github.com/ipfs/js-ipfs/pull/69, still more to come
    - generic
      - [x] being able to start and stop the daemon (graciously using SIGINT)
      - [x] upgrade the http-api to have 2 conns (one for API and the other for gateway)
      - [x] lock the repo if a daemon is being run (a la go-ipfs)
      - [x] update the tests to follow this new pattern
      - [x] merge cli offline and cli with api running tests
      - [x] adding tests with js-ipfs-api for extra level of interop guarantees
   - http-api endpoints that follow with the http-api-spec
     - [x] version
     - [x] bootstrap
  - js-ipfs-data-importing
    - [x] fix nested dir bug https://github.com/ipfs/js-ipfs-data-importing/pull/5

**js-ipfs-api**
  - [x] CR+M https://github.com/ipfs/js-ipfs-api/pull/215

**ipfs-geoip**
  - [x] CR https://github.com/ipfs/ipfs-geoip/pull/7

**libp2p**
  - [~] webrtc-explorer reboot https://github.com/diasdavid/webrtc-explorer/pull/10 - Did more work, still not finished as my attention was dragged to js-ipfs and other goals, nevertheless did:
    - [x] establish DataChannels between peers (channel manager) 
    - [x] fill finger tables correctly on the browser
    - [x] change the design and spec out the necessary bits to be interface-transport and interface-connection compatible
  - [x] create custom build of libp2p for js-ipfs  https://github.com/ipfs/js-libp2p-ipfs/pull/1 (also created the repo for the browser one which will have different transports https://github.com/ipfs/js-libp2p-ipfs-browser)
**npm on ipfs**
  - [~] _[777509/785588]_ super close to have the complete clone (overcome the IPFS memory leaks by just monitoring the process and restarting after it gets too 'hot')

**station**
  - [x] CR https://github.com/ipfs/station/pull/198

**ipscend**
  - [~] working on an ipscend blog post for today that raised all of the following: 
    - [x] https://github.com/diasdavid/ipscend/pull/42
    - [x] CR+ M https://github.com/diasdavid/ipscend/pull/44
    - [x] CR + M https://github.com/diasdavid/ipscend/pull/43
    - [x] CR + M https://github.com/diasdavid/ipscend/pull/40
    - [x] https://github.com/diasdavid/ipscend/pull/45
    - [x] https://github.com/diasdavid/ipscend/pull/46

**js-ipfsd-ctl** - Features that I needed for ipscend
  - [x] custom api addr https://github.com/ipfs/js-ipfsd-ctl/pull/60
  - [x] custom gateway addr https://github.com/ipfs/js-ipfsd-ctl/pull/61

**specs**
  - [x] pave the path for the internals API spec https://github.com/ipfs/specs/pull/78
  - http-api
    - [x] input on https://github.com/ipfs/http-api-spec/pull/58
    - [x] R https://github.com/ipfs/http-api-spec/pull/24
    - [x] R https://github.com/ipfs/http-api-spec/pull/29
    - [x] R https://github.com/ipfs/http-api-spec/pull/32
    - [x] R https://github.com/ipfs/http-api-spec/pull/34
    - [x] R https://github.com/ipfs/http-api-spec/pull/35
    - [x] R https://github.com/ipfs/http-api-spec/pull/37
    - [x] R https://github.com/ipfs/http-api-spec/pull/40
    - [x] R https://github.com/ipfs/http-api-spec/pull/41
    - [x] R https://github.com/ipfs/http-api-spec/pull/42
    - [x] R https://github.com/ipfs/http-api-spec/pull/43
    - [x] R https://github.com/ipfs/http-api-spec/pull/44

**Comment by RichardLitt** [comment]
Thanks, all. Please add your starred updates to the weekly: https://github.com/ipfs/weekly/pull/21. 

The next sprint is: https://github.com/ipfs/pm/issues/93.
