### ISSUE TITLE
Sprint: February 22 -- March 7

### ISSUE THREAD

**Issue by RichardLitt** [ipfs/pm#93]
# Sprint February 22nd

## Sprint Discussions

[Schedule](https://github.com/ipfs/pm#sprint-discussion-schedule)

Please take notes in a separate pad, if you can, and link it here.

Endeavour         | Lead            | Time (PDT - **UTC/Z** - CET) | Pad
:---------------: | :-------------: | :--------------------------: | :----:
sync              | @RichardLitt    | 9:00pDT **17:00Z** 18:00CET  | IRC: #ipfs on Freenode
apps on ipfs      | @dignifiedquire | 10:30PDT **18:30Z** 19:30CET | https://public.etherpad-mozilla.org/p/ipfs-feb-22-apps-on-ipfs
infrastructure    | @lgierth        | 11:00PDT **19:00Z** 20:00CET | https://public.etherpad-mozilla.org/p/ipfs-feb-22-infrastructure
libp2p            | @diasdavid      | 11:30PDT **19:30Z** 20:30CET | https://public.etherpad-mozilla.org/p/ipfs-feb-22-libp2p
js-ipfs           | @diasdavid      | 12:00PDT **20:00Z** 21:00CET | https://public.etherpad-mozilla.org/p/ipfs-feb-22-js-ipfs
go-ipfs           | @whyrusleeping  | 12:30PDT **20:30Z** 21:30CET | https://public.etherpad-mozilla.org/p/ipfs-feb-22-go-ipfs

Please add the Agenda to the Pad before the endeavour sprint starts.

## Sprint Deliverables

- Add your tasks below in a comment, that way we only have people listed who are really in the sprint
- Add links to issues down here. Only add things you can finish this sprint.

**Comment by dignifiedquire** [comment]
## Apps on IPFS

#### Lead: @dignifiedquire

#### Participants

- @dignifiedquire
- @jbenet 
- @noffle 
- @RichardLitt 
- @diasdavid 


## Agenda

- Webui
  - Contributions
  - ipfs geoip  
- Station
  - ARM
  - Stability
  - Tests
- Dignified Hacks


## Notes
- Webui
  - Contributions
    - TODO(@dignifiedquire): Writing captainlog
    - Please ask questions if you have some
    - Updated https://github.com/ipfs/webui/pull/229 with more details about the work needed to be done
  - ipfs geoip
    - Nearly working, just missing pin on 0.3  
- Station
  - ARM
    - Blocked on some electron-packager/electron issues for proper build
  - Stability
  - Tests
- Dignified Hacks
  - First episode of @dignifiedquire hacking on the webui this week

**Comment by RichardLitt** [comment]
#### To Do this week

- [ ] Sprint Management
- [ ] Write the weekly roundup
- [ ] Review all open PRs on http-api-spec
- [ ] Fill out RichardLitt/better-github-templates to answer https://github.com/ipfs/community/issues/108

**Comment by diasdavid** [comment]
## Libp2p

#### Lead: @diasdavid

#### Participants

## Agenda

Status Update
Next:
  finish webrtc-explorer reboot
  libp2p-utp update to utp-native
  libp2p-websockets for js and go (cause go doesn't have a good WebRTC implementation)
  exo-transports spec

**Comment by noffle** [comment]
# @noffle sprint goals

- finish outstanding PRs + get them merged
  - [ ] https://github.com/whyrusleeping/multireq/pull/2
  - [ ] https://github.com/ipfs/go-ipfs/pull/2323
  - [ ] https://github.com/ipfs/go-ipfs/pull/2368
  - [ ] https://github.com/ipfs/go-ipfs/pull/2370
- make go-ipfs compatible with 'go get' again
  - [ ] work /w lgierth to solve gateway unreliability
  - [ ] modify gx-go to publish a git repo that is dumb-http compatible
  - [ ] modify gx-go to rewrite urls to use ipfs.io
  - [ ] TEST: full publish workflow of a current go-ipfs dep that has no children
- integrate ipfs-dag improvements back into js-ipfs-merkle-dag
  - [ ] rename to ipfs-merkle-dag-node
(as opposed to the ipld type, ipfs-ipld-node)
  - [ ] add my notes/thoughts to daviddias' [internal API docs](https://github.com/ipfs/specs/pull/78)
  - [ ] split js-ipfs-merkle-dag into ipfs-merkle-dag-service (remove node impl)

**Comment by diasdavid** [comment]
## js-ipfs

#### Lead: @diasdavid

#### Participants

- @jbenet
- @RichardLitt
- @diasdavid
- Nathan

## Agenda

- Status Update
- Next: 
    - finish https://github.com/ipfs/js-ipfs/pull/69, which includes
      - http-api for every feature already implemented with tests and js-ipfs-api tests (for max interop)
      - make the cli use the http-api if the daemon is running
    - integrate libp2p-ipfs into js-ipfs to have swarm listen and connect
    - bitswap

**Comment by diasdavid** [comment]
#### DAVID DIAS TODO

**js-ipfs**
  - [ ] https://github.com/ipfs/js-ipfs/pull/69
  - [ ] Captain.log
  - [ ] Estimate time for completion of remaining components
  - swarm
    - [ ] listen
    - [ ] connect
    - [ ] interop
  - js-libp2p-ipfs
  - js-ipfs-data-importing
**js-ipfs-api**


**libp2p**
  - [ ] webrtc-explorer reboot https://github.com/diasdavid/webrtc-explorer/pull/10
  - [ ] libp2p-utp
  - [ ] libp2p-websockets

**npm on ipfs**


**station**


**ipscend**

**js-ipfsd-ctl**

**specs**

**extra**
  - [ ] make a contribution to go-ipfs

**Comment by whyrusleeping** [comment]
## @whyrusleeping sprint goals
- [ ] large big huge testing framework/tests
- [ ] pinning fix PR merged go-ipfs#2384
- [ ] build process improved
  - [ ] force gx to use 0.4.0 gateways
  - [ ] better docs around building from source
  - [ ] go compiler version checks
  - [x] make gx handle cross compilations better
- [ ] try for zero random test failures on travis and circle

**Comment by nginnever** [comment]
<h3>@nginnever goals</h3>
- js-ipfs
 - [ ] command cat (meow)
- js-ipfs-data-importing (js-ipfs issue #41)
 - [ ] streamImporter (more questions)
 - [~] BufferImporter (CR)
 - [ ] export function
 - [ ] browser / mocha tests
- Webui
 - [ ] write some tests for new components
 - [ ] document in contibuting.md

**Comment by whyrusleeping** [comment]
## go-ipfs

#### Lead: @whyrusleeping

#### Participants

- @jbenet
- @diasdavid
- @whyrusleeping
- @RichardLitt
- @noffle
- @dignifiedquire

## Agenda

- CI is greener, needs to be even more greenerer
- Large Big Huge Test Things (tm)

## Notes

- generate sequence of random actions
- build harness to run those generated actions, and halt on failure
- check results and integrity every so often

**Comment by lgierth** [comment]
## Infrastructure

#### Lead: @lgierth

#### Participants

 - @RichardLitt
 - @jbenet
 - @dignifiedquire
 - @whyrusleeping
 - @diasdavid

## Agenda

- a lot of requests for pinbot to work again. (also on 0.4)
- gateway issues
- moving away from docker, in part
- metrics
  - v03x
- dist.ipfs.io needs https

## Notes

- pinning
  - goroutine explosion and thus bitswap contention, there's a PR by @whyrusleeping fixing it
  - pinbot and pinbot-v03x
  - there is a PR open for pinbot, which starts collecting a note for each !pin invocation
- geoip
  - merkledag and source data need pinning on both v03x and v04x
  - ipfs-station will use geoip merkledag, and ships go-ipfs 0.3.11
- ssl for *.ipfs.io
  - the current cert only covers ipfs.io and gateway.ipfs.io
  - i fucked up the identity verification for getting a wildcard
  - having another try now :)
- gateway issues
  - multireq was incorrectly passing on certain error responses, instead of trying the second network too
  - docker daemon sometimes crashes
  - docker sometimes loses track of container state
  - moving away from docker for now, will write down issues we had
  - next: runc and runit
- metrics
  - http://metrics.i.ipfs.io
    - set up cjdns, get peering (https://github.com/hyperboria/peers), and tell @lgierth your IPv6 address to add it to the VPN allowlist
  - v03x metrics are back and have their own dashboard
  - the current gateway/api HTTP metrics are from go-ipfs's point of view
  - we badly need nginx-level metrics, but the really useful stuff is part of their pay-per-instance subscription
  - we're going to parse nginx logs and make metrics from that
  - we'll have birds-eye view metrics of ipfs.io in a bit: https://github.com/whyrusleeping/ipfs-watcher

**Comment by lgierth** [comment]
- infrastructure
  - [x] handle gx in solarnet deployment
  - [ ] identity validation for *.ipfs.io cert
  - [ ] migrate from docker to runc+runit
  - [ ] write down docker issues
- pages / dnslink
  - [x] comprehensible messaging in dnslink-deploy
  - [x] make blog independent of website
  - [x] use _dnslink and CNAME for blog: `dig +short
- pinning
  - [ ] pin geoip on v04x and v03x
  - [ ] fix pinbot
- metrics
  - [ ] bring back ipfs metrics on master
  - [ ] nginx metrics

**Comment by dignifiedquire** [comment]
- libp2p
  - karma-peer
    - [ ] Add dynamic browser launching
- ipfs-geoip
  - [ ] Pin all the data
  - [x] Release `2.0.0`
- webui
  - [x] Use new ipfs-geoip for location data
  - [x] Add polling to the peers page
  - [ ] Files browser
  - [ ] Write captain.log
  - [x] Finish tests for peers caching
- dignified hacks
  - [x] Base setup on beamp.pro
  - [x] Decide on content for the first session: "Webui File Browser"
  - [ ] Schedule first session
  - [ ] Do first session
- go-ipfs
  - Big Bad Tests (TM)
    - [x] Randor - Randomized testing prototype
    - [ ] Base structure
    - [ ] Add and pin commands
    - [ ] Better randomness generators
- PM
  - [ ] Discuss new sync format
  - [ ] Write update for weekly

**Comment by Kubuxu** [comment]
#### @Kubuxu TODO:
* [ ] - write blag about CRDTs in IPFS
* [x] - play with new implementation of IPLD - ipfs/go-ipld#19
* [ ] - track down https://github.com/ipfs/go-ipfs/issues/2405
* [ ] - work on two stage caching for IPFS:
 * [ ] - [go-twocache](https://github.com/Kubuxu/go-twocache)
 * [ ] - vendor it with gx, use by (30, 60) by default
 * [ ] - extend IPNS with custom caching times

**Comment by RichardLitt** [comment]
IRC mid-fortnight hangout today. Will post updates in here.

**Comment by RichardLitt** [comment]
Endeavour         | Lead            | Time (PDT - **UTC/Z** - CET) | Pad
:---------------: | :-------------: | :--------------------------: | :----:
sync              | @RichardLitt    | 9:00pDT **17:00Z** 18:00CET  | IRC: #ipfs on Freenode

**Comment by diasdavid** [comment]
### DAVID DIAS SPRINT CHECKIN

#### js-ipfs

**Summary:**

**Tasks:**
  - [x] CR+M https://github.com/ipfs/js-ipfs/pull/72
  - [x] CR+M https://github.com/ipfs/js-ipfs/pull/74
  - [x] CR+M https://github.com/ipfs/js-ipfs/pull/78
  - [x] CR+M https://github.com/ipfs/js-ipfs/pull/76
  - [x] CR+M https://github.com/ipfs/js-ipfs/pull/77
  - [x] https://github.com/ipfs/js-ipfs/pull/69
    - [x] http-api: id (+ tests + js-ipfs-api tests)
    - [x] replace globals by eslint-env mocha
    - [x] http-api: bootstrap + tests
    - [x] cli:id to use the daemon if on + tests
    - [~] chase https://github.com/ipfs/js-ipfs/issues/70
  - [ ] management
    - [x] captain.log
    - [x] update js-ipfs feature threads with new and refreshed action items
    - [x] update roadmap https://github.com/ipfs/js-ipfs/pull/71
    - [ ] estimate time for completion of remaining components
  - swarm
    - [x] listen
    - [ ] connect
    - [ ] interop
  - js-libp2p-ipfs
  - js-ipfs-data-importing
    - [x] CR https://github.com/ipfs/js-ipfs-data-importing/pull/6
  - js-ipfs-unixfs
    - [x] CR+M https://github.com/ipfs/js-ipfs-unixfs/pull/3
  - js-peer-id
    - [x] some cleanup https://github.com/diasdavid/js-peer-id/pull/6
  - js-peer-info
    - [x] https://github.com/diasdavid/js-peer-info/pull/5
    - [x] https://github.com/diasdavid/js-peer-info/pull/6
    - [x] https://github.com/diasdavid/js-peer-info/pull/8

#### js-ipfs-api

**Summary:**

  - [x] debug and fix ls and refs on js-ipfs-api for 0.4.0 https://github.com/ipfs/js-ipfs-api/commit/a185c92f007cbf640d7877ed2c88deeffcd8ea25 
  - [x] CR+M https://github.com/ipfs/js-ipfs-api/pull/224
  - [x] CR+M https://github.com/ipfs/js-ipfs-api/pull/221

#### libp2p

**Summary:**

  - [x] webrtc-explorer 2.0.0 alpha release
    - https://github.com/diasdavid/webrtc-explorer/pull/10
    - http://blog.daviddias.me/2016/02/09/webrtc-explorer-2-0-0-alpha-release
  - [x] libp2p-utp https://github.com/diasdavid/js-libp2p-utp/pull/2
  - [x] libp2p-websockets
  - js-libp2p-swarm
    - [x] migrate to mocha, istanbul, chai and standard 6 https://github.com/diasdavid/js-libp2p-swarm/pull/19
   - js-libp2p-tcp 
     - [x] major update, now knows how to handle multiple listeners, understands multiaddr directly on the createListener and knows how to close them all. This breaks interface-transport, but what it means is that it needed to be improved anyway. https://github.com/diasdavid/js-libp2p-tcp/pull/3
     - [x] https://github.com/diasdavid/js-libp2p-tcp/pull/4
  - [x] deprecated js-spdy-stream-muxer https://github.com/diasdavid/js-spdy-stream-muxer/pull/8 (use libp2p-spdy instead)
  - [x] 0.2.0 js-libp2p-spdy (completely new version) https://github.com/diasdavid/js-libp2p-spdy/pull/2
  - [x] 0.3.0 interface-stream-muxer https://github.com/diasdavid/interface-stream-muxer/pull/5
  - [x] use interface-stream-muxer tests directly on js-libp2p-spdy https://github.com/diasdavid/js-libp2p-spdy/pull/3
  - [x] 0.1.0 + 0.2.0 js-libp2p-multiplex https://github.com/diasdavid/js-libp2p-multiplex/pull/1

#### specs

**Summary:**

- [x] R https://github.com/ipfs/http-api-spec/pull/51/files
- [x] R https://github.com/ipfs/http-api-spec/pull/29
- [x] R https://github.com/ipfs/http-api-spec/pull/53

#### extra

**Summary:**

  - [ ] (but essential) learn Go
  - [x] make a contribution to go-ipfs - https://github.com/ipfs/go-ipfs/pull/2430
  - [x] write `IPFS pinning bot` nodes https://github.com/ipfs/notes/issues/113

**Comment by RichardLitt** [comment]
### Summary

These past two weeks have been productive. I helped us switch up the sprint, so that we have a Monday off and that we run on a fortnightly basis. This involved a lot of talking to people. I reviewed all of the [open PRs](https://github.com/ipfs/http-api-spec/pulls) on http-api-spec, and merged a few of them - we're getting there, although there is more work to do (mostly involving me talking to @whyrusleeping). This coincided with a lot of go-ipfs PRs. We published last month's weekly, which took way more time than it ought to have, and I'm hoping that never happens again. I also udpated a few bugs and added a dependency, wihch gets PR creators, to `name-your-contributors`, the module I use for getting a list of community contributors for the IPFS Weekly. I gave a talk about this module at BostonJS, and got to talk about IPFS there, too.

#### Tasks I said I'd do

- [x] Sprint Management
- [x] Review all open PRs on http-api-spec https://github.com/ipfs/http-api-spec/pulls
- [x] Write the weekly roundup
- [ ] Fill out RichardLitt/better-github-templates to answer https://github.com/ipfs/community/issues/108

#### Extra stuff I did

- [x] Gave talk at BostonJS about `name-your-contributors`
- [x] Fixed bugs with [name-your-contributors](https://github.com/RichardLitt/name-your-contributors)
- [x] Updated the commands section on the website https://github.com/ipfs/website/pull/99
- [x] Commenting on sync changes; ran the mid-Monday sprint https://github.com/ipfs/pm/issues/95 https://github.com/ipfs/pm/issues/96
- [x] Copy editing: [Captain's Log](https://gist.github.com/RichardLitt/c5c022ed8973d4a1c68d/revisions)
- [x] go-ipfs PR about bitswap unwant args https://github.com/ipfs/go-ipfs/pull/2409, resolve recursive option: https://github.com/ipfs/go-ipfs/pull/2410, config option defaults: https://github.com/ipfs/go-ipfs/pull/2412, removing period from DNS example https://github.com/ipfs/go-ipfs/pull/2421, small language changes in https://github.com/ipfs/go-ipfs/pull/2422, https://github.com/ipfs/go-ipfs/pull/2423, https://github.com/ipfs/go-ipfs/pull/2424
- [x] PRed a note to the git sign-off hook. https://github.com/ipfs/community/pull/110
- [x] Updated get-started on website. PR https://github.com/ipfs/website/pull/101
- [x] Code Review: https://github.com/ipfs/specs/pull/81, https://github.com/ipfs/js-ipfs-api/pull/221, https://github.com/ipfs/go-ipfs/pull/2416, CR https://github.com/ipfs/go-ipfs/pull/2417, https://github.com/ipfs/go-ipfs/pull/2443, https://github.com/ipfs/js-ipfs/pull/76#issuecomment-192401362, https://github.com/ipfs/go-ipfs/pull/2447/files, https://github.com/ipfs/go-ipfs/pull/2446/files, https://github.com/ipfs/go-ipfs/pull/2399, https://github.com/ipfs/go-ipfs/pull/2396, https://github.com/ipfs/go-ipfs/pull/2382, https://github.com/ipfs/go-ipfs/pull/2384, https://github.com/ipfs/go-ipfs/pull/2403

**Comment by Kubuxu** [comment]
#### @Kubuxu Update:
* [ ] - write blag about CRDTs in IPFS
 * [x] - drafts
 * [ ] - I have to fix my node first - https://github.com/ipfs/go-ipfs/issues/2405 related
* [x] - play with new implementation of IPLD - ipfs/go-ipld#19
* [x] - report and help with https://github.com/ipfs/go-ipfs/issues/2405 
* [ ] - work on two stage caching for IPFS:
 * [ ] - [go-twocache](https://github.com/Kubuxu/go-twocache)
  * [x] - first prototype
 * [ ] - vendor it with gx, use by (30, 60) by default
 * [ ] - extend IPNS with custom caching times
* [~] - AUR packaging
 * [x] - package `gx` to AUR - https://aur.archlinux.org/packages/gx/
 * [x] - package `gx-go` to AUR - https://aur.archlinux.org/packages/gx-go/
 * [ ] - improve `go-ipfs-git` - I can't really contact the maintainer
 * [x] - package `ipget`
 * [ ] - package `fs-repo-migrations` - what should be the name? `fs-repo-migrations` is too general

I wasn't super productive when it comes to IPFS (Uni started, Vulkan got released) but I was able to get something done. `gx` gx-go` and `ipget` are now available on AUR which is really nice. I worked on blag about CRDT on IPFS which would sum up my thoughts, ideas, problems and solutions. Something others could reference while implementing their owns. I am blocked really hard on https://github.com/ipfs/go-ipfs/issues/2405, I can flush the datastore but it will probably repeat. Also general question: how to name packaged `fs-repo-migrations`? Ping me on IRC with possible names.

**Comment by dignifiedquire** [comment]
## @dignifiedquire Sprint Checking

> Success is stumbling from failure to failure with no loss of enthusiasm.
> - Winston S. Churchill

Two weeks have gone by, and I actually got everything done I set out to do
in the last sprint. `karma-peer` now has the ability to dynamically launch browsers,
which will help @diasdavid, and hopefully more people, to write better tests for
libp2p in the browser.
The "Big Bad Tests" for `go-ipfs` are on on their way with
`randor`, which now is able to rerun tests predictably based on stored data, so it's
easy to find and fix bugs. @whyrusleeping is already working on the first bug that
`randor` detected.
A big highlight for me personally was the first show of "dignified hacks" last Monday, where I
live streamed myself coding on the big webui refactoring. There were some technical
issues but I hope to do another one this week.
The overall progress on the webui is that I started on the files browser (based on new files
api in 0.4) which already lists files and is able to create directories. In addition all
the geolocation data now uses the fixed ipfs-geoip.
And last but not least, I famliarized myself with the codebase of the website, fixing some
basic performance issues (image compression, dead code) and started thinking of what the
next iteration might look like.

### Big Long Lists

#### Things I said I would do

- libp2p
  - karma-peer
    - [x] Add dynamic browser launching
- ipfs-geoip
  - [x] Pin all the data (0.4 is done, not sure about 0.3)
  - [x] Release `2.0.0`
- webui
  - [x] Use new ipfs-geoip for location data
  - [x] Add polling to the peers page
  - [x] Started work on the files browser
  - [x] Write captain.log (https://github.com/ipfs/webui/issues/259)
  - [x] Finish tests for peers caching
- dignified hacks
  - [x] Base setup on beamp.pro
  - [x] Decide on content for the first session: "Webui File Browser"
  - [x] Schedule first session
  - [x] Do first session
- go-ipfs
  - Big Bad Tests (TM)
    - [x] Randor - Randomized testing prototype
    - [x] Base structure
    - [x] Add and pin commands
    - [x] Better randomness generators
- PM
  - [x] Discuss new sync format
  - [x] Write update for weekly
- website
  - [x] Ship new install instructions

#### Things I did additionally

- website
  - [x] [Compress images and remove unused jquery](https://github.com/ipfs/website/pull/104)
  - [x] [Add missing link getting started link](https://github.com/ipfs/website/pull/103)
- webui
  - [x] Split large `index.js` files into multiple parts (reducers and actions)
  - [X] Review PRs
    - https://github.com/ipfs/webui/pull/253 -> https://github.com/ipfs/webui/pull/257
    - https://github.com/ipfs/webui/pull/262
    - https://github.com/ipfs/webui/pull/261
- misc
  - [X] CR and Merge https://github.com/ipfs/js-ipfs-api/pull/218
  - [X] Fix `object patch` in js-ipfs-api https://github.com/ipfs/js-ipfs-api/pull/220
  - [X] Propose talk to SquatConf https://github.com/squatconf/talks/pull/26
- station
  - [x] Set up RaspberryPi2, install and run ifps and station on it.
- dignified hacks
  - [X] Setup Youtube LiveStreams as beam.pro doesn't properly handle old content
- GoIPFS
  - Big Bad Tests (randor)

**Comment by nginnever** [comment]
<h3>@nginnever Sprint</h3>

The past two weeks I have been studying more than I have been producing but I am getting much more comfortable with tests, the difference between using IPFS in the browser and node env, standards and practices, and so on. I wasn't able to spend as much time as I would like working on and studying our react webui project but I did tune into dignified hacks and that was helpful for a quick view of our components and data flow in the webui. 

I spent some time researching a few commands in go-ipfs (cat and object get). I wrote some notes or a step-by-step analysis of what happens during those commands or what I can understand as to what's happening. I spent some time writing web tests for data-importing module with dig and I started writing some export feature code to unwrap our hashes and retrieve files.  Also created a distribution file for peer-id that will require node/forge rebuild to be able to work with browserify.    

- js-ipfs
 - [~] command cat (meow)
- js-ipfs-data-importing (js-ipfs issue #41)
 - [ ] streamImporter (more questions)
 - [~] BufferImporter (CR)
 - [ ] export function
 - [~] browser / mocha tests
- js-peer-id
 - [x] create dist file
 - [ ] document node forge and inability to use browserify in readme
- Webui
 - [ ] write some tests for new components
 - [ ] document in contibuting.md

**Comment by noffle** [comment]
I've been spending time reflecting on my own goals individually and how they connect to my work on IPFS. tl;dr I'm going to be focusing more on js-ipfs and on building p2p primitives to support apps on IPFS. My week reflects this:

I did a lot of reading on p2p subjects (bittorrent, david dias' webrtc work, gossip protocols), and produced several modules: 3 to support ipfs-pad (p2p text editor), and 2 to support p2p pubsub (potentially for haad's orbit-db).

- go-ipfs
  - [x] rebased + added tests to an [outstanding PR](https://github.com/ipfs/go-ipfs/pull/2435)
- pm
  - [x] personal okr planning
- js-ipfs
  - [x] basic spec'cing out of the 'ipfs init' process
- ipfs-pad
  - [x] [bisecting-numbers](https://github.com/noffle/bisecting-numbers)
  - [x] [bisecting-between](https://github.com/noffle/bisecting-between)
  - [x] [hyperswarm](https://github.com/noffle/hyperswarm)
- p2p pubsub
  - [x] [secure-gossip](https://github.com/noffle/secure-gossip)
  - [x] [pubsub-swarm](https://github.com/noffle/pubsub-swarm)

**Comment by whyrusleeping** [comment]
These past couple weeks have been spent harding our testing, and fixing issues that have popped
up while doing so. I also in this last week started setting up teamcity to be used as our own
CI so we don't have to wait hours for travis to decide it wants to run our tests
teamcity also gives us awesome metrics on our tests and nice statistics on failures and
failure rates

Other:
- worked on libp2p
  - updated some dependencies
  - made a few small tweaks that should help with address discovery
  - enabled the use of utp without a utp listener address in config (and visa versa)
- default values for commands lib
- introduced 'IPFS_LOW_MEM' flag, doesnt do much yet. but will be worked on 
- lots of test fixing
  - t0060 using port zero
- repair multireq, still not perfect, but better.
- improved the UX of building ipfs from source
  - makefile asserts GOPATH, go version
  - uses 0.4.0 gateways for fetching gx deps
  - readme updated to be more helpful
- fixup ipfs-update to address issues @chriscool discovered
- a bunch of gx work

**Comment by lgierth** [comment]
### @lgierth sprint update

I just came back from a nice and productive week in Paris. I got to spend lots
of time with @cjdelisle and @ansuz at @xwiki-labs, we discussed the state
and future of cjdns/fc00, layed out ideas for routing improvements, and drafted
spec documents for the switch and cryptoauth layers. I'll post them to the
github.com/fc00/specs repo shortly, and we'll continue working on them for the
rest of March. I want to start working on Go implementations of the switch and
cryptoauth in April.

IPFS-wise, the sprint was dominated by hunting down subtle issues. The v04x/v03x
multiplexer called multireq still doesn't seem to be 100 % good. I fixed a couple
bugs with tremendous help from @whyrusleeping. I've also been debugging issues
with fetching big DAGs (e.g. GeoIP). The metrics dashboard at metrics.i.ipfs.io
has gotten a facelift too, and will get more detailed metrics on HTTP requests
and responses.

- infrastructure
  - [x] handle gx in solarnet deployment
  - [ ] ~~identity validation for *.ipfs.io cert~~ taken over by @whyrusleeping 
  - [ ] migrate from docker to runc+runit
  - [ ] write down docker issues
- pages / dnslink
  - [x] comprehensible messaging in dnslink-deploy
  - [x] make blog independent of website
  - [x] use _dnslink and CNAME for blog: `dig +short CNAME _dnslink.blog.ipfs.io`
  - [x] update ipfs.io, dist.ipfs.io, chat.ipfs.io
  - [x] fix `dns` command docs ipfs/go-ipfs#2438
- pinning
  - [x] pin geoip on v04x
  - [ ] ~~pin geoip on v03x~~ blocked by pinning issues
  - [x] fix pinbot
- metrics
  - [ ] bring back ipfs metrics on master
  - [ ] nginx metrics
  - [x] multireq metrics
  - [x] v03x/v04x uptime metrics
  - [x] use proper rate() function for HTTP graphs
- fc00/cjdns
  - [ ] cryptoauth spec draft
  - [ ] switch spec draft
  - [x] cjdns fixes cjdelisle/cjdns#910 cjdelisle/cjdns#911 fc00/go-cjdns#1
- reminder to self
  - github assignments: https://github.com/issues/assigned
