### ISSUE TITLE
Sprint: March 7-20

### ISSUE THREAD

**Issue by RichardLitt** [ipfs/pm#97]
# Sprint March 7th -- 20th

## Sprint Discussions

[Schedule](https://github.com/ipfs/pm#sprint-discussion-schedule)

Please take notes in a separate pad, if you can, and link it here.

Endeavour         | Lead            | Time (PDT - **UTC/Z** - CET) | Pad
:---------------: | :-------------: | :--------------------------: | :----:
sync              | @RichardLitt    | 9:00pDT **17:00Z** 18:00CET  | IRC: #ipfs on Freenode
apps on ipfs      | @dignifiedquire | 10:30PDT **18:30Z** 19:30CET | https://public.etherpad-mozilla.org/p/ipfs-mar-7-apps-on-ipfs
infrastructure    | @lgierth        | 11:00PDT **19:00Z** 20:00CET | https://public.etherpad-mozilla.org/p/ipfs-mar-7-infrastructure
libp2p            | @diasdavid      | 11:30PDT **19:30Z** 20:30CET | https://public.etherpad-mozilla.org/p/ipfs-mar-7-libp2p
js-ipfs           | @diasdavid      | 12:00PDT **20:00Z** 21:00CET | https://public.etherpad-mozilla.org/p/ipfs-mar-7-js-ipfs
go-ipfs           | @whyrusleeping  | 12:30PDT **20:30Z** 21:30CET | https://public.etherpad-mozilla.org/p/ipfs-mar-7-go-ipfs

Please add the Agenda to the Pad before the endeavour sprint starts.

## Sprint Deliverables

- Add your tasks below in a comment, that way we only have people listed who are really in the sprint
- Add links to issues down here. Only add things you can finish this sprint.

**Comment by dignifiedquire** [comment]
## Apps on IPFS

### Lead: @dignifiequire

### Participants

- @dignifiedquire
- @diasdavid
- @haad
- @nginever

### Agenda

- Webui
- dignified hacks (on the webui)
- Station @ RaspberryPi
- orbitDB

### Notes

- Webui
  - Files is WIP, more progress this week
  - Logs are crashing the browser, too much data
    - TODO: allow for filtering on `ipfs log tail`
- Station working on RaspberryPi
  - TODO: Add to weekly
- OrbitDb
  - https://github.com/haadcode/orbit-db
  - https://github.com/haadcode/anonymous-networks/tree/refactor/orbit-db
  - EventLog and KV-store

**Comment by diasdavid** [comment]
## Library Peer to Peer!

#### Lead: David Dias - @diasdavid

#### Participants

## Agenda

Update
  - Redo a lot of old code to new patterns
  - Lot's of new improvements, e.g. less stream wrapping
  - APIs are changing a bit, less magic

Next
  - Finish Swarm update https://github.com/diasdavid/js-libp2p-swarm/pull/20
  - Get js-libp2p-ipfs and go-ipfs examples

**Comment by diasdavid** [comment]
## IPFS JavaScript Implementation 

#### Lead: David Dias - @diasdavid

#### Participants

## Agenda

Update
  - Foundations
  - Contributions
  - data-importing (voxelot)

Next
  - jsipfs swarm (dependent on libp2p stuff)
  - complete jsipfs files
  - bitswap

**Comment by lgierth** [comment]
## Infrastructure

#### Lead: @lgierth

#### Participants

- @daviddias
- @dignifiedquire
- @lgierth
- @richardlittauer
- @whyrusleeping

## Agenda

- multireq
- metrics
- fetching & pinning

## Notes

- jbenet still seeing glitches with multireq
  - nginx metrics will hopefully shed some light
- more metrics from go-ipfs!
  - number of peers by transport, bitswap wants/provs/bw, etc.
- pinning performance
  - pinbot is not the issue
  - multireq neither
  - likely it's the fetching
- fetch performance
  - some merkledags with depth>1 get stuck
  - it continues only after a restart, then gets stuck again later
  - reproducible with geoip
  - also reproducible with a certain gx import set
  - gets stuck on the same hash reproducibly
  - whyrusleeping is on it

**Comment by diasdavid** [comment]
## DAVID DIAS TODO

### js-ipfs

- management
  - [ ] estimate time for completion of remaining components
  - swarm
    - [x] listen
    - [ ] connect
    - [ ] interop
  - js-libp2p-ipfs
  - js-ipfs-data-importing
    - [x] CR https://github.com/ipfs/js-ipfs-data-importing/pull/6
  - js-ipfs-unixfs
    - [x] CR+M https://github.com/ipfs/js-ipfs-unixfs/pull/3
  - js-peer-id
    - [x] some cleanup https://github.com/diasdavid/js-peer-id/pull/6
  - js-peer-info
    - [x] https://github.com/diasdavid/js-peer-info/pull/5
    - [x] https://github.com/diasdavid/js-peer-info/pull/6
    - [x] https://github.com/diasdavid/js-peer-info/pull/8

**js-ipfs-api**
  - [x] debug and fix ls and refs on js-ipfs-api for 0.4.0 https://github.com/ipfs/js-ipfs-api/commit/a185c92f007cbf640d7877ed2c88deeffcd8ea25 
  - [x] CR+M https://github.com/ipfs/js-ipfs-api/pull/224
  - [x] CR+M https://github.com/ipfs/js-ipfs-api/pull/221

**libp2p**
  - [x] webrtc-explorer 2.0.0 alpha release
    - https://github.com/diasdavid/webrtc-explorer/pull/10
    - http://blog.daviddias.me/2016/02/28/webrtc-explorer-2-0-0-alpha-release
  - [x] libp2p-utp https://github.com/diasdavid/js-libp2p-utp/pull/2
  - [x] libp2p-websockets
  - js-libp2p-swarm
    - [x] migrate to mocha, istanbul, chai and standard 6 https://github.com/diasdavid/js-libp2p-swarm/pull/19
   - js-libp2p-tcp 
     - [x] major update, now knows how to handle multiple listeners, understands multiaddr directly on the createListener and knows how to close them all. This breaks interface-transport, but what it means is that it needed to be improved anyway. https://github.com/diasdavid/js-libp2p-tcp/pull/3
     - [x] https://github.com/diasdavid/js-libp2p-tcp/pull/4
  - [x] deprecated js-spdy-stream-muxer https://github.com/diasdavid/js-spdy-stream-muxer/pull/8 (use libp2p-spdy instead)
  - [x] 0.2.0 js-libp2p-spdy (completely new version) https://github.com/diasdavid/js-libp2p-spdy/pull/2
  - [x] 0.3.0 interface-stream-muxer https://github.com/diasdavid/interface-stream-muxer/pull/5
  - [x] use interface-stream-muxer tests directly on js-libp2p-spdy https://github.com/diasdavid/js-libp2p-spdy/pull/3
  - [x] 0.1.0 + 0.2.0 js-libp2p-multiplex https://github.com/diasdavid/js-libp2p-multiplex/pull/1

**npm on ipfs**


**station**


**ipscend**

**js-ipfsd-ctl**

**specs**

- [x] R https://github.com/ipfs/http-api-spec/pull/51/files
- [x] R https://github.com/ipfs/http-api-spec/pull/29
- [x] R https://github.com/ipfs/http-api-spec/pull/53
**extra**
  - [ ] (but essential) learn Go
  - [x] make a contribution to go-ipfs - https://github.com/ipfs/go-ipfs/pull/2430
  - [x] write `IPFS pinning bot` nodes https://github.com/ipfs/notes/issues/113

**Comment by haadcode** [comment]
### @haadcode sprint goals - 7-20 Mar

#### Summary
I'll be working on integrating *orbit-db* (1) to *Orbit* (2) in order to make sure *orbit-db* provides an easy embeddable p2p database for apps on IPFS. It also means I can refactor a huge bunch of the *Orbit* code and simplify the "backend" logic of the app as well as refactor the UI to a more manageable state. The overall goal is to make *Orbit* a little cleaner so that others can start contributing to is. 

1) https://github.com/haadcode/orbit-db
2) https://github.com/haadcode/anonymous-networks

#### Tasks

##### Orbit
  - [ ] Integrate with orbit-db
  - [ ] Refactor everything
  - [ ] Make a stable build/release after the first two
  - [ ] Candy: App icon for Orbit

##### Pubsub
  - [ ] Test @noffle's pubsub prototype and give feedback (https://github.com/noffle/pubsub-swarm)

**Comment by dignifiedquire** [comment]
## @dignifiedquires TODO

- Webui
  - Work on the files screen
  - Review and merge config PR
- Station
  - Use latest ipfs-geoip + failure handling
- WebRTC 
  - Reading and research on the current landscape of implementations
  - Spec reading
- Randor
  - Add nested files api operations
  - [x] Fix parallel bug with pin-rm

**Comment by RichardLitt** [comment]
### Summary

I am going to focus on copy editing some of our blog posts that need to go out, because we should publish them and I think a little elbow grease will get them out the door. I will also be diving into js-ipfs and seeing if I can help out with building `ipfs block` there. Along with these I am going to be generally working through my backlog of issues and things to do. 

### Tasks
- [ ] Sprint Management
- [x] Write the weekly roundup
  - [+] Get feedback from @jbenet
  - [ ] Publish
- [ ] js-ipfs block
- [ ] Writing:
  - [ ] Review 0.4.0 post
  - [ ] Reveiw ipscend post https://github.com/ipfs/blog/pull/31

**Comment by noffle** [comment]
# @noffle Sprint Goals

## Summary

I want to make headway on the "init" process for js-ipfs: this means getting a clear understanding of what initializing a repo means with respect to IPFS, resolving any non-existant dependencies, and implementing the initialization logic. I don't have a clear view yet on the full dependency graph for this, so I'll try and update this list as the amount of work involved becomes clearer.

I'd also like to build **hyperarray**: an ordered list CRDT built on a [hyperlog](https://github.com/mafintosh/hyperlog). This will form the underlying document model for an ipfs-pad document. I've been largely inspired by [r-array](https://github.com/dominictarr/r-array)'s design and API.

## Tasks

### js-ipfs

- [ ] spec document of 'ipfs init' process (started [here](https://github.com/ipfs/js-ipfs/issues/42#issuecomment-190470930))
- [ ] outline work for 'repo init'
- [ ] outline work for 'ipfs init' for js-ipfs

### ipfs-pad

- [ ] hyperarray
- [ ] start an *Architecture* document

### pm

- [ ] update OKR document with my goals for the rest of Q1

**Comment by nginnever** [comment]
<h3> Summary </h3>

I want to continue to make progress with my understanding of IPFS. I feel I am at around 70% knowledge and this is keeping me from awnsering some of the bigger questions about data importing like what structures should a browser be able to use in lack of an fs.. yet should we use unixfs and such. I will be moving towards more defined tasks from the go implementation like building out more commands. Also starting to take a look at libp2p and networking. And spending some time with react and the webui to keep my application development chops in line. 

P.S. Also want to work with those geniuses up there on pub/sub and CRDT systems

<h3> TODO </h3>
- js-ipfs
 - [~] command cat (meow)
 - [ ] command object get
- js-ipfs-data-importing (js-ipfs issue #41)
 - [ ] streamImporter (more questions)
 - [~] BufferImporter (CR)
 - [ ] export function
 - [~] browser / mocha tests
- Webui
 - [ ] write some tests for new components
 - [ ] document in contibuting.md to help others get involved

**Comment by lgierth** [comment]
### @lgierth todo

- infrastructure
  - [ ] nginx metrics
  - [ ] ~~identity validation for *.ipfs.io cert~~ taken over by @whyrusleeping
  - [ ] migrate from docker to runc+runit
  - [ ] write down docker issues
- fc00/cjdns
  - [ ] cryptoauth spec draft
  - [ ] switch spec draft
  - [x] debug cjdns crashes
  - [x] cjdns peering dignifiedquire & whyrusleeping
- pages / dnslink
  - [ ] `ssh blog@pages.i.ipfs.io publish <hash>`
- go-ipfs
  - [ ] bring back ipfs_* metrics
  - [ ] harden gateway path prefix
- errands
  - [x] deploy weekly #5 and #6
  - [ ] pin geoip on v03x, for station
- reminder to self
  - github assignments: https://github.com/issues/assigned
- org stuff

**Comment by jbenet** [comment]
@nicolagreco and I will be having a hangout about IPLD this monday 3/14. interested researchers feel free to join. time TBD, probably after the general hangout. (@richardlitt if you can assign a time that would be great)

**Comment by jbenet** [comment]
@nicola and I will be having a hangout about IPLD this monday 3/14. interested researchers feel free to join. time TBD, probably after the general hangout. (@richardlitt if you can assign a time that would be great) cc @mildred if interested

**Comment by nicola** [comment]
@rychipman will join the IPLD meeting ^

**Comment by RichardLitt** [comment]
Set up for 3pm Eastern Time (Should be 8 CET, 7GMT) on Monday. In the calendar.

**Comment by RichardLitt** [comment]
Note: tomorrow is a mid-fortnight sprint. We will have a Google Hangout at Noon EST, 5PM CET. Link will be posted in IRC.

**Comment by nicola** [comment]
@RichardLitt @jbenet could we shift the meeting on IPLD just about 30 minutes?

**Comment by mildred** [comment]
I will join

**Comment by RichardLitt** [comment]
@nicola Sure! Which way - forwards or backwards?

**Comment by nicola** [comment]
@RichardLitt 3:30 EST :)

**Comment by RichardLitt** [comment]
Done. Note: daylight savings affected the states. That mean sprint hangout will follow the calendar: 1pm EST, 10am PST, 5pm GMT, and 6pm CET.

**Comment by RichardLitt** [comment]
# IPFS Sprint Mid-week hangout Notes

## @diasdavid

Focus on Libp2p, interop with go-p2p. Work on libp2p swarm. The api has completely changed. Before, I was exposing a simple API like dial, and then internally it would figure out which transport to use. Now, instead, we expose these internal steps as different function calls. You still have the nice high-level API to the other peer, but there's a lot more stuff exposed. There's more tests, too, making swarm less brittle. So on that, you now have a swarm version ready. What I'm working now is getting the websocket transport to the new transport scheme, which resulted from this upgrade on p2p swarm.

- Francisco has been shipping a lot by tackling issues which weren't tagged. Implementing HTTP API endpoints and the CLI commands which work with those to call js-ipfs core functions. Huge props.

- David Dias has had interesting conversations on swarm because when you have to deal with several transports at the same time, and several collections that get multiplexed over other connections, and then you have several parts of the code that will use this multiplex connection to open streams using different transports, and you want to abstract most of these things away and make it really simple, you get some problems. For example, if some user is transferring a huge file over IPFS, and decides to close his laptop, all of his connections will drop, and if those collections are multiplexed over a single connection, what is going to happen is that all of those points in the IPFS code which were transferring blocks will try to reestablish a collection. It'll call swarm again, asking it to dial to this other peer. Because these parts - for example, bitswap - don't need to understand that they are transferring across of the connection, they just need to know that they have a stream that they can use, it means that several parts of the code might try dialing the same peer at the same time. This is suboptimal. You get all of these streams which were multiplexed popping up errors because now they are on a single p2p connection. I am trying to come up with an elegant way of handling these errors. If too many peers dial, it becomes a racing condition (which peer dials first, etc), which is inefficient. So, I've opened an issue, got some feedback. And right now, I am getting more confident that a solution to this problem is a state machine, or a mutex strategy

https://github.com/diasdavid/js-libp2p-swarm/issues/24

### This week
Go-p2p and js-p2p interop. Getting that done. If that goes well, he'll go into Bitswap. I might build bitswap on js-land, just to have some example code.

## @dignifiedquire

@dignifiedquire has worked on the webui. He's got peers working, and all of the geolocation data is now fetched all through IPFS again. Mostly, he's been working on the files API. You can delete stuff, create files and folders.

Preview works: You can view text files, images, and videos. Anything that the browser could play for you, you can use in the webui.

### This week

Getting the webui polished and finished. Also, fixing config. It was PRed by @sucha (TODO), who also worked on tests, and then Friedel broke it a bit.

## @haad

Haads been working on Orbit and Orbit-db. Got it integrated into IPFS, so that's all working quite nicely on both sides. The turn around times are fairly good. It works, it loads.

There's a lot of bugs and things that need to be worked on. Thanks @noffle for bouncing ideas and giving feedback.

### This week

Work on orbit; test @noffle's prototype and give feedback. No blockers.

## @lgierth

Been sick recently, but everything that he's started is in progress. Not really finished yet, but getting there. Friday he's flyin go to New York.

### Week in three words

Multireq metric pages.

## @nginnever

Lots of browser testing this week, for js-ipfs data importing and for js-merkledag. Everything is ok, except for one issue of not being able to find a function, although it works on @dignifiedquire's machine, but @diasdavid should be able to help. Also, writing tests for containers for the webui. 

### Next Week

Nat testing.

## @noffle

Focused on ipfs-init working with js-ipfs. @noffle wrote a spec-like document showing how that works. He's also been thinking a lot of about the structure of distributed apps on top of IPFS. So, he's making a quick prototype of a distributed IPFS-powered wiki. If you're a reader, you just look through a gateway; if you're a publisher, you just publish a new root hash of the wiki. Might work well for a lot of applications. Inspired after playing with zeronet.

### This Week

Finish this prototype, possibly work on the IPFS-Etherpad prototype.

## @RichardLitt

PRed some things - went over all of the PRs in http-api-spec. Revieweed 0.4.0 blogpost and I need to do that again. Published the weekly. Started work on ipfs-block; also perused all of /faq and /support. Also hung out with @jbenet.

### This week

Going to keep work on ipfs-block.

## @whyrusleeping

Fixed a bug where IPFS would hang for large files; it was a multiplexer bug, in the end. There's a bug in Yamux which hasn't been fixed, where if you have too many in flight open streams, the connection will hang. If you raise that limit, the open ones will close down. The limit has been raised to around 16k, and merged that in, but there's still more to do there

### This week

Ship 0.4.0. @RichardLitt needs to review stuff; Everyone to review the changelog. Other than that, should be pretty silent. Distributions to be updated, too.

**Comment by diasdavid** [comment]
## DAVID DIAS CHECK IN

> following the summary check in format. For a complete task list done during this sprint, check https://github.com/ipfs/pm/issues/97#issuecomment-193680854.

This last sprint I had the chance to give a lot of time to js-ipfs and libp2p, with the goal of getting js-ipfs working on the browser and exchanging blocks with other js-ipfs nodes and go-ipfs nodes. I've made a lot of contributions and updates to: js-libp2p-ipfs, js-ipfs-data-importing, js-multiaddr, js-mafmt, js-peer-id, js-ipfs-repo, js-libp2p-swarm, js-libp2p-tcp, js-libp2p-utp, js-libp2p-websockets, js-libp2p-multiplex. These changes bubbled up to js-ipfs.

Also had a good time hacking with @xicombd, good discussions and remote hacking/debugging with @nginnever, good conversations with @dignifiedquire and @nginnever which resulted in the understanding of the new IPFS JavaScript Project guidelines, and last but not the least, the IPLD hangout with a bunch of IPLD enthusiasts.

I've also got the chance to write and submit the paper for ICWE and organize and host the first Research & Development meetup.

**Comment by RichardLitt** [comment]
### Summary

I feel my work has been a bit slow the past two weeks. I worked on the http-api-spec, some more, redoing `ipfs object` and opening a lot of PRs on go-ipfs. I also went through go-ipfs and added defaults to all of the options, which I think will help out in the future, and am getting a bit more comfortable with reading go. I've sent out two weeklies, and spent a lot of time helping organize the IPFS trip to New York for next week, and I spent a good amount of time going through ipfs/faq and ipfs/support checking up on all of the old issues which weren't updated. I did not get to help review the 0.4.0 ship, nor did I do significant work on js-ipfs block, which I am unhappy about. Hoping to get more work done this coming sprint, especially with the in-person coding time ahead. 

### Tasks

- [x] Sprint Management
- [x] Write the weekly roundup
- [~] js-ipfs block https://github.com/ipfs/js-ipfs/pull/81
- [~] Writing:
  - [x] Review 0.4.0 post
  - [ ] Reveiw ipscend post https://github.com/ipfs/blog/pull/31

### Extra
- [x] Checked in on https://github.com/ipfs/fs-repo-migrations/pull/10
- [x] CR https://github.com/ipfs/specs/pull/83, https://github.com/ipfs/go-ipfs/pull/2458
- [x] Went over the http-api-spec pull requests with @whyrusleeping
- [x] Added serve option to blog makefile https://github.com/ipfs/blog/pull/35, and to website https://github.com/ipfs/website/pull/106
- [x] Went through most questions in ipfs/support, ipfs/faq
- [x] PR ipfs/faq Readme. https://github.com/ipfs/faq/pull/100
- [x] Fixed up `ipfs object` PR for HTTP API, opened lots of relevant issues in go-ipfs
- [x] Added programmatic defaults to Gocode https://github.com/ipfs/go-ipfs/pull/2484
- [x] Updated diag subcommand options https://github.com/ipfs/go-ipfs/pull/2487

**Comment by dignifiedquire** [comment]
## @dignifiedquire Update

My main focus this time was the webui. I have made some good progress on the files explorer interface, refactoring some code and writing more tests. I'm now working on cleaning up the UI, preparing mockups and plans for the final phase of the implementation. 

After a some discussions and issues with our JavaScript setups I've started to create [dignified.js](https://github.com/dignifiedquire/dignified.js) which is going to be the module to help us have a unified testing, linting and building solution in all our JavaScript projects. This is an ongoing effort that I'm working on together with @diasdavid and @nginnever. 

Also in addition after the great IPLD hangout last week I've started implementing parts of it in [rust](https://github.com/dignifiedquire/rust-ipld) with the goal of finding a typesafe and general interface on how to define mappings between raw IPLD and higher level abstractions like unix-fs.

**Comment by lgierth** [comment]
### @lgierth sprint update

The past few weeks Berlin has been a huge drag on me, tons of org stuff to take care of, and was generally very easily distracted. My task list is testament to that :) I made a bit of progress on everything, but wasn't able to focus on any particular task very well. I feel quite energized though now that I'm in NYC, so I am to finish all of last sprint's stuff, and maybe a thing or two more.

My focus is still: v03x/v04x multireq stability, metrics, pages deployment, and cleaning up the mess which is the infrastructure repo.

- infrastructure
  - [x] parse metrics from nginx logs (using mtail)
  - [ ] deploy mtail-nginx to all hosts
  - [ ] ~~identity validation for *.ipfs.io cert~~ taken over by @whyrusleeping
  - [x] struggle with gc on saturn host
  - [x] fix gc_capacity on gateway hosts
  - [x] disable gc on storage hosts
  - [ ] migrate from docker to runc+runit
  - [ ] write down docker issues
- fc00/cjdns
  - [ ] cryptoauth spec draft
  - [ ] switch spec draft
  - [x] debug cjdns crashes
  - [x] cjdns peering dignifiedquire & whyrusleeping
  - [x] cjdns vs. tinc hyperboria/cjdns#112
- pages / dnslink
  - [x] figure out the how -- similar to [sshcommand](https://github.com/dokku/sshcommand)
  - [ ] `ssh blog@pages.i.ipfs.io publish <hash>`
- go-ipfs
  - [ ] bring back ipfs_* metrics
  - [ ] harden gateway path prefix
  - [x] fix --enable-gc in docker container
- errands
  - [x] deploy weekly \#5 and \#6 and \#7
  - [ ] pin geoip on v03x, for station
- reminder to self
  - github assignments: https://github.com/issues/assigned
- org stuff

**Comment by nginnever** [comment]
<h3>@nginnever Update</h3

This past week I continued to work on web testing the data-importing and merkle-dag modules. This kicked off conversation about new ways to handle our tests so that in the future things will be more consistent. 

I also began working on an export function for data-importing that will unMarshal our hashes and begin to pipe together streams of dag linked data for our files get and files cat commands.

Worked a bit with the webui but still need to study that type of react structure more to feel useful.

**Comment by noffle** [comment]
### Summary

Lots of reading and a few PRs this week some libp2p modules -- mostly usability improvements. Big accomplishment of the week is that the majority of the ipfs initialization logic for js-ipfs is now written.

Several of us (haad, jbenet, whyrusleeping, nginnever) discussed approaches to pubsub in more detail, and I did some further background reading on previous discussions across ipfs/* repos.

Last weekend I wrote a prototype wiki powered by IPFS. [A few pieces](https://github.com/search?q=user%3Anoffle+ip-wiki) are written so far, but the overall goal is to gain a better understanding of the functionality still missing in IPFS to make apps like these relatively simple.

### Tasks

- js-ipfs
 - [x] wrote [spec document of 'ipfs init' process](https://github.com/ipfs/js-ipfs/issues/42#issuecomment-190470930)
https://github.com/ipfs/js-ipfs/issues/42#issuecomment-190470930
 - [x] peer-id: [expose # of key bits](https://github.com/diasdavid/js-peer-id/pull/11)
 - [ ] ipfs init
   - [x] basic init steps (check repo, keygen, config gen, write to blob store)
   - [x] init tests
   - [ ] add default assets
- libp2p
 - [x] lots of spec & code reading
- secure-gossip
 - [x] help @haad figure out [a bug](https://github.com/noffle/secure-gossip/pull/1) with @diasdavid
- pubsub research
 - [x] catch up on [existing discussion](https://github.com/ipfs/notes/issues/64)
 - [x] hangouts discussion /w @haad @jbenet @whyrusleeping @nginnever
- ipfs-pad
 - [ ] hyperarray
 - [ ] start an architecture document
- ipfs-wiki
 - [x] initial design & research document
 - [x] work on design notes
 - [x] work on prototype
- ipld
 - [x] IPLD hangouts discussion
- pm
 - [x] NY logistics

**Comment by haadcode** [comment]
### @haadcode Sprint End Summary
I integrated orbit-db into Orbit and it's working nicely. Sending messages feels instantenous and responsive. With that, the "backend" code of Orbit is now a lot smaller and manageable. I was able to refactor the UI code of Orbit a little along the way but it still needs quite a bit of work. Orbit now has a nice new app icon for the desktop app and as a favicon in the browser. I refactored orbit-db a little by taking out the append-only log functionality into its own module (https://github.com/haadcode/ipfs-log) so that it can be used more easily as a building block in other apps, or eg. as a transport data structure for CRDTs.

#### Highlights 
  - ipfs-log (https://github.com/haadcode/ipfs-log)

#### Tasks

##### Orbit
  - [X] Integrate with orbit-db
  - [~] Refactor everything
  - [X] Make a stable build/release after the first two
  - [X] Candy: App icon for Orbit

##### Pubsub
  - [~] Test @noffle's pubsub prototype and give feedback (https://github.com/noffle/pubsub-swarm)

##### Extra
  - [X] Create a module out of orbit-db's log (https://github.com/haadcode/ipfs-log)

**Comment by whyrusleeping** [comment]
Spent most of my effort on getting 0.4.0 ready to ship. This involved lots of testing work, and also a lot of organizational stuff. 
I also did a large amount of performance analysis and have good ideas for improving perf overall moving forward. 
My list of weekly accomplishments feels short, many of these are rather large items.
- fixed double transfer encoding header
- worked on 0.4.0 blog post
  - please review!!! ipfs/blog#37
- debugged gx on windows issues
- wrote a large stress test for migrations
  - ~200k files, 2000 pins
- worked on benchmarks for various ipfs operations (expect perf changes in the near future)
- minor bugfix in go-datastore (prevents a panic)
