### ISSUE TITLE
Sprint: March 21 → April 6

### ISSUE THREAD

**Issue by RichardLitt** [ipfs/pm#98]
# Sprint March 21st through April 6th

## Sprint Discussions

[Schedule](https://github.com/ipfs/pm#sprint-discussion-schedule)

Please take notes in a separate pad, if you can, and link it here.

Endeavour         | Lead            | Time (PDT - **UTC/Z** - CET) | Pad
:---------------: | :-------------: | :--------------------------: | :----:
sync              | @RichardLitt    | 10:00PDT **17:00Z** 18:00CET  | IRC: #ipfs on Freenode
apps on ipfs      | @dignifiedquire | 11:30PDT **18:30Z** 19:30CET | https://public.etherpad-mozilla.org/p/ipfs-march-21-apps-on-ipfs
infrastructure    | @lgierth        | 12:00PDT **19:00Z** 20:00CET | https://public.etherpad-mozilla.org/p/ipfs-march-21-infrastructure
libp2p            | @diasdavid      | 12:30PDT **19:30Z** 20:30CET | https://public.etherpad-mozilla.org/p/ipfs-march-21-libp2p
js-ipfs           | @diasdavid      | 13:00PDT **20:00Z** 21:00CET | https://public.etherpad-mozilla.org/p/ipfs-march-21-js-ipfs
go-ipfs           | @whyrusleeping  | 13:30PDT **20:30Z** 21:30CET | https://public.etherpad-mozilla.org/p/ipfs-march-21-go-ipfs

Please add the Agenda to the Pad before the endeavour sprint starts.

## Sprint Deliverables

- Add your tasks below in a comment, that way we only have people listed who are really in the sprint
- Add links to issues down here. Only add things you can finish this sprint.

**Comment by RichardLitt** [comment]
Go-ipfs notes:

This week in go-ipfs, we prepped for finally shipping version 0.4.0. This included lots of testing, writing of information, and verification of different aspects of ipfs. I wrote a test for the fs-repo-migrations that adds a very large number of objects (over 200,000) and pins a couple thousand of them, runs the migration, verifies ​*everything*​, runs a gc, and then verifies everything again. Once that got working, I kicked off a test run of that with the numbers bumped by a factor of 10 (over two million objects!) and everything (eventually) completed just fine.
During our hangout, @dignifiedquire brought up how much he really doesn't like our config file. We talked about this for a little while and decided to add in validation functions for various config keys, so that when the user is editing the config, they can be more sure about not breaking anything.

**Comment by RichardLitt** [comment]
Anyone mind if we move the Monday hangout next week to Tuesday?

**Comment by dignifiedquire** [comment]
SGTM

**Comment by diasdavid** [comment]
## libp2p

#### Lead: @diasdavid

#### Participants

## Agenda & Nodes

- update
  - js-libp2p-swarm
  - js-libp2p-tcp
  - js-libp2p-websockets
  - js-libp2p-multiplex
- stream-muxing headache
  - https://github.com/diasdavid/js-libp2p-multiplex/
  - https://github.com/diasdavid/js-libp2p-spdy
- uTP, "why u no half closed streams"

**Comment by diasdavid** [comment]
## js-ipfs

#### Lead: @diasdavid

## Agenda

- update
  - jsipfs swarm
  - jsipfs files add
  - js-libp2p-ipfs
  - js-ipfs-data-importing
- standardizing JS development accross IPFS org repos, with all that we learned
- ipfs init
- files + mfs API
- update documentation (readme) with examples in every module
- ipld upgrade
- bitswap
- ask about this line https://github.com/nginnever/js-ipfs-merkle-dag/blob/master/src/dag-service.js#L27 (path should be checked for more than just exist?)

**Comment by diasdavid** [comment]
## DAVID DIAS TODO

### js-ipfs

- **management**
  - [ ] estimate time for completion of remaining components
- **jsipfs swarm**
  - [ ] peers
  - [ ] addrs
  - [ ] connect
  - [ ] disconnect
  - [ ] interop
- **jsipfs files**
- **js-libp2p-ipfs**
- **js-ipfs-data-importing**
- **js-multiaddr**
- **js-mafmt**
- **js-peer-id**
- **js-ipfs-repo**

### js-ipfs-api

### libp2p

- **webrtc-explorer**
- **js-libp2p-swarm**
- **js-libp2p-tcp**
- **js-libp2p-utp**
- **js-libp2p-websockets**
- **js-libp2p-multiplex**

### npm on IPFS

### IPLD

### webui

### specs

- **http-api-spec**
- **specs**

### extra

**Comment by dignifiedquire** [comment]
### @dignifiedquire TODO

- Ship dignified.js for all of js-ipfs

**Comment by RichardLitt** [comment]
### To do

- [~] Sprint Management
- [~] Write the weekly roundup
- [ ] js-ipfs block https://github.com/ipfs/js-ipfs/pull/81
- [ ] http-api-spec work
- [ ] 0.4.0 blogpost checking

**Comment by nginnever** [comment]
<h3>TODO</h3>
- js-ipfs-data-importing
 - [ ] exporter
- js-ipfs-merkle-dag
 - [ ] add is-ipfs to check valid multihashes
- is-ipfs
 - [ ] add buffer support
- js-ipfs
 - [ ] cat command
 - [ ] get command
- Webui
 - [ ] write tests
 - [ ] document in contibuting.md

**Comment by RichardLitt** [comment]
## Apps on IPFS

#### Lead: @dignifiedquire

#### Participants

## Agenda

- webui
- orbit -- we should discuss orbit and orbit-db in this hangout (+2)
- ip-wiki prototype (https://github.com/search?q=user%3Anoffle+ip-wiki)
- ongoing pubsub discussion
- I think the MediaChain folks want to talk a bit here, too



**You have 30 minutes for this agenda**, 5 minutes before the meeting ends, consider moving the remaining items to a github discussion thread so that all the other sprint meetings can start in time.

## Notes

- webui
  - no drag and drop of folders into the webui - (browsers (chrome) will stop supporting drag and drop of folders)
  - needs a more helpful config menu for the ipfs config (to avoid users making mistakes and crashing their nodes)
  - webui release process will be deferred to 0.4.1 release. It needs to be a) documented b) audited (signed releases, etc)
  - dignifiedquire will make webui mockups available so that others can give feedback on the design. Might be better to use some tool for this job, a service perhaps?
- orbit
  - orbit discussion was postponed to next week
- pubsub
  - we have https://github.com/noffle/pubsub-swarm, but next want to build something on top of libp2p that benefits from the IPFS network (connection sharing, etc)
- ip-wiki
  - (live demo)
  - still very young, can't publish new content yet, but fully usable using only the browser + public gateway
  - could benefit from research on existing CRDT-based wiki and git-based wiki ideas


##### After sprint meeting is finished, create the respective action items on the Github sprint issue

**Comment by haadcode** [comment]
### @haadcode sprint goals - 21 Mar - 1 Apr

#### Summary
This sprint I'll continue the work on Orbit. Plan to refactor the UI code, improve the messaging (it's a little broken atm), fix broken UX feedback elements (such as loading bars) and fix bugs as I go. Really just a lot of grunt work.

#### Tasks

##### orbit-db
  - [ ] Use ipfs-log module
  - [ ] Stretch goal: Add pinning to db and ipfs-log objects
  - [ ] Stretch goal: try replacing current pubsub with @noffle's pubsub-swarm

##### ipfs-log
  - [ ] Fix message history fetching
  - [ ] Stretch goal: Stream API for ipfs-log

##### Orbit
  - [ ] Make message history more reliable
  - [ ] Continue UI refactoring
  - [ ] Fix broken UX elements and UI bugs

**Comment by lgierth** [comment]
### @lgierth todo

- metrics
  - [ ] deploy mtail-nginx to all hosts
  - [ ] make gateway dashboard use nginx metrics
  - [ ] bring back ipfs_p2p_peers metrics
- pages
  - [ ] `ssh <pagename>@pages.ipfs.team publish <hash>`
  - [ ] blog@pages.ipfs.team
- go-ipfs
  - [ ] harden gateway path prefix
  - [ ] v04x/v03x paragraph for 0.4.0 blog post
- infrastructure
  - [ ] track down gateway slowness
  - [ ] ~~identity validation for *.ipfs.io cert~~ taken over by @whyrusleeping
  - [ ] migrate rest of ansible playbooks to provsn
- errands
  - [x] deploy weekly \#8
  - [ ] pin geoip on v03x, for station
- reminder to self
  - github assignments: https://github.com/issues/assigned

**Comment by noffle** [comment]
### Summary

I'm aiming to finish js-ipfs init this week, and have been making fixes and documentation improvements to various js- and libp2p- modules along the way. I'm also reflecting on libp2p and where it'll fit in for IPFS app developers in the near future.

### Tasks

##### js-ipfs

- [x] init: add default assets (intro docs) to repo
- [x] init: tests tests tests
- [ ] init: CLI and HTTP init routes
- [ ] separate repo setup/teardown into its own module

##### js-ipfs-data-importing

- [x] write a readme & example
- [x] various bug fixes

##### js-libp2p-multiplex

- [x] update readme & add example

##### libp2p

- [ ] thinking & note taking on how libp2p and IPFS apps will work together

**Comment by RichardLitt** [comment]
Our mid-sprint hangout is happening in 25 minutes! Yay!

**Comment by RichardLitt** [comment]
Due to a lot of the team being at the [NYC Blockchain workshop](http://nyc.blockchainworkshops.org/) today, we're going to move the sprint hangouts to this Wednesday, April 6th.

**Comment by nginnever** [comment]
<h3>Sprint End Summary</h3>
The past few weeks I have spent most of my time working on the files api and data. Started building the core and cli for js-ipfs files commands. Worked with a few other modules as well. Merged some PR's on is-ipfs to add buffer support and tests. The js-ipfs-merkle-dag module now does more than just check the existence of a multihash, it uses is-ipfs to assert it is a correct multihash and throws appropriate errors if not. 

- dignified.js
 - [x] PR https://github.com/jbenet/js-multihash/pull/5
 - [x] PR https://github.com/diasdavid/js-ipld/pull/9
 - [x] PR https://github.com/xicombd/is-ipfs/pull/5
 - [x] PR https://github.com/diasdavid/js-libp2p-distributed-record-store/pull/3
- js-ipfs-data-importing
 - [~] exporter
- js-ipfs-merkle-dag
 - [x] add is-ipfs to check valid multihashes
 - [X] needs CR (now merged)
- is-ipfs
 - [x] add buffer support
 - [X] use dignified.js tests
- js-ipfs
 - [X] cat command
 - [X] get command
- Webui
 - [ ] write tests
 - [ ] document in contibuting.md

**Comment by diasdavid** [comment]
# DAVID DIAS check in

> **Summary:** The last part of this sprint was most filled by meetings, conversations and planning, which resulted in consolidated ROADMAPs for js-ipfs, libp2p, registry-mirror and js-ipld. You can check the most recent entry of Captain.log at https://github.com/ipfs/js-ipfs/issues/30#issuecomment-205884015 , there is a lot of space for contributions :). Other than that, a lot of work went into the `zlib` problem that @dignifiedquire has now solved, plus CR+M a lot of contributions from several js-ipfs contributors. One last thing, the Research & Development Meetup is now a thing in Lisbon and if you are around, I totally recommend participating, check for the next event here: http://www.meetup.com/ipfs-lisbon-meetup/events/229807984. 

### js-ipfs

- **management**
  - [x] roadmap
  - [x] captain.log entry - https://github.com/ipfs/js-ipfs/issues/30#issuecomment-205884015
- **jsipfs files**
- **js-libp2p-ipfs**
- **js-ipfs-data-importing**
  - [x] https://github.com/ipfs/js-ipfs-data-importing/pull/11
  - [x] greeen https://github.com/ipfs/js-ipfs-data-importing/pull/12
  - [x] CR+M https://github.com/ipfs/js-ipfs-data-importing/pull/8
- **js-multiaddr**
- **js-mafmt**
- **js-peer-id**
- **js-ipfs-repo**
- [x] CR+M https://github.com/ipfs/js-ipfs/pull/88
- [x] CR+M https://github.com/ipfs/js-ipfs/pull/91
- [x] CR+M https://github.com/ipfs/js-ipfs/pull/94
- [x] CR+M https://github.com/ipfs/js-ipfs/pull/99
- [x] CR+M https://github.com/ipfs/js-ipfs/pull/98
- [x] R and W more for js-project-guidelines https://github.com/ipfs/community/pull/111

### libp2p

- **webrtc-explorer**
- **js-libp2p-swarm**
  - [x] fix dirty identify bug with websockets https://github.com/diasdavid/js-libp2p-swarm/pull/32
  - [x] tests with multiplex https://github.com/diasdavid/js-libp2p-swarm/pull/33
- **js-libp2p-tcp**
- **js-libp2p-utp**
- **js-libp2p-websockets**
- **js-libp2p-multiplex**
  - [x] https://github.com/diasdavid/js-libp2p-multiplex/pull/7

### npm on IPFS

- [x] fix ipfs-blob-store https://github.com/ipfs/ipfs-blob-store/pull/10 (due to updates on js-ipfs-api)
- [x] add more info https://github.com/diasdavid/registry-mirror/pull/34
- [x] fix deps https://github.com/diasdavid/registry-mirror/pull/35 

### specs

- **specs**
  - [x] clean up specs https://github.com/ipfs/specs/pull/89

### extra

- [x] R https://github.com/ipfs/blog/pull/37
- [x] RDM#2 http://www.meetup.com/ipfs-lisbon-meetup/events/229807984/
- [x] R 0.4.0 blog post release
- [x] Files API section for 0.4.0 blog post release https://github.com/ipfs/blog/pull/37/commits/a2358b1432759d0d6e5bdb6ab58316e20f86fa5a
- [x] add coverage reports to test suites https://github.com/dignifiedquire/dignified.js/pull/4

**Comment by RichardLitt** [comment]
### Summary

Nothing to report. This week was taken up with organizing and meetings in New York. I ran the event last Wednesday, where over 100 people came to AWS to hear about IPFS and other blockchain orgs. That was good.

**Comment by whyrusleeping** [comment]
# Recap
last week we had lots of dicussion about Q2 goals for our projects.
From this, i've got a good idea of the set of tasks we want to accomplish over the next three months.
0.4.0 will be shipped today, and after that I will post a project roadmap for go-ipfs and go-libp2p

**Comment by lgierth** [comment]
### @lgierth sprint update

I've been in NYC for this whole sprint, and even taking the team week into
account, this has been a really productive sprint for me after a long time :)

I had to fight the DNS outage on March 27th together with @jbenet, and we
learned quite a few interesting things that I'll be putting into action this
next sprint. We'll also follow up with a detailed public post mortem.

0.4.0 is ready to ship, I worked on the changelog and blog post with the others,
and shipped a security fix for an XSS vulnerability in the gateway's path prefix
feature which was added in v0.3.10.

Apart from that: more work on metrics for go-ipfs and infrastructure, and
debugging of hanging and slow go-ipfs daemons.

- dns outage
  - [x] firefighting
  - [x] post mortem ipfs/ops-private#4
  - [ ] work on post mortem actionables
- metrics
  - [x] deploy mtail-nginx to all hosts ipfs/infrastructure#158
  - [x] make gateway dashboard use nginx metrics
  - [x] gateway content-type metrics
  - [x] ipfs open FDs metrics
  - [x] ipfs.io/blog and /version response time metrics (using ipfswatch)
  - [ ] bring back ipfs_p2p_peers metrics
- pages
  - [ ] `ssh <pagename>@pages.ipfs.team publish <hash>`
  - [ ] blog@pages.ipfs.team
  - [ ] versioning via `previous` link
- go-ipfs
  - [x] security: harden gateway path prefix ipfs/go-ipfs#1988
  - [x] v04x/v03x paragraph for 0.4.0 blog post
  - [x] v0.4.0 changelog
  - [ ] discuss extension of v03x EOL
  - [x] test fs-repo-migrations stress test
  - [x] test distributions immutability ipfs/distributions#58
- infrastructure
  - [x] finally write down infrastructure goals ipfs/infrastructure#157
  - [ ] ~~identity validation for *.ipfs.io cert~~ taken over by @whyrusleeping
  - [ ] debug automatic GC
  - [ ] parallel upload for provsn
  - [ ] migrate rest of ansible playbooks to provsn
- errands
  - [x] deploy weekly \#8
  - [x] deploy fix to weekly \#6
  - [x] deploy website
  - [x] more yubikeys
  - [x] meet with nycmesh.net
  - [x] update whyrusleeping on vpn allowlist
  - [x] reinstate update.ipfs.io
  - [ ] transfer domains to gandi account ipfs/infrastructure#84
  - [ ] pin geoip on v03x, for station
- reminder to self
  - github assignments: https://github.com/issues/assigned
